facebook/react-native-website

- docs/state.md
That one was extremely old—I don't even think it was supported by the old website.
Surprised this has been broken for so long.
> Fix React docs link

- docs/getting-started.md
Site no longer uses straight markdown format.
> Update links to Watchman installation guide.

- website/versioned_docs/version-0.51/touchableopacity.md
Hierarchy was spelled incorrectly.
#<Issue>
> Spelling update

- website/versioned_docs/version-0.51/animated.md
2nd example of Animated.event() had the arguments incorrectly presented
was:
Animated.event([
{rawEvent}, 
{gestureState},
{listener}
])
this correction:
Animated.event([
{rawEvent}, 
{gestureState}],
{listener}
)
#<Issue>
> correct 2nd example of Animated.event()

- website/pages/en/showcase.js
The sentences were collapsing with the anchor, as shown here:
[Before text change](https://i.imgur.com/n1NaGKc.png)
[After text change](https://i.imgur.com/moGJpfD.png)
> Fix sentences collapsing with anchor text

- website/versioned_docs/version-0.5/contributing.md
Some of the link are fails in [How to Contribute](https://facebook.github.io/react-native/docs/contributing.html) page.
> Fixed url in Contributing.md

- docs/easing.md
- website/versioned_docs/version-0.43/easing.md
- website/versioned_docs/version-0.5/easing.md
- website/versioned_docs/version-0.51/easing.md
The link to `Animated.timing()` was wrong. 
Also applied to versioned docs.
> Fix Animated.timing() link in Easing

- docs/image.md
- website/versioned_docs/version-0.51/image.md
> Fix a typo in image docs

- website/static/movies.json
* In [Networking · React Native](https://facebook.github.io/react-native/docs/network.html), access to `https://facebook.github.io/react-native/movies.json` currently returns 404. 
* This PR fixes it by copying `movies.json` from [react\-native/movies\.json at master · facebook/react\-native](https://github.com/facebook/react-native/blob/master/website/src/react-native/movies.json).
> Add movies.json used in networking tutorial

- docs/native-components-android.md
`View.propTypes` are deprecated and not available since RN 0.49.
Replaced with `ViewPropTypes`.
> Replace deprecated View.propTypes by ViewPropTypes

- docs/testing.md
> Fix broken link to react native tutorial on jest website

- website/versioned_docs/version-0.51/actionsheetios.md
Small issue, but when using `ActionSheetIOS` if you copy the example, you'll run into an issue the way the code is commented. Changed the comment structure so it will work when copied.
> Fixed typo - comment was blocking closing bracket

- docs/contributing.md
- website/versioned_docs/version-0.5/contributing.md
Links to `support.html` were wrong, changed to `help.html`.
Also applied to versioned docs.
Fixes #50.
> Change support links to help links

- docs/building-for-apple-tv.md
- website/i18n/en.json
- website/sidebars.json
This is directly connected with Android TV PR to react-native core (https://github.com/facebook/react-native/pull/16500)
* Added docs for Android TV. These are mostly the same as for Apple TV. The specifics include:
* Build Changes
* Known issues
* Unified docs for Apple TV and Android TV into one document: "Building For TV Devices" with platform (Android/iOS) toggler
> Add docs for building for Android TV and unify them with Apple TV docs

- docs/linking.md
Fixes this:
on this: https://facebook.github.io/react-native/docs/next/linking.html#docsNav
> Remove unnecessary comment slashes

- docs/handling-text-input.md
This PR changes the URL in the docs Markdown in order to get the right url for `React Documentation`.
#55
> Fix Controlled Components link on handling-text-input.md

- docs/performance.md
> [Performance] Add info about debuggerWorker.js thread

- docs/virtualizedlist.md
Continuation from PR #41 and following up issue #40, in this PR I added back the props documentation of `VirtualizedList` component. All the documentation and description were taken from https://facebook.github.io/react-native/docs/0.48/virtualizedlist.html with some adjustment to match the current doc style.
Notice that I removed `scrollEventThrottle` from props documentation as it has been covered in `ScrollView`. I also remove `first` and `last` props from the doc as they are actually the `State` of the component (https://github.com/facebook/react-native/blob/ed2bfcb35a2756eb700882ab8e21b6b273efa80a/Libraries/Lists/VirtualizedList.js#L209).
Before:
Current:
> Add missing doc virtualizedlist

- docs/performance.md
Selecting the thread inside `Sources` tab is not necessary. 
Conversation: https://github.com/facebook/react-native/issues/15003#issuecomment-351504239
> [Performance.md] Fix details about Chrome Javascript Profiling

- docs/layout-props.md
Fixed alphabetical ordering for the Prop 'direction'
#<Issue>
> Fix alphabetical ordering layout-props.md

- docs/stylesheet.md
Copied documentation of StyleSheet props from https://facebook.github.io/react-vr/docs/stylesheet.html.
Please confirm that react-vr `StyleSheet`'s props function the same as react-native `StyleSheet`'s
> Add props to stylesheet.md

- website/static/css/react-native.css
Due to `margin-right: 0;` of `.docsNavContainer` `.hash-link` became 'un-clickable' when title parent missed hover.
So `margin-right: 0;` has been removed in order to fix this bug.
**Actual behavior:**
**Fixed behavior:**
#71
> Fix hover anchor click.

- docs/tutorial.md
As shown in [#17208](https://github.com/facebook/react-native/issues/17208) in facebook/react-native, "`App.js` should not include `AppRegistry.registerComponent('SampleApp', () => App)`;. That is only needed in `index.js.`"
Replace `AppRegistry` with `export default App;`
> Updated tutorial.md to fix export error

- docs/appstate.md
Hello,
On Android, it appears that the AppState becomes [`background`](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/appstate/AppStateModule.java#L59) when you start a new intent from your app. It is worth mentioning because when you use third-party SDKs that rely on other activities, you'll enter this state. On iOS, the behavior is not the same (AppState stays active).
> Update appstate.md with note on Android activities

- docs/statusbar.md
- docs/tutorial.md
- website/pages/en/versions.js
This fixes a problem with the 'Release Notes' link on the [versions page](https://facebook.github.io/react-native/versions.html).
There was an unwrapped ternary expression:
```JavaScript
<a
href={
"https://github.com/facebook/react-native/releases/tag/v" +
version +
".0" +
isRc
? "-rc.0"
: ""
}
>
Release Notes
</a>
```
Which evaluates like:
```JavaScript
("https://github.com/facebook/react-native/releases/tag/v" + version + ".0" + isRc) ? "-rc.0" : ""
```
Making the href attribute always `-rc.0`.
The fix just wraps the ternary statement in brackets, for the intended functionality:
```JavaScript
<a
href={
"https://github.com/facebook/react-native/releases/tag/v" +
version +
".0" +
(isRC ? "-rc.0" : "")
}
>
Release Notes
</a>
```
Which, obviously, evaluates like:
```JavaScript …
```
> Fix 'Release Notes' link on versions page

- website/static/css/react-native.css
Due to anchor link fix, margin between sidebar and content container has been increase, from 60px to 100px.
In order to fix this issue, docsNavContainer now have a width of 240px and mainContainer has a margin-left of 20px on screen greater than 1024px.
**Before**
**After**
#71 and #79
> Decrease margin between sidebar and content.

- docs/getting-started.md
Node 4 will no longer be in maintenance LTS status as of April 2018, and we are not currently running tests on Node 4, so we cannot guarantee it will work.
> Bump minimum Node version required to 6

- docs/animations.md
Fixes link to "`LayoutAnimation` API" section.
> Fix link to LayoutAnimation

- docs/textinput.md
This will add the `contextMenuHidden` prop to TextInput.
Related `react-native` PR: https://github.com/facebook/react-native/pull/17335
> Add contextMenuHidden to TextInput

- docs/scrollview.md
Related PR on main repo: https://github.com/facebook/react-native/pull/17368
> Document onScrollBeginDrag and onScrollEndDrag

- docs/webview.md
Adds a security warning to the documentation for `WebView` because the current implementation (on both platforms) does not support transmitting an origin to validate that messages are being sent to (or received by) the expected origin.
> Add Security Warning to WebView

- docs/images.md
The @2x and @3x image example showed the file directory containing the `img` directory and the React example source url showed `assets` as the directory.
#<Issue>
> Change require url

- docs/cameraroll.md
`assetType='All'` means that videos are also included which might cause a problem since the example only uses the `<Image />` element to display the photos
> Corrected example

- docs/accessibility.md
I found the language "and so on" used to describe `accessibilityComponentType` property imprecise as it suggests there are more options than the ones already listed.
Looking at the declaration [ViewAccessiblity.js](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewAccessibility.js#L33) I've updated the list to be exhaustive. 
This PR is related to https://github.com/facebook/react-native/issues/13740 as it would make the documentation reflect the current level of support for accessibilityComponentType.
> Update description of accessibilityComponentType in accessibility docs

- docs/layout-props.md
- website/versioned_docs/version-0.52-RC/layout-props.md
In 0.52.0-RC, value `justifyContent` was added to `spaceEvenly` (facebook/react-native@1050e0b). Update the docs to reflect this. Note that this is already explained in the existing link to Mozilla, so I don't believe we need to add any more detail of what `spaceEvenly` is.
> Added `spaceEvenly` value to `justifyContent`

- docs/datepickerios.md
- website/versioned_docs/version-0.52-RC/datepickerios.md
`DatePickerIOS` has a new prop `locale` in 0.52.0-RC thanks to facebook/react-native@fd9c361; this adds the missing docs for that.
> Added `locale` prop to `DaterPickerIOS`

- docs/gesture-responder-system.md
- website/versioned_docs/version-0.5/gesture-responder-system.md
The file ResponderEventPlugin.js is nowhere to be found in the source code of react-native although it is referenced by name 33 times in 6 files. ResponderEventPlugin can be found inside of Libraries\Renderer\ReactNativeRenderer-prod.js though.
Having had a look at ReactNativeRenderer-prod.js I realised that there are neither details nor documentation inside of this file. Thus, I would propose to completely remove this sentence.
> Remove out of date reference to ResponderEventPlugin.js

- docs/integration-with-existing-apps.md
Added missing CxxBridge to React subspecs for Objective-C
#<Issue>
> Added missing subspecs for Objective-C

- docs/contributing.md
Seems like these docs are from some past time when the website was contained in the main repo.
> Update contributing.md to reflect splitting of repos

- website/showcase.json
instead of remote
http://is1.mzstatic.com/image/thumb/Purple118/v4/9c/86/19/9c861944-900e-2d61-18b5-9250b3840277/source/175x175bb.jpg
:shruggie:?
...to avoid:
```
Mixed Content: The page at 'https://facebook.github.io/react-native/' was loaded over HTTPS, but requested an insecure image 'http://is1.mzstatic.com/image/thumb/Purple118/v4/9c/86/19/9c861944-900e-2d61-18b5-9250b3840277/source/175x175bb.jpg'. This content should also be served over HTTPS.
```
> use local skype icon

- docs/modal.md
The `onRequestClose` spec tablet show required by platform correctly.
#<Issue>
> Fix Modal `onRequestClose` attribute required spec table

- netlify.toml
I was tired to checkout every branch to review visual changes and I think that deploying each pull requests could be useful and a time saver for maintainers as well as contributors.
We could easily achieve this with Netlify and their deploy preview service.
Here's deploy preview in action on `react-native-website`: https://github.com/charpeni/react-native-website/pull/3.
Note that [`siteConfig.js`](https://github.com/facebook/react-native-website/blob/master/website/siteConfig.js) will be altered in Netlify infra because we need `baseUrl` to be `/`.
For the additional configuration on GitHub & Netlify let's hook up on Slack @hramos.
🦖 🤖 :tada:
> Add configuration for deploy preview

- docs/cameraroll.md
The mimeType propType was wrong in the doc instead of string it is an array
#<Issue>
> Update Cameraroll.md - mimeType propType

- website/blog/2018-01-09-react-native-monthly-6.md
I'll just c/p the comment from the original pull request on react-native repo:
A blog post with notes from the second React Native monthly meeting. I've gathered notes after the meeting in this blog post.
No test plan, submitting just a documentation file.
[DOCS] [ENHANCEMENT] [blog/2018-01-09-react-native-monthly-6.md] - Submitting notes from React Native monthly #6.
> Add notes for React Native monthly

- docs/javascript-environment.md
This PR moves each feature into a correct/updated heading from when it was first written.
Admittedly it's quite an odd page with a sprinkling of some features but not all, and potentially should use the ES20XX naming convention instead?
> fix: move features into correct headings

- docs/cameraroll.md
> playableDuration property missing in documentation

- docs/image.md
Related to, but IMHO shouldn't be blocked by, https://github.com/facebook/react-native/pull/17759.
> Document Image resizeMode=center

- docs/stylesheet.md
Phrase read "so a line defined by it look crisp", changed it to "so a line defined by it can look crisp". Alternatively it could be made to read "so that a line defined by it looks crisp".
> Wording correction in hairlineWidth documentation

- docs/integration-with-existing-apps.md
I just went through this guide when adding React Native to my existing Android app and made a few parts clearer / easier.
> Update Integration with existing apps (Android)

- docs/integration-with-existing-apps.md
I noticed that when following the Android integration as documented here, `React.Component`s were never unmounted and figured out it was because you need to call `ReactRootView#unmountReactApplication()` in your Activities `onDestroy`. This was only documented in the `ReactRootView#startReactApplication()` JavaDoc though.
This PR adds this call to the integration guide so in the future people who just copy/paste the sample won't have this issue.
> Update Android Integration Guide

- docs/javascript-environment.md
- docs/pushnotificationios.md
- website/versioned_docs/version-0.38/pushnotificationios.md
- website/versioned_docs/version-0.39/pushnotificationios.md
- website/versioned_docs/version-0.40/pushnotificationios.md
- website/versioned_docs/version-0.44/pushnotificationios.md
- website/versioned_docs/version-0.45/pushnotificationios.md
- website/versioned_docs/version-0.46/pushnotificationios.md
- website/versioned_docs/version-0.47/pushnotificationios.md
- website/versioned_docs/version-0.49/pushnotificationios.md
I have been changed for missing method called `presentLocalNotification` on `PushNotificationIOS`.
Fixed broken link on `JavaScript Environment`.
> Add missing method on PushNotificationIOS

- docs/debugging.md
Because there is a change in the YellowBox API (https://github.com/facebook/react-native/commit/26038f5) the docs need to be updated
This also fix this issue
https://github.com/facebook/react-native/issues/17503
> Updating docs because changes in YellowBox API

- website/versioned_docs/version-0.52/debugging.md
Because there is a change in the YellowBox API (facebook/react-native@26038f5) the docs need to be updated
This also fix this issue
facebook/react-native#17503
> Updating docs because changes in YellowBox API ( Versioned Docs )

- docs/cameraroll.md
Add a section to include an extra key required on iOS 11 and later in order to write to the camera roll.
> Update cameraroll.md permissions section

- docs/cameraroll.md
This PR fixes the wrong type of `start_cursor` and `end_cursor` properties.
Screenshot:
> Fix `start/end_cursor` type (`CameraRoll`)

- README.md
Just started contributing to this repo today and had trouble viewing changes I made to some markdown files. Thanks to @charpeni's comment on #169, I realized you have to switch to the MASTER version. This update clarifies that in the README. I also figured the README should remind people to fork the repo when cloning like the README in [reactjs](https://github.com/reactjs/reactjs.org).
> Update README for contributing

- docs/accessibility.md
Hi!
I made some changes to the example in https://facebook.github.io/react-native/docs/accessibility.html#sending-accessibility-events-android to make it more helpful. I found it a little confusing when I first saw it. The changes are the following:
* Use UIManager instead of non-existing RCTUIManager
* Use single quotes instead of weird quotes: `“”`
* Use `setState` instead of directly manipulating `this.state`
* Add import statement to show where the APIs come from
* Fix markdown syntax of inline code in another paragraph
> Update accessibility event example in accessibility.md

- docs/actionsheetios.md
- website/versioned_docs/version-0.51/actionsheetios.md
- website/versioned_docs/version-0.52/actionsheetios.md
Hi, where is a small mistake in the example for ActionSheetIOS button orders and the array index. 'Remove' should be the destructive button and 'Cancel' is for cancel. Destructive button renders on top of cancel, even if it has a lower index(tested on RN 51)
> Fix button orders and indexes in ActionSheetIOS examples

- docs/running-on-device.md
Problem: the `echo` command (as is in the docs) discards the double quotes (they are expanded by the shell). The double quotes must be preserved for proper udev config loading.
> Preserve quotes in udev config (they are required)

- docs/integration-with-existing-apps.md
Just a small followup to my PR https://github.com/facebook/react-native-website/pull/166.
This makes it more likely people will install the correct version of React.
I was just reading the guide again now and realized it's easy copy&paste commands without reading the text around them, and install a wrong version of React.
> Small tweak in 'Integration with existing apps'

- docs/integration-with-existing-apps.md
I followed the [guide](https://facebook.github.io/react-native/docs/next/integration-with-existing-apps.html) step by step and ran into an error on my machine. I've spent a while googling and finally found a solution here:
https://github.com/facebook/react-native/issues/7965
Adding this step should prevent the error.
(I'm using the same screenshot as used here: https://facebook.github.io/react-native/docs/getting-started.html)
> Fix an error in 'Integration with existing apps' (iOS)

- docs/signed-apk-android.md
If org.gradle.configureondemand=true is set for gradle, gradle will skip bundleJsAndAsset gradle task, which will result into the app crashing on startup with this in the logs:
java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server
Since it is not clear from the error what is causing this, I would recommend adding this additional note to potentially save a lot of time for people figuring this out (it was not trivial to find the answer by googling).
> note to not have a gradle setting which breaks android release build

- docs/integration-with-existing-apps.md
Preview here:
https://deploy-preview-217--react-native.netlify.com/docs/next/integration-with-existing-apps.html
`RCTAnimation` is needed for `FlatList`, otherwise we get an error:
Most mobile apps use some sort of a scrollable list and [FlatList](https://facebook.github.io/react-native/docs/flatlist.html) is the default way to do that. Therefore most people will need to include `RCTAnimation`, and this PR saves time Googling.
I added comment so it's clear what this dependency is for and people can always remove it if not needed.
> Integration with iOS apps - Include RCTAnimation

- docs/upgrading.md
The documentation says that "You may specify a React Native version by passing an argument: `react-native-git-upgrade X.Y`". However, if I run `react-native-git-upgrade 0.53` I get 
```
Error: The specified version of React Native 0.53 doesn't exist.
Re-run the react-native-git-upgrade command with an existing version,
for example: "react-native-git-upgrade 0.38.0",
```
Running `react-native-git-upgrade 0.53.3` works.
This pull request changes the documentation so that it says "You may specify a React Native version by passing an argument: `react-native-git-upgrade X.Y.Z`" so that it is uniform with the error message.
> Fix react-native-git-upgrade documentation

- docs/integration-with-existing-apps.md
See podspec should be lowercase
https://github.com/facebook/react-native/blob/master/third-party-podspecs/glog.podspec
> Glog lower case matters

- docs/picker.md
If we render Picker without having width and height set explicitly, the component will not be visible. This caused an issue to a few people that I mentor and each of them spent quite some time debugging.
> Improved the documentation regarding Picker

- docs/textinput.md
Remove from doc according to commit
facebook/react-native@dabb78b since v0.53
This PR is to complete previous one #188.
> Remove maxHeight from TextInput

- docs/text.md
To go along with https://github.com/facebook/react-native/pull/17398
> Document letterSpacing, including on Android

- docs/native-modules-ios.md
I'm an iOS beginner and missed this import. I later figured it out, but hopefully this PR will save others some time.
The import is correctly added in the next code sample below but I believe we should add it right in the first example - this is the first bit of code people copy&paste and it doesn't work currently.
> Small clarification in Native Modules (iOS)

- docs/keyboardavoidingview.md
I saw a question about `KeyboardAvoidingView` on StackOverflow and realized the docs were missing example usage (see e.g. [`Button`](https://github.com/facebook/react-native-website/edit/master/docs/button.md)).
Preview:
> Add an example to KeyboardAvoidingView

- docs/flatlist.md
I've just updated the `docs/flatlist.md` file with updated info based on `ViewabilityConfig` interface. I've tried to upload screenshots but was unable to update the local website. There were no error though from `docusaurus`.
Pull Request explains the properties taken by `viewabilityConfig` and the error and how to avoid  #17408 on `react-native` repo.
> added docs for viewabilityConfig based on ViewabilityConfig interface

- docs/accessibility.md
- docs/view.md
Updated documentation for https://github.com/facebook/react-native/pull/17627
> Add accessibilityElementsHidden prop

- docs/permissionsandroid.md
This PR improves the documentation of the `PermissionsAndroid`-module.
Improvements:
* Correct return values for `check` and `request` method.
* Return constants listed.
Screenshot:
> Improve documentation of PermissionsAndroid module

- docs/keyboard.md
According to the official React documentation on ComponentWillMount method: 
> Avoid introducing any side-effects or subscriptions in this method. For those use cases, use componentDidMount() instead.
> Update keyboard example.md

- docs/image.md
Following the Fresco update in the upcoming version, I have updated the version of fresco in the docs. 
Related issue: https://github.com/facebook/react-native/pull/18496
> Update Fresco version in the docs

- docs/sectionlist.md
When first going through this example, it was unclear to me that `ListItem` and `Header`  where not importable components. The error was rather cryptic as well.
Also, the heterogeneous example made the sections prop look like it expected a different data structure. Plus, adding explicit function params for clarity.
> Documentation Clarification: SectionList

- docs/image.md
1. Android implementation pending review: https://github.com/facebook/react-native/pull/17404
2. Current behaviour on iOS (as well as on Android per https://github.com/facebook/react-native/pull/17404) differs from what's documented for an image that's larger than the view.
> Update Image resizeMode=repeat docs

- docs/animated.md
Documentation to https://github.com/facebook/react-native/pull/18630
> Document Animated.subtract

- docs/textinput.md
Adds docs for https://github.com/facebook/react-native/pull/18526 
New prop `textContentType` on `TextInput`.
> Update textinput.md with textContentType

- docs/scrollview.md
Updated docs to show horizontal support for snapToInterval and snapToAlignment on android.
References this [PR](https://github.com/facebook/react-native/pull/18648)
> updated docs to show support for snapToInterval/Alignment on android

- docs/progressbarandroid.md
This PR is for the confusing docs on the `ProgressBarAndroid` component.
I've done the following:
- Re-phrased the initial copy for the component description
- Add a copy pastable snippet that can work out of the box in "create-react-naitve-app" and or in expo
- Hopefully made the docs a bit better for everybody 😄 
This is a screnshot of the snippet running in an emulator
and here is running on expo
https://snack.expo.io/rysZ_cooz
> Update the ProgressBarAndroid copy and example 

- docs/textinput.md
- website/versioned_docs/version-0.55/textinput.md
from version v0.55.2
https://github.com/facebook/react-native/commit/c9ff0bc212b680232f7379fba7b9332927075c3c
> TextInput `onKeyPress` method is now supported on Android

- docs/improvingux.md
Locking screen orientation in your app is not a "good practice". It's not difficult at all to handle multiple orientations. The PR updates the text so that it doesn't sound like we're recommending people to lock the screen orientation.
> Don't recommend locking screen orientation

- docs/getting-started.md
- website/versioned_docs/version-0.5/getting-started.md
Install HAXM links were invalid.
This change fixes that so the links can be accessed again.
> Fix install HAXM links in getting-started.md

- docs/troubleshooting.md
- website/versioned_docs/version-0.5/troubleshooting.md
There are a bunch of "CocoaPods doesn't compile with version `0.xx.y` of RN" issues on facebook/react-native, and this plugin addresses those. The lib will port any changes to the source code that are needed to make it run automatically.
> Add a note about CPFRN in the troubleshooting next to the other CP issues

- docs/text.md
This removes the "`clip` only for IOS" message, since
now android also has support for it
Related PR:
facebook/react-native#18540
> Update ellipsizeMode prop of Text

- docs/sectionlist.md
Include the alternative to provide an error callback instead of providing the itemLayout in SectionList to fullfill requirements to use  scrollToLocation.
> SectionList > scrollToLocation: Alternative onScrollToIndexFailed

- docs/keyboardavoidingview.md
Docs state that the `keyboardVerticalOffset` prop for `keyboardAvoidingView` is required.   
But I do not believe this to be the case.   
I have yet to see a working example where this prop is even supplied.   
Indeed, this component works for me on both ios and android, without supplying it..   
(And when I did briefly try it out, I did not notice any difference.)
I changed the docs from `keyboardVerticalOffset` `Required: Yes` to `Required: No`
#<Issue>
> fix docs: `keyboardVerticalOffset`Not Required

- docs/flexbox.md
The description text is talking about alignItems: 'stretch' property, but used alignItems: 'center' instead.
#<Issue>
> typo: alignItems: 'stretch'

- docs/backhandler.md
Adding second example for using the Android Back Handler appropriately with the react component lifecycle. The initial example is good, but it doesn't cover the particular use case that I was looking at having it do.
This documentation change I believe could have helped with the following react-native issues:
https://github.com/facebook/react-native/issues/18954
https://github.com/facebook/react-native/issues/15497
https://github.com/facebook/react-native/issues/17110
https://github.com/facebook/react-native/issues/15303
https://github.com/facebook/react-native/issues/15149
This one is semi related... it is a bit older though so it is a slightly different issue. 
https://github.com/facebook/react-native/issues/4736
> Android Back Handler Documentation Example

- website/blog/2018-05-07-using-typescript-with-react-native.md
Follow on to: https://github.com/facebook/react-native-website/pull/314
Relates to: https://github.com/facebook/Docusaurus/pull/652 (future version of Docusaurus will not respect deprecated `authorImage`)
IS:
cc @yangshun
> Use authorImageURL, authorImage is deprecated in Docusaurus

- docs/getting-started.md
- website/versioned_docs/version-0.5/getting-started.md
Moving to Node 8 in React Native will allow us to be consistent with Facebook, e.g. trailing commas.
As of April 30, Node 4.x is end of life, and Node 6.x entered maintenance mode (see https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742).
> [Node 8.x] Update docs to reflect new min version

- docs/debugging.md
Added shortcuts for developer menu on Windows and Linux. Typing adb commands is not necessary anymore.
This should help people not needing to go on https://stackoverflow.com/a/37497678 every time.
> Windows and Linux shortcuts for developer menu

- docs/building-from-source.md
react native master uses android build tools 26.0.3, this change reflect that
https://github.com/facebook/react-native/commit/a3931e95317acaff5ceb1d2fb0f26ae67744c8a3
> use build-tools 26.0.3

- website/blog/2015-09-14-react-native-for-android.md
- website/blog/2017-08-07-react-native-performance-in-marketplace.md
- website/blog/2017-08-30-react-native-monthly-3.md
- website/blog/2017-09-21-react-native-monthly-4.md
Resolves part of: https://github.com/facebook/react-native-website/issues/316.
WAS:
IS:
WAS:
IS:
WAS:
IS:
WAS:
IS:
***
Note: `2015-11-23-making-react-native-apps-accessible` still has a broken image. The `authorFBID` does not work here. Noted on https://github.com/facebook/react-native-website/issues/316.
The Twitter URLs are not a permanent fix as they change when a new picture is uploaded, also noted on https://github.com/facebook/react-native-website/issues/316.
cc @yangshun
> Update broken profile images

- docs/panresponder.md
#233 
Puts the panResponder example in the constructor instead of componentWillMount().
> Refactor: PanResponder example to avoid componentWillMount()

- docs/images.md
After losing some time with an error about a "cannot read property 'width' of undefined", I dug into the source and found out that indeed, you MUST provide a `style` prop with key `width` and `height`.
This was not mentioned in the documentation and even made the provided example wrong.
> Rectify ImageBackground documentation

- docs/getting-started.md
The `.md` here will not be translated to `.html` when we build the site. As a result, we should change it to `.html` in the source.
FYI, we had something similar at https://github.com/facebook/react-native-website/blame/master/docs/getting-started.md#L156
> Fix broken link

- docs/testing.md
It's currently a link to /dev/null
> Remove 'website' from table of contents

- website/static/docs/android-setup.html
Fixes #385 
```
cd website
yarn start
```
Open http://localhost:3000/react-native/docs/android-setup.html, got redirected
Serve with simple python HttpServer
```
cd website
yarn build
cd build
python -m SimpleHTTPServer 8000
```
Open http://localhost:8000/react-native/docs/android-setup.html, got redirected
Open https://deploy-preview-390--react-native.netlify.com/docs/android-setup.html and got redirected
> redirect for react-native android-setup

- docs/animated.md
it was unclear to me if `event` could actually be a considered as an opaque structure, ie if it would work as expected for any kind of thing the user can actually provide as a `onScroll` listener for example.
It should be clear that it's safe to call with null or regular js listener
cc @sahrens
> Add details for Animated.forkEvent

- docs/flatlist.md
Modified the getItemLayout section such that it is easier to read through. Even though "a priori" technically a correct term, I feel like changing it will save some people (including me) a Google search.
> Grammar and sentence flow in FlatList docs

- docs/navigation.md
StackNavigator is deprecated and `createStackNavigator` should be used instead.
> Update navigation.md. Use createStackNavigator

- docs/image.md
No longer needed for current fresco lib.
> remove proguard rules no longer needed

- docs/contributing.md
- docs/removing-default-permissions.md
- website/core/RemarkablePlugins.js
- website/i18n/en.json
- website/package.json
- website/siteConfig.js
- website/static/css/codeblocks.css
- website/static/css/hero.css
- website/static/css/react-native.css
- website/static/css/tabs.css
- website/yarn.lock
Docusuarus 1.3.0 brings about some [backwards-incompatible CSS changes](https://github.com/facebook/Docusaurus/blob/master/CHANGELOG.md#breaking-changes). So the team is helping the major users update 😄 
cc @JoelMarcey @endiliey
Ran the site locally and visited every page.
> Update Docusaurus to 1.3.0

- docs/network.md
- website/static/movies.json
While running the fetch example, I saw this warning :
```ExceptionsManager.js:71 Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.```
I verified in the [doc](https://facebook.github.io/react-native/docs/flatlist.html#keyextractor), `keyExtractor` should return a `string`.
> Fix a warning in the Networking Fetch Example

- docs/javascript-environment.md
This documentation accompanies the PR https://github.com/facebook/react-native/pull/18555, which adds `console.group` and `console.groupEnd` to the polyfill.
> Add console group, groupEnd

- docs/navigation.md
What?
Adds the default exporting of `App` in `App.js`
Why?
Without exporting, `index.js` was not able to easily identify the App as described in the steps. This solved our problem and we were up and running.
> adds default exporting of `App`

- docs/performance.md
You should run generateModulePaths.js.
modulePaths.js is the file being generated by running generateModulePaths.js.
> Fix typo in documentation for unbundling

- .circleci/config.yml
Fixes #428.
A naive way to catch 404s, if there are any crashes while building the doc, `build/react-native/index.html` won't be there.
Example: https://circleci.com/gh/charpeni/react-native-website/6.
> Add check for index.html on CircleCI

- docs/images.md
Image no longer has a resizeMode property.
> Change docs to use "contain" instead Image.resizeMode.contain

- docs/image.md
Release 0.56 added support for Image.defaultSource on Android. This PR changes docs to reflect that https://github.com/facebook/react-native/commit/b0fa3228a77d89d6736da6fcae5dd32f74f3052c
> Android added support for Image.defaultSource

- docs/modal.md
In Props section animated prop is mentioned and the description is missing. Either we should add description to the prop or remove animated prop in Props list. 
In this commit, description is added as animated prop is deprecated. Use the animationType prop instead.
> Added description to animated prop in Modal.md

- docs/headless-js-android.md
I've read the following countless time: "You can do anything in your task as long as it doesn't touch UI: network requests, timers and so on" - without giving it much thought as I haven't done any headless JS. 
My brain always interpreted this the following way: "You can do anything in your task as log as it doesn't touch UI, network requests, timers and so on". Note the comma in my interpretation. So I always thought - what for do I need headless JS if I can't basically do anything in it??? 
To my dismay it turns out you can do EVERYTHING in a headless JS as long as you don't touch UI... I showed this to some other people and they also agree that you need to read the sentence few times till you get the meaning...
That's why I'm proposing the more simple formulation:
"You can do anything …
> better wording in the Headless JS docs

- docs/building-for-apple-tv.md
This PR updates the `Building for TV` doc page so that it correctly lists the dev menu buttons on Android.
Previously it says long press play/pause, however this is incorrect. The buttons are either normal press 'menu', or long press 'fast-forward'.
You can see that here:
Menu: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java#L145
FF: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java#L162
I have also confirmed this on my own Android TV!
If anyone can tell me if the iOS button is incorrect, I can also update that.
> Fix dev menu button references for Android TV

- docs/accessibility.md
I've added two props for accessibility: accessibilityRole and accessibilityStates. These are meant to indicate to talkback on android and voiceover on iOS what the purpose of a focused element is (accessibilityRole) and the state of the focused element (accessibilityState). I added documentation for each of these props.
> Updated react docs with two new props that can be set for accessiblity

- docs/performance.md
We renamed the command in this revision: https://github.com/facebook/react-native/commit/ebf5aeab280f2ebc439ec39d25c48fdf1980cf73
So we should now change docs to reflect that. Is the doc versioned, though? How do people access docs for older versions of React Native, if at all?
Thanks!
> Rename 'unbundle' to 'Random Access Modules bundle'

- docs/building-from-source.md
The current gradle version doesn't match the version in the example.
If anyone wants to build React Native Android from source won't be able to find that string because of the version mismatch.
This PR sets the gradle version to match the latest RN version (0.56)
> Update gradle version in example to match RN master

- docs/performance.md
This PR changes the information about how to get the inline requires blacklist from the Metro `verboseNames`.
After https://github.com/facebook/metro/issues/204, the `verboseNames` in Metro contain already relative paths, so the process has got way simpler now
> Update performance docs

- docs/viewpagerandroid.md
- website/versioned_docs/version-0.56/viewpagerandroid.md
Corrected few typos on ```docs/viewpagerandroid.md``` & ```versioned_docs/version-0.56/viewpagerandroid.md```
These typos exist under **onPageScroll** & **onPageScrollStateChanged** 
List of corrected typos:
- ether > either
- [0,1) > [0, 1]
- it's > its
> Fixed typos in viewpagerandroid.md

- docs/webview.md
Recently, a new required prop was introduced to render inline HTML in WebView. This PR adds a "Hello World" example.
PR for: 
- [react-native-community/discussions-and-proposals/issues/5](https://github.com/react-native-community/discussions-and-proposals/issues/5)
- [facebook/react-native/issues/20464](https://github.com/facebook/react-native/issues/20464)
> Add example with inline HTML to WebView

- docs/signed-apk-android.md
Improve docs on splitting APKs for newer version of gradle
Gradle v3.1 complains about conflicting configuration as below
<pre>
Conflicting configuration : 'armeabi-v7a,x86' in ndk abiFilters cannot be present when splits abi filters are set : x86,armeabi-v7a
</pre>
> Update docs on splitting APKs

- docs/native-components-android.md
The example was not working at all. There was a lot of code missing in order to make it work. Especially the import statements as well as methods in the `java` classes. You further used `RCTImageView` which is areserved keyword from react-native. The example was very hard to follow. It shoud be easier now.
> Added missing code

- docs/webview.md
As of React Native 0.56 to include static html you seem to need to set `originWhitelist` prop otherwise it will fail with an unhelpful error.
> Clarify how to include static html

- docs/performance.md
The folder path for `react-native-xcode.sh` in the document is deprecated and it now lives in a new location. This PR updates it to that location. Other reference to it, in https://facebook.github.io/react-native/docs/integration-with-existing-apps is correct.
> Update react-native-xcode.sh folder path

- docs/getting-started.md
Using `export PATH=$PATH:$ANDROID_HOME/emulator` instead of  `export PATH=$PATH:$ANDROID_HOME/tools` Because of Android Studio Emulator path Update, (https://stackoverflow.com/questions/40931254/could-not-launch-emulator-in-android-studio/51902207#51902207)
> Emulator bash_profile update

- docs/debugging.md
- website/versioned_docs/version-0.5/debugging.md
[`OkHttpClientProvider#replaceOkHttpClient`](https://github.com/facebook/react-native/blob/v0.56.0/ReactAndroid/src/main/java/com/facebook/react/modules/network/OkHttpClientProvider.java#L49) is no longer effective.
I updated guide for stetho to use `setOkHttpClientFactory` instead of that.
> Fix stetho instruction.

- website/pages/en/help.js
There was a tweet indicating openness to PRs for the sections on this page.
The Expo forums are preferred to the Slack group and more closely monitored by Expo contributors, so adding that here.
> [help] Adding Expo forums to list of forums

- docs/building-from-source.md
[A recent PR in react-native](https://github.com/facebook/react-native/pull/20357) (which has already been merged into master) bumped Android NDK to version r17b.  
This PRs update the links the correct version of the Android NDK
> Update Android NDK links to the current version

- docs/text-style-props.md
- docs/text.md
[This PR](https://github.com/facebook/react-native/pull/20572) makes `textTransform` be for Android too.
This PR just removes the "iOS"-tags from the style, to reflect that it's for Android too, now
> docs for `textTransform` +Android style

- docs/navigation.md
React Navigation no longer encourage support for redux and they will drop support very soon. See https://reactnavigation.org/docs/en/redux-integration.html
> Remove mention of Redux

- docs/running-on-device.md
Current instructions imply that you should update this line of code to switch between release and debug. Actually, you should just add a conditional statement to do so.
> Better instructions for "Configure app to use static bundle" when releasing iOS app

- docs/accessibility.md
"accessibleComponentType" => "accessibilityComponentType" 
This is on `CustomRadioButton` so it's not technically wrong, but I would presume a component that eventually renders a `View` with `accessibilityComponentType` would use that name in its own API.
> Correct a11y prop name in example

- docs/out-of-tree-platforms.md
- website/i18n/en.json
- website/sidebars.json
This PR adds a new page to the React Native docs that showcases other platforms that have been developed for React Native, and a bit documenting the API change that was added in https://github.com/facebook/react-native/pull/20825 . In the future, this should be able to be expanded with more information on making/maintaining React Native platforms.
> Add a new page documenting React Native's out-of-tree platform support

- docs/switch.md
Switch docs didn't reflected deprecations and new props for 0.57.
> Updated Switch docs to 0.57

- docs/upgrading.md
0.13 to 0.14 is pretty old. I think it's more important to tell people 0.57 has manual steps
> Use latest examples that need manual upgrades

- docs/animations.md
Before: `...to get an negation relationship at -300...`
After:    `...to get a negation relationship at -300...`
> Fix a-instead-of-an grammar error

- docs/props.md
Greetings component example in procs.md didnn't have enclosing jsx tag and thus failed, this is to fix that.
> Fixed props.md example on Greetings component

- docs/getting-started.md
The Ejecting documentation looks to have moved. So just fixing the broken link.
> Fixing broken Eject Link

- docs/getting-started.md
Fix some broken links in getting started, I did look around and noticed that somebody else also noticed it, I'm referring the respective issue here too.
Ref: #571
> Fix getting started broken links

- docs/getting-started.md
Emulators is located in emulators folder not tools folder in more recent versions.
> As of this release, the Android Emulator will be released separately from the SDK Tools. This release contains a variety of performance improvements, new features, and bug fixes.
>
>  [by Emulator release notes (25.3.0 (March 2017)) | Android developer](https://developer.android.com/studio/releases/emulator)
**However tools folder has high priority than emulator folder**. it makes **run the previous version of the emulator command** in the tools folder which **throws error "PANIC: ..."**.
To fix it, adjust priority of emulator folder be high than tools folder.
Sum up,
- `${ANDROID_PATH}/tools/emulator` is not working
- `${ANDROID_PATH}/emulator/emulator` is working
Following references are related …
> Adjust the path priority of the emulator folder

- docs/appregistry.md
- docs/debugging.md
- docs/geolocation.md
- docs/getting-started.md
- docs/linking.md
- docs/permissionsandroid.md
- docs/pushnotificationios.md
- docs/running-on-device.md
- docs/upgrading.md
This PR implements the proposal "Use Expo CLI in the Quick Start section of the docs":
https://github.com/react-native-community/discussions-and-proposals/issues/23
* Updates Getting Started with steps to get started using Expo CLI and up-to-date instructions for getting support.
* Updates CRNA references in the docs so that they also make sense for projects created with Expo CLI.
> Update Getting Started to use Expo CLI

- docs/getting-started.md
- website/versioned_docs/version-0.5/getting-started.md
- website/versioned_docs/version-0.57/getting-started.md
Hello!
Just fix this
https://facebook.github.io/react-native/docs/getting-started.html
> Fix 'Expo getting started' link

- docs/textinput.md
- website/versioned_docs/version-0.57/textinput.md
Small documentation tweak - added information about default value of `clearButtonMode` property to `TextInput` component.
> add default value to TextInput clearButtonMode description

- docs/integration-with-existing-apps.md
> This is for projects which integrate react-native in existing android applications.
Any Native Module which uses `startActivityForResult()` and expects to catch the result in its `onActivityResult()` would fail if we do not override the `onActivityResult()` in our React Activity and pass it on to the `ReactInstanceManager` instance created.
> Missing code for passing result to ReactInstanceManager

- docs/building-for-apple-tv.md
- docs/touchablewithoutfeedback.md
- website/versioned_docs/version-0.57/building-for-apple-tv.md
- website/versioned_docs/version-0.57/touchablewithoutfeedback.md
I encountered some problems while developing an app for Android TV using the docs.
After checking react-native commits these are the changes that i think need to be done.
based on PRs https://github.com/facebook/react-native/pull/18470 and https://github.com/facebook/react-native/pull/19718 touchableHandleActivePressIn and touchableHandleActivePressOut are now deprecated and removed forhandling focus and blur interactions and instead touchableHandleFocus and touchableHandleBlur should be used.
In addition i find it a little ambiguous and confusing using the Touchable.js method names instead of components props names. so i changed them too for better readability and integrity.
I also added onBlur and onFoucs to TouchableWithoutFeedback as there had missing description. …
> Update TouchableWithoutFeedback and Building For TV Devices

- docs/keyboardavoidingview.md
- website/versioned_docs/version-0.57/keyboardavoidingview.md
I removed the `Methods` section from the `KeyboardAvoidingView` docs.  
These methods aren't really meant to be called by the user and the method names were incorrect in the documentation.  If there is a scenario where these methods may legitimately be called by a user, let me know and I'll re-add the methods and fix their names instead
> remove methods from the KeyboardAvoidingView docs

- docs/easing.md
- website/versioned_docs/version-0.12/easing.md
- website/versioned_docs/version-0.23/easing.md
- website/versioned_docs/version-0.43/easing.md
- website/versioned_docs/version-0.5/easing.md
- website/versioned_docs/version-0.51/easing.md
- website/versioned_docs/version-0.55/easing.md
static in easing; 
to
static in(easing)
> fix typo easing

- docs/animated.md
- website/versioned_docs/version-0.5/animated.md
- website/versioned_docs/version-0.50/animated.md
- website/versioned_docs/version-0.51/animated.md
- website/versioned_docs/version-0.52/animated.md
- website/versioned_docs/version-0.55/animated.md
- website/versioned_docs/version-0.56/animated.md
- website/versioned_docs/version-0.57/animated.md
Presumably docs intend to state: 'indicating'.
> Typo: Change 'indiciating' to 'indicating'

- docs/switch.md
On [web version](https://facebook.github.io/react-native/docs/switch) camelcase anchors not supported
> Invalid anchors

- docs/understanding-cli.md
[@orta commented on 9 Aug: ](https://github.com/facebook/react-native-website/pull/462#issuecomment-411766140)
> Looks like it got pulled out into it's own repo - the right link is probably https://github.com/facebook/metro/blob/master/packages/metro-config/src/configTypes.flow.js - want to update that?
Fixed in this commit
> Fix broken link in understanding-cli.md

- website/pages/en/index.js
As we're using `cleanUrl` in Docusaurus, we don't need to add the HTML extension on links.
> Remove html extensions from links on index page

- docs/signed-apk-android.md
In React Native v0.57.4, the generated APK can be found under `android/app/build/outputs/apk/release/app-release.apk`.
This path seems to have changed with the Android Gradle plugin v3.0.0, however, there doesn’t seem to be a good reference for this change. I’ve only found similar remarks on [Stack Overflow](https://stackoverflow.com/questions/46985530/change-apk-output-folder-in-gradle-4-1/48121314#comment81522854_46985530) and on [F-Droid’s issue tracker](https://gitlab.com/fdroid/fdroidserver/issues/363#note_38091024).
> Fix path of generated APK

- website/versioned_docs/version-0.57/switch.md
The Switch docs have been updated on master, but also needs to be reflected in the 0.57 docs, since that's the first version to introduce these changes.
> Add thumbColor changes to Switch on versioned 0.57

- docs/stylesheet.md
See https://github.com/facebook/react-native/commit/a8e3c7f5780516eb0297830632862484ad032c10
`StyleSheet.create` is now an identity function, the `ReactNativePropRegistry` (`StyleSheetRegistry`) was removed.
> Removed performance section from stylesheet as no longer true

- docs/out-of-tree-platforms.md
This pull request updates the out-of-tree platform documentation to reflect the module name search pattern changes made in this commit:
https://github.com/facebook/react-native/commit/4b106be47765dd391f7a4cc6cf0e705ae977b90a
> Update Out-of-Tree Platform docs to reflect new module patterns

- docs/share.md
This commit adds a basic example to the Share API. The example highlights use of the Share.sharedAction, Share.dismissedAction, and Share.share methods as well as how they are intended to be used together.
This PR seeks to enhance API documentation through examples.
> Adds a basic example to Share API

- docs/accessibility.md
The `accessibilityStates` prop is referred to as `accessibilityState` in two places, which is wrong and causes confusion.
This fixes it!
> Add missing 's' in accessibilityStates prop mentions

- docs/datepickerandroid.md
This is maybe out of scope, but it's not obvious from the docs page that the static "methods" (dateSetAction, dismissedAction) are getters without looking at source. Is there a better way to show this in the docs?
Alternatively, is there a reason this needs to be a getter in the implementation vs a static constant string?
> fix incomplete sentence in DatePickerAndroid docs

- docs/layout-props.md
- Fixed grammar in the `aspectRatio` segment
- Changed the supported types of many props from `number, , string` to the more fitting `number, string`
> Fixes to the Layout Props page

- docs/imagebackground.md
- docs/images.md
- website/i18n/en.json
- website/sidebars.json
The `ImageBackground` component is currently hidden inside the Images docs. Since many people only skim through the sidebar when looking for a solution, that most likely will pass unnoticed. Besides, with a page of its own, the docs now include the prop reference for ImageBackground, no longer requiring that the developer reads through the source code to find the available props.
> Add docs for ImageBackground

- docs/props.md
"Notice that {pic} is surrounded by braces, to embed the variable pic into JSX. " is not a grammatically correct sentence.
It can be quickly fixed by removing the comma, but the sentence can be made more concise and clear.
My proposed fix:
"Notice the braces surrounding `{pic}` - these embed the variable `pic` into JSX." 
This changes the focus of the sentence to braces and explains more concisely what function they are performing.
> Small grammar fix

- docs/getting-started.md
Basically, when re-installing the whole suite of tools on my new laptop, I noticed that all the newer JDKs where creating issues when trying to run React Native on Android.
So I think we should stick to the JDK 8 until we are fully supporting the newer ones 😅
> Tweak the wording of the getting started to stick to jdk 8

- docs/picker-item.md
The prop descriptions of the 'color' and 'value' prop in picker-item.md were switched. Changed them to their proper positions.
> Fixed prop descriptions of 'color' and 'value' props in picker-item.md

- docs/state.md
I felt like returning unnecessary element with `' '` is not a great practice for beginners to follow along with.
- Added pre-check condition that returns `null` on `isShowingText is False`.
Functions with just `return` could be wrapped with parenthesis instead of curly brace + `return` keyword.
- Refactor unnecessary curly braces with parenthesis.
> Refactor State doc to return proper element and keep consistent format.

- docs/switch.md
Update the Switch prop tintColor to match source code
https://github.com/facebook/react-native/blob/0.57-stable/Libraries/Components/Switch/Switch.js (line 120)
> tintColor is deprecated, updated docs to reflect this change

- docs/view-style-props.md
The `Shadow Props` are currently only references in the `Image` > `style` section, which suggests they're only available there. I think that's misleading and the shadow properties are also available in `View` styles. Along the (more obvious) layout and transform props. 
This PR aims to make it clear which properties can be used within a `View`'s style.
> Add reference to shadow props in View style docs

- docs/images.md
Its unclear in the docs that the 1x version should be included too when providing @2x and @3x images. I believe that you do need it, correct me if I'm wrong?
File structure should be:
```
└── img
├── check.png
├── check@2x.png	    
└── check@3x.png	    
```
not
```
└── img
├── check@2x.png	    
└── check@3x.png	    
```
> File structure should include the 1x version too.

- docs/webview.md
- website/versioned_docs/version-0.57/webview.md
We've forked WebView into [react-native-community/react-native-webview](https://github.com/react-native-community/react-native-webview), but I think we forgot to update the documentation.
> docs(webview.md): Tell people to use community fork

- docs/out-of-tree-platforms.md
Add React Native Turbolinks as a solution to build hybrid apps with react-native
> Add React Native Turbolinks

- website/blog/2018-05-07-using-typescript-with-react-native.md
Good morning! I wrote this blog post earlier this year, but Babel 7 has since been released with builtin TypeScript support. Since this blog post has become very popular among people looking for TypeScript with React Native, I have been receiving an increasing number of requests from the community to update the blog post to point to Babel 7 instructions.
This pull request adds a section to the introduction of my blog post that gives instructions for Babel 7, includes a brief description of its limitations, and points to workarounds written by @damassi. /cc @ds300 who wrote react-native-typescript-transformer.
> Updates React Native with TypeScript post with Babel 7 instructions

- website/pages/en/help.js
The forum is dead.
Also removed "at large" because "Communities" should be good enough as a headline.
> Remove discuss.reactjs.org.

- docs/touchableopacity.md
RN's touchableOpacity appears to be sensitive for `style` prop, but I us not included in docs (neither here nor in `touchableWithoutFeedback`). I'm not sure whether this feature should be documented. If not, please close this PR.
> Add style props for TouchableOpacity

- docs/performance.md
config object projectRoot setting is added.
ROOT_FOLDER path resolve bug is fixed.
> performace doc config.js some issue is fixed.

- docs/images.md
It seems that the links for "packager defaults" and "packager config file" are transposed.
> Swap Static Non-Image Resources documentation packager links

- docs/navigation.md
Issue #684 
Added `createAppContainer` to example to conform to the React-Navigation breaking changes listed here
https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html
> added createAppContainer to example

- docs/textinput.md
Adds docs for facebook/react-native#21575
New prop `autoComplete` on `TextInput`.
> Update textinput.md with autoComplete

- docs/geolocation.md
Hello,
I feel like it'd be better to use the `Google Location Services API` by default in React Native, but it might be a blocker since it uses the Google Play Services.
It is far way superior than `android.location` though, so I think this should be stated in the React Native docs.
> Add a notice on Geolocation API for Android

- docs/getting-started.md
This allows windows to find adb.exe, a file required for react-native run-android to work properly.
> Added instrutions to add platform-tools to Path.

- website/pages/en/versions.js
Changed it to be consistent with the rest of the titles with “versions” in it.
> Lower cased “versions”

- docs/stylesheet.md
It literally points to the same reference as absoluteFill.
https://stackoverflow.com/questions/53676723/react-native-what-is-the-difference-between-stylesheet-absolutefill-and-styl/53775303#53775303
> Remove absoluteFillObject

- docs/animated.md
- website/versioned_docs/version-0.44/animated.md
- website/versioned_docs/version-0.46/animated.md
- website/versioned_docs/version-0.48/animated.md
- website/versioned_docs/version-0.49/animated.md
- website/versioned_docs/version-0.5/animated.md
- website/versioned_docs/version-0.50/animated.md
- website/versioned_docs/version-0.51/animated.md
- website/versioned_docs/version-0.52/animated.md
- website/versioned_docs/version-0.55/animated.md
- website/versioned_docs/version-0.56/animated.md
- website/versioned_docs/version-0.57/animated.md
The `Animated.loop` documentation didn't explicitly show it takes an optional `config` object as a second argument nor did it follow the same format as other functions on the same page.
Also went back and updated the docs from `0.44` onwards. That's as far back as the docs mention the `loop` function from what I could see.
> Document Animated.loop config in the same style as other functions

- docs/text-style-props.md
The docs say that `letterSpacing` is iOS-only but it also works on Android.
Why do we document the `Text` styles in both `text.md` and `text-style-props.md`?
Adam Comella
Microsoft Corp.
> Text: Indicate that `letterSpacing` works on Android

- docs/text.md
- docs/textinput.md
RN PR that introduced the `maxFontSizeMultiplier` prop on iOS: https://github.com/facebook/react-native/pull/20915
There are some other minor changes due to running prettier on the files I touched.
Adam Comella
Microsoft Corp.
> Text/TextInput: Document `maxFontSizeMultiplier` prop

- docs/text.md
This feature is difficult to implement at the native level.
Original issue: https://github.com/facebook/react-native/issues/22811
> Add no support for numberOfLines on nested Text

- docs/getting-started.md
As I faced problem in setting up the react-native environment in my windows machine with AMD processor. It is hard to understand where the problem is. Most of the time we guide on the basis of Operating system but sometimes all the things are not working same in all the processors. Here 'android-studio' is not working correctly. The android emulator is not able to open as there is no intel HAXM. This is simple update for the AMD users.
> Update getting started for AMD users.

- website/pages/en/index.js
I am planning a more thorough overhaul of the home page but I want to get these small changes in for now, even if they won't stay around for too long. After reading through the React Native website I got the feeling that the React Native project is somewhat pretentious. I'm not trying to blame anyone, I believe this accumulated over years and 2019 is quite different from 2015 – I would have probably written things in a similar style back then. I would like to thoroughly change the website to give a more modest and mature impression of React Native. Instead of touting how amazing React Native can be, I believe we should aim to be highly informative and simplistic in our language instead of joking around. Let the technology speak for itself and give people that wow effect.
The particular …
> More modest introduction to React Native.

- website/i18n/en.json
- website/siteConfig.js
- website/static/css/header.css
I'm starting on revamping the website a bit. This is a very simple first step. This diff changes the header to:
* Remove the link to React. I'm sure people can find the React website on their own, and we can reclaim some header real-estate for later use.
* Fix the search icon which was way too low
* Make the version number slightly less prominent by removing the underline and making the font smaller.
Before and after:
> Minor header changes

- docs/getting-started.md
My team is working on a proposal for making the Getting Started Guide more clear (right now, most people think the only way to use React Native is via Expo). In the meantime, I'd like to make this small addition.
With nearly 10k stars on Github, Ignite CLI has been the most popular third-party CLI to init React Native apps for three years now. So I'd like to add it to the Getting Started Guide.
> Add Ignite CLI to Getting Started guide

- docs/running-on-simulator-ios.md
From react-native version 0.57.3 default simulator is no longer iPhone 6. More info - https://github.com/facebook/react-native/commit/1d1a41e303c0af5acc1e05b2f5c7928809e6bf62
> Changed default iOS simulator from iPhone 6 to iPhone X

- docs/textinput.md
React Native has this issue where when using a `TextInput` with `multiline` set as `true`, the text is aligned to the top on iOS and to the center on Android by default, which causes confusion, evidenced by the amount of likes in [this comment](https://github.com/facebook/react-native/issues/13897#issuecomment-300735822). I believe the `textAlignVertical` default should be changed when `multiline` is `true`, but since I don't know if there are any reasons the issue I linked was closed, I suggest this is at least documented.
> Add warning about multiline centering the text on Android

- docs/virtualizedlist.md
Noticed the FlatList in the previous section was a link but not the next reference. Made it a clickable link.
> Make FlatList reference link

- docs/building-from-source.md
- docs/getting-started.md
- website/versioned_docs/version-0.5/building-from-source.md
- website/versioned_docs/version-0.5/getting-started.md
In RN 0.58, we use Android SDK 28, NDK 17c and build tools 28.0.3. This corrects tools version in the doc.
> update Android SDK to 28 in docs

- docs/getting-started.md
Following up on #749, I missed a section. This adds it there too.
cc @charpeni
> Add Ignite CLI to iOS section too

- docs/image-style-props.md
Due to changes on the Fresco website currently link on the Image Style Props points to non existing page.  This PR replaces old link with new valid one.
> Fix Fresco docs link on the Image Style Props page

- docs/textinput.md
Makes the docs much more useful!
> Link to all KeyboardType screenshots

- docs/getting-started.md
Reading the first page of https://facebook.github.io/react-native/docs/getting-started.html, it is not clear that the node version needs to be 8+. Just adding this here to help others with installation, specially those of us who already have node running and need to upgrade.
> Node version requirement made more prevalent

- docs/touchablehighlight.md
It's clear from https://github.com/facebook/react-native/issues/11834 that the underlying issue won't be fixed, so we should update the documentation so people understand that for `activeOpacity` to work they need to set `underlayColor`.
> Explicitly state that `activeOpacity` requires `underlayColor`

- docs/getting-started.md
This is a trivial change, it just changes the wording of a sentence because I, subjectively, believe that it conveys better it's meaning that way.
Rationale: the way I read `install Xcode and set up your Android development environment.` is that it's giving instructions in a sequential way, that is, telling the user to install Xcode and, after that, set up the Android dev environment. Of course, after the initial confusion, anybody will be able to tell that such an interpretation is not right and the problem will be solved, but if that initial confusion could be avoided by making the sentence clearer (using "or" instead of "and") I think it'd be great.
This change is a totally subjective nitpick, so if the maintainers disagree with it you can just close the PR.
> Change wording to improve sentence

- docs/text.md
- docs/textinput.md
Introduced by this commit: https://github.com/facebook/react-native/commit/4936d284df36071047ce776d9e2486c0371f7b97
Adam Comella
Microsoft Corp.
> Text/TextInput: Android now supports `maxFontSizeMultiplier` prop

- docs/upgrading.md
This guide points to rn-diff which is not very active, and uses `git-upgrade` which doesn't show
> changes in the project template files
at all.
[rn-diff-purge](https://github.com/pvinis/rn-diff-purge) is kept up to date, it's much much easier to keep going, as it's literally purging the old version, making a new one and then diffing them. This way people can see the actual changes in the template.
Some more info [here](https://github.com/react-native-community/discussions-and-proposals/issues/68#issuecomment-452227478) if needed.
> update to rn-diff-purge

- docs/integration-with-existing-apps.md
- website/versioned_docs/version-0.5/integration-with-existing-apps.md
Issues: Related to [#13439](https://github.com/facebook/react-native/issues/13439)
PR: Related to [#23336](https://github.com/facebook/react-native/pull/23336)
fix android code,and also docs need to change
@cpojer
> fix_#23336

- docs/testing.md
Adds information about Detox end-to-end tests to the "Contributing > Testing your Changes" page.
This makes it easier for contributors to understand the role Detox tests play, encourages them to add additional tests, and will serve as a linking point for more thorough "how to add Detox tests" content to be added soon.
> Testing page detox

- docs/text.md
Updated minor code snippet typo in text.md file. Common mistake that is easily missed by the human eye. Example: "Where is the the laundry Brock? I have had had just about enough of you."
> Update code snippet typo in text.md

- docs/running-on-device.md
The `AppDelegate.m` template already has the changes mentioned in the 3rd section, so this step is unnecessary in the documentation.
https://github.com/facebook/react-native/blob/master/template/ios/HelloWorld/AppDelegate.m#L35
I'm also curious if the code mentioned in the first "Pro Tip" should be included in the template as well?
> Remove section that's already included in the template

- docs/upgrading.md
Latest React Native CLI will bring an improved `upgrade` command, see: https://github.com/react-native-community/react-native-cli/pull/176
This PR attempts to document it.
cc @cpojer @pvinis @kelset
> docs: update the upgrading guide

- website/versioned_docs/version-0.5/understanding-cli.md
`cliEntry.js` should be replaced with `cli.js`, since that is the new filename of this entry point.
> Fix cliEntry.js reference in understanding-cli docs

- docs/text.md
> add fontFamily supporting only one font doc

- docs/stylesheet.md
Forgot to remove that in my last PR. https://github.com/facebook/react-native-website/commit/5dd1bf4df7bf4b5bab6aa94d43017a4b589e06fe
> Remove absoluteFillObject link

- docs/share.md
Running this code example causes an error with the latest version of RN because the `Button` component expects a `title` prop. Secondly, the `async` function was written incorrectly.
> Update Share API docs

- docs/appregistry.md
Added documentation for registerCancellableHeadlessTask and cancelHeadlessTask.
Fixed parameter names for parameters which were renamed.
> Updating AppRegistry.md to add documentation for new methods

- docs/accessibility.md
- docs/view.md
Documentation updates related to https://github.com/facebook/react-native/pull/22047
> Accessibility Escape

- docs/signed-apk-android.md
The `-genkey` parameter for `keytool` is deprecated, `-genkeypair` is preferred according to the [keytool docs](https://docs.oracle.com/javase/6/docs/technotes/tools/solaris/keytool.html#genkeypairCmd).
> Update keytool parameter in signed-apk-android.md

- website/blog/2019-03-12-releasing-react-native-059.md
The JSC changes in the 0.59 blogpost had an incomplete contributors list. There are a lot of folks who put in work over a multi-year timespan that I missed. This PR adds those missing parties based off of discussions with those involved and research I did.
> [0.59][Blog] Add missing contributors to attribution list for JSC changes

- docs/native-modules-ios.md
Since there is an annoying warning logged at every startup, and it wasn't clear to me until I dug in a bit that it was a class method on the module, I thought this note would be helpful.
> Add note about implementing requiresMainQueueSetup

- docs/textinput.md
- website/versioned_docs/version-0.59/textinput.md
[A PR in 0.59](https://github.com/facebook/react-native/commit/11df0ea) introduces TextInput prop rejectResponderTermination for iOS; this PR adds the missing docs.
Looks like my format on save also struck and changed a few lines in a table.
> Add entry for new iOS TextInput prop rejectResponderTermination

- docs/image.md
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Replaced "compile" to "implementation"

- docs/appregistry.md
Fix `registerCancellableHeadlessTask` description formatting from `h2` to regular text
> Fix registerCancellableHeadlessTask description

- docs/javascript-environment.md
`metro-react-native-babel-preset` includes 'Optional Chaining' proposal so I thought that this is interesting enough feature to highlight it on the list of available JS transformations in RN environment.  
I have also introduced few small changes to examples just to make them consistent in code style.
> Add 'Optional Chaining' to list of JS transformations

- docs/accessibilityinfo.md
Update `AccessibilityInfo` doc to follow the new methods and events (please refer to https://github.com/facebook/react-native/pull/23839, https://github.com/facebook/react-native/pull/23913)
It adds these new methods: 
* `isBoldTextEnabled()`
* `isGrayscaleEnabled()`
* `isInvertColorsEnabled()`
* `isReduceMotionEnabled()`
* `isReduceTransparencyEnabled()`
And the corresponding event listeners:
* `boldTextChanged`
* `grayscaleChanged`,
* `invertColorsChanged`,
* `reduceMotionChanged`
* `reduceTransparencyChanged`
> Update AccessibilityInfo with new methods and events

- docs/props.md
Due to the full bleed on iPhone X, the top gets completely cut off in this example. Setting the view 50 from the top makes all of the greetings visible.
> Render example correctly on iPhone

- docs/communication-android.md
- docs/communication-ios.md
- docs/native-modules-android.md
Related to #844 
> Updated occurences of outdated lifecycle methods like `componentWillMount` to `componentDidMount`
> Remove references to outdated lifecycle hooks

- docs/image.md
- docs/text.md
- docs/touchablewithoutfeedback.md
- docs/view.md
I noticed RN docs mention type "node" in most place (except button, why? no idea).
But in practise, it seems codebase has this typed as string, see https://github.com/facebook/react-native/search?p=2&q=accessibilitylabel&unscoped_q=accessibilitylabel
You can notice that ios & android implementation explicitly use string (same for the (react-native-)web).
The only place we see node in the codebase, is in the deprecated props, see https://github.com/facebook/react-native/blob/408207b356849ca3cefad0ce91a3889e73bd8682/Libraries/DeprecatedPropTypes/DeprecatedImagePropType.js#L34
> Fix: accessibilityLabel is a string

- docs/netinfo.md
I think it would be helpful to mention that NetInfo is deprecated since v0.59.
> Add deprecation notice to NetInfo

- docs/performance.md
rAF is not available via TimerMixin anymore. It's polyfilled into the global scope and the documentation needs to reflect that.
> requestAnimationFrame polyfill now in global scope

- docs/sectionlist.md
As mentioned in the issue it should be `Section` and not `Separator`
Fixes: https://github.com/facebook/react-native-website/issues/855
> fixes to sectionlist docs

- docs/touchablewithoutfeedback.md
As explained in https://github.com/facebook/react-native/issues/1352#issuecomment-106938999 any child components passed to TouchableWithoutFeedback must pass through their props to the React Native View component. This adds that information to its docs.
> TouchableWithoutFeedback responder props gotcha

- docs/backandroid.md
- docs/listview.md
- docs/modal.md
- docs/switch.md
- docs/transforms.md
- docs/vibrationios.md
- docs/virtualizedlist.md
- docs/webview.md
- website/versioned_docs/version-0.59/asyncstorage.md
- website/versioned_docs/version-0.59/imagestore.md
- website/versioned_docs/version-0.59/maskedviewios.md
- website/versioned_docs/version-0.59/netinfo.md
- website/versioned_docs/version-0.59/slider.md
- website/versioned_docs/version-0.59/viewpagerandroid.md
Standardize the deprecation notice under a quote markdown, and deprecated Lean Core packages that have been removed in 0.59.
Closes #848.
> Add deprecated notices

- docs/getting-started.md
On my machine with Manjaro Linux 18.0.3 bash profile doesn't work, but .bashrc works.
Bash version: 5.0.0(1) release
uname:
Linux marat-pc 4.19.23-1-MANJARO
> Replace bash profile to bashrc

- docs/linking.md
When I copied this example code into my AppDelegate.m:
```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
return [RCTLinkingManager application:application
continueUserActivity:userActivity
restorationHandler:restorationHandler];
}
```
I got the following warning when compiling my project:
```
⚠️  /my/file/ios/Project/AppDelegate.m:72:152: conflicting parameter types in implementation of 'application:continueUserActivity:restorationHandler:': 'void (^ _Nonnull __strong)(NSArray<id<UIUserActivityRestoring>> * _Nullable __strong)' vs 'void (^__strong _Nonnull)(NSArray * _Nullable __strong)' [-Wmismatched-parameter-types]
- (BOOL)application:(UIApplication …
```
> Fix compilation warning for mismatched param types

- docs/textinput.md
It would have been helpful to know that `onSelectionChange` only works when `multiline` is enabled, hence the change to help others from running into the same issue without knowing what is wrong :)
Fixes #880
> Correct documentation for `onSelectionChange`

- docs/statusbar.md
* [`setNetworkActivityIndicatorVisible` is only available on iOS' ](https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L290)
* [`setBackgroundColor` is only available on Android](url);
* [`setTranslucent` is only available on Android](https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L319)
> docs(status): add platform for for non-cross-platform methods

- docs/accessibility.md
- docs/view.md
https://github.com/facebook/react-native/pull/24344
Remove deprecated `accessibilityComponentType` and `accessibilityTraits` props.
> chore: remove accessibilityComponentType and accessibilityTraits props

- docs/accessibility.md
I think it's important to not only talk about testing for VoiceOver in accessibility page but also about TalkBack for Android. 
Thus, this PR adds a small section about it, adding info about how to install TalkBack on the emulator, how to enable it, how to use the shortcut in the device or via terminal.
> docs: add info about Android TalkBack into accessibility page

- website/versioned_docs/version-0.58/textinput.md
- website/versioned_docs/version-0.59/textinput.md
> Remove autoComplete prop from 0.58 & 0.59

- docs/activityindicator.md
The docs say that the default color of the activity indicator is gray, however it is a dark cyan shade on Android.
Updating the docs to state it correctly.
To be precise, the default color depends on the Android theme that a developer chooses or the default theme of the phone. However, unless something is modified, it's mostly this green.
<table>
<tr>
<td align="center">
Native <br/><code>ActivityIndicator</code><br/> on Android
</td>
<td align="center">
Native <br/><code>ActivityIndicator</code><br/> on iOS
</td>
</tr>
<tr>
<td align="center">
</td>
<td align="center">
</td>
</tr>
</table>
> Fix default ActivityIndicator color on Android

- docs/alert.md
As can be seen in the implementation, there is no type argument for `Alert.alert`:
https://github.com/facebook/react-native/blob/master/Libraries/Alert/Alert.js#L47
> Docs - Alert.alert() does not have a type argument

- docs/alert.md
In the next version of RN, `cancelable` will be `false` by default.
I changed the documentation to explain not how to opt-out but instead to opt-in to dismissable popups.
I have also mentioned that the behavior changed in v0.60 and have clarified that the option has no effect on iOS.
> Behavior changes to the `cancelable` option

- docs/layout-props.md
Has been a source of confusion because the wording states that flex on RN is different than CSS but doesn't detail how it's different when actually flex is quite similar to CSS. Ideally it would be nice to get a code pointer to implementation in Yoga but haven't found a clean place to point.
examples of confusion: 
https://stackoverflow.com/questions/43143258/flex-vs-flexgrow-vs-flexshrink-vs-flexbasis-in-react-native
https://github.com/facebook/react-native/issues/11565
> Update flex description

- docs/signed-apk-android.md
This PR updates signed-apk-android with a recommendation to use Android App Bundle as opposed to the traditional method of building APK (or split APKs).
The benefits of using Android App Bundle is that it allows for automatic APK splitting done by Google Play. This way saving developers from distributing natively compiled binaries (especially JSC) compiled for four CPU architectures to all their users.
I described the motivation behind this more on a blog post here https://blog.swmansion.com/make-your-react-native-app-3x-smaller-44c993eda2c9
Notes: I decided to rename the section to "Publishing to Google Play Store" as the previous title was no longer relevant but keeping the "id" the same to keep the same URL
> Recommend using Android App Bundle for publishing Android app

- docs/layout-props.md
- website/versioned_docs/version-0.57/layout-props.md
Hello react-native-website team
Based on https://github.com/react-native-community/releases/blob/master/CHANGELOG.md , https://github.com/facebook/react-native/commit/b81c8b5 , and https://github.com/facebook/react-native/commit/5906c26466f347ff74fc637ecb33ceeb908269e0 , the bug specified in the docs, which says "overflow: visible only works on iOS. On Android, all views will clip their children." should be fixed for 0.57 and up. 
Sorry if I did something wrong, first time :)
> fixed Layout props saying overflow does not work on android for 0.57+

- docs/actionsheetios.md
`ActionSheetIOS.showActionSheetWithOptions()` accepts `anchor` as options (cf https://github.com/facebook/react-native/blob/758eb9fa7bba1d1a14fd8c8870e2a00ad3a31809/Libraries/ActionSheetIOS/ActionSheetIOS.js#L46), but it is not documented.
resolves #892
> document existence of `anchor` option

- docs/getting-started.md
I think this should be removed since Nuclide is being retired: https://nuclide.io/
> Remove references to Nuclide in Getting Started

- docs/getting-started.md
Change "specifc" to "specific" in getting-started page
> Fix typo in getting started page

- docs/layoutanimation.md
`checkConfig` has been disabled and should be removed from documentation.
From the RN codebase:
```
checkConfig(...args: Array<mixed>) {
console.error('LayoutAnimation.checkConfig(...) has been disabled.');
},
```
> Remove disabled checkConfig from LayoutAnimation API documentation

- docs/appregistry.md
There is a missing horizontal section rule between `registerCancellableHeadlessTask()` & `startHeadlessTask()`, thus, rendering the text in a large font. Corrects rendering of paragraph text.
Here is the complete description of the current issue.
> fix(typo): add horizontal rule

- docs/getting-started.md
[This commit](https://github.com/Rahul-Sagore/react-native-website/commit/d97faeede73db2b8962db87a372ea1ff02777da8#diff-a39c9f7aa728d5fa3b973bc6ba49228a) on 13th march changed the Tab title from **Building Projects with Native Code** to **React Native CLI Quickstart**.
But "Building Projects with Native Code" was still getting used in documentation below. It needed update too.
> Update getting started Tab title everywhere

- CONTRIBUTING.md
- docs/getting-started.md
As discussed with @cpojer - we should stop directing people to a JDK download site where it is seemingly impossible to fetch a JDK8 install, and even if it were possible would be subject to sub-optimal update and license policies.
Commit message with resasoning for the specific change and a link for more context follows:
Markdown: emphasize non-Oracle OpenJDK distribution
As of April 2019 Oracle restricts it's non-OpenJDK distributions to
non-commercial use, and the Oracle OpenJDK builds will not be updated
promptly for security patches
non-Oracle OpenJDK versions will still be distributed as users would expect
(open-source and unrestricted commercial use, plus regular updates), so the
getting started guide should emphasize non-Oracle OpenJDK versions
Of those, the AdoptOpenJDK project …
> Emphasize non-Oracle OpenJDK distributions in Getting Started guide

- docs/animations.md
- docs/debugging.md
- docs/getting-started.md
- docs/more-resources.md
- website/package.json
- website/pages/en/versions.js
- website/siteConfig.js
- website/versioned_docs/version-0.58/geolocation.md
- website/versioned_docs/version-0.58/listview.md
- website/yarn.lock
- Update Docusaurus to 1.9.0
- Enable collapsible side bar
- Clean up some hrefs that were pointing to `.html` extensions. This should have been done when the `cleanUrl` option was enabled but it still works because we generate both `/path/index.html` and `/path.html` in v1. This will break in v2 so better change it now.
- Enable the scroll-to-top button
> Update Docusaurus to 1.9.0

- docs/components-and-apis.md
The links on the[ components and api page](https://facebook.github.io/react-native/docs/components-and-apis/) to the respective components are all broken. 
This was due to them pointing to docs/components-and-apis/"component-name" when it should be docs/"component-name"
> Fix broken links

- CONTRIBUTING.md
These guidelines are outdated and we do not recommend people to write guides like that any longer. This change refers people to the contributing guidelines in the RN repo, which also mentions documentation changes.
> Remove the "Guidelines for Text".

- docs/performance.md
This removes outdated docs although we definitely need to rewrite most of this page in the future.
> Remove outdated docs about Metro's configuration file.

- docs/datepickerios.md
Adding APIs for #929 
Alphabetized
Added APIs
-initialDate
-onChange
> update datepickerIOS with new APIs for #929

- .gitignore
- netlify.toml
- website/package.json
- website/siteConfig.js
- website/sync-community-repos.js
- website/yarn.lock
* A script to fetch the list of repos from the Community Github Org and then parse out the information that we need.
* An example page to display the repo information.
* Run the scripts when the CI server, and Netlify, builds the website.
This PR is meant to start a conversation about what we would like to include on the community page of the website. There are still lots of open questions:
Currently, I have just included the first paragraph of the [meta repo](https://github.com/react-native-community/meta) and a bare bones repo list. There is a lot more we could include:
* Highlight the key repos like "releases", "discussions-and-proposals", and "meta".
* Include some information about why the org exists and what the difference between the libraries contained in it and from other …
> Add page for the Community Github Org with list of repos

- docs/flatlist.md
- website/core/Footer.js
Call out flexWrap anti-pattern for multi-column layouts.
Clean up renderItem docs a bit.
> [FlatList] Add note on multi-column layouts

- docs/scrollview.md
- website/i18n/en.json
- website/versioned_docs/version-0.59/scrollview.md
Original issue #883 
"the keyboard will not dismiss automatically when the tap was handled by a children"
"the keyboard will not dismiss automatically when the tap was handled by children of the scroll view"
as suggested by @wagnermaciel
This is my first time ever making a pull request to an open source project and i'm not entierly sure about the changes in `website/i18n/en.json`  but they were automatically generated and i saw that that particular file was supposed to be included according to the `.gitignore` so i left them there and brought them along.
> Typo in ScrollView documentation #883

- website/i18n/en.json
- website/sidebars.json
- website/siteConfig.js
- website/versioned_sidebars/version-0.59-sidebars.json
As a follow up of #934, by @cpojer 
> I'm wondering if there is a way to split up the Docs and API pages into two separate top-level entry points both with their own sidebars? For Docs, it should only have the Guides sections and for API it should have the Components and API sections. Is this possible?
This PR splits up the Docs and API pages into two separate navigations.
Note that this only takes effect in the 0.59 docs onwards. We could technically go back and edit the sidebars for all the previous versions but not sure if it'll be worth it. I could do it the maintainers think it's necessary. But modifying old versions is not recommended and even I'm not sure what undesired consequences there will be.
Now there are two top-level entry points for docs-related content - Docs and API
> Split up Docs and API

- docs/images.md
- website/i18n/en.json
- website/versioned_docs/version-0.59/images.md
Fix #863 
The linked `Config.js` file was moved to `react-native-community/cli` and gives 404 now. I've replaced it with a link to the Metro config option `assetExts` as explained [here](https://github.com/facebook/react-native-website/issues/863#issuecomment-495602772).
I've added a 2nd link to the 'Metro configuration' which is a bit redundant, but it doesn't hurt. Let me know if you want it.
> Fix #863 - broken link in Images guide

- website/siteConfig.js
The website should still default to 59 until we release 0.60.0.
And we are still having issues publishing 0.60 RC 0.
Having the website point to a version not out yet will only lead to confusion.
> Set back the default to 59

- .circleci/config.yml
Storing `node_modules` in a workspace archive is not recommended, as the archive needs to be uploaded to the CDN before it can be downloaded again by dependent jobs. Using the cache to persist the git repo across jobs should speed up builds.
Brings the Circle CI config in line with what we're doing for the core repo.
> [CI] Migrate to Circle CI 2.1

- website/package.json
- website/yarn.lock
Follow up of https://github.com/facebook/react-native-website/pull/934. Upgrades Docusaurus to v1.11.0 which contains a fix of the problem where the blog sidebar was collapsed because the docs had a collapsible sidebar.
> Update Docusaurus to v1.11.0

- docs/getting-started.md
> Small typo in the documentation

- docs/animations.md
I found that the examples link are outdated. So, I find some similar link to update it.
> Update examples link

- docs/textinput.md
> autoCompleteType Spelling Error

- docs/components-and-apis.md
Currently, in [Components and APIs](https://facebook.github.io/react-native/docs/components-and-apis), links to most components/APIs are broken, because they incorrectly start with `../`. Also, some links end with `.html`, which is inconsistent with the rest of the website.
This PR fixes and canonicalizes the links.
> Fix broken links in Components and APIs

- docs/appstate.md
Changes for `AppState` are merged into RN (https://github.com/facebook/react-native/pull/25039), so this PR adds info about new events for said component.
> Update docs for AppState module

- docs/touchablewithoutfeedback.md
> docs(TouchableWithoutFeedback): property `backgroundColour` doesn't exist

- docs/headless-js-android.md
Updates documentation to reference alternative solution introduced in https://github.com/facebook/react-native/pull/23231 for usages of `setTimeout` in a headless JS task, where the intention of the timeout is to block execution of the remainder of the JS task.
> Update docs to reference ability to retry headless JS tasks

- docs/keyboardavoidingview.md
- docs/progressbarandroid.md
This is part of #929 
> The properties of these component has not changed
- An additional text to [`indeterminate`](https://github.com/facebook/react-native/blob/master/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.android.js#L25) prop
- An additional text to [`behavior`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L35) prop
- An additional text to [`keyboardVerticalOffset`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L52) prop
> Update progressbarandroid.md & keyboardavoidingview.md

- docs/datepickerios.md
Countdown is actually a native prop in iOS and can be used.
> Add doc for countdown

- docs/linking.md
This PR is in reference to Issue [#929](https://github.com/facebook/react-native-website/issues/929)
Pertinent code is [here](https://github.com/SaraChicaD/react-native-website/blob/master/docs/linking.md):
```
sendIntent()
javascript
sendIntent();
Android-Only. Launch an Android intent, with or without extras (optional key-value pair).
```
and is derived from [here](https://github.com/facebook/react-native/blob/master/Libraries/Linking/Linking.js):
```
/*
* Launch an Android intent with extras (optional)
*
* @platform android
*
* See https://facebook.github.io/react-native/docs/linking.html#sendintent
*/
sendIntent(
action: string,
extras?: Array<{key: string, value: string | number | boolean}>,
): Promise<void> {
if (Platform.OS === 'android') {
return NativeLinking.sendIntent(action, …
```
> Updates Docs: Linking

- docs/style.md
Adds missing period to abbreviation `e.g.`
> Add missing period to abbreviation

- docs/appstate.md
The previous link seems to have been deprecated and is currently displaying an index page for UIKit.
> Fix AppState Apple documentation link

- docs/running-on-simulator-ios.md
Changing iPhone 4s to iPhone 5s as newer xcode versions doesn't support iPhone 4s anymore.
> Updated docs on running on ios simulator

- docs/using-a-scrollview.md
Link goes to deprecated component, which then links onward. This links directly to the new component.
> change link from deprecated component

- docs/handling-text-input.md
As seen in the "Controlled Components" article, it is generally recommended to keep state as "true". In this TextInput, the value prop is not set to the state like in the "textinput.md" doc.
> Added value prop to the TextInput

- website/versioned_docs/version-0.5/upgrading.md
This PR is related to react-native-community/upgrade-helper#38 and adds [Upgrade Helper](https://github.com/react-native-community/upgrade-helper) tool as an option to the `Upgrading to new React Native versions` documentation. It also:
1. Puts "how to automatic upgrade with CLI without Git" in a troubleshooting section;
1. Recommends [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project) as a way to clear project cache after you upgrade but have encountered errors with version mismatch;
1. Uses `yarn` instead of `npm` when asking for installing dependencies.
The second one is done mostly because there was work done by @mikehardy on turning the package into a plugin for the CLI so the user can simply run `react-native clean-project`.
I'm very much open for …
> Add `upgrade-helper` as an upgrading option

- docs/scrollview.md
The `duration` prop was added in [#22884](https://github.com/facebook/react-native/pull/22884). But was revert [here](https://github.com/facebook/react-native/commit/4c69ccd0fb55e994bd4604e5194206e442ec5958#diff-f8f8b220fc0d1573e4f8b78c84415075).
See the issue [#25589](https://github.com/facebook/react-native/issues/25589) in the React Native repository.
> delete deprecated duration prop from ScrollView

- docs/view.md
The example for the `pointer-events` prop of view specifies an invalid value of `all`. This PR corrects this by changing the example value to `auto` instead.
> Fix invalid example of <View> pointer-events value

- docs/flexbox.md
Simple typo fix in documentation.
> Fix typo in 'aligItems'

- docs/flexbox.md
- docs/linking.md
- docs/pickerios.md
Fixes #1122 
The anchor was camelCase instead of lower case
> Fix send intent link

- website/core/RemarkablePlugins.js
The Expo SDK version map for embeds isn't being kept up to date and I believe it makes most sense / is consistent with the React Native Web Player to just use the latest version all the time.
> Remove Expo SDK version mapping for embeds and use latest instead

- README.md
These recommendations look a lot like "install this thing globally" but everything is available and used via the local dependencies. These should be dropped.
> Removes steps not needed from the website setup

- docs/components-and-apis.md
This remove the deprecated `NavigatorIOS` from [Components and APIs](https://facebook.github.io/react-native/docs/0.59/components-and-apis) section
> remove deprecated NavigatorIOS reference

- docs/hermes.md
Related to : https://github.com/facebook/react-native/issues/25679
To use `Hermes` with `ProGuard`, rule should be added to prevent crash.
It would be nice to let everyone know this in the document.
> Add ProGuard rule for using Hermes

- website/versioned_docs/version-0.59/linking.md
"openSettings" is only available from v0.60 on.
See https://github.com/facebook/react-native/blob/0.59-stable/Libraries/Linking/Linking.js.
> Remove `openSettings` from docs for v0.59

- website/versioned_docs/version-0.60/debugging.md
Adds https://github.com/facebook/react-native-website/pull/1195 to the current version
> Update React DevTools link in 0.60

- docs/pushnotificationios.md
The `details` parameter of `presentLocalNotifications` is translated to a OBJ-C [`UILocalNotification`](https://developer.apple.com/documentation/uikit/uilocalnotification) and thus has all its parameters, including `alertTitle`.
> Mention `alertTitle` parameter for `presentLocalNotification`

- docs/layoutanimation.md
Adds full API documentation for the LayoutAnimation API, and clears up some clarity problems in the LayoutAnimation docs page. There's definitely still room for improvement, but this PR should fix some of the more serious issues.
Changes/Notes:
- Adds a code example at the start to illustrate the use of `LayoutAnimation`. This might not be 100% necessary since the actual mechanism of calling `configureNext` before `setState` is so straightforward. It's easy for someone who isn't interested to skip the code block, though.
- Explicitly has `configureNext` reference `create` and the `Presets` as potential arguments, and vice-versa.
- Spells out the nested object parameter types for `configureNext`'s first argument. The word "config" is a bit overloaded here but I couldn't think of another …
> Thoroughly document LayoutAnimation API

- docs/getting-started.md
- website/versioned_docs/version-0.60/getting-started.md
I had a video chat with @rachelnabors today and during the call she raised two issues that have come up when discussing documentation with the community:
1. We currently provide advice for people who come "from a web development background" or are "familiar with native development", but there is no explicit advice for people who don't fit into those categories.
2. It is not explained well enough what Expo is and how it relates to React Native in the intro paragraph.
In order to address point 1, I directed the advice towards people who are "new to mobile development" or "already familiar with mobile development", which I believe should cover everybody.
In order to address point 2, I rewrote the Expo CLI introduction paragraph to attempt to concisely explain how Expo relates  to React …
> Adjust getting started wording

- docs/native-modules-setup.md
- website/package.json
The third party tool (react-native-create-library) suggested on this page is stale and appears to have been abandoned, in it's current state it does not work on iOS. I've swapped this out for an alternative library that is in active development and is currently working on iOS and android, even on React Native 0.60+
> Update recommended native modules lib

- docs/upgrading.md
This PR is the same as #1063 but for the main `upgrading.md` documentation.
Apparently there's an issue on how to fetch the correct file, for `0.59` the `upgrading.md` that lives under `version-0.5` but for `0.60` it's picking up the one under `docs`.
For now I'm fixing this as it is and we should have a plan to fix it in a proper way in the source.
> Add upgrade docs to `0.60`

- website/core/RemarkablePlugins.js
- website/siteConfig.js
We had to fix the width of Snack player to `100%` instead of a specific dimension.
> Display a right side nav

- docs/button.md
- website/versioned_docs/version-0.60/button.md
Replace image with Expo example for `Button` component.
|Android|iOS|
|---|---|
|<img width="600" src="https://user-images.githubusercontent.com/9092510/64185798-0a893780-ce6e-11e9-9f98-13c96995b9bb.png"/>|<img width="600" alt="Screenshot 2019-09-03 at 17 05 19" src="https://user-images.githubusercontent.com/9092510/64185890-2ee51400-ce6e-11e9-887e-c65d6aea0fe7.png">|
> imp: Replace img with snack example

- website/static/css/react-native.css
Fixed the issue @rachelnabors found since the new side nav.
| State | `min-width: 768px` | `min-width: 1440px` |
| - | - | - |
| Before | <img src="https://user-images.githubusercontent.com/7189823/64248479-7d97ba00-cf11-11e9-8c48-1553a09a1fd9.png" /> | <img src="https://user-images.githubusercontent.com/7189823/64248411-4923fe00-cf11-11e9-83d7-b2d074782025.png" /> |
| After | <img src="https://user-images.githubusercontent.com/7189823/64248257-fb0efa80-cf10-11e9-8b96-b49de530df7a.png" /> | <img src="https://user-images.githubusercontent.com/7189823/64248336-1ed24080-cf11-11e9-8f69-e73b444e7925.png" /> |
> Split components and APIs grid in 2 or 3

- docs/height-and-width.md
The 2nd code block was including the following text and throwing an error.
> [Tutorial] Fix 2nd code block rendering

- docs/hermes.md
This Hermes issue points out that the documentation for turning on Hermes in an existing app is quite terse: https://github.com/facebook/hermes/issues/96
This diff adds links to the existing RN docs, and is generally more verbose.
> Explicitly mention how to upgrade RN when switching to Hermes

- docs/integration-with-existing-apps.md
I encountered the error from cocoapods:
Then I found the pod name should be `Yoga`, not `yoga`
> fix pod name yoga -> Yoga

- docs/typescript.md
- remove `Unexpected token (46:0)`
- add `export default`
> fix TS example

- docs/scrollview.md
For some reason the diff shows the entire paragraph, but I changed:
> ...can lead to scroll performance problems due to the volume of information being send over the bridge.
to:
> ...can lead to scroll performance problems due to the volume of information being **sent** over the bridge.
> Fix minor typo in ScrollView docs

- docs/stylesheet.md
There are some code snippets that use `var` for declaring `styles` whereas some other snippets use `const`.
Modified the page to all use `const` for consistency.
> docs: keep consistency of stylesheet declaration

- docs/image.md
In the docs: https://facebook.github.io/react-native/docs/image#resizemode
The default `resizeMode` is not indicated.
In the source: https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.ios.js#L114
The default `resizeMode` is `cover`.
> [docs] [Image] Indicate the default `resizeMode`

- docs/appregistry.md
- docs/debugging.md
- docs/getting-started.md
- docs/linking.md
- docs/permissionsandroid.md
- docs/pushnotificationios.md
- website/versioned_docs/version-0.5/debugging.md
- website/versioned_docs/version-0.5/getting-started.md
- website/versioned_docs/version-0.60/appregistry.md
- website/versioned_docs/version-0.60/linking.md
- website/versioned_docs/version-0.60/permissionsandroid.md
- website/versioned_docs/version-0.60/pushnotificationios.md
These updates replace some links with better versions and clarify messaging when there are warnings about projects using "Create React Native App" (which doesn't exist anymore).
> Assorted Expo-related updates

- docs/flatlist.md
I think there should be key inside `renderItem` callback
> Add key prop to Example usage of FlatList's `renderItem` prop

- docs/textinput.md
> fix(docs): add missing methods on the TextInput doc for focus and blur

- docs/layoutanimation.md
The demo regarding the use of `LayoutAnimation` API should `import LayoutAnimation from 'react-native'` but it doesn't and therefore you can't run that code right away.
> add missing LayoutAnimation import

- docs/alert.md
Type isn't just there in the sources anymore: https://github.com/facebook/react-native/blob/v0.61.2/Libraries/Alert/Alert.js#L42
> Remove type from alert.md

- .alexignore
- website/versioned_docs/version-0.59/asyncstorage.md
- website/versioned_docs/version-0.59/imagestore.md
- website/versioned_docs/version-0.59/scrollview.md
- website/versioned_docs/version-0.59/text.md
- website/versioned_docs/version-0.59/textinput.md
- website/versioned_docs/version-0.59/view.md
This PR enables the linter for the version 0.59 docs and fixes the current linter errors for files in that version.
#1338
> Fix lint errors in docs version 0.59

- docs/textinput.md
It adds docs for missing `onTextInput` property.
`onTextInput` source: https://github.com/facebook/react-native/blob/v0.61.2/Libraries/Components/TextInput/TextInput.js#L565
`TextInputEvent`: https://github.com/facebook/react-native/blob/v0.61.2/Libraries/Components/TextInput/TextInput.js#L64
> Update docs: add missing onTextInput property to TextInput component

- docs/getting-started.md
Currently, there are duplicate formulas on cask, so this command fails to install.
Please see related issue: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106
> fix JDK8 installation command

- docs/vibration.md
- website/versioned_docs/version-0.22/vibration.md
- website/versioned_docs/version-0.22/vibrationios.md
- website/versioned_docs/version-0.24/vibration.md
- website/versioned_docs/version-0.49/vibration.md
- website/versioned_docs/version-0.5/vibration.md
- website/versioned_docs/version-0.5/vibrationios.md
- website/versioned_docs/version-0.54/vibration.md
- website/versioned_docs/version-0.56/vibration.md
- website/versioned_docs/version-0.58/vibration.md
- website/versioned_docs/version-0.60/vibration.md
This PR will correct the typo on `asynchronous` while it should mean `synchronous`.
> Fix typo on Vibration API doc files

- website/versioned_docs/version-0.6/netinfo.md
As of this PR and version of the docs, NetInfo was marked as deprecated:
https://github.com/facebook/react-native-website/pull/838
However, these versions of the documentation shows a restored bare-bones doc for NetInfo:
https://facebook.github.io/react-native/docs/0.9/netinfo
https://facebook.github.io/react-native/docs/0.7/netinfo
etc.
This seems to be because subsequent versions propagate from the file edited in this PR. Simply removing the file causes the 0.58 version to propogate, so approach is to update the file itself to fix this problem.
> Updates doc that causes propogation of inaccurate netinfo documentation

- docs/animations.md
The file (`NativeAnimationsExample.js`) was moved by https://github.com/facebook/react-native/commit/3945f10561622a3e361190919d0a6d397f67ef8b#diff-b24b9172a3a7b428c3cd7066710a927f.
> Update link to NativeAnimationsExample in animations.md

- docs/typescript.md
Fixes #1460 so it is more obvious not to rename the main `./index.js` entrypoint.
> Add message to Typescript docs for main entry point

- website/pages/en/index.js
A link on the React Native homepage leading to `https://octoverse.github.com/projects#repositories` is dead. I've updated it with a working one.
> Update link on React Native homepage

- docs/refreshcontrol.md
- website/core/RemarkablePlugins.js
- website/versioned_docs/version-0.60/refreshcontrol.md
At the request of @rachelnabors, I added support to Snack for the `supportedPlatforms` URL query param that lets you specify what platforms a Snack will run on. This PR integrates the param into the Snack Remarkable plugin used here and gives an example of using it on the RefreshControl API reference page.
Here is what it looks like with the web option disabled on the RefreshControl page:
> Add supportedPlatforms param to Snack embeds

- docs/text.md
- website/versioned_docs/version-0.60/text.md
Fixes an issue introduced by yours truly in https://github.com/facebook/react-native-website/pull/1484 when the order of Android and iOS was swapped.
> Fix Android Oreo version wording in Text docs

- docs/sectionlist.md
By default, SectionList on iOS have property `stickySectionHeadersEnabled` set to `true` so header element should have any background to be displayed properly.
Before and after change:
Adding `backgroundColor` doesn't affect appearance of other examples.
> fix SectionList example appearance on iOS

- website/package.json
- website/yarn.lock
Resolves GitHub security warnings raised with the following packages:
- debug - Affected versions: < 2.6.9
- underscore.string - Affected versions: < 3.3.5
- lodash.merge - Affected versions: < 4.6.2
Test Plan:
Verified dependencies were removed or upgraded to resolved versions.
```
$ yarn why debug
=> Found "debug@2.6.9"
$ yarn why lodash.merge
=> Found "lodash.merge@4.6.2"
$ yarn why underscore.string
Using globally installed version of Yarn
yarn why v1.12.1
[1/4] 🤔  Why do we have the module "underscore.string"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
```
> Bump Docusaurus version to 1.14.3

- docs/direct-manipulation.md
This bit was confusing because originally I used `onLayout` to get `pageY` but then realized that `onLayout` doesn't provide that value (not sure why exactly). Therefore I looked around and `measure` seems to do so but its docs suggest to use `onLayout` at some point 🙃
> onLayout does not provide pageX and pageY

- website/static/css/docs-prevnext.css
This PR fixes an issue with the bottom of the prev/next buttons passing the sidebar.
Before:
After:
> Fix the spacing on the footer of prev/next buttons

- docs/image.md
On `"react-native": "^0.61.4"` the current versions to enable GIF support on Android didn't actually animate a GIF, as per https://frescolib.org/docs/index.html it seems the doc is simply outdated
> Update com.facebook.fresco versions for Android

- docs/flatlist.md
- website/versioned_docs/version-0.52/flatlist.md
- website/versioned_docs/version-0.54/flatlist.md
- website/versioned_docs/version-0.55/flatlist.md
- website/versioned_docs/version-0.56/flatlist.md
- website/versioned_docs/version-0.58/flatlist.md
- website/versioned_docs/version-0.60/flatlist.md
https://facebook.github.io/react-native/docs/flatlist#scrolltoindex
The viewOffset property of Flatlist.scrolltoIndex is optional.
I think the "Required" Notation at the end is unnecessary.
> Removed "Required" annotation of viewOffset in scrollToIndex

- docs/pushnotificationios.md
There seems to be broken link to Apple's developers documentation in `finish()` function description (https://facebook.github.io/react-native/docs/pushnotificationios#finish). Current one redirects to main `UIApplicationDelegate` page.
This PR fixes that and points directly to `application:didReceiveRemoteNotification:fetchCompletionHandler:` instance method docs.
> Fix PushNotificationIOS fetchCompletionHandler documentation link

- docs/hermes.md
https://github.com/facebook/react-native/issues/26252
Currently Hermes does not support AAB, only APK for Android.
This update will add a warning to the documentation to help warn other developers when trying to build with Hermes and AAB.
> Add warning about AAB and Hermes

- docs/flexbox.md
- Improved grammar by adding missing commas, determiners, etc.
- Removed an unrelated reference to Yoga.
- Swapped the last two paragraphs so that the one that mentions additional examples comes before the one that introduces the next guide.
> Fixes to Layout with Flexbox

- website/pages/en/index.js
Remove following warnings when running `yarn start`:
```
➜  website git:(master) yarn start
yarn run v1.19.1
$ docusaurus-start
LiveReload server started on port 35729
[BABEL] Note: The code generator has deoptimised the styling of /Users/haruelrovix/Projects/react-native-website/website/node_modules/docusaurus/lib/core/metadata.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/haruelrovix/Projects/react-native-website/website/node_modules/docusaurus/lib/core/metadata.js as it exceeds the max of 500KB.
Docusaurus server started on port 3000
Warning: Invalid DOM property `class`. Did you mean `className`?
in a
in TwitterButton
in div
in section
in Section
in HeaderHero
in main
in Index
in div
in body
in html
in Site
Warning: Invalid …
```
> fix: Invalid DOM property and unique key warnings

- website/versioned_docs/version-0.28/appstate.md
- website/versioned_docs/version-0.42/appstate.md
- website/versioned_docs/version-0.46/appstate.md
- website/versioned_docs/version-0.53/appstate.md
- website/versioned_docs/version-0.54/appstate.md
- website/versioned_docs/version-0.55/appstate.md
- website/versioned_docs/version-0.58/appstate.md
- website/versioned_docs/version-0.60/appstate.md
The following _TODO_ comment is currently showing in the page of `AppState`:
Here's a PR to put it as code comment as I believe it is not supposed to be there.
> Remove TODO showing in the docs of `AppState`

- docs/inputaccessoryview.md
Following changes has been made:
* functional component and hook
* supported platforms fix (disable Android)
* `View` container replaced with `Fragment`
* store initial text in `const`
* other small tweaks (sort imports, component name, style)
Refs #1272
> rewrite InputAccessoryView example using hooks

- docs/height-and-width.md
unnecessary back-ticks are breaking the layout of the page and the last example
> Bug with extra back-ticks is fixed

- docs/handling-touches.md
Since this page was moved out of the Getting Started docs and the ScrollView is being merged into a mini tutorial, this should link ahead to ScrollView's API docs.
> Removing references to next pages

- docs/getting-started.md
RN 0.61 enables Fast Refresh by default for new apps. There is no need to instruct users to manually enable it in the Getting Started guide.
> docs: Remove advice to enable Fast Refresh for new apps

- docs/javascript-environment.md
TypeScript list item under Javascript Syntax Transformers section was pointing to the flow type web page instead of typescript.
> update incorrect link to typescript

- website/package.json
- website/yarn.lock
Docusaurus was having some issues with formatting JSX code blocks correctly. This was problematic in some of our examples. After working with them, they updated Docusaurus accordingly
> Upgrading docusaurus to fix JSX formatting incorrectly.

- docs/native-modules-ios.md
In our project we accidentally implemented the `invalidate` method on a native module we wrote to control a user's session. `SessionCacheModule.invalidate` was being called every time we triggered a dev mode reload, which would log us out :(
I'm adding cautionary notes to the docs in case someone encounters this footgun as well
> Add reserved method name note to iOS module docs

- docs/image.md
**IOS** : I found some issues of `blurRadius`. i tested on 38 devices, when i increase the number of `blurRadius` > `5` then its started applying on that. You can see [27905](https://github.com/facebook/react-native/issues/27905)  [16780](https://github.com/facebook/react-native/issues/16780) [20910](https://github.com/facebook/react-native/issues/20910)
**ANDROID** : `blurRadius` its working if `blurRadius` < `5`  or  >, 🎉
@gaearon @hramos   thanks. Please review this PR 🎉 that's my first PR in this repo 🙌
🙌Happy to contribute with your team🙌
> Docs |  IOS  blurRadius  > 5

- website/versioned_docs/version-0.60/image.md
Disclaimer, I'm not used to the repo neither docusaurus, so I may have done something wrong.
Checking: https://facebook.github.io/react-native/docs/image#gif-and-webp-support-on-android
is outdated starting from react-native 0.60. It seems that the website is not up to date to the changes made in that [Commit](https://github.com/facebook/react-native-website/pull/1515). Which means that the current documentation doesn't work for Images support on Android for RN > 0.60
> Update images doc for rn 0.60

- docs/flexbox.md
The current descriptions of the behavior for 'column' and 'column-reverse'  when wrapping is enabled are incorrect. They state that the next line will start to the left of the first line. This PR edits these descriptions to say that the next line will start to the _right_ of the first line.
> Correct mistakes in flexDirection description

- docs/alertios.md
- docs/asyncstorage.md
- docs/datepickerandroid.md
- docs/datepickerios.md
- docs/imageeditor.md
- docs/imagepickerios.md
- docs/pickerios.md
- docs/progressbarandroid.md
- docs/progressviewios.md
- docs/pushnotificationios.md
- docs/segmentedcontrolios.md
- docs/slider.md
- docs/statusbarios.md
- docs/timepickerandroid.md
- docs/viewpagerandroid.md
- website/i18n/en.json
By deprecation notes standardization I have meant following changes:
* using current NPM package name
* using similar phrasing
* positioning deprecation note always on the top of the page
The rest of changes are basically a concept, which you might not like. 
I was aiming to clarify deprecation and discourage developers to use those parts of RN so I have added  🚧emoji to the title of pages marked as deprecated Component or API. (Of course I'm open to change selected emoji, this could be anything else.)
I can work further on this PR or on any other solution that help in the case mentioned above.
> deprecation indicator and deprecation notes standardization

- docs/datepickerios.md
Belongs to  facebook/react-native-website#1579
Created a nice little snack for people to view DatePickerIOS in action using both Function & Class Component examples.
> DatePickerIOS - Added Snack Examples 🍿

- docs/devsettings.md
- website/sidebars.json
Started writing the doc for addMenuItem() as DevSettingsModule.
> [DOC]: API Reference for DevSettings.addMenuItem() #1523

- docs/clipboard.md
- website/i18n/en.json
Adding deprecation notice for the `Clipboard` module, as it is now moved to the [community](https://github.com/react-native-community/react-native-clipboard)
Ref: https://github.com/facebook/react-native/blob/master/index.js#L301-L309
> docs: add deprecation notice for clipboard

- docs/textinput.md
This prop which was added on [here](https://github.com/facebook/react-native/pull/25407) wasn't documented in the docs nor in the API. Related with #1579
> TextInput: Added new docs for PasswordRules Prop

- docs/progressbarandroid.md
- docs/progressviewios.md
There has been a change in repository name for `progress-view` and `progress-bar-android`
This PR is to reflect the URL change.
> docs: update url for progress bar android and progress view

- docs/textinput.md
#1579 
removed `selectionState` props from `TextInput` as it is no longer used in the component.
ref: https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js
> docs: remove unused prop from TextInput docs

- docs/switch.md
Issue: #1579
- Updated snack and example.
I improved the example in order to explore more props, since there is a Snack example in the [`next` version of documentation](http://facebook.github.io/react-native/docs/next/switch).
> Switch: update Snack example

- docs/picker.md
Issue: #1579
- Updated snack example.
As I mentioned in #1594 there is also a Snack example in the [`next` version of documentation](http://facebook.github.io/react-native/docs/next/picker) for this component. So I just improved the visibility of the component.
> Picker: update Snack example

- docs/alert.md
Belongs to facebook/react-native-website#1579
Created nice little snack examples for trying out the Alert module using both Function & Class Components.
It currently only supports Android & iOS - For Web support, keep an eye on https://github.com/necolas/react-native-web/issues/1026
> 🍿 Added Snack Examples for the Alert 🚨 module

- docs/hermes.md
- docs/integration-with-existing-apps.md
- docs/linking-libraries-ios.md
- docs/native-modules-setup.md
- docs/out-of-tree-platforms.md
- docs/removing-default-permissions.md
- docs/running-on-device.md
- docs/running-on-simulator-ios.md
- docs/signed-apk-android.md
- docs/troubleshooting.md
- docs/upgrading.md
I noticed that in the docs the 'react-native' command sometimes doesn't have the 'npx' prefix and sometimes it does.
Considering that we're using it with 'npx' on the front page, I believe it would be a good idea to stay consistent through all the docs with it.
> Added npx prefix to react-native commands within docs

- docs/toastandroid.md
This PR aims to move the old **ToastAndroid** examples to a Snack example (added hooks into it) as stated on #1579
> ToastAndroid: Ported the examples into Snack, using hooks in the advanced usage

- docs/share.md
Hi,
Just wanted to point out a tiny word that was missing in the docs that messed up the grammar.
The page on [Share](https://facebook.github.io/react-native/docs/share) currently states:
> In Android, Returns a Promise which always be resolved with action being `Share.sharedAction`.
This PR adds the word _will_ to the above sentence, leading to this improved sentence:
> In Android, Returns a Promise which will always be resolved with action being `Share.sharedAction`.
It's a small issue but having perfect docs is always nice :)
> fix grammar - add 'will'

- docs/image.md
- docs/view.md
In Reference to #1579 
This PR adds a Snack Example for `<Image/>` component with a use case for a functional component.
> Image & View: add snack examples to use functional components

- docs/hermes.md
- docs/integration-with-existing-apps.md
- docs/removing-default-permissions.md
- docs/running-on-device.md
- docs/running-on-simulator-ios.md
- docs/signed-apk-android.md
#1630 
There are some react-native command examples that were missing `npx`, which is the preferred method to use the react-native cli.
> docs: add npx in front of react-native command

- website/i18n/en.json
- website/sidebars.json
This PR adds new "Props" section to the "API" page sidebar which contains all props related pages earlier listed in section below. 
The order of sections can be changed, it's only a proposal aiming to tidy up the sidebar.
> move props related pages to separate section in sidebar

- docs/stylesheet.md
`StyleSheet.absoluteFill `cannot be spread into an object.
> 🐛Fix erroneous use of absoluteFill

- docs/clipboard.md
#1579,
Added example using hooks to clipboard API.
> added clipboard example

- website/versioned_docs/version-0.60/text.md
the title style looks up the header phone so i fix that.
> fix title style in the first example in text component API docs

- website/core/RemarkablePlugins.js
The InputAccessoryView docs have a web player that is failing with this error:
Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&amp;args[]=undefined&amp;args[]=%20Check%20the%20render%20method%20of%20%60UselessTextInput%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
The full error message is:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: [missing argument].[missing argument]
I noticed we're using a three year old build of the react-native-web-player. Upgrading to the latest 2.0.0 alpha version seems to have fixed it.
At the same time, I updated the Snack player to use a …
> Update ReactNativeWebPlayer version, bump Expo SDK version

- docs/alert.md
I updated the Alert documentation page so its formatting matched the rest of the documentation pages, and fixed a little bit of grammar.
> Alert documentation and minor fixes

- website/versioned_docs/version-0.60/textinput.md
i try to find this file in react-native repository, i think this file it's deprecated.
if you click in the link appears 404 not found.
> remove DocumentSelectionState link textinput docs #1518

- docs/communication-ios.md
I encountered this (now broken) link to the old Geolocation library. I changed it to the Github of the new [react-native-geolocation](https://github.com/react-native-community/react-native-geolocation) library because I still think that it's a good example. Unless of course a native module inside the React Native codebase should be used.
I can change the link to a specific file, if so should it be changed to [this](https://github.com/react-native-community/react-native-geolocation/blob/master/ios/RNCGeolocation.m) file?
> Fix (communication-ios): Link to Geolocation library

- docs/network.md
Refs #1649. 
This PR adds `fetch` Class Component example to the Networking page. Also function names in code blocks above example has been corrected and one of variables has been renamed to match naming used in examples below. ES version and "proposal" mention has been deleted since `async` is widely used and it's not a very meaningful detail after all.
> add fetch class component example

- docs/image.md
#1579 
Double checked `Image` API to see if there was a missing proptypes.
Turns out there are `height` and `width` prop in the Image component, but it doesn't seem to have any effect in the actual code. (Making a PR in the core to remove the props https://github.com/facebook/react-native/pull/28151)
All other props seems to be included in the docs.
I've also rearranged the props to be in alphabetical order so its easier for readers to keep track.
> docs: arrange Image Props in alphabetical order

- website/pages/en/help.js
Updates to the community page `/help`, specifically the **Conferences** paragraph
- Add **React Conf 2019** playlist to the list of playlists
- Remove references to the previous conference its out of date and replace with "TBA" until further notice.
> Update conferences information (add React Conf 2019 playlist)

- docs/accessibilityinfo.md
Issue: #1579
- Updates jsx example with React Hooks
- Adds Snack example with React Hooks
Please note: I’ve tested with SnackPlayer and the version of React Native it uses underneath does not include the methods `isReduceMotionEnabled` and `isScreenReaderEnabled` from the AccessibilityInfo API. For that reason, I used `fetch` in the Snack example.
> Refactor AccessibilityInfo Example into React Hooks

- docs/getting-started.md
- website/versioned_docs/version-0.60/getting-started.md
- website/versioned_docs/version-0.61/getting-started.md
Updated "Getting Started" docs to explain the recommendation against installing a specific version of the react-native CLI.
Reading back through the getting started docs, I found myself confused with how the CLI should now be installed. After some googling, I realized `npx` auto-installs missing dependencies. I've explained this in the RN CLI dependency instructions.
> Clarify installation recommendation for react-native CLI.

- docs/segmentedcontrolios.md
- website/versioned_docs/version-0.60/segmentedcontrolios.md
`@react-native-community/segmented-control` recently changed its repo name to `segmented-control`.
This PR fixes the link to the correct URL.
> docs: fix link for segmented control community package

- docs/text.md
Hi, I've added functional component examples with hooks for Text component. #1579
> added functional component examples with hooks

- website/versioned_docs/version-0.61/typescript.md
Currently, accessing the document for `typescript` https://reactnative.dev/docs/typescript leads to page for React Native v0.60, which specifies the template version to be v6.2.0, for RN 0.60.
To use the typescript-template with the latest version 0.61.5, user would want to use the current latest version of `react-native-typescript-template`.
The document for typescript that does not have a specified template version only exists in the `@next` version of the document, which I believe is more suited for the rc versions?
Once the React Native 0.62 gets released, the template version for 0.61 will need to be specified (I'm assuming it's going to be 6.3.x), but until then, the document for 0.61 should not specify any version for the typescript template.
> docs: update typescript template for 0.61

- docs/shadow-props.md
After messing up with git :sweat_smile: I'm reopening this PR, sorry for the inconvenience.
Issue: #1579
- Added Snack example
I'm aware that Slider is deprecated but it not works with Expo Managed workflow.
> add Shadow Props example

- website/versioned_docs/version-0.58/geolocation.md
Refs #1554 
This small PR adds deprecation notice to the `Geolocation` page to prevent confusion and similar problems mentioned in issue linked above.
> add deprecation notice to the Geolocation page

- docs/dimensions.md
Inspiration - To address this [stackoverflow question](https://stackoverflow.com/questions/44978804/whats-the-difference-between-window-and-screen-in-the-dimensions-api)
Contains the snack with both class & functional component examples and also a bit of update to the documentation regarding screen, window & event listener.
Pending items in this PR:
Previously this was raised in https://github.com/facebook/react-native-website/pull/1601 but closing it cuz the older one has conflicts with master & It's easier to merge this one
> Dimensions 📐 - updated Docs 📑 & new snack examples ✨

- docs/performance.md
Fix bad `s/js/javascript/` followed by `s/javascript/jsx/` for a `json` code block.
Link to the `.md` instead of `.html` version of the file.
> [docs] Fix code block type and link

- docs/typescript.md
- website/versioned_docs/version-0.60/typescript.md
`yarn add typescript @types/jest @types/react @types/react-native @types/react-test-renderer  -D`
for dev dependencies, I got this in dependencies that's why I have to change this ...  :)
Thanks
> Add -D in yarn typescript

- docs/performance.md
Just a tiny suggestion of improvement to `Investigating the Loaded Modules` section.
With this change `packager/modulePaths.js` file will have more readability and, mainly, will allow better diff comparison between commits.
> Tiny improvement to loaded modules code example

- docs/keyboard.md
I added a `function` component example with hooks beside the `class` component example
> added Keyboard API example using function components & hooks

- docs/inputaccessoryview.md
- docs/keyboardavoidingview.md
- docs/progressbarandroid.md
- docs/progressviewios.md
Refs #1579 
This small PR adds correct `supportedPlatforms` param to the few Snack examples.  Some of them were using old  `platform` parameter, some were missing it at all.
> add correct 'supportedPlatforms' param to the few examples

- docs/imagebackground.md
Here is an update for the [#1579 ](https://github.com/facebook/react-native-website/issues/1579) regarding the ImageBackground component.
The example was either a class or a function component so I turned it into one functional.
> [#1579] update ImageBackground component doc

- docs/components-and-apis.md
Refs https://github.com/facebook/react-native-website/issues/1579#issuecomment-588361038
As @rachelnabors requested, this PR removes all deprecated APIs and Core Components form the summary page (https://reactnative.dev/docs/next/components-and-apis).
> remove deprecated APIs and Core Components form the summary page

- docs/easing.md
Refs #1579.
This PR adds Snack example to the Easing page. I was trying not to overcomplicate this example but at the same time make it meaningful, hope I have achieved that. I'm open to any suggestions or corrections.
@rachelnabors Also this example has not a perfect UX on the `web` due to the way in which Scroll/Flat/Section Lists components has been implemented there, but is working. Please let me know if you want to disable this platform.
> add Snack example to Easing page

- docs/pixelratio.md
Refs #1579.
This PR adds Snack example to the Pixel Ratio page.  This example is very simple and I have deliberate chosen text representation for the image/resource size calculation, mainly for the clarity what this API can do and which information it provides. But the phrasing might be the first thing to tweak here ; )
Preview:
> add Snack example to PixelRatio page

- docs/dimensions.md
Refs #1676.
Link used in notice to `useWindowDimensions` on the Dimensions page is incorrect (only on the `next` branch of docs). This is just a simple fix for this 404, problematic page:
* https://reactnative.dev/docs/next/dimensions
> fix link to 'useWindowDimensions' on the Dimensions page

- docs/appstate.md
Updated 'AppState' API with 'memoryWarning' event, issue #1579
> Update 'AppState' with 'memoryWarning' event

- docs/colors.md
RN doesn't support uppercase named colors. Add to the doc, so web developers, can know the difference and prevent unexpected behaviour.
> Warn about using uppercase color names

- docs/profiling.md
After merge of #1672 I have spotted that after rebasing images are broken. This PR fixes all images on the `Profiling` page, sorry for that!
> fix broken images on the Profiling page

- website/static/css/docs.css
This small PR introduces design tweak to the `onPageNav` component (right sidebar). My goal  here was to mimic main sidebar design and improve readability. Preview demonstrate page scrolling with nested child and then hover effect and click.
* [Page used for the preview](https://reactnative.dev/docs/next/native-modules-ios)
> design: update 'onPageNav' style to mimic sidebar UI

- docs/touchableopacity.md
Refs: #1579
This PR introduce few small changes to the TouchableOpacity page:
* old example removed
* examples code unified based on Functional Component
* example names updated
* Prettier run on examples
* adjusted formatting in Reference
Nothing major as seen above, just an overall cleanup.
> update TouchableOpacity page

- docs/vibration.md
Addresses https://github.com/facebook/react-native/issues/27920. Vibration on iOS only supports a plain `Vibration.vibrate()` call. 
Vibrating by pattern is not supported: https://github.com/facebook/react-native/blob/2f758c3abbef33a47cd3651e7213066f53fb373f/Libraries/Vibration/RCTVibration.mm#L39-L48 https://github.com/facebook/react-native/blob/2f758c3abbef33a47cd3651e7213066f53fb373f/Libraries/Vibration/RCTVibration.mm#L28-L31
Canceling vibration is not supported: https://github.com/facebook/react-native/blob/2f758c3abbef33a47cd3651e7213066f53fb373f/Libraries/Vibration/RCTVibration.mm#L39-L48
Intentionally used "webNote" for Android notes to force Android notes to show up by default. If no webNote is present, the notes block will default to empty as displaytabs() will hide everything …
> Clarify Vibration iOS API

- website/static/css/tabs.css
This PR introduce small UI/design tweak which changes tabs divider color to the same used for TOC border (currently tabs border is dark gray):
Also I have made a small CSS cleanup and I have removed unnecessary code (probably leftover from the older design) for the vertical devices. As you can see below only visible change is that tabs divider is present now:
> design: use same color for tabs divider as used for TOC border

- docs/accessibilityinfo.md
- docs/actionsheetios.md
- docs/activityindicator.md
- docs/appstate.md
- docs/button.md
- docs/dimensions.md
- docs/drawerlayoutandroid.md
- docs/easing.md
- docs/flatlist.md
- docs/image.md
- docs/keyboardavoidingview.md
- docs/modal.md
- docs/picker.md
- docs/pixelratio.md
- docs/refreshcontrol.md
- docs/safeareaview.md
- docs/scrollview.md
- docs/sectionlist.md
- docs/switch.md
- docs/touchablehighlight.md
- docs/touchablenativefeedback.md
- docs/virtualizedlist.md
This PR focuses on updating the headers of several pages for better navigation (adjusting headers affects right sidebar content) and for the better consistency between documentation pages.
I have also removed in-content props/method link lists on the `SectionList` and `TouchableHighlight` pages. This was useful before, but currently it duplicates the function of the right sidebar.
> update the headers for the better navigation and consistency

- docs/more-resources.md
The **Showcase** link under https://reactnative.dev/docs/more-resources#examples is currently pointing to https://reactnative.dev/docs/showcase/, which results in a 404 Not Found.
This change points it to the correct one under https://reactnative.dev/showcase.
> Fix "Showcase" link under "More Resources"

- docs/animated.md
#1579 
According to #1573 the Animated doc is not super clear that you have a callback option for start(). 
So the purpose of this PR is to add the proper docs and code example about callback option for start().
> WIP: Update Animated.md to add proper docs about start(), stop(), and reset()

- docs/vibration.md
Added function/class component toggler in 'Vibration' API, issue #1579
> Update 'Vibration' with function/class component toggler

- docs/flatlist.md
https://github.com/facebook/react-native-website/issues/1579
After some digging i found that in FlatList since this commit facebook/react-native@1a499f4 the default value of `removeClippedSubviews` on Android is true. Because there is a mismatch between the docs and the actual implementation i think that the docs should be updated with the correct behaviour.
Referencing related issue https://github.com/facebook/react-native-website/issues/1648
> Update FlatList removeClippedSubviews default props documentation

- docs/getting-started.md
- docs/typescript.md
Fixed the usage of the typescript template and added a note.
This change has been going back and forth in the document, and I can understand why it can be confusing, since the behavior changes depending on which version of the cli they're using.
In `react-native-cli` version 2 and older (and the globally installed `react-native` before the cli got its own repository), the cli required you to get rid of the prefix `react-native-template-`, but starting from version 3 of the `react-native-cli` the behavior changed to type the whole template name.
> docs: fix template

- docs/settings.md
Refs #1579. This PR adds basic Snack example to the `Settings` API page.
Unfortunately `Settings.watchKeys` in the current version of React Native do not register and fire callback after `Settings.set` calls (but callback is called on "outside" changes). This is the reason why example is not working as expected. More information here: facebook/react-native#28213
@rachelnabors guided me thought this process and asked to push the code from the stash in current state. It means that this PR is technically WIP and at least one more commit is expected here.
> add Snack example to the Settings page

- docs/hermes.md
In 0.62.0 another ProGuard rule is required for the build to work
Related to https://github.com/facebook/react-native/issues/28270.
> hermes: Fix ProGuard rules for 0.62.0

- website/versioned_docs/version-0.61/dimensions.md
Small PR to fix the `useWindowDimensions` page link in the `Dimensions` documentation.
> Fix `useWindowDimensions` page link

- docs/intro-react.md
We weren't being explicit about this. Studying more React on my own and with others, I think it makes sense to add a little clarification that `Cat` is the component and `<Text>` is the React element—that represents Views. Would've loved to put this in the prior section on Native Components and Core Components, but honestly, we really needed to explain that RN isn't a compiler and what Views are in relation to Native Components. Hopefully this little bit helps drive this home even more :)
> Clarify what a component and element are

- website/pages/en/index.js
I looked at the example and felt something was missing and realized `header` was not imported.
Since there was already an `Header` component imported, I felt it might make sense to rename the variable and then import it from something that relates to styling. I went with `./Typography`
> import missing style in example

- docs/sectionlist.md
#1579
This PR Contains new Function + Class Component examples for `SectionList`
> Updating SectionList Snack Examples with Functional and Class Based Component 

- docs/transforms.md
This PR updates the `Transforms` API page. The following changes has been made:
* examples has been simplified and adjusted to fit better narrow Snack player
* intro text has been adjusted (also example reference has been removed)
* code block has been added to the `transform()` examples
* type table has been adjusted for the readability
I have also removed the type table below deprecated methods because it content was confusing and invalid (deprecated methods were accepting `number` or `string` depending on performed transformation).
> update Transforms page and simplify examples

- docs/flatlist.md
#1579
As per this commit https://github.com/facebook/react-native/commit/bde1d63 `FlatList` will get addtional props called `getNativeScrollRef` to get the underlying host component of `FlatList`. 
Because `getNativeScrollRef` will land on `v0.62` i think it's important to add it to the docs.
> Adding FlatList getNativeScrollRef() methods

- docs/backhandler.md
Have added snack examples for BackHandler and also added references to React Navigation & React Native hooks.
> 🔙 Updated BackHandler Docs with snack examples 🤾🏽‍♂️

- docs/devsettings.md
Refs #1523.
This PR adds basic documentation for the `DevSettings.reload()` method.
Source: [facebook/react-native/Libraries/Utilities/DevSettings.js](https://github.com/facebook/react-native/blob/d0324f693c6ba5cabc92902f801db8c55cf4200a/Libraries/Utilities/DevSettings.js)
> add missing method to the DevSettings docs

- website/versioned_docs/version-0.43/animated.md
- website/versioned_docs/version-0.43/layout-props.md
- website/versioned_docs/version-0.44/animated.md
- website/versioned_docs/version-0.45/layout-props.md
- website/versioned_docs/version-0.46/animated.md
- website/versioned_docs/version-0.46/layout-props.md
- website/versioned_docs/version-0.47/layout-props.md
- website/versioned_docs/version-0.48/animated.md
- website/versioned_docs/version-0.48/layout-props.md
- website/versioned_docs/version-0.49/animated.md
- website/versioned_docs/version-0.51/layout-props.md
- website/versioned_docs/version-0.52/layout-props.md
- website/versioned_docs/version-0.55/layout-props.md
- website/versioned_docs/version-0.56/layout-props.md
- website/versioned_docs/version-0.57/layout-props.md
Fixed some links to `origami` and `yoga` that had old domain.
> Update link to origami and yoga

- docs/scrollview.md
#1579
As I mentioned in #1648, the `ScrollView` docs are out of date, stating that the `removeClippedSubviews` prop defaults to `true`. [This is no longer the case](https://github.com/facebook/react-native/blob/10254a900a2332fc87063d9287da2403abbdf5c3/Libraries/Components/ScrollView/ScrollView.js#L1085).
This PR just removes the out-of-date line from the docs.
> Update ScrollView docs to reflect that removeClippedSubviews no longer defaults to true

- docs/appregistry.md
> AppRegistry API and docs update  #1579

- docs/modal.md
This small PR disables `web` platform in Modal functional example because this component it's not working correctly in browser right now. Class component had `web` platform disabled earlier.
> disable web platform in Modal functional example

- docs/flexbox.md
This small PR adjust headers on the `Flexbox` page to add missing `onPageNav` component to the right column which should improve page navigation.
> fix onPageNav on Flexbox page

- docs/sectionlist.md
https://github.com/facebook/react-native-website/issues/1579
Based on this commit https://github.com/facebook/react-native/commit/06f32bff82f2d05b3b1643d2338113f66d1e192f `legacyImplementation` is totaly removed from the source.
> Updating SectionList API

- docs/appearance.md
- docs/usecolorscheme.md
- website/i18n/en.json
- website/sidebars.json
While the hook is mentioned in `Appearance` already, I am splitting it out into its own dedicated API doc and sidebar entry.
```
cd website
yarn
yarn start
```
Verified Appearance and useColorScheme docs.
> Split out useColorScheme

- README.md
This PR updates the `README.md` file. The goal was to use similar, coherent structure to the `react-native` repository [Readme](https://github.com/facebook/react-native/blob/master/README.md). The following changes has been made:
* add `Contents` links at the top of file, just after description
* add links to the prerequisite software (also I have bumped recommended Node version)
> Question here: Can we bump it even to 12 for the website since `next` [docs](https://reactnative.dev/docs/next/environment-setup) are recommending the latest LTS for RN?
* utilize emojis in main headers (most of emojis was taken straight from `react-native`  readme)
* add license badge
* use code formatting for the paths and files/folders names
* https://github.com/Simek/react-native-website/tree/readme-update
> update Readme file, add TOC, add badge

- docs/debugging.md
- docs/hermes.md
- docs/integration-with-existing-apps.md
- docs/native-modules-setup.md
- docs/profiling.md
- docs/running-on-device.md
- docs/troubleshooting.md
- website/blog/2016-11-08-introducing-button-yarn-and-a-public-roadmap.md
- website/blog/2017-03-13-introducing-create-react-native-app.md
- website/siteConfig.js
This PR adds two missing languages (Shell and TypeScript) used on the docs site to the Prism code highlighter config. This change improves the related code appearance.
> add 'sh' and 'tsx' to the Prism highlighter config

- docs/testing.md
This small PR fixes Docusaurus warning related to invalid header field:
> Header field "hero" in ~/projects/react-native-website/docs/testing.md is not supported.
Image linked there was not displayed on the page.
> fix Docusaurus warning

- design/Illustrations/illustrations_security.ai
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-0.61/alertios.md
- website/versioned_docs/version-0.61/asyncstorage.md
- website/versioned_docs/version-0.61/clipboard.md
- website/versioned_docs/version-0.61/datepickerandroid.md
- website/versioned_docs/version-0.61/datepickerios.md
- website/versioned_docs/version-0.61/imageeditor.md
- website/versioned_docs/version-0.61/imagepickerios.md
- website/versioned_docs/version-0.61/pickerios.md
- website/versioned_docs/version-0.61/progressbarandroid.md
- website/versioned_docs/version-0.61/progressviewios.md
- website/versioned_docs/version-0.61/pushnotificationios.md
- website/versioned_docs/version-0.61/segmentedcontrolios.md
- website/versioned_docs/version-0.61/slider.md
- website/versioned_docs/version-0.61/statusbarios.md
- website/versioned_docs/version-0.61/timepickerandroid.md
- website/versioned_docs/version-0.61/viewpagerandroid.md
In 0.62 we won't show deprecated components and APIs in the sidebars, though they will still be searchable. Deprecation remains something we need to address more seriously. Let's watch how this changes docs use!
> Adding deprecation notices to 0.61's sidebars

- website/siteConfig.js
This is a followup PR to #1782.
Now that that is merged, we can bump the default version to be 0.62 - which as far as I can see from previous commits (https://github.com/facebook/react-native-website/commit/5a0f9d26acd484212debc0d11971c1a4fbb649fc#diff-c272134cac3612b41f93893bbaa34d24) it's just this change.
We will need to merge this **only** when 0.62.0 is out.
> Update default version to 0.62

- docs/intro-react.md
Tiny PR which fixes a couple of typos in the [React Fundamentals](https://reactnative.dev/docs/intro-react) page.
> Fix typo in intro-react page

- README.md
Refs: #1769
This PR includes few additional minor tweaks to the `README.md` file:
* fix weird issue with ✈️ emoji in the permalink
* use same note formatting for the branch name as used for commit message
* fix versions page link and update text
* https://github.com/Simek/react-native-website/tree/readme-minor-tweaks
> additional minor tweaks to the Readme file

- website/i18n/en.json
Refs: #1782 
This small PR adds missing i18n (localization) strings generated while running Docusaurus after version `0.62` cut.
> add missing i18n strings after 0.62 cut

- docs/pixelratio.md
iOS does return a user value using getFontScale
> Update to pixelratio.md - getFontScale() returns value on iOS

- docs/getting-started.md
The docs [here](https://reactnative.dev/docs/getting-started) for Windows > Android lists the following package as a requirement;
* `Performance (Intel ® HAXM)`
However, in the case of having Hyper-V enabled, like for Docker, installing that package results in failure;
> This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. Please ensure Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information. 
The docs also link an article related to AMD, which also happens to mention Hyper-V;
> If you want to use Hyper-V at the same time as the Android Emulator on your Intel processor-based computer, you will also need the same Android Studio and Android Emulator versions …
> No Intel HAXM when using Hyper-V

- docs/testing-overview.md
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-0.62/testing-overview.md
- website/versioned_sidebars/version-0.62-sidebars.json
if you take a look at the current public docs, the testing guide link in the sidebar redirects to a wiki page at https://github.com/facebook/react-native/wiki/Tests
I'm not 100% sure where the problem is but this solution works without breaking anything.
let me just add that the testing docs should probably not be versioned, and there is a tooling for this (versionedDocsBlacklist.json) but I don't have time to dig into that now. Thanks.
> fix: fix wrong testing guide redirect

- docs/keyboardavoidingview.md
this improves:
- some wording
- typo in `Platform.Os`
- renamed `keyBoardAvoidingComponent` to `KeyboardAvoidingComponent`
> KeyboardAvoidingView docs minor improvements

- website/i18n/en.json
- website/versioned_docs/version-0.59/maskedviewios.md
- website/versioned_sidebars/version-0.62-sidebars.json
This PR removes `MaskedViewIOS` from `0.62` sidebar (it's a deprecated component and according to latest decisions deprecated pages should not be a part of the sidebar). I have also updated the repository name in deprecation notice and added deprecation mark to the page title.
> remove MaskedViewIOS from 0.62 sidebar

- website/blog/2020-03-26-version-0.62.md
This small PR improves code blocks syntax highlight in `0.62` release blog post, fixes two typos and updates the internal links.
> 0.62 release blog post update

- website/versioned_docs/version-0.62/tutorial.md
Refs: #1802, #1804
This PR fixes `Hello World` example in `0.62` versioned docs. It's a backport of #1785.
> fix Hello World example in 0.62 docs

- docs/getting-started.md
Motivation:
* It seems that some of external links to `Watchman` are outdated.
Modification:
* Fix broken links
Result:
* The page is updated with the correct links.
> Fix outdated links in `getting-started.md` page

- website/versioned_docs/version-0.60/typescript.md
- website/versioned_docs/version-0.61/typescript.md
Specified the version of typescript template to use for starting up RN project in typescript, as specified in https://github.com/react-native-community/react-native-template-typescript
> docs: specify typescript template version

- website/versioned_docs/version-0.61/segmentedcontrolios.md
Initial PR #1774 was created before PR #1779 which added separate SegmentedControliOS page to the `0.61` version of docs. Without a PR rebase I was not able to access that file, sorry for that!
This PR fixes 404 images links on that page and replaces code block with a Snack example.
> update SegmentedControliOS page generated for 0.61

- docs/navigation.md
Component attribute should be the same as function name, HomeScreen. I've also added ProfileScreen function to complete the example code.
> Fixed component attribute for HomeScreen

- docs/share.md
This PR fixes the types of Share.sharedAction and Share.dismissedAction.
These two static properties are not callable, but these are strings. ref: https://github.com/facebook/react-native/blob/master/Libraries/Share/Share.js#L154
> Fix types in Share module

- docs/handling-text-input.md
Import (Component) removed because there is no use in the example.
```javascript
import React, { Component, useState } from 'react';
```
> Remove unnecessary import (Handling Text Input)

- docs/statusbar.md
On Android API levels before 23, the barStyle property is ignored. This change documents this effect to avoid bad surprises.
Thanks for this great project! ❤️
> DOC: Precise when the StatusBar barStyle is enforced

- docs/tutorial.md
- website/versioned_docs/version-0.62/tutorial.md
The sample crashes if `marginBottom` is a String. Using a number solves the crash.
> App crashes if marginBottom is a string

- docs/safeareaview.md
Add information about `SafeAreaView`'s implementation to try to reduce the number of hits on [#22211](https://github.com/facebook/react-native/issues/22211)
> Add information about padding behavior for SafeAreaView

- docs/intro-react-native-components.md
This fixes facebook/react-native#28592
> Fixed image source example as it wasn't working in non-web RN

- website/versioned_docs/version-0.62/textinput.md
Remove empty h2 that is between textBreakStrategy and underlineColorAndroid
> Remove empty h2

- website/versioned_docs/version-0.62/keyboardavoidingview.md
Basically a copy of #1803, but to 0.62 instead of master.
> Fix typos in KeyboardAvoidingView docs for 0.62

- docs/appearance.md
- website/i18n/en.json
- website/versioned_docs/version-0.62/appearance.md
Related to https://github.com/facebook/react-native/issues/26705.
A fix for https://github.com/facebook/react-native/issues/26705 will have the Appearance module return `light` if the app is being debugged using Chrome Debugger.
```
yarn
yarn start
```
Verified Appearance page shows the callout.
> Document getColorScheme behavior while sync debugging

- docs/touchablehighlight.md
The button background needs to be in a child View otherwise the background becomes black instead of slightly dimmed.
> Incorrect use of TouchableHighlight in example

- docs/accessibility.md
Fixed a few places in the accessibility docs where code snippets included curly quotes and references to code where quoted when they should have been in back-ticks to be monospaced (as is common in the rest of the docs).
> Minor tidy of Accessibility docs

- website/versioned_docs/version-0.62/intro-react.md
This small PR fixes typo on the versioned React Intro page for 0.62, fixes #1842.
> fix React Intro typo in 0.62

- docs/picker.md
- docs/pickerios.md
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-0.61/pickerios.md
- website/versioned_docs/version-0.62/picker.md
- website/versioned_sidebars/version-0.62-sidebars.json
This PR adds depreciation note to the `Picker` component page, updates depreciation note on the `PickerIOS` and removes `Picker` from the `0.62` and `next` sidebars (similar as all other deprecated components), fixes #1836.
Deprecation note can be found in the code here:
* https://github.com/facebook/react-native/blob/master/index.js#L163
> add deprecation note to the Picker components

- website/i18n/en.json
- website/versioned_docs/version-0.5/intro-react-native-components.md
This PR adds copy of Core Components page to the first versioned docs to prevent 404 (it's simpler and  more future-proof than finding and removing links from all the older versions), fixes #1780.
> add Core Components page to the first versioned docs to prevent 404

- docs/modal.md
Component was being imported in the functional component example, but it was not used in the example.
> Remove unused Component import

- docs/colors.md
- docs/platformcolor.md
This PR updates `Platform Color` API page according to the changes introduced in facebook/react-native#28703. It also adds `R.color` link for Android and information about prefixes to both sources.
> update Platform Color usage on iOS, add Android R.color

- docs/button.md
- website/versioned_docs/version-0.37/button.md
- website/versioned_docs/version-0.42/button.md
- website/versioned_docs/version-0.49/button.md
- website/versioned_docs/version-0.5/button.md
- website/versioned_docs/version-0.50/button.md
- website/versioned_docs/version-0.51/button.md
- website/versioned_docs/version-0.58/button.md
- website/versioned_docs/version-0.60/button.md
- website/versioned_docs/version-0.62/button.md
The link to the _wide variety of button components built by the community_ on the [Button page](https://reactnative.dev/docs/button) seems to be broken and points to a 404 page.
This PR fixes it so the link correctly points to the intended destination.
> Fix link to button components built by the community

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/other.md
This small PR adds issue templates (in short, "Bug" and "Other") and helpful links to the "New issue" flow on the GitHub. Files are heavily based on the React Native repository [config files](https://github.com/facebook/react-native/tree/master/.github/ISSUE_TEMPLATE). The main motivation behind those changes were to help newcomers and guide them in the correct place, to help reporters to create quality issues and requests and to streamline the whole process and make it more consistent with current React Native approach.
I would like also to thank @rachelnabors for the help and tweaks during the creation process of this PR.
> add issue templates and helpful links based on RN repository config

- docs/animated.md
- docs/animatedvalue.md
- docs/animatedvaluexy.md
- website/i18n/en.json
- website/sidebars.json
Refs #1801, #426
For unknown for me reason `Animated.Value` and `Animated.ValueXY` pages has been lost without a sidebar entries for the few releases. After a quick glance at the code those APIs docs seems up to date.
This PR updates both pages to roughly match current standards, `Animated.ValueXY` class component example has been replaced with functional example in Snack, both of them has been added to the sidebar and a mentions has been added to the `Animated` page.
I can also port those changes to the `0.62` branch if you think it would be helpful.
> update animated values pages, add them to the sidebar

- website/i18n/en.json
- website/versioned_docs/version-0.58/webview.md
Fixes #1154
This small PR improves a bit the last version of `WebView` component page and fixes the issue mentioned above by:
* updating the deprecation note to the standardized form,
* removing in content props and method listing (which functionality was replaced by the `onPageNav` component located at the right side of the screen).
> standardize WebView page: update deprecation note, remove listing

- website/i18n/en.json
- website/versioned_docs/version-0.58/cameraroll.md
Fixes #1503.
This small PR improves a bit the last version of CameraRoll component page and fixes the issue mentioned above. Summary of changes:
* deprecation note added,
* in content method listing removed (this functionality was replaced by the `onPageNav` component located on the right side of the screen).
> standardize CameraRoll page: add deprecation note, remove listing

- docs/components-and-apis.md
- docs/libraries.md
- website/i18n/en.json
- website/sidebars.json
- website/versioned_docs/version-0.62/components-and-apis.md
- website/versioned_docs/version-0.62/libraries.md
- website/versioned_sidebars/version-0.62-sidebars.json
- It's a safe bet to say that every React Native project ever shipped contains some kind of third party JavaScript library, and so we should help users to understand this and to learn how they can integrate libraries into their projects. This came up in a discussion with several folks interested in https://reactnative.directory/
- In my mind, this is the first step towards creating a first-class section on the topic, similar to the [flutter.dev Packages & Plugins section](https://flutter.dev/docs/development/packages-and-plugins/using-packages) (shout-out to Flutter folks, nice work).
- I included a backport to 0.62 docs because this isn't tied to a specific React Native version and would be immediately useful. Feedback is probably best kept to just docs/libraries.md as the versioned copy …
> Add workflow page "Using Libraries"

- docs/flatlist.md
Update code examples to avoid anonymous function on renderItem.
I'd assume that some people might use code examples as a first point of contact or a best practice and it's probably worth to write them avoiding known issues. According to the performance guidelines here: https://reactnative.dev/docs/optimizing-flatlist-configuration#avoid-anonymous-function-on-renderitem anonymous function on renderItem will recreate itself each time render function called and therefore might cause performance degradation.
> Avoid anonymous function on renderItem in code examples.

- docs/appearance.md
- website/versioned_docs/version-0.62/appearance.md
Added missing `addChangeListener` and `removeChangeListener` APIs present in Appearance module: https://github.com/facebook/react-native/blob/0.62-stable/Libraries/Utilities/Appearance.js
Updated docs for 0.62 and current.
> fix: add missing Appearance module APIs

- docs/appstate.md
when appState was being created with useState, the _handleAppStateChange had the original appState reference at the time that the event listener was created, and therefore never updated and remained 'active'. Adding a useCallback also did not seem to update appState, even if appState was added as a dependency.
> AppState Function Component Example Fix: useRef instead of useState

- docs/hermes.md
- website/versioned_docs/version-0.62/hermes.md
Summary:   
This is problem is fixed with bumping SoLoader version in this commit:   
https://github.com/facebook/react-native/commit/0a6f058b6bd0493f7eece972b1f73be3606ca8d5#diff-5df8978d901ea853da66f065feee64ab
> Update android app bundle notice in hermes doc

- docs/components-and-apis.md
- website/versioned_docs/version-0.62/components-and-apis.md
In https://github.com/facebook/react-native-website/pull/1902 I made a typo and wrote "refer this guide" rather than "refer to this guide". I also added "please" before "refer" to be more polite.
> fix: "refer to" rather than "refer"

- docs/accessibility.md
- website/versioned_docs/version-0.5/accessibility.md
- website/versioned_docs/version-0.62/accessibility.md
This PR updates all versions of Accessibility page and introduces following changes:
* remove `accessibilityValue` from `0.61` docs and below ( fixes #1489 )
* remove `this` to promote more functional components
* fix `sendAccessibilityEvent` example
* sort headers (Android before iOS)
* backport few formatting tweaks from the current version to the versioned docs
* replace "pretty" quotation marks with the regular double quotes
> update Accessibility pages, tweak examples

- docs/touchablenativefeedback.md
This documents rippleRadius added to TouchableNativeFeedback which is & will be available in RN 0.63. See https://github.com/facebook/react-native/pull/28009/files
> chore: document rippleRadius in TouchableNativeFeedback

- website/static/css/docs.css
This PR introduces ability to mark pages in the main (left) sidebar as "New". This was a nice-to-have feature for a some time, but Docusaurs do not offer a build-in solution or feature for adding such marks and produced HTML do not have any common used anchors. 
To solve this issue I decided to use `href` attribute and "contain" [selector](https://www.w3schools.com/cssref/sel_attr_contain.asp) to match the desired pages. 
The downside of this solution is that the CSS should be updated at least on each version cut.
I have tested those changes with the latest browsers on Win (Chrome, FF, Edge), macOS (Chrome, Safari) and iOS (Chrome, Safari). Few CSS properties has been added to ensure that the design is similar everywhere.
> add ability to highlight new pages in the sidebar

- docs/typescript.md
- docs/upgrading.md
- website/i18n/en.json
This small PR tweaks titles of the two following pages for the sake of simplicity:
* `Using TypeScript with React Native` -> `Using TypeScript`
* `Upgrading to new React Native versions` -> `Upgrading to new versions`
> Update two page titles (remove "React Native")

- docs/rectorsize.md
- website/i18n/en.json
- website/sidebars.json
We have many shared complex object types that bloat component and API references. It's time to start cutting some up into handy to reference pages, starting with those in service of `Pressable`
> Adding the start of Object Types reference

- website/static/css/docs.css
This PR adds new platform labels for the props and methods (change cherry-picked from the `Pressable` PR) and updates the design of the table headings.
There were other colors tested for the iOS like shades of blue, violet and orange, but it ended as near black (`#222`) because of [this](https://developer.apple.com/app-store/marketing/guidelines/) Apple marketing guide. There is no official rules and guides according to the stand-alone iOS logo usage. There are also different versions of iOS logo used by Apple on the website:
* https://developer.apple.com/assets/elements/icons/ios/ios-128x128_2x.png
* https://www.apple.com/v/iphone/home/ah/images/chapternav/iphone_ios_light__jjio8uqmjxei_large.svg
Screenshot below is only a mock to present the visual aspect of the tables and labels …
> Platform labels and slim table headings

- docs/native-modules-ios.md
This PR fix RCTAlertManager link in native-modules-ios.md, when you click this link appears 404.
> fix RCTAlertManager.m link in Native Modules iOS

- docs/image.md
This small PR replaces the inline listed props for Image component `style` with link to the [Image Style Props](https://reactnative.dev/docs/next/image-style-props) page.
> replace inline Image style props with link to the Image Style Props page

- docs/intro-react.md
Change `<Cat food={["fish", "kibble"]} /> age={2}` to `<Cat food={["fish", "kibble"]} age={2} />`.
> Props note correction

- website/static/css/header.css
This PR changes the background of the search bar from dark to light.
There have been quite a few instances recently where I really struggled to find the search bar on the site, as there is not a whole lot of contrast between the search bar and the rest of the header.
Current search bar: 
Proposed search bar:
> Add light background to the search bar

- website/i18n/en.json
- website/sidebars.json
- website/siteConfig.js
- website/versioned_sidebars/version-0.59-sidebars.json
- website/versioned_sidebars/version-0.60-sidebars.json
- website/versioned_sidebars/version-0.61-sidebars.json
- website/versioned_sidebars/version-0.62-sidebars.json
The Components and APIs docs have been growing: components have shared props, APIs have shared objects. There's a lot of content now! I was thinking perhaps it would make sense to split them into two sections in the navigation structure like so
> Moving API and Components to their own sections

- docs/activityindicator.md
- docs/button.md
- website/static/css/docs.css
- website/static/css/react-native.css
This PR introduces improved labels design and updates the `ActivityIndicator` and `Button` pages code references according to the new "standard" based on `Pressable` docs.
I have also updated the examples a bit but mainly for the better readability.
> improved labels design + ActivityIndicator and Button pages tweaks

- docs/linking.md
missing word in the linking documentation
> Update linking.md. Missing word in linking documentaion

- docs/signed-apk-android.md
Since the previous step is:
```
$ cd android
$ ./gradlew bundleRelease
```
so next step we need to go back to the project root folder
> Need go back to project root before run testing

- docs/libraries.md
Hi,
Noticed there is a small typo in the https://reactnative.dev/docs/libraries page, this fixes it.
> Fix typo in using libraries docs page

- docs/pressable.md
This PR fixes the `Pressable` component ripple effect property on Android according to the latest code in the stable branch of 0.63 release. Color property has been replaced with the `RippleConfig` object which provides greater flexibility for the users.
Refs:
* https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Components/Pressable/Pressable.js#L128 
* https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Components/Pressable/useAndroidRippleForView.js#L28
Kudos @vonovak !
> fix Android ripple property on the Pressable page

- website/pages/en/index.js
- website/siteConfig.js
- website/static/css/header.css
- website/static/css/homepage/HeaderHero.css
- website/static/js/announcement.js
Adds the banner added in https://github.com/facebook/react-native-website/pull/1971 to every page.
Black lives matter.
> We can do better - show banner on every page

- website/static/css/header.css
The banner is not clickable on mobile because the pointer events are blocked by nav.
> Fix banner links not clickable on mobile

- website/static/css/header.css
This small PR fixes a display issue with the sticky navs and BLM banner. 
Also the background color of the banner has be adjusted to stand out a bit more.
> small tweaks for the BLM banner

- website/static/css/header.css
Fixes #1976
This small PR changes the approach to fixing the overlap and pointer events issues on mobile after introducing BLM banner. Previous fix breaks the main header pointer events on the desktop.
> fix overlap and BLM pointer events issue on mobile

- README.md
This small PR adds the `@reactnative` Twitter badge to the README file. Inspiration and code has been taken from the [React Native](https://github.com/facebook/react-native) repository.
> add twitter badge to the README

- website/static/css/header.css
- website/static/js/announcement.js
This PR is an attempt to mimic more reactjs.org style of BLM banner and small design changes on the reactnative.dev. The changes includes banner at the top, content grayscale filter and some minor improvements to prevent white background before the BLM banner loads and jumping of the header after the BLM banner loads (this problem has occured when components switched their places).
> mimic more reactjs.org BLM banner style, add grayscale filter

- docs/text.md
- website/versioned_docs/version-0.62/text.md
Because of this wrong endBlock you can not see the chapter `Nested text`(until you switch to class component example)
> Fix wrong endBlock in text.md

- docs/getting-started.md
- macOS Catalina now uses Zsh instead of Bash
It took me a while to figure this out when I was installing RN on a fresh OS. 🙂 You can find more information here: https://thenextweb.com/dd/2019/06/04/why-does-macos-catalina-use-zsh-instead-of-bash-licensing/
> fix: update installation instructions

- docs/drawerlayoutandroid.md
- website/versioned_docs/version-0.62/drawerlayoutandroid.md
Fixes an issue where the Expo Snack crashes at runtime due to invalid styling syntax.
> Fixed DrawerLayoutAndroid padding syntax which was causing the Expo Snack to crash

- docs/libraries.md
The react-native-unimodules link is updated. 
The current repo has been deprecated in favor of expo/expo monorepo
> Docs: Update react-native-unimodules link

- docs/running-on-device.md
- website/versioned_docs/version-0.5/running-on-device.md
- website/versioned_docs/version-0.62/running-on-device.md
I followed the [running locally](https://github.com/facebook/react-native-website#running-locally) instructions, but could not reproduce this bug #1993 locally.
Then I tried `npm run build` and found same bug in the release build.
Problem was in the comment `` position were facing issues. 
Repositioning comments solved the issue. 
Also repositioning comment has no impact on lint ( tested running `npm run lint` )
> Bug Fix #1993

- docs/accessibility.md
- website/static/css/docs.css
This PR replaces the platform names with the platform labels on the Accessibility page. This required a few additional CSS tweaks. Also the order of the sections has been adjusted.
> use platform labels on the Accessibility page

- docs/platform-specific-code.md
I think the documentation used to describe only two platform options in the paragraph I've changed. I've added two words to make it slightly more accurate and consistent.
> Add two words to platform-specific-code.md

- docs/getting-started.md
- docs/intro-react-native-components.md
- docs/libraries.md
- docs/more-resources.md
- website/versioned_docs/version-0.62/getting-started.md
- website/versioned_docs/version-0.62/intro-react-native-components.md
- website/versioned_docs/version-0.62/libraries.md
- website/versioned_docs/version-0.62/more-resources.md
Fixes #1975
This small PR fixes the two invalid links reported in the issues above in the current and 0.62 versioned docs. The reason why `getting-started.md` was converted to the same page link lies inside RNW custom redirects.
> fix few invalid links on the website

- docs/native-modules-android.md
- docs/native-modules-ios.md
- docs/navigation.md
- docs/network.md
- website/versioned_docs/version-0.5/accessibility.md
- website/versioned_docs/version-0.62/accessibility.md
This PR includes the changes from the Prettier run on all the website pages.
This is a periodic maintenance action, the last similar one was #1900 PR.
> changes from the Prettier run on all the pages

- docs/appstate.md
I found out that when _handleAppStateChange is triggered, appState is still "active". Therefore, ```appState.match(/inactive|background/)``` always return null. I believe this because _handleAppStateChange passed to useEffect was not updated. I propose a fix that is to add _handleAppStateChange to dependencies list of useEffect.
> Fix bug in example of AppState functional component

- docs/optimizing-flatlist-configuration.md
Due to https://github.com/facebook/react-native/commit/636d01bbd0b9a2e9617f8063713183a0a3a4d5fe
> Remove legacyImplementation

- docs/debugging.md
This diff replaces YellowBox docs with LogBox.
> Replace YellowBox docs with LogBox docs.

- docs/native-components-android.md
ReactImageManager's constructer is 
```
public ReactImageManager(ReactApplicationContext reactContext) {
mCallerContext = reactContext;
}
```
but while calling it in `ReactPackage` the code written is 
```
@Override
public List<ViewManager> createViewManagers(
ReactApplicationContext reactContext) {
return Arrays.<ViewManager>asList(
new ReactImageManager() **//Error here**
);
}
```
**Fix:**
```
@Override
public List<ViewManager> createViewManagers(
ReactApplicationContext reactContext) {
return Arrays.<ViewManager>asList(
new ReactImageManager(reactContext)
);
}
```
ReactImageManager 's constructer needs reactContext, so passing it solves the issue.
> Added missing argument in code snippet.

- docs/modal.md
This property is already documented further up this page, in addition to this instance wasn't defined as being Android-only.
> Remove duplicate documentation property for statusBarTranslucent on Modal

- website/static/css/header.css
- website/static/js/announcement.js
This PR adds an ability to slide up announcement bar on scroll (in a bit hacky, but working way). 
There were a lot of small UI/display glitches at the beginning, I have manage to fix most of them (I hope), but this solution is not ideal in any mean, it's just a temporary UX fix mainly for the small, mobile devices.
> Add an ability to slide up announcement bar on scroll

- website/core/RemarkablePlugins.js
- website/pages/en/help.js
- website/static/js/codeblocks.js
this PR remove ununsed parameters and variables declarations in different files.
> remove unused variables declarations and parameters in different files.

- docs/appstate.md
We experienced that the documentation was faulty so after we at @enpit found a fix, we wanted to share it with you. 
The old trigger `appState.current.match(/inactive|background/) && nextAppState === "active"` would never work because the useState hook doesn't update the state fast enough for the function to work. The solution is to use useRef instead and optional (to display the inactive status under iOS) also use a `useState` for cosmetics.
> Fixed the Function Component Example

- docs/alert.md
The `cancelable` property value is by default set to `false` in the source as can be seen [here](https://github.com/facebook/react-native/blob/master/Libraries/Alert/Alert.js#L61). I have updated the docs accordingly.
Please let me know if any changes are required.
> Fix Alert API docs

- docs/getting-started.md
Matching the configuration screenshot of the default folder location. I had some trouble during environment configuration when I figured out that the location from the screenshot provided was the correct one (for the Sdk location).
> updated default folder location for Android Sdk in Windows

- docs/getting-started.md
- website/versioned_docs/version-0.63/getting-started.md
With the release of v0.63.0, the default Android SDK version has been upgraded to 29 (https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#android-specific-2). I think it's necessary to update the documentation to reflect the changes.
> Update Android version in environment setup

- docs/flexbox.md
- website/versioned_docs/version-0.63/flexbox.md
On this site: https://reactnative.dev/docs/flexbox#align-items, the example for "Align Items" is not working
Fixes Issue #2040
> Fixed bug in AlignItems.

- docs/accessibility.md
- website/versioned_docs/version-0.5/accessibility.md
- website/versioned_docs/version-0.62/accessibility.md
- website/versioned_docs/version-0.63/accessibility.md
The notation of Talk**b**ack seems to more accurate for Talk**B**ack.
There is already `TalkBack` notation on the page, thus I unified the notation there.
> (Accessibility) fix some cases

- docs/hermes.md
- website/versioned_docs/version-0.62/hermes.md
this PR fix link in Hermes docs, metro configuration link!!.
when you click this link, 404 appears.
> fix link in hermes docs, metro configuration link.

- docs/intro-react.md
Without the "multiple times" part, the correct phrase would be "You can render this component in multiple places".
This could also be reworked as "You can render this component in multiple places and multiple times without repeating your code...".
> Fix missing "in" in intro-react.md

- docs/intro-react.md
There are two examples placed one on top of the other where the code is exactly the same. 
This makes the docs harder to understand, as referencing the same exact code for pointing out two different things in consecutive paragraphs can be confusing to a newcomer. It feels like a mistake, even though it can be backed that it is not.
I suggest removing the `export default Cat;` from the first example, where introducing the concept of default exports is not necessary, and use it only on the second code block, where the complete function component is displayed and once the concept has been properly introduced in the previous paragraph. 
I think this makes more sense and avoids the duplicate.
> Modify duplicate code block in intro-react.md

- docs/running-on-device.md
Change initialization of LaunchScreen in AppDelegate.m from using the XIB (which is now deprecated in 0.63) to the Storyboard file.
> Update LaunchScreen pro tip to use Storyboard

- docs/tutorial.md
- website/static/css/docs.css
Fixes #2014 
This PR replaces the React and React Native state usage comparison image on the Tutorial page with the two code block arranged in the column (also the problem from the issue above has been fixed). On the small devices blocks are stacked in rows.
Live preview: https://deploy-preview-2026--react-native.netlify.app/docs/next/tutorial#state
> replace state usage comparison image with the code blocks

- docs/switch.md
- website/versioned_docs/version-0.62/switch.md
- website/versioned_docs/version-0.63/switch.md
Fixes #2032.
Currently due to properties differences between core and out-of-tree `web` platform there are display issues with `Switch` component in the Snack Preview. This PR disables the `web` preview for the Switch to prevent causing unnecessary confusion for the website readers.
> disable web platform preview for the Switch component

- docs/getting-started.md
Just some quick clarifications to the Environment Setup section. Now that macOS defaults to `zsh`, I thought it might be useful to explicitly provide instructions for configuring with `zsh`.
> Clarify android environment variables for macOS and Linux

- docs/typescript.md
- website/pages/en/showcase.js
Fixes #2073 
This small PR fixes the reported in the issues above issue with Infinite Red link on the showcase page and updates few links on the Typescript page (for example: https://infinite.red/ignite redirect user to GitHub page).
> fix and update few links

- website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
Fixing the broken link for the RTL Example in the blog post.
https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps
> Fixing the broken link for the RTL Example

- docs/security.md
Noticed this great page and thought `expo-secure-store`, using keychain services on iOS and SharedPreferences and Keystore on Android, is worth mentioning too. 🙂
> Add `expo-secure-store` to a list of libraries to consider for secure storage

- docs/text-style-props.md
- docs/text.md
- website/versioned_docs/version-0.60/text.md
- website/versioned_docs/version-0.62/text.md
- website/versioned_docs/version-0.63/text.md
This PR updates the Text Style Props page (alphabetical order, platform labels, default values and additional description) and removes in content styles listing on the Text page for the current and few newest, versioned docs.
Source: https://github.com/facebook/react-native/blob/master/Libraries/DeprecatedPropTypes/DeprecatedTextStylePropTypes.js
> update Text Style Props, replace inline listing with link on Text website

- docs/platformcolor.md
I found this section specially hard to read, so I'm proposing some minor tweaks that I think will make it easier to understand. 
I also added a mention to the fallback values which the function can receive, taking from the original PR which introduced the changes (https://github.com/facebook/react-native/pull/27908)
I don't know what the exact policy is on this, but since this was introduced in RN 0.63.0, perhaps this could also be clarified on the docs, as using it from an older version will throw a `_reactNative.PlatformColor is not a function` error.
> Minor wording changes in PlatformColor.md

- docs/javascript-environment.md
Replace "standards functions" with "standard functions"
> Fix typo in javascript-environment.md

- docs/statusbar.md
- website/static/css/docs.css
This PR updates the `StatusBar` component page and introduces following changes:
* rewritten example:
* simplify code
* include transition toggler on iOS devices
* use `SafeAreaView` instead of container styles adjustments
* platform labels
* missing default values added
* missing types added
Also the small CSS adjustments were required because the page contains first occurrence of platform label inside the table and the small fix was required for the labels in the right sidebar.
> update StatusBar example and docs

- docs/pixelratio.md
this PR update iOS pixels description, this devices are very old!.
> update PixelRatio.md with new devices description.

- docs/running-on-device.md
- website/versioned_docs/version-0.5/running-on-device.md
- `Build number` is now nested inside of `Software information`.
- `Developer Options` now resides at `Settings` root.
Screenshots:
> Update instructions for enabling developer options on Android.

- website/versioned_docs/version-0.63/security.md
#2075 adds `expo-secure-store` to a list of libraries to consider for secure storage, this commit just backports that change to the live docs in 0.63.
> Backport #2075 to 0.63

- website/static/css/docs.css
Hello! Currently, when viewing the documentation in a desktop browser, if the right side navigation bar has more items than can fit within the page's height, there is no way to view these items. For example, users cannot navigate through all of the props of large components such as `View` or `FlatList` by using the right navigation bar. (https://reactnative.dev/docs/flatlist.html)
This pull requests adds a vertical scroll bar when there are more right nav items than can fit the screen. Otherwise, there is no scroll bar.
> Fix scrolling bug in side nav

- docs/getting-started.md
PR regarding issue #1610
Added a quick guide on how to upgrade the project Gradle version to avoid errors when using the lastest version of JDK.
Updated the Android Studio installation guide.
> Updated Android Environment setup

- docs/native-components-android.md
it's possible that "vend a view" is android-specific terminology, in which case, please feel free to close this.
> fix simple typo

- website/versioned_docs/version-0.58/cameraroll.md
Refs #2001 
This small PR fixes the `Edit` button on the latest versioned docs page for CameraRoll. The autogenerated by Docusaurus link is broken because the CameraRoll page has been removed from the current docs.
> fix CameraRoll edit button

- docs/running-on-device.md
- website/versioned_docs/version-0.62/running-on-device.md
Refs #2001
This PR replaces the Markdown headings with the HTML ones to prevent `onPageNav` (right sidebar) from populate on the Running on Device page.
All the changes has been backported to the `0.63` versioned docs to affect most of the website users.
Quote from my comment in the mentioned issue:
> The problems described above are known issues caused by content switching tabs (platform and OS in this case). For the same reason the right sidebar has been disabled on the Environment Setup page.
> 
> Within the current docs platform restrictions (Docusaurus V1) it is not possible to fix this problem cleanly in our codebase (also the V1 development has been frozen a while ago in favor of V2). Unfortunately the only solution for now is to disable the onPageNav (the right sidebar) on this …
> remove broken on-page sidebar from Running on Device page

- website/static/css/header.css
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/4138357/88712979-3776b680-d0e0-11ea-8259-d1fa026ef612.gif)|![after](https://user-images.githubusercontent.com/4138357/88712990-3b0a3d80-d0e0-11ea-9c18-7d9d556380e3.gif)|
The Black Lives Matter call to action banner added a fixed 100px to the pre-content banner height. Docusaurus seems to have a built-in anchor style to handle this itself, so this just updates that -80 to -180. Mobile was off a bit differently but 160px looked alright there.
EDIT: mobile before and after:
|Before|After|
|---|---|
|![before-mobile](https://user-images.githubusercontent.com/4138357/88713605-2ed2b000-d0e1-11ea-9329-108657a464b9.gif)|![after-mobile](https://user-images.githubusercontent.com/4138357/88713617-32fecd80-d0e1-11ea-97a8-664 …
> Correct anchor height offset for Black Lives Matter banner

- docs/getting-started.md
- website/versioned_docs/version-0.63/getting-started.md
Fixes #2019 
This PR fixes the problem described in the issue above and fixes the issue with initial page render (unnecessary sections were visible before the user interacts with tabs).
@rachelnabors Unfortunately I was not able to fix the issue and retain the `devNote` blocks, so the fix requires to removed them. I will work on restoring them in the future. To make the fix available to most of the users I have also backported all the changes from the current page to `0.63` versioned docs.
> fix Environment Setup page sections, backport all the changes to 0.63

- docs/image-style-props.md
This PR updates the Image Style Props page and includes the following changes:
* examples titles, examples reorder, examples visible in the sidebar
* platform label
* properties reorder
* description for the `backfaceVisibility` and `opacity`
* default values
* formatting tweaks
> update the Image Style Props page

- docs/refreshcontrol.md
- website/static/css/docs.css
- website/static/css/react-native.css
This PR updates the `RefreshControl` component page and introduces the following changes:
* platform and required labels
* example cleanup
* defined defaults
* section for `RefreshLayoutConsts.SIZE` with additional information
* minor formatting tweaks
Source for the changes: https://github.com/facebook/react-native/tree/master/Libraries/Components/RefreshControl
In addition to the page update the following PR sizes two minor display issues with the platform labels. One related to latest scroll fix and second related to the multiple platforms for one property.
> update RefreshControl page, fix minor platform labels display issues

- docs/height-and-width.md
Fixes #2071
Refs #2079
---
This PR adds the Percentage Dimensions section with a Snack example and short description (which for certain can be updated and phrased better 😉) to the Height and Width page. 
I have also optimized a bit the readability of the other examples on that page.
> add percentage dimensions section to the Height and Width page

- docs/testing-overview.md
- website/versioned_docs/version-0.62/testing-overview.md
- website/versioned_docs/version-0.63/testing-overview.md
The two testing libraries were finally merged today: https://callstack.com/blog/merge-of-react-native-testing-libraries/. No need to differentiate now. I used the "React Native Testing Library" naming to resemble "React Testing Library". It's the branding name and is easier to pronounce than `@testing-library/react-native`
> chore: reflect latest React Native Testing Library changes

- website/package.json
- website/siteConfig.js
- website/yarn.lock
Refs facebook/docusaurus#3124
Fixes #2081
This PR updates Docusaurus to the latest version and adds `slugPreprocessor` config field with RegExp removing HTML content. 
`slugPreprocessor` function is executed before creating the hash link slug, this enables the hash links customization.
> update Docusaurus, fix hash links

- docs/appearance.md
- docs/appregistry.md
- website/static/css/docs.css
This PR updates the Appearance and AppRegistry API pages to the new standards. Not all Types and descriptions has been added due to lack of the information in the RN source code and decision what to do with the Flow types, for example: [`React.ComponentType`](https://flow.org/en/docs/react/types/#toc-react-componenttype).
Appearance requires only few minor changes but the AppRegistry has been edited heavily:
* types related to AppRegistry extracted to separate section
* required labels (I had to add new `two-line` class for in-table properties with the lengthy description)
* methods alphabetical order
* other minor formatting and wording tweaks
Source:
* https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Appearance.js
* …
> update Appearance and AppRegistry pages

- docs/permissionsandroid.md
Adds `ACCESS_BACKGROUND_LOCATION` to list of permissions that require prompting the user.
> Add background location to dangerous permissions

- docs/integration-with-existing-apps.md
Updated the Swift statement, that you use when moving your app to production, so that in works in modern projects with Swift 3.x and up. Additionally I aligned the code example with the Objective-C version, so that it does not assign to a variable i.e. removed `let mainBundle =`.
> Updated statement for newer Swift and aligned with ObjC statement.

- website/static/css/header.css
- website/static/js/announcement.js
Fixes #2134
This PR changes the height of BLM banner from `100px` to `60px` and updates the banner text style to ensure that in the most cases text will fit in two lines (previously on some mobile devices text could break to three lines) and additional space can be reduced.
**Desktop (Win + 4k)**
**Desktop (MacBook Pro 15)**
**Mobile (iPhone SE)**
> adjust BLM banner height and text style

- docs/signed-apk-android.md
It resolves the warning:
```
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format.
```
> Update keystore type to PKCS12

- .circleci/config.yml
- docs/flatlist.md
- docs/textinput.md
- website/package.json
- website/yarn.lock
This PR introduces the following changes:
* bumps most of dependencies to the latest version (including minor release of Docusaurus V1)
* Prettier was not updated because since 1.17.0+ Markdown tables format were changed to use the minimal required characters count instead of adjusting table to the content, AFAIK it's not configurable (@rachelnabors please let me know if it's a problem from your point of view, I can update Prettier in the separate PR)
* adds simple script (`update-lock`) to optimize the Yarn lockfile to the `package.json`
* adds `homepage` field to `package.json`
* replaces the `license` with the correct [SPDX ID](https://spdx.org/licenses/)
* replaces `repository` field value in `package.json` with the [shortcut](https://docs.npmjs.com/files/package.json#repository)
* …
> bump most of dependencies, update package.json

- .gitignore
- website/package.json
- website/scripts/sync-api-docs/extractDocsFromRN.js
- website/scripts/sync-api-docs/generateMarkdown.js
- website/scripts/sync-api-docs/magic.js
- website/scripts/sync-api-docs/platforms.js
- website/scripts/sync-api-docs/preprocessGeneratedApiDocs.js
- website/scripts/sync-api-docs/sync-api-docs.js
- website/scripts/sync-api-docs/titleToId.js
- website/yarn.lock
The PR is part of an effort to merge the initial script created by @motiz88 . The project is a part of MLH fellowship program and involves automatic generation of the website docs from code comments and flow types as the end result.
To learn more about the project you can visit the project wiki: 
- [Project details](https://github.com/MLH-Fellowship/0.4.x-projects/wiki/React-Native-Flowtype-API-Docs-Generator)
- [RN Docs Standards](https://github.com/MLH-Fellowship/react-native/wiki/RN-Docs-standards)
* Add experimental script to sync API docs from code
* sync-api-docs: Support methods
* [remove before merging] Sync some API docs
* [remove before merging] Netlify fix
* sync-api-docs: add docs extraction script
* sync-api-docs: Improvements to method docs
* sync-api-docs: update docgen …
> Add initial script for auto doc-gen

- docs/linking.md
getInitialURL does not need a parameter. It turns the URL. addEventListener needs a 'url' parameter, however it's simply the string 'url' which wasn't clear.
Also, it may return `null` when debugger is enabled.
> Fixed Linking.getInitialURL and addEventListener

- docs/debugging.md
- docs/timers.md
This PR adds notes regarding the issue when Android timers are not in sync with the debugger. 
See here for the discussion https://github.com/facebook/react-native/issues/29591.
> Adding notes regarding the issue when Android timers are not in sync with the debugger

- docs/touchablehighlight.md
Fixes #2141 
Fix prop types of android props in TouchableHighlight component by replacing the `bool` type to `number` type in the markdown.
> Add correct prop types for Android props in TouchableHighlight

- docs/touchableopacity.md
Fixes #2141 
Fix prop types of android props in TouchableOpacity component by replacing the `bool` type to `number` type in the markdown.
> Add correct prop types for Android props in TouchableOpacity

- docs/touchablenativefeedback.md
Fixes #2141 
Fix prop types of android props in TouchableNativeFeedback component by replacing the `bool` type to `number` type in the markdown.
> Add correct prop types for Android props in TouchableNativeFeedback

- docs/integration-with-existing-apps.md
- docs/layoutanimation.md
- website/versioned_docs/version-0.5/integration-with-existing-apps.md
- website/versioned_docs/version-0.62/integration-with-existing-apps.md
- website/versioned_docs/version-0.63/integration-with-existing-apps.md
I tried to follow the "[Integration with Existing Apps](https://reactnative.dev/docs/integration-with-existing-apps)" Android guide, but did not succeed because the guide was outdated.
I have updated the guide with support for Autolinking.
My changes reflect what can be found in a [normal](https://github.com/facebook/react-native/tree/master/template/android) React Native Installation.
> Integration with existing apps updates

- docs/intro-react.md
Appreciate to the good document.
I think 'props' in render() is unnecessary. This will cause confusion to the biginner like me.
> remove unnecessary argument of render()

- docs/animations.md
- docs/communication-ios.md
- docs/inputaccessoryview.md
- docs/panresponder.md
- docs/platformcolor.md
- website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
- website/blog/2020-07-06-version-0.63.md
- website/versioned_docs/version-0.63/animations.md
- website/versioned_docs/version-0.63/inputaccessoryview.md
- website/versioned_docs/version-0.63/panresponder.md
- website/versioned_docs/version-0.63/platformcolor.md
This PR fix broken link on react-native-website because recently RNTester directory have been moved.
> Fixing Broken Link Because RNTester Changed Path

- docs/direct-manipulation.md
The examples in the Direct Manipulation section look to have fallen victim to a rogue codemod; they are currently a mix of functional and class syntax that doesn't actually work.
In this PR I do too many things (sorry):
* fix indentation (2 spaces everywhere)
* remove styles that don't aid in the understanding of the concept of direct manipulation
* convert everything from class to functional/hooks syntax
* repair the opacity example by dimming the button `onPressIn` instead of `onPress`
* use conventional ref forwarding to achieve the desired effect in the example where we show how to forward the effect of `setNativeProps` from a wrapper component to a child component
T74535407
> Modernize code examples in the direct manipulation section

- docs/alert.md
Source:
* https://github.com/facebook/react-native/blob/master/Libraries/Alert/Alert.js
This PR updates the existing Alert page and includes the following changes:
* adds `prompt` method (iOS only, previously only available for `AlertIOS`)
* adds `Alert` related types definitions
* rewrites Android dismiss example as Snack
* adds platform and required labels
* adds small text tweaks
> update Alert API page, include iOS specific functions from deprecated AlertIOS

- docs/transforms.md
- website/versioned_docs/version-0.62/transforms.md
- website/versioned_docs/version-0.63/transforms.md
Added matrix to transform props, as matrix is available in the transform property for stylesheet
ref: https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/processTransform.js#L48-L50
> docs: add matrix to transform

- docs/direct-manipulation.md
> docs: update deprecated usage of findNodeHandle in measureLayout

- docs/textinput.md
Original summary by @yungsters in [1b994f9](https://github.com/facebook/react-native/commit/b7b0e232028723794af4c79fc6366c483ae2350b):
> Introduces support for `onPressIn` and `onPressOut` on the `TextInput` component.
> This makes it possible to add visual feedback when users touch interact with `TextInput` components.
> TextInput: Add new `onPressIn` and `onPressOut` docs

- website/pages/en/index.js
This PR introduces few small tweak to the website homepage:
* out of tree platform repositories in the Community section are now linked,
* add RN macOS to the example platforms,
* unify dashes used on the home page (currently all three dashes have been used - `hypens`, `endash` and `emdash`), this PR change all of them to be `endash`.
> link out-of-tree platforms, add macOS platform, unify dashes on homepage

- docs/flatlist.md
- docs/sectionlist.md
- docs/viewtoken.md
- docs/virtualizedlist.md
- website/i18n/en.json
- website/sidebars.json
Source for the changes:
* https://github.com/facebook/react-native/blob/master/Libraries/Lists/SectionList.js
* https://github.com/facebook/react-native/blob/master/Libraries/Lists/ViewabilityHelper.js
* https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js
* https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedSectionList.js
This PR introduces the following changes and it is the initial step on working on the `List` components (some code, styling or formatting might change in the next few PRs related to other lists):
* extracts `ViewToken` object type to the separate page
* updates the `SentionList` props and description
* adds require and platform labels
* updates props order to be alphabetic
@rachelnabors Feel free to change …
> update SectionList page, extract ViewToken, add labels

- docs/building-for-tv.md
This adds a bit of info for other people struggling with Android TV.
> Added workarounds for TextInputs

- docs/image.md
- docs/layoutevent.md
- docs/text.md
- docs/textinput.md
- docs/touchablewithoutfeedback.md
- docs/view.md
- website/i18n/en.json
- website/sidebars.json
Source:
* https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js
* https://github.com/facebook/react-native/blob/master/Libraries/Text/TextProps.js
* https://github.com/facebook/react-native/blob/master/Libraries/Types/CoreEventTypes.js
This PR updated the Text page and introduces the following changes:
* add unique for Text component `TextLayout` and `TextLayoutEvent` objects definitions
* update examples to avoid `console.log` usage
* utilize platform labels
* required/optional related changes
* update `PressEvent` related props
Withing this changes also I have extracted the `LayoutEvent` to the separate page (located in Object Types). It is used by multiple components and those components pages also have been updated. 
@rachelnabors I have also decided not split …
> update Text page and add types, add LayoutEvent object page

- docs/signed-apk-android.md
https://github.com/react-native-community/cli/blob/master/docs/commands.md#run-android
`--variant [string]`
> Incorrect argument

- docs/textinput.md
- website/versioned_docs/version-0.62/textinput.md
- website/versioned_docs/version-0.63/textinput.md
Release Note - https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#breaking-1
Commit - https://github.com/facebook/react-native/commit/3f7e0a2c9601fc186f25bfd794cd0008ac3983ab
According to the Release Notes, the `onTextInput` prop is removed from **TextInput**
> Docs: Removing `onTextInput` prop from TextInput

- docs/running-on-device.md
> Signing not under General for me

- docs/getting-started.md
This PR aims to add an Android NDK installation guide that will be required by React Native version `0.64`. 
See here for reference. https://github.com/facebook/react-native/commit/18ffe12203d03b4e960d61d7bb50cd02bba94663
@Simek Can you add `Wait on future Release` tag for this?. When it does land and gets included in a React Native release, this doc change should accompany it.
cc @safaiyeh
> Adding Android NDK Installation Guide

- docs/integration-with-android-fragment.md
- website/sidebars.json
@seba1342 and I have added documentation for how to render a React Native component into a Fragment on Android. We are hoping to set up equivalent docs for a similar approach for iOS adding a component to a UIViewController.
We have set up a working example repo for this here: https://github.com/svnm/react-native-android-fragment-example
There was no current documentation on how to achieve this so we thought it would be best to add a new page to the docs. We used the approach set up by hudl https://github.com/hudl/react-native-android-fragment which has been merged in to react native now as [ReactFragment.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java)
We found some additional discussion and questions on this …
> Docs: Integration with android fragment

- docs/actionsheetios.md
That PR is updating `ActionSheet` docs according to the change feature from [PR](https://github.com/facebook/react-native/pull/28792) which is adding a possibility to disable buttons.
~~Don't merge till https://github.com/facebook/react-native/pull/28792 will be merged.~~
EDIT: PR on RN is merged.
> Add new option to ActionSheetIOS called disabledButtonsIndices

- docs/getting-started.md
Python is not required anymore on windows platform. The only binary addon for react-native project are some deps of `ws`, [which now have prebuilt binary and are optional](https://github.com/websockets/ws#opt-in-for-performance-and-spec-compliance). 
Tested on a brand new windows 10 image with only node installed, the initiating process goes well.
> Remove unnecessary python dependency

- docs/network.md
added note for android's android:usesCleartextTraffic flag in manifest file to allow non ssl encrypted networking - to go alongside the existing note for ios.
> Update network.md to show android non ssl block

- docs/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-ios.md
this PR remove link in `can be invoked`  in `native-modules.ios.md` I try to found this file in version 
https://github.com/facebook/react-native/blob/0.63-stable/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm#L756  it doesn't exists this specific line.
in master tree with recent version `turbomodule folder ` doesn't exists.
> remove link in native-modules-ios

- docs/keyboardavoidingview.md
changed the equality operator from equality to strict equality (from == to ===) when testing Platform.OS
> fixes equality operator used in platform test

- docs/clipboard.md
- docs/pickerios.md
- docs/progressbarandroid.md
- website/versioned_docs/version-0.61/clipboard.md
- website/versioned_docs/version-0.61/pickerios.md
- website/versioned_docs/version-0.61/progressbarandroid.md
- website/versioned_docs/version-0.61/progressviewios.md
- website/versioned_docs/version-0.62/clipboard.md
- website/versioned_docs/version-0.62/picker.md
- website/versioned_docs/version-0.62/progressbarandroid.md
- website/versioned_docs/version-0.62/progressviewios.md
- website/versioned_docs/version-0.63/picker.md
- website/versioned_docs/version-0.63/progressbarandroid.md
- website/versioned_docs/version-0.63/progressviewios.md
Some of the deprecated modules has been moved out of the react-native-community org to its own orgs. (ref: https://github.com/react-native-community/discussions-and-proposals/blob/master/partners/0002-apply-organization-repository-policy.md)
This PR fixes the URL of some of the transferred repositories to the new url.
- Picker
- ProgressView
- ProgressBarAndroid
- Clipboard
> docs: fix url of transferred repositories

- docs/segmentedcontrolios.md
- website/versioned_docs/version-0.60/segmentedcontrolios.md
- website/versioned_docs/version-0.61/segmentedcontrolios.md
- website/versioned_docs/version-0.63/segmentedcontrolios.md
The repository for react-native-segmented-control has recently changed to https://github.com/react-native-segmented-control/segmented-control , so I've fixed the url.
The package name is still `@react-native-community/segmented-control` for now, but this will also change in the future, so I'll make the change once that happens.
> docs: change url for react-native-segmented-control

- docs/tutorial.md
- website/versioned_docs/version-0.63/tutorial.md
Titles prop is given in button component in tutorial, it is fixed as title
> wrong prop usage fixed

- website/src/pages/index.js
Fixes #2285
This PR adds a "fix" for the reported issue by wrapping two links with `<span>` tags. 
I have also updated the two links used in in that section.
> fix homepage community section links

- website/docusaurus.config.js
Fixes #2295
This PR adds [blog plugin configuration option](https://v2.docusaurus.io/docs/blog/#feed) which enables the RSS feeds for the blog posts on the website.
> add blog posts feeds

- website/docusaurus.config.js
- website/sitePlugin.js
- website/snackPlayerInitializer.js
- website/src/theme/Layout.js
cc @Simek , should fix Github Pages trailing slash issues
/myDoc will not redirect 301 to /myDoc/ anymore
Temporary fixes https://github.com/facebook/react-native-website/issues/2291
> attempt to fix trailing slash issues on GH pages

- website/src/theme/Layout.js
Currently old links like https://reactnative.dev/docs/switch.html are leading to 404 pages. 
This PR adds a temporary redirect (in same fashion as trailing slash fix) for links ending with `.html`. 
The result isn't ideal (the redirect is visible), but this should be enough until the problem will be fixed on the built server package.
> temporary fix .html ending links on the client side

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
Node 14 is the new active LTS as of October 27, 2020, so we have dropped support for Node 10 and declared Node 12 LTS as the minimum supported version going forward. This should only affect releases 0.64 and onward.
> Bump minimum Node version to 12

- docs/platformcolor.md
- website/versioned_docs/version-0.63/platformcolor.md
This PR updates the `PlatformColor` API page and introduce the following changes:
* header for supported colors list
* colors list moved above Developer Notes
* mention about supporting both notations (Objective-C and Swift) on iOS
* additional link to supported [UIColor Standard Colors](https://developer.apple.com/documentation/uikit/uicolor/standard_colors) on iOS
* example converted to Snack
* example content updated in a way which shows colors usage from each supported list for both platforms
The changes has been also backported to `0.63` docs. 
Earlier due to lack of support of `PlatformColor` in Expo SDK guide had to use plain code blocks, but in a meanwhile the SDK 39 has been released which includes this API.
> [PlatformColor] updated supported colors section, updated example converted to snack

- docs/layoutanimation.md
- website/versioned_docs/version-0.63/layoutanimation.md
Changes:
```diff
- background: "lightGrey"
+ backgroundColor: "lightgrey"
```
In example of LayoutAnimation stylesheet for 'title' contains 'background' property.
It throws error as it should be 'backgroundColor'.
also value of the same is 'lightGrey' which is not supported. It should be 'lightgrey'.
> Chaged from 'background' to 'backgroundColor'

- docs/imagebackground.md
- website/versioned_docs/version-0.63/imagebackground.md
Fixes #2303
This small PR updates `ImageBackground` page and fixes the error in the `next` example and ports the example changes back to `0.63` for the consistency.
> fix and update ImageBackground example

- docs/components-and-apis.md
- website/versioned_docs/version-0.63/components-and-apis.md
This PR update the Core Components and APIs page and introduces the following changes:
* moves Android section above iOS to match the docs sidebar order
* fixes the Android header in `next` docs
* fixes two malformed links in `next` docs
> [Core Components and APIs] fix android header, reorder sections, fix links

- docs/safeareaview.md
- website/sidebars.json
- website/versioned_docs/version-0.63/safeareaview.md
- website/versioned_sidebars/version-0.63-sidebars.json
This PR moves the [`SafeAreaView`](https://reactnative.dev/docs/safeareaview) component to the iOS Components group, because it only have an effect on the some iOS devices. On Android it is treater as a regular `View` component. 
The component implementation was working like that from the beginning, but the page was probably missed during the sidebar groups refactor. We were able to spot this earlier and patch it in the V1 (Archive) `next` branch, but it looks like that after the V2 merge the entry in `next` sidebar was missing.
The change is applied to `next` and `0.63` docs and includes `supportedPlatforms` parameter for the Snack examples.
> move SafeAreaView to iOS components, fix sidebar in next docs

- website/plugins/remark-snackplayer/package.json
- website/plugins/remark-snackplayer/src/index.js
- website/sitePlugin.js
- website/snackPlayerInitializer.js
- website/yarn.lock
This PR simplifies the `parseParams` method used in `remark-snackplayer` plugin, extracts node processing to separate function and comments out few console logs left from debugging here and there.
> chore: simplify parseParams in Snacks plugin, comment out few logs

- docs/image.md
The Image component methods "prefetch" and "queryCache" are async functions.
I added this to the docs and added the android only callback of the prefetch method. 
(RN-source: https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.android.js#L197)
The prefetch method returns a Promise<boolean> (that is always true but added it anyway).
Elements of the "queryCache" result can also be "disk/memory", 
(RN-source: https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.android.js#L214)
I could add some example code to the queryCache method.
Not sure if that would be helpful.
> [image-component] add docu for method parameters and return value

- docs/performance.md
- website/versioned_docs/version-0.63/performance.md
The first paragraph under "Slow navigator transitions" is split in two for no apparent reason, causing unwanted formatting:
This PR simply joins the two paragraphs into one.
> Fix typo under "Slow navigator transitions"

- website/showcase.json
Update blog link for Wix in the customer showcase to be: https://medium.com/wix-engineering/react-native-at-wix-the-architecture-db6361764da6
Built locally:
> Add link to Wix blog post

- docs/_getting-started-macos-android.md
Remove HAXM requirement because hard it's:
1. not needed
2. virtually impossible to install on newer macOS:
Not used on OS X v10.10 Yosemite and higher:
"For OS X v10.10 Yosemite and higher, the Android Emulator uses the built-in Hypervisor.Framework by default, and falls back to using the Intel Hardware Accelerated Execution Manager (HAXM) if Hypervisor.Framework fails to initialize (such as when running on OS X v10.9 or earlier)."
https://android-developers.googleblog.com/2018/07/android-emulator-amd-processor-hyper-v.html
Not supported on OS X v10.9 or earlier:
"Supported Operating Systems:
...
macOS* 10.12, 10.13, 10.14"
https://github.com/intel/haxm/releases/tag/v7.6.5"
(https://github.com/intel/haxm/releases/download/v7.6.5/haxm-macosx_v7_6_5.zip -> Release Notes.txt)
So by my …
> Remove HAXM requirement

- website/versioned_docs/version-0.63/typescript.md
On the React Native documentation website, code snippets have a `Copy` button in the top right corner.  So if the commands for `yarn` and `npm` are in the same code block, the user might click `Copy` and then paste both commands into their shell.
> avoid confusing clipboard copy behavior

- docs/_integration-with-exisiting-apps-objc.md
- docs/debugging.md
- docs/libraries.md
- docs/linking-libraries-ios.md
- docs/troubleshooting.md
This PR adds few missing NPM/Yarn tabs instead of static code blocks (related only to one package manager). The changeset also includes the small tweaks to other code blocks (correct syntax highlight - when no language is specified, default is `jsx`).
> add few package managers tabs, update few code blocks

- website/versioned_docs/version-0.63/typescript.md
Refs #2319
This PR ports back changes to the Typescript page from `next` branch to to the `0.63`. The changes mainly includes migration to Tabs component and corrected links.
> [Typescript] port back changes from `next`

- docs/alert.md
- docs/image.md
- website/docusaurus.config.js
- website/src/css/customTheme.scss
This PR updates the Image component docs page and introduces the following changes:
* update to match the current API and props with `0.64` branch cut - https://github.com/facebook/react-native/tree/0.64-stable/Libraries/Image
* missing prop types added - ImageSource, ImageLoadEvent - and ImageCacheEnum extracted to separate section for the readability
* platform and "required" labels added
* small tweak to labels indicator display in ToC for better readability
* ability to manually enlarge some table columns width
* fixed internal links (V2 still misses the slug functionality)
* fixed Grade script highlight
> [Image] update docs, add missing types, improve required label

- .gitignore
- docs/layoutanimation.md
- package.json
- plugins/remark-snackplayer/README.md
- plugins/remark-snackplayer/package.json
- plugins/remark-snackplayer/tests/index.js
- sync-api-docs/package.json
- website/docusaurus.config.js
- website/package.json
- yarn.lock
This PR preforms cleanup after the workspace introduction and includes the following changes:
* `husky` and `prettier` has been moved to workspace dependencies, Prettier command has been added to the new workspaces and code has been formatted
* `remark-snackplayer` has been extracted to external package, than copied-in back during the migration process, so in theory we are using fork of [published in NPM package](https://www.npmjs.com/package/remark-snackplayer), to avoid confusion package has been set to private, name has been changed to `@react-native-website/remark-snackplayer` and installation section has been removed from readme file
* `@react-native-website/remark-snackplayer` tests fixed (and made cross-platform)
* there is no need for `@react-native-website/remark-snackplayer` in …
> cleanup after workspace introduction, fix remark-snackplayer tests

- README.md
This PR updates Readme to match the workspace changes. Unfortunately Yarn workspaces are not compatible with the npm, but Yarn already is already listed in prerequisites. So to prevent the compatibility issues the npm alternative command has been removed.
Lately NPM released v7 of their CLI page which supports workspaces, but the implementation is different than Yarn and the both workspaces setups are not compatible with each other - https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
Maybe in time the compatibility package emerges which allow user of both tools to work with both workspace setups.
> update Readme to match the workspace changes

- website/src/css/customTheme.scss
This small PR tweaks a bit the footer design to fit better the four columns introduced in #2329. Changes includes better spacing and improved line height (because there are now multi line links).
> tweak footer design to fit better four columns

- docs/textinput.md
- website/versioned_docs/version-0.63/textinput.md
The docs say if multiline=false, but then the example below it is if multiline=true.
> Fix wrong boolean in docs

- docs/ram-bundles-inline-requires.md
Updates the guide on setting up inline requires in accordance with https://github.com/facebook/metro/pull/591, which is a Metro PR that **has not landed yet**. When it does land and gets included in a React Native release, this doc change should accompany it.
> Update inline requires doc for upcoming API change

- website/src/css/versions.scss
- website/src/pages/versions.js
This PR updates the Versions page and introduces the following changes:
* Master docs header renamed to `Next version (Unreleased)`
* `Stable versions` has been split to `Latest version` and `Previous versions`
* `init` command utilizes `npx` instead of deprecated global CLI
* spacing between the section have been adjusted
> update the versions page

- website/versioned_docs/version-0.62/linking.md
- website/versioned_docs/version-0.63/linking.md
- `Linking.addEventListener(url, callback)` tempts the reader to pass in a URL, when it should be the hardcoded string `"url"` instead
- `Linking.getInitialURL` doesn't take an argument
> Fix Linking docs

- docs/headless-js-android.md
- docs/navigation.md
- website/versioned_docs/version-0.63/headless-js-android.md
- website/versioned_docs/version-0.63/navigation.md
Changed **"A task is a async function"**  to **"A task is an async function"** on both the `docs` folder located in /docs and the docs for version 0.63.
> [docs]: minor grammar change

- website/src/css/customTheme.scss
This PR adds the basic styling for the `figure` and `figcaption` elements currently used, for example, on the Pressable page. The changeset also includes two small tweaks for other elements inside the `.markdown` scope.
> add basic styling for figure and figcaption elements

- website/src/css/customTheme.scss
Refs https://github.com/facebook/docusaurus/issues/3820
This small PR add a temporary fix/workaround to the Navbar overflow issues reported in the Docusuaurs repository.
The fix causes the Algolia search button to shrink to small version earlier and the width breakpoint have been selected in a way which should prevent an overflow to happen.
This should not hurt UX in any significant way, since the search field is only a button, which pops out the search form in modal.
> add temporary fix for navbar overflow issue

- website/src/css/customTheme.scss
Refs #2358
This PR is a small continuation of referenced PR above. This time the changes improves the docs sidebar sizing for certain small resolutions which still at too wide for the mobile menu check.
> small tweaks for the docs sidebar styling

- website/src/css/customTheme.scss
This PR adds simple React Native logo animation which is triggered on hover over the logo wrapper (so it's mainly relevant for the desktop users). The animation addition is not targeted to change the website visitor experience or amaze anyone, rather than it's a little step to make interacting with website a bit more unique, than the usual, generic docs site.
> add simple React Native logo animation

- docs/building-for-tv.md
- docs/native-components-ios.md
- docs/native-modules-android.md
- docs/native-modules-ios.md
- docs/native-modules-setup.md
- docs/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.60/building-for-tv.md
- website/versioned_docs/version-0.60/native-components-ios.md
- website/versioned_docs/version-0.60/native-modules-setup.md
- website/versioned_docs/version-0.60/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.61/building-for-tv.md
- website/versioned_docs/version-0.61/native-components-ios.md
- website/versioned_docs/version-0.61/native-modules-setup.md
- website/versioned_docs/version-0.61/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.62/building-for-tv.md
- website/versioned_docs/version-0.62/native-components-ios.md
- website/versioned_docs/version-0.62/native-modules-setup.md
- website/versioned_docs/version-0.62/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.63/building-for-tv.md
- website/versioned_docs/version-0.63/native-components-ios.md
- website/versioned_docs/version-0.63/native-modules-android.md
- website/versioned_docs/version-0.63/native-modules-intro.md
- website/versioned_docs/version-0.63/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-setup.md
- website/versioned_docs/version-0.63/optimizing-flatlist-configuration.md
Refs #2364
This PR fixes the "Javascript" -> "JavaScript" capitalization typo across all docs and versioned docs files.
> fix "Javascript" capitalization typo across all docs

- plugins/remark-snackplayer/package.json
- plugins/remark-snackplayer/src/index.js
- plugins/remark-snackplayer/tests/markdown/test2.md
- plugins/remark-snackplayer/tests/output/output1.html
- plugins/remark-snackplayer/tests/output/output2.html
- website/docusaurus.config.js
- yarn.lock
This PR adds [`data-snack-loading` param](https://github.com/expo/snack/blob/main/docs/embedding-snacks.md) to the `remark-snackplayer` plugin and sets the default value to `lazy` to reduce the overhead when entering a page with multiple instance of Expo Snack - https://web.dev/iframe-lazy-loading/.
I have also updated the plugin tests, package description and bumped the dependencies.
> add loading param to remark-snackplayer plugin

- docs/image.md
- docs/pressable.md
- docs/scrollview.md
- docs/shadow-props.md
- docs/textinput.md
- Add support for `shadowColor` on API level >= 28 ([cfa4260598](https://github.com/facebook/react-native/commit/cfa42605989eee5a9de42bdb1259fb7f4d9451fb) by [@IjzerenHein](https://github.com/IjzerenHein))
- Adds support for the `onProgress` event on `Image` ([fa0e6f8051](https://github.com/facebook/react-native/commit/fa0e6f8051d2208af467b789a2a9306ec7ddad76) by [@yungsters](https://github.com/yungsters))
- ScrollView now supports `contentOffset` ([ed29ba13f9](https://github.com/facebook/react-native/commit/ed29ba13f97f240c91fdf6c0ef3fb601046697b9) by [@JoshuaGross](https://github.com/JoshuaGross))
- Add `showSoftInputOnFocus` to TextInput on `iOS` ([d54113d8c4](https://github.com/facebook/react-native/commit/d54113d8c4bcd0e0c7a09acca60819724eb69926) by …
> [docs]: Add 0.64 required updates to the documentation - Part 1/x

- docs/shadow-props.md
- docs/share.md
- docs/view-style-props.md
- website/src/css/customTheme.scss
This PR updates the Share, Shadow Props and View Props page to match latest patterns for doc pages. The changes includes platform labels, alphabetic order, fixed grouping and more.
Also the style of `<code>` blocks inside the table has be adjust a bit for better appearance when used inside the text line.
> update Share, Shadow and View Props pages to match latest patterns

- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.63/_getting-started-windows-android.md
By installing Node via nvm-windows instead of directly, users will be able to easily switch between the multiple different versions of Node that their various projects may require. If users first install Node directly and then realize they need the version-switching functionality that nvm-windows provides, they will need to uninstall Node before installing nvm-windows and re-installing Node through there - a likely and avoidable hassle.
> Recommend Node be installed via nvm-windows

- docs/appregistry.md
- docs/devsettings.md
- docs/interactionmanager.md
- docs/keyboard.md
- docs/layoutanimation.md
- docs/linking.md
- docs/panresponder.md
- docs/settings.md
- docs/usecolorscheme.md
- docs/usewindowdimensions.md
- docs/vibration.md
- website/src/css/customTheme.scss
This PR focuses on updating the Reference section in various components and APIs, so they follow latest UX patterns (like pattern description, required markings, supported platforms, properties and methods order). 
I have also converted the `useColorScheme` hook example to Snack, because current version of Expo supports that hook (which were a problem short after the release).
> update references sections on several pages, improve few examples

- docs/flatlist.md
- docs/virtualizedlist.md
This PR updates the `FlatList` and `VirtualizedList` reference sections, to match latest UX patters, which includes:
* alphabetical order of properties and methods
* "required" and "platform" labels
* few, added default values
* and other minor, formatting tweaks.
> update FlatList and VirtualizedList references

- docs/accessibilityinfo.md
- docs/appearance.md
- docs/devsettings.md
- docs/layoutanimation.md
- website/src/css/customTheme.scss
This PR updates the `AccessibilityInfo` page to the latest UX pattern, adds platform labels, sorts the methods and properties in alphabetical order and adds minor formatting tweaks.
The change set includes also minor changes to few pages, but the changes are only related to the formatting.
> update AccessibilityInfo page, small fixes on other pages

- docs/_getting-started-windows-android.md
- docs/platform.md
- website/sidebars.json
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.63/platform.md
- website/versioned_sidebars/version-0.63-sidebars.json
Fixes: #1509
This PR adds the initial version of `Platform` API page to the documentation. The page is present in main docs and has also been ported to latest versioned docs - `0.63`.
The page currently will include basic example and simple definitions of available properties.
Probably the descriptions can bee improved a lot and more content could be added in. The main goal for me was to add a missing part of documentation, hope someone will improve this in time.
> Add missing Platform API docs

- docs/flexbox.md
Corrected a typo that said a main axis was used instead of a cross-axis.
> Typo fix at Flexbox.md

- docs/native-modules-setup.md
Bob now lives under https://github.com/callstack/react-native-builder-bob and published as `react-native-builder-bob`. This PR updates the references in the documentation.
> Update documentation to point to new repo for Bob

- website/src/pages/help.md
Hi, I'm an Infinite Red contractor (you can see me on https://infinite.red/company) ... I was reading the React Native docs today, and noticed that the link to our Slack community was old and busted - here's the current correct link. Thanks!
> Update the Infinite Red Slack Community URL in help.md

- docs/animated.md
- website/versioned_docs/version-0.60/animated.md
- website/versioned_docs/version-0.61/animated.md
- website/versioned_docs/version-0.62/animated.md
- website/versioned_docs/version-0.63/animated.md
fixed the dead link to [rebound](https://github.com/facebookarchive/rebound), as the project page no longer exists
> docs: fix dead link to rebound

- website/src/pages/help.md
We have replaced the #react-native channel with #help-react-native, which this now links to directly
Related to #2405
> Update Reactiflux invite link

- docs/security.md
- website/versioned_docs/version-0.63/security.md
Hello!
I am the author of [react-native-encrypted-storage](https://github.com/emeraldsanto/react-native-encrypted-storage), secure alternative to Async Storage using Keychain and EncryptedSharedPreferences, and wanted to include it in the security docs, along with the existing options.
> docs: add another secure alternative to Async Storage in security page

- docs/text.md
- website/versioned_docs/version-0.62/text.md
- website/versioned_docs/version-0.63/text.md
Remove platform section from `adjustsFontSizeToFit` attribute in v0.62.0 and v0.63.0 documentation.
Text components `adjustsFontSizeToFit` platform support is currently marked as `iOS` even though this PR has added the feature to Android as well: https://github.com/facebook/react-native/pull/26389 and is mentioned in the release notes of v0.62.0 here: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0620
> Update text.md adjustsFontSizeToFit platform

- docs/performance.md
- website/versioned_docs/version-0.62/performance.md
- website/versioned_docs/version-0.63/performance.md
Noticed link to profiling is dead on and after 0.62. 
(Before 0.62, `Profiling` section exists on the performance doc just like [this](https://reactnative.dev/docs/0.61/performance#profiling), but looks like it's not there now.)
> Fix link to profiling in performance doc

- docs/actionsheetios.md
- website/versioned_docs/version-0.63/actionsheetios.md
In RN codebase, we have added feature to indicate userInterfaceStyle for native action sheet, and the doc is deprecated.
> Describe new added feature userInterfaceStyle in ActionSheetIOS

- docs/flatlist.md
- docs/sectionlist.md
- docs/virtualizedlist.md
- website/versioned_docs/version-0.60/flatlist.md
- website/versioned_docs/version-0.60/sectionlist.md
- website/versioned_docs/version-0.60/virtualizedlist.md
- website/versioned_docs/version-0.61/flatlist.md
- website/versioned_docs/version-0.61/sectionlist.md
- website/versioned_docs/version-0.61/virtualizedlist.md
- website/versioned_docs/version-0.62/flatlist.md
- website/versioned_docs/version-0.62/sectionlist.md
- website/versioned_docs/version-0.62/virtualizedlist.md
- website/versioned_docs/version-0.63/flatlist.md
- website/versioned_docs/version-0.63/sectionlist.md
- website/versioned_docs/version-0.63/virtualizedlist.md
The docs for components such as `ListHeaderComponent`, `ListFooterComponent` etc. in the virtualized list components (`FlatList`, `VirtualizedList` etc.) say that it can accept a React Component Class, a render function, or a rendered element. However, they don't really accept a render function.
You can see from the source code that the code never calls the passed prop as a function, only as a component or element: https://github.com/facebook/react-native/blob/6079256fcc222fb2581c804c340905ed9d8ac1ca/Libraries/Lists/VirtualizedList.js#L878. The type annotations for this prop also annotate it as a component or element.
While passing a render function (`ListHeaderComponent={() => <SomeThing />}`) appears to work, it's only because this is also the same signature as a function component. But …
> Fix the description for the *Component props for vritualized lists

- docs/touchableopacity.md
- website/versioned_docs/version-0.62/touchableopacity.md
- website/versioned_docs/version-0.63/touchableopacity.md
Per the discussion here https://github.com/facebook/react-native/issues/29272, setOpacityTo is now a deprecated and completely-removed API. This PR updates the TouchableOpacity documentation to remove it from there as well.
> Remove documentation of setOpacityTo instance method

- docs/flexbox.md
- website/versioned_docs/version-0.63/flexbox.md
On react-native flexShrink default value is not 1 but 0. 1 is the default value for the web and this can be confusing.
> Fix FlexShrink default value

- docs/platform.md
- docs/platformcolor.md
- website/versioned_docs/version-0.63/platform.md
- Added missing "methods" section with a `select()` method to [Platform API](https://reactnative.dev/docs/platform) reference as detailed in the [Platform Specific Code](https://reactnative.dev/docs/next/platform-specific-code#platform-module) section.
Fixes [#2453](https://github.com/facebook/react-native-website/issues/2453)
> #2453 - Add missing methods section to Platform API reference

- docs/flatlist.md
- docs/virtualizedlist.md
- website/versioned_docs/version-0.60/flatlist.md
- website/versioned_docs/version-0.60/virtualizedlist.md
- website/versioned_docs/version-0.61/flatlist.md
- website/versioned_docs/version-0.61/virtualizedlist.md
- website/versioned_docs/version-0.62/flatlist.md
- website/versioned_docs/version-0.62/virtualizedlist.md
- website/versioned_docs/version-0.63/flatlist.md
- website/versioned_docs/version-0.63/virtualizedlist.md
FlatList and VirtualizedList's default keyExtractor now checks item.id and item.key as of v60.0
> Update flatlist.md and virtualizedlist.md

- docs/platformcolor.md
- website/versioned_docs/version-0.63/platformcolor.md
this PR update android example in `PlatformColor` when you run in android device app crash, i fix that according this closed PR https://github.com/facebook/react-native/pull/27908, reference this issue #2454
> fix example in PlatformColor

- docs/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-ios.md
I tried the following code example and got an error. Read [this stackoverflow question](https://stackoverflow.com/questions/39692230/got-is-not-a-recognized-objective-c-method-when-bridging-swift-to-react-native) for the details. Since this affects swift 3+ I propose correcting this code example, and optionally mentioning this quirk in a short sentence.
> Fix swift bug in native-modules-ios.md

- docs/flatlist.md
- docs/pressable.md
- docs/scrollview.md
- docs/text.md
- docs/view.md
- docs/virtualizedlist.md
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.63/scrollview.md
Fixes: #2179
This PR updates the ScrollView page, adds platform labels, missing defaults and one missing prop, reported earlier in issue mentioned above. Also I have removed the deprecated prop `DEPRECATED_sendUpdatedChildFrames` from the base (`next`) docs because the property will be removed in upcoming `0.64` release - https://github.com/facebook/react-native/commit/345d0c1abb1afe937a06982c4328caee57820832.
Besides that I have normalized the `View Style` type naming across all of base docs files.
> update ScrollView page, add platform labels, add missing prop and defaults

- website/versioned_docs/version-0.63/modal.md
With Android back button, there was an announcement that the modal window closed, but the code failed to make it invisible.
Inserted line corrects this.
> Inserting omitted code
