facebook/react-native-website

- docs/systrace.md
Just Updated `Systrace` API with basic introduction, and added class/function component example.Ref issue #1579
> Update 'Systrace' API

- docs/drawerlayoutandroid.md
This small PR sorts `DrawerLayoutAndroid` props and methods alphabetically.
> sort DrawerLayoutAndroid props and methods

- docs/sectionlist.md
This small PR fixes broken in #1717 Section List class component example (syntax error).
> fix Section List class component example

- docs/layout-props.md
Related to #1579 
- API has been updated on flexWrap (no other changes found)
- Added Expo Example (hooks, ➡️  functions...)
> Docs: LayoutProps

- website/versioned_docs/version-0.60/toolbarandroid.md
Add information about the community ToolbarAndroid package https://github.com/react-native-community/toolbar-android
> docs: add information about toolbar android

- docs/appregistry.md
> AppRegistry example added

- docs/text.md
>  Adding onTextLayout prop info #1579

- docs/scrollview.md
From https://github.com/facebook/react-native/commit/f8a64f9d61054046bffc286df3e9abf805aac0d4 and https://github.com/facebook/react-native/commit/51aacd5241c4b4c0b9b1e1b8f9dabac45e5b5291
> Edit to `fadingEdgeLength`

- docs/testing.md
Just making a minor improvement: I thought we can do a better job of explaining what is meant by "test the component from the user perspective"
> clarify component test dos and don'ts

- docs/integration-with-existing-apps.md
- docs/pixelratio.md
> 🎨 Format menu paths

- docs/platform-specific-code.md
See https://github.com/facebook/react-native/blob/master/Libraries/Utilities/__tests__/Platform-test.js
> document default and native keys for Platform.select

- docs/view-style-props.md
@rachelnabors  this pr i only update this example with functional component !!!
> update view style props example with functional components

- docs/flexbox.md
@rachelnabors  i change this little example with functional components with arrow functions!!
> update flexbox examples with functional components

- docs/tutorial.md
Hello World example had a couple extra curly brackets
> Fix typo on tutorial.md

- docs/testing-overview.md
I have circled back to this again and made some small updates, I think this is a little better :) I hope the changes are clear, if not let me know.
> minor improvements to testing guide

- docs/intro-react.md
I am a also cat -> I am also a cat!
> Fix grammatical error in cat greeting

- docs/out-of-tree-platforms.md
It's not a fork of react, but it is a very notable wrapper - allows using react native on Linux, macOS, and Windows.
> Added proton native to out of tree projects

- docs/images.md
> Changed links for Metro docs

- website/static/css/react-native.css
Refs #1813, #1831.
Fix in table links appearance. Tested locally, I was not able to spot any regression/issues.
> fix in table links appearance

- docs/native-modules-ios.md
Was running into issues with this line, turned out I was forgetting to rebuild my project!
I'm sure there's better ways to word this, too. In general I think it would be nice to mention rebuilding somewhere near the top.
> [NativeModules iOS] Remind people to rebuild

- docs/refreshcontrol.md
Hi,
I just saw a warning when I opened the snack example, so I fixed it :)
> fix(RefreshControl): fix SnackPlayer

- docs/platform-specific-code.md
> Explanation doesn't include all examples provided

- docs/layout-props.md
> Add description to layout-props for flexBasis, flexGrow, and flexShrink.

- docs/network.md
- website/versioned_docs/version-0.62/network.md
This small PR fixes requests loop in the functional example on the Networking page, fixes #1849.
> fix functional example on the Networking page

- website/versioned_docs/version-0.5/getting-started.md
- website/versioned_docs/version-0.60/getting-started.md
- website/versioned_docs/version-0.61/getting-started.md
- website/versioned_docs/version-0.62/getting-started.md
> fixed broken watchman links

- docs/interactionmanager.md
> Added  cleanup method to interaction manager hook example

- docs/height-and-width.md
this PR i update both examples with arrow functions!
> update  height and width examples with arrow functions

- docs/props.md
this pr only remove component import in both examples.
> delete unused component  in Props Examples

- docs/intro-react.md
- website/versioned_docs/version-0.62/intro-react-native-components.md
- website/versioned_docs/version-0.62/intro-react.md
Fix Image components by adding uri property to their source prop.
Fixes #1876
> Fix Image components by adding uri property to their source prop.

- docs/keyboardavoidingview.md
this pr only remove component in react import
> remove unused Component in keyboardAvoidingView example

- docs/getting-started.md
> Updated Step 3. in getting-started.md

- docs/animations.md
> Fix UseEffect Array Dependency lint error in Expo Playground

- docs/animations.md
A small improvement to Animations docs. It's easier to understand example when example includes a minimum of mocks.
> Update ScrollView with Animated Event examples

- docs/getting-started.md
- website/versioned_docs/version-0.62/getting-started.md
Hey, first off, thank you for the thorough documentation! I just noticed some redundant, slightly confusing instructions for Android and MacOS. I thought they should match the instructions for iOS.
> edited documentation for macOS and android

- website/blog/2018-11-01-oss-roadmap.md
> docs(roadmap): update octoverse projects link

- website/blog/2020-03-26-version-0.62.md
This PR fix RN flipper documentation link. if you try to click appears 404 error
> fix flipper documentation link. 

- docs/handling-text-input.md
- docs/intro-react-native-components.md
- docs/intro-react.md
- docs/introduction.md
- docs/using-a-listview.md
This PR Update page Introduction (The Basic)
> Update examples introduction docs with the new standardize

- docs/actionsheetios.md
- docs/backhandler.md
- docs/permissionsandroid.md
- docs/settings.md
- docs/toastandroid.md
This PR update Android iOS Apis examples with new standardize!!!
> update ios and android Apis examples with new standardize

- docs/image-style-props.md
- docs/layout-props.md
- docs/shadow-props.md
- docs/text-style-props.md
- docs/view-style-props.md
This PR update all Props examples with the new standardize!! `Layout Props` has this standardize.
> update props examples with the new standardize

- docs/flexbox.md
- docs/height-and-width.md
- docs/style.md
This PR update all design examples with new Standardize!!
> update design docs examples with new standardize

- docs/accessibilityinfo.md
- docs/alert.md
- docs/animated.md
- docs/appstate.md
- docs/dimensions.md
- docs/easing.md
- docs/interactionmanager.md
- docs/keyboard.md
- docs/layoutanimation.md
- docs/linking.md
- docs/panresponder.md
- docs/pixelratio.md
- docs/share.md
- docs/stylesheet.md
- docs/systrace.md
- docs/transforms.md
- docs/vibration.md
this PR update all API examples docs with new standardize functions!!
> update API examples docs with the new standardize!!

- docs/actionsheetios.md
- docs/animatedvaluexy.md
- docs/animations.md
- docs/backhandler.md
- docs/checkbox.md
- docs/datepickerios.md
- docs/handling-text-input.md
- docs/native-modules-android.md
- docs/native-modules-ios.md
- docs/navigation.md
- docs/network.md
- docs/picker.md
- docs/progressbarandroid.md
- docs/progressviewios.md
- docs/props.md
- docs/state.md
- docs/tutorial.md
- docs/usewindowdimensions.md
> Issue #1921 standardized functions

- docs/activityindicator.md
- docs/button.md
- docs/flatlist.md
- docs/image.md
- docs/imagebackground.md
- docs/refreshcontrol.md
- docs/safeareaview.md
- docs/scrollview.md
- docs/sectionlist.md
- docs/switch.md
- docs/text.md
- docs/textinput.md
- docs/touchablehighlight.md
- docs/touchableopacity.md
- docs/touchablewithoutfeedback.md
- docs/view.md
This PR Update Core Components with new standardize functions, some example in core components like `KeyboardAvoidingView` it has this standardize!!
> update CoreComponents function Examples

- docs/getting-started.md
> Adding stepped instructions for running RN application

- website/static/css/docs-prevnext.css
- website/static/css/docs.css
- website/static/css/footer.css
- website/static/css/react-native.css
This PR includes small tweaks and small visual changes to the bottom components of the website: feedback box, prev/next navigation and footer.
In this changes I have also includes few minor CSS tweaks to the elements introduced earlier (platform labels, slim table headers).
> update slightly feedback box and footer designs

- docs/pressable.md
Got some feedback. Wanted to make the language a bit easier to understand
> Tiny edits to pressable wording

- docs/components-and-apis.md
https://reactnative.dev/docs/picker
> Remove picker as this is being deprecated

- website/static/css/homepage/Community.css
> fix responsive grid

- docs/animatedvaluexy.md
> Fixed Issue #1897 added description

- website/core/Footer.js
This PR updates the links in the `Footer` component (removes `.html` and trailing `/`) and stores `baseUrl` in the local variable to simplify the code.
> update links format in the Footer component

- docs/tutorial.md
This PR remove undefined styles.countContainer from docs/tutorial#state code example.
> Removing undefined styles.countContainer from View component

- docs/running-on-simulator-ios.md
this PR update iOS simulators descriptions, i think` iPhone 5s` it is old  so i changed for `iPhone SE`.
> update descriptions iOS simulator in running-on-simulator-ios.md

- website/pages/en/index.js
- website/static/css/homepage/HeaderHero.css
Supporting a movement that is important and will hopefully make a difference.
> Black Lives Matter banner

- docs/platform-specific-code.md
This PR includes 2 fixes for grammatical issues
> Fixed grammatical issues

- docs/inputaccessoryview.md
this little PR remove letter "s" in Know issues.!
> remove letter "s" inputaccesoryview

- docs/flatlist.md
this PR update `Flatlist` example i think select one button and change background color it's  a good example, not like older example to select one button it never turn off background color.
> update second example in Flatlist docs

- docs/text.md
Updating Text docs according to the change from https://github.com/facebook/react-native/pull/29157 which is adding android_hyphenationStrategy prop.
Thanks a lot. Fabrizio
> adding docs for android_hyphenationStrategy

- docs/upgrading.md
> Link to the actual Upgrade Helper, not the GitHub repo for it

- website/versioned_docs/version-0.63/pressable.md
> Fixed a minor typo

- website/versioned_docs/version-0.63/pressevent.md
> Fixed some minor typos

- docs/getting-started.md
- website/versioned_docs/version-0.63/getting-started.md
Somehow I missed eating a piece of pie in #2035 😄
> Update Android version in environment setup

- docs/pressable.md
> Clarify <Pressible> Docs

- website/pages/en/index.js
Resolves #2021. Also: `doesn't compromise on your users' experience` --> `doesn't compromise your users' experiences`
> Quick Grammatical change

- docs/textinput.md
update grammar error in importantForAutofill description
> Update textinput.md grammar for importantForAutofill description

- docs/statusbar.md
Added notch height information in StatusBar currentHeight description.
> Updated StatusBar currentHeight description regarding issue #2049

- docs/debugging.md
> Fix typo :zap:

- website/blog/2020-07-17-react-native-principles.md
I found these a bit confusing. I think in the original draft these examples were meant to show what React is *continuing* working on — not what React has popularized. Let's just cut it?
> Tweak blog wording

- website/blog/2020-07-17-react-native-principles.md
Thanks for this post: very helpful in making and communicating adoption decisions. This PR makes a uniquely tiny update for grammatical correctness 😄
Changelog:
- Update `unique` to adverbial `uniquely` in sentence about positioning to agree with the adjective `positioned` that it modifies.
> Make a small correction to Principles blog post

- website/pages/en/help.js
It hasn't been updated in awhile
> Removing Video show from Help

- website/blog/2020-07-23-docs-update.md
It didn't look quite right, and I couldn't keep quiet. 😉
> fix typo in blog post

- docs/intro-react-native-components.md
Extra "to" in the sentence "React Native lets you to build your own Native Components".
> Minor grammar fix in Introduction

- docs/using-a-scrollview.md
This PR fixes a small error in the ScrollView page.
> Small improvement / error fix in using-a-scrollView.md

- website/versioned_docs/version-0.63/debugging.md
> not sure if intentional 😉

- docs/typescript.md
Repost of #2011 with some changes (due to original author inactivity and missing CLA sign) .
> add uninstall commands to the TS note (repost of #2011)

- docs/direct-manipulation.md
> rectification of misleading docs between measure(callback) and onLayout

- docs/textinput.md
Preview: https://deploy-preview-2124--react-native.netlify.app/docs/next/textinput#passwordrules
> [TextInput] Add notes about `passwordRules`

- website/image-check.js
this little PR remove unused promises in `website/image-check.js`
> Remove unused promises in image-check file

- docs/getting-started.md
Fixed a few typos in getting started.
> Fix Typos in getting-started.md

- docs/more-resources.md
The blurb mentioned Redux which is in the old boilerplate. This PR updates the description to accurately reflect the current state of Ignite.
> Updates Ignite blurb to reflect latest boilerplate

- docs/publishing-to-app-store.md
- docs/running-on-device.md
- website/sidebars.json
This PR is for [this issue](https://github.com/facebook/react-native-website/issues/2127).
> run-on-device Building -> Guides (iOS): Publishing

- docs/flatlist.md
Small link addition, for quicker finding of code documentation.
> Adding a link to ViewabilityHelper.js

- docs/flexbox.md
- website/i18n/en.json
- website/yarn.lock
solves #2163 
replacing images with snack player for better ux
> adding snack player instead of images for flexbox

- docs/inputaccessoryview.md
Hello...
With these changes, we will have a better UI design...
Good Luck
> UI & UX Design with InputAccessoryView

- website/static/css/homepage/AppList.css
Fixes #2182
This small PR fixes the small graphical issue with the showcase app list by overriding the default link styles.
I have also added simple images hover effect (based on the opacity).
> fix homepage showcase app list graphical issue

- docs/scrollview.md
Related PR - #https://github.com/facebook/react-native/pull/27666/
Updating `disableIntervalMomentum` doc for ScrollView.
> Updated ScrollView `disableIntervalMomentum` doc

- docs/debugging.md
fixed a typo in unhandled error
> updated debugging.md

- netlify.toml
Fix Netlify config for the archive branch:
- publish URL is relative to base
- don't reduce versions for the production archive.reactnative.dev deployment
cc @Simek
> Netlify publish dir should be relative to base dir

- website/siteConfig.js
cc @Simek 
This should be merged on archive branch
This will temporarily break the archive search,  but will be fixed by merging this Algolia PR: https://github.com/algolia/docsearch-configs/pull/2668
We'll merge this Algolia PR once v2 site is live
> archive.reactnative.dev => update algolia index name

- website/docusaurus.config.js
> Try fix deployment

- website/docusaurus.config.js
- website/static/CNAME
> fix deployment CNAME

- docs/pixelratio.md
this PR update Pixel Ratio description specify `iPhone SE` generation.!
> update PixelRatio iOS description.

- docs/pressable.md
- website/versioned_docs/version-0.63/pressable.md
Add snack bar for the [example of pressable](https://reactnative.dev/docs/pressable#example)
> Add snack for the Pressable

- website/versioned_docs/version-0.60/animations.md
- website/versioned_docs/version-0.60/communication-ios.md
- website/versioned_docs/version-0.60/inputaccessoryview.md
- website/versioned_docs/version-0.60/panresponder.md
- website/versioned_docs/version-0.60/usecolorscheme.md
- website/versioned_docs/version-0.61/animations.md
- website/versioned_docs/version-0.61/communication-ios.md
- website/versioned_docs/version-0.61/inputaccessoryview.md
- website/versioned_docs/version-0.61/panresponder.md
- website/versioned_docs/version-0.61/usecolorscheme.md
- website/versioned_docs/version-0.62/animations.md
- website/versioned_docs/version-0.62/communication-ios.md
- website/versioned_docs/version-0.62/inputaccessoryview.md
- website/versioned_docs/version-0.62/panresponder.md
- website/versioned_docs/version-0.62/usecolorscheme.md
- website/versioned_docs/version-0.63/communication-ios.md
- website/versioned_docs/version-0.63/usecolorscheme.md
Fix `AppearanceExample.js` link on `Appearance.useColorScheme` docs.
> Fix RNTester broken links

- .circleci/config.yml
Refs: https://github.com/facebook/docusaurus/pull/3497
This PR attempt to fix the OOM issues occurring on the CircleCI. It it possible that they are caused by the Webpack Teraser plugin.
CC @slorber
> attempt to fix CI OOM issues

- website/docusaurus.config.js
> Adding important privacys and ToS links for FB OSS

- docs/textinput.md
- website/versioned_docs/version-0.63/textinput.md
> [docs] fix: minor grammer changes

- docs/security.md
- website/versioned_docs/version-0.62/security.md
- website/versioned_docs/version-0.63/security.md
the react-native-dotenv repo has migrated from zetachang to goatandsheep
issue #2325
> updated react-native-dotenv link

- docs/scrollview.md
- website/versioned_docs/version-0.63/scrollview.md
> StickyHeaderIndices updated with missing info

- docs/typescript.md
- website/versioned_docs/version-0.63/typescript.md
Fixed devDependencies flag in the "Adding TypeScript to an Existing Project" yarn command.
> Fixed devDependencies flag in yarn command

- website/versioned_docs/version-0.62/tutorial.md
- website/versioned_docs/version-0.63/tutorial.md
> Minor grammar correction to tutorial.md

- website/versioned_docs/version-0.63/maskedviewios.md
this PR update `react-native-masked-view` link name and URL!.
> update link name in MaskedViewIOS

- docs/native-modules-intro.md
> Javascript->JavaScript in native-modules-intro

- docs/hermes.md
- website/versioned_docs/version-0.63/hermes.md
This has been a frequently source of confusion. See https://github.com/facebook/hermes/issues/48#issuecomment-513340897 for an example.
> Update hermes.md to explain debugging on Hermes

- docs/_getting-started-macos-android.md
- website/versioned_docs/version-0.60/_getting-started-macos-android.md
- website/versioned_docs/version-0.61/_getting-started-macos-android.md
- website/versioned_docs/version-0.62/_getting-started-macos-android.md
- website/versioned_docs/version-0.63/_getting-started-macos-android.md
> Update brew syntax

- docs/handling-touches.md
- website/versioned_docs/version-0.63/handling-touches.md
by adding a conjunction and making the verb tenses consistent.
> Fix comma splice

- website/src/pages/index.js
this PR add curly braces in code example i think it looks bad without curly braces for people try to copy this component!.
> add curly braces in main component example

- docs/native-components-ios.md
- website/versioned_docs/version-0.60/native-components-ios.md
- website/versioned_docs/version-0.61/native-components-ios.md
- website/versioned_docs/version-0.62/native-components-ios.md
- website/versioned_docs/version-0.63/native-components-ios.md
> Remove unnecessary brackets from native-components-ios.md

- website/src/pages/help.md
Reverts #1292 as we now allow direct links to channels again
> Link directly to Reactiflux's React Native channels

- docs/native-modules-android.md
- website/versioned_docs/version-0.63/native-modules-android.md
> Fix typos in native-modules-android.md

- website/versioned_docs/version-0.63/keyboardavoidingview.md
> Fix: change comparison to equal value and equal type

- website/versioned_docs/version-0.63/navigation.md
- Change "For iOS with bare React Native project..." to "For iOS in a bare React Native project..."
> Improve language used in navigation.md

- website/versioned_docs/version-0.60/introduction.md
- website/versioned_docs/version-0.61/introduction.md
- website/versioned_docs/version-0.62/introduction.md
- website/versioned_docs/version-0.63/introduction.md
> Correct the version react hooks were released

- website/showcase.json
> Point to the correct Shopify React Native apps

- docs/intro-react.md
- website/versioned_docs/version-0.60/intro-react.md
- website/versioned_docs/version-0.61/intro-react.md
- website/versioned_docs/version-0.62/intro-react.md
- website/versioned_docs/version-0.63/intro-react.md
> docs: fix dead link

- docs/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-ios.md
> Fix syntax error.

- docs/activityindicator.md
- website/versioned_docs/version-0.63/activityindicator.md
> Fix spacing for Class Component in ActivityIndicator Docs

- docs/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-ios.md
this PR fix image example in `native-modules-ios.md`
reference this issue #2443
> fix image in native modules ios

- docs/scrollview.md
- website/versioned_docs/version-0.63/scrollview.md
It seems to be a mistake from a copy paste on `alwaysBounceHorizontal` above :)
> Fix ScrollView alwaysBounceVertical doc

- docs/flatlist.md
- website/versioned_docs/version-0.60/flatlist.md
- website/versioned_docs/version-0.61/flatlist.md
- website/versioned_docs/version-0.62/flatlist.md
- website/versioned_docs/version-0.63/flatlist.md
> Remove unnecessary `

- docs/more-resources.md
- website/versioned_docs/version-0.63/more-resources.md
Fixes #2499.
This small PR generalizes the More Resources page intro by removing the old continuity no longer valid after #1496.
> generalize More Resources page intro

- docs/alert.md
> Fixed typo – containg -> containing

- docs/native-modules-intro.md
- website/versioned_docs/version-0.63/native-modules-intro.md
> Pay wasn't capitalized (Native Modules intro)

- website/showcase.json
Updating the blog link to point to the new blog that Coinbase released last half
Current: [Onboarding Thousands of Users with React Native](https://blog.coinbase.com/onboarding-thousands-of-users-with-react-native-361219066df4)
New: [Optimizing React Native](https://blog.coinbase.com/optimizing-react-native-7e7bf7ac3a34)
> Update Coinbase blog

- website/versioned_docs/version-0.63/more-resources.md
Just a small fix I noticed while reading through the docs for "More Resources"
> Update Docs for Ignite now using "MobX-State-Tree" for state management

- docs/native-modules-setup.md
We recently moved the scaffolding part of Bob to a new package for faster bootstrapping. The PR changes the documentation to reflect that.
> Change the command for scaffolding a module

- docs/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.60/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.61/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.62/optimizing-flatlist-configuration.md
- website/versioned_docs/version-0.63/optimizing-flatlist-configuration.md
Refs: #2495
This is a typo fix, which was proposed in the referenced above PR, but author do not have accepted the Facebook CLA. 
I have waited a bit and than tried to poke the author, but it seems like the PR has been abandoned
> fix FlatList guide typo

- docs/virtualizedlist.md
- website/versioned_docs/version-0.63/virtualizedlist.md
Just adding a single spacing. Look at diff for more details.
> Add missing space after comma

- docs/height-and-width.md
- website/versioned_docs/version-0.63/height-and-width.md
- website/versioned_docs/version-0.64/height-and-width.md
As part of
#2533
The added information felt like it deserves a "note" styling.
> Change styling to note

- docs/height-and-width.md
- website/blog/2021-03-12-version-0.64.md
- website/docusaurus.config.js
- website/package.json
- website/src/css/customTheme.scss
- website/src/pages/index.js
- website/src/theme/DocItem/index.js
- website/src/theme/DocItem/styles.module.css
- website/versioned_docs/version-0.63/height-and-width.md
- website/versioned_docs/version-0.64/height-and-width.md
- yarn.lock
This PR updates the website engine - Docusuaurs - to the latest released version.
The changest includes tweak and fixes for RN website custom theme, re-swizzled components and some minor layout improvements across the different website modules.
The detailed Docusuaurs changelog can be found there:
* https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md
> update Docusaurus to latest release, add fixes to custom theme

- docs/image.md
- website/versioned_docs/version-0.64/image.md
Add nativeID prop to Image component, missing from the docs.
> chore: add nativeID to image.md

- docs/native-modules-ios.md
> fix return type

- docs/flatlist.md
- website/versioned_docs/version-0.64/flatlist.md
this PR update second example in Flatlist i think it's better to change the text color if the user clicks and change the backgroundColor!.
> docs: update second Flatlist example.

- docs/keyboard.md
- website/versioned_docs/version-0.62/keyboard.md
- website/versioned_docs/version-0.63/keyboard.md
- website/versioned_docs/version-0.64/keyboard.md
Fixes #2561
This PR includes the Keyboard API examples refactor to fix the reported Alert issue on iOS and improve the general code quality and readability.
> refactor Keyboard API examples

- .circleci/config.yml
- website/package.json
- website/src/css/customTheme.scss
- website/src/pages/index.js
- website/src/theme/DocItem/index.js
- yarn.lock
This PR bump the React packages version to the latest release, add small tweaks to the custom styles and fixes few Prettier warnings.
> minor React bump, small style tweaks and fixes

- docs/using-a-scrollview.md
while running this code on expo it says "Can't find variable: App" . So, I declared it using the const keyword and exported it default below the function
> App variable is not declared

- docs/text-style-props.md
- website/versioned_docs/version-0.62/text-style-props.md
- website/versioned_docs/version-0.63/text-style-props.md
- website/versioned_docs/version-0.64/text-style-props.md
added import of status bar to to avoid crashing on expo
> FIX: added StatusBar import

- docs/text-style-props.md
- website/versioned_docs/version-0.64/text-style-props.md
> Fix: added missing import of Slider

- website/versioned_docs/version-0.62/using-a-scrollview.md
- website/versioned_docs/version-0.64/using-a-scrollview.md
I've declared app variable ref #2568 on all version of the docs
> changed for all version docs pull request #2568

- website/src/pages/index.js
The `WelcomeScreen` returns nothing.
Use '(' instead of '{' or add "return (" and ")" seems better.
> docs: fix inaccurate example

- docs/hermes.md
- website/versioned_docs/version-0.64/hermes.md
> Add notes about enabling Hermes for iOS

- docs/animated.md
- website/versioned_docs/version-0.63/animated.md
- website/versioned_docs/version-0.64/animated.md
this PR fix space between two buttons,  i think looks better than older example.
> fix Animated example with space buttons

- website/src/css/customTheme.scss
Text is more accessible (correct contrast ratio - [WCAG](https://www.w3.org/TR/WCAG21/#contrast-minimum))
> Accessibility improvement

- docs/text.md
- website/versioned_docs/version-0.64/text.md
That issue was closed, so I believe that it is ideal to remove this mention
> Remove mention of a closed issue in the documentation

- docs/intro-react.md
> String Change

- website/blog/2021-05-20-GAAD-One-Year-Later.md
Hot fix to correct the handle of a contributor being highlighted.
> GAAD Article Hot-fix

- docs/sectionlist.md
- website/versioned_docs/version-0.64/sectionlist.md
Missed `const` for Class Component example
> Docs: Update sectionlist.md

- docs/_getting-started-macos-android.md
just the information to install via sdkmanager command
thanks
> about installation using the sdkmanager command

- website/src/css/customTheme.scss
this PR fix style text in hamburger menu for different devices.
Before:
After:
@Simek i test for different iphone sizes and android and looks better!:
> fix text in hamburger menu for mobile devices

- docs/intro-react.md
> Removed "TextInput" from the imports as it was never used.

- docs/systrace.md
- website/versioned_docs/version-0.64/systrace.md
this PR fix style between two buttons looks better right now!. :)
Before:
After:
> docs: fix style buttons in Systrace API

- website/showcase.json
Add Mercari's new blog to the showcase: https://medium.com/mercari-engineering/why-we-decided-to-rewrite-our-ios-android-apps-from-scratch-in-react-native-9f1737558299
-----
Build locally:
`cd react-native-website`
`yarn`
`cd website`
`yarn start`
open http://localhost:3000/
> Add Mercari's blog to the showcase

- docs/native-modules-ios.md
- website/versioned_docs/version-0.64/native-modules-ios.md
> Fix typo: NativeNodules -> NativeModules

- docs/_integration-with-exisiting-apps-java.md
- docs/_integration-with-exisiting-apps-objc.md
- docs/_integration-with-exisiting-apps-swift.md
- website/versioned_docs/version-0.64/_integration-with-exisiting-apps-java.md
- website/versioned_docs/version-0.64/_integration-with-exisiting-apps-objc.md
- website/versioned_docs/version-0.64/_integration-with-exisiting-apps-swift.md
this PR update examples with functional component!.
> docs: update examples  _integration-with-exisiting-apps

- docs/intro-react.md
- website/versioned_docs/version-0.64/intro-react.md
> spelling mistake in line 256 intro-react.md

- docs/network.md
- website/versioned_docs/version-0.64/network.md
this PR update network examples, i think looks better refactor with async await!.
> website: update networking examples 

- docs/touchablehighlight.md
- docs/touchablenativefeedback.md
- docs/touchableopacity.md
- docs/touchablewithoutfeedback.md
- docs/view.md
this PR adds required labels in different components!.
cc: @Simek
> website: add bunch required labels in different components

- docs/scrollview.md
Adds the new prop `automaticallyAdjustsScrollIndicatorInsets` to the docs for `ScrollView`.
Prop added here: https://github.com/facebook/react-native/pull/29809
> Update scrollview.md adding new prop automaticallyAdjustsScrollIndicatorInsets

- docs/accessibility.md
Support for this role was added in https://github.com/facebook/react-native/commit/da899c0cc4372830e5ca053a096b74fff2a19cb8
> Add "togglebutton" accessibilityRole

- docs/modal.md
Documentation update for PR - https://github.com/facebook/react-native/pull/31500
> update onRequestClose for IOS modal

- docs/security.md
- website/versioned_docs/version-0.62/security.md
- website/versioned_docs/version-0.63/security.md
- website/versioned_docs/version-0.64/security.md
- website/versioned_docs/version-0.65/security.md
Updates the link for `async-storage`.
> Update async-storage github link

- docs/pressable.md
This PR adds documentation for **unreleased** but **merged** foreground prop in Pressable https://github.com/facebook/react-native/pull/31632
> add foreground prop in pressable ripple config

- website/versioned_docs/version-0.65/text.md
> fix warning: functions are not valid as ReactChild

- website/blog/2021-08-19-h2-2021.md
Add React Native in H2 2021 post
> Add React Native in H2 2021 post

- website/blog/2021-08-19-h2-2021.md
> Add ignore to name

- website/blog/2021-08-19-h2-2021.md
- website/blog/2021-08-26-many-platform-vision/index.md
- website/blog/2021-08-30-react-native-is-hiring-managers.md
- website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
Adds truncation to recent blog posts, to help clean up the blog index page.
> Add truncation to recent blog posts

- docs/signed-apk-android.md
This bit of clarifying text would have saved me some time as I tried to figure out where to put the variables so that they wouldn't be checked into my repository.
> Add a note about where to place the Gradle vars

- docs/animations.md
**Background**
i want to add animation to my project, and start jump into the animation section on the docs.
And i tried to understand the code example, and i found that there was some undefined style object.
> docs: remove unused style object

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.66/_getting-started-linux-android.md
- website/versioned_docs/version-0.66/_getting-started-macos-android.md
- website/versioned_docs/version-0.66/_getting-started-macos-ios.md
- website/versioned_docs/version-0.66/_getting-started-windows-android.md
this PR fix redirect troubleshooting page, when you click this link redirect for the last section!.
> docs: update getting started troubleshooting link 

- website/versioned_docs/version-0.66/linking.md
this PR fix close tag in linking docs!.
> docs: fix tag in linking docs

- docs/intro-react.md
The state property in the example is "isHungry" :)
> Fix tiny error from state informational blockquote

- docs/signed-apk-android.md
> Fix reference to anchored link

- docs/roottag.md
> Update CHANGELOG link

- website/package.json
- yarn.lock
This PR bumps the Docusuaurs to the latest release, which according to the entries in the changelog and comments in the few reported issues, should improve the code related to the tabs issues and should reduce the unwanted scrolling to the top:
* Fixes #2771
* https://github.com/facebook/react-native-website/issues/2771#issuecomment-937669558 
* Fixes #2807 
* https://github.com/facebook/react-native-website/issues/2807#issuecomment-952882417
If any of the issues still occurs after deployment of this PR, please re-open old or create new issues.
CC: @slorber
> bump Docusaurus and other website depenedencies

- docs/publishing-to-app-store.md
- website/versioned_docs/version-0.60/publishing-to-app-store.md
- website/versioned_docs/version-0.61/publishing-to-app-store.md
- website/versioned_docs/version-0.62/publishing-to-app-store.md
- website/versioned_docs/version-0.63/publishing-to-app-store.md
- website/versioned_docs/version-0.64/publishing-to-app-store.md
- website/versioned_docs/version-0.65/publishing-to-app-store.md
- website/versioned_docs/version-0.66/publishing-to-app-store.md
- yarn.lock
I removed the not found link in https://reactnative.dev/docs/publishing-to-app-store
> Removed the empty link

- docs/alert.md
> Fix typo in alert.md

- docs/statusbar.md
Provide a brief description of what a "status bar" is.  To address #2870.
> Fix for #2870 - description of status bar.

- docs/safeareaview.md
- website/versioned_docs/version-0.66/safeareaview.md
this PR update SafeAreaView docs!.
> docs: update SafeAreaView 

- docs/threading-model.md
Changes to the `threading-model` for the fabric deep dive docs
> threading-model formatting

- docs/images.md
Test on iOS 14.5:
Image component support that four border radius properties now.
> update word from currently to may

- docs/fabric-renderer.md
- website/versioned_docs/version-0.66/fabric-renderer.md
> Typofix in fabric-renderer.md file

- docs/fabric-renderer.md
- docs/glossary.md
- website/versioned_docs/version-0.66/fabric-renderer.md
- website/versioned_docs/version-0.66/glossary.md
This PR includes small typo fixes in the Architecture section.
> Architecture section minor fixes

- docs/signed-apk-android.md
Updated the release bundle aab file name
> Update release aab file

- docs/native-modules-android.md
Fixed folder path inside code block
> docs: unwanted text in code block

- docs/tutorial.md
Current name `React-Native-specific` seems like a React Native library as that is the library naming convection, recommended to remove hyphen from the name to React-Native specific
> update name in tutorial.md

- docs/running-on-device.md
this PR updates doc file "running-on-device.md" , removing text and fix this issue #2941,
> remove text on docs running-on-device

- docs/layout-props.md
This PR was not complete: https://github.com/facebook/react-native-website/pull/2451/files
> Fix flexShrink default value in Layout Props docs

- website/docusaurus.config.js
- website/src/css/customTheme.scss
- website/src/css/index.scss
- website/src/pages/index.js
Summary
Following a suggestion in https://github.com/facebook/react-native-website/pull/2986, moving to use an announcement bar:
> docs: Moving to use Announcement Banner for the Support Ukraine Initiative

- docs/running-on-simulator-ios.md
- website/versioned_docs/version-0.66/running-on-simulator-ios.md
this PR update iOS simulators according this PR https://github.com/react-native-community/cli/pull/1478
> docs: update iOS runnning on simulator

- docs/actionsheetios.md
This PR adds the `dismissActionSheet` method documentation. Follow-up of https://github.com/facebook/react-native/pull/33189
> feat: Add dismissActionSheet method documentation

- website/blog/2022-03-30-version-068.md
Opting in into -> Opting in to
> Improve wording of new architecture header title

- website/versioned_docs/version-0.68/running-on-simulator-ios.md
@Simek  i forgot update specially 0.68 version.
> docs: update running ios simulators 0.68 version

- docs/the-new-architecture/backward-compatibility.md
This PR introduces the topic of backward compatibility in the new architecture refactoring and adds some pointers to relevant sections within the guide.
> [Guide - The New Architecture] What Backward Compatibility Is

- docs/hermes.md
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.66/hermes.md
- website/versioned_docs/version-0.67/hermes.md
- website/versioned_docs/version-0.68/hermes.md
#3066 
This PR fixes text readability issues in the [Hermes setup guide](https://reactnative.dev/docs/hermes) on devices with smaller screen size.
> :children_crossing: improve hermes logo alignment on mobile devices

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/getting-started.md
- website/versioned_docs/version-0.68/_getting-started-linux-android.md
- website/versioned_docs/version-0.68/_getting-started-macos-android.md
- website/versioned_docs/version-0.68/_getting-started-macos-ios.md
- website/versioned_docs/version-0.68/_getting-started-windows-android.md
- website/versioned_docs/version-0.68/getting-started.md
fix for: https://github.com/facebook/react-native-website/issues/3053
> Update setup guide node version

- docs/the-new-architecture/why.md
This section provides the basic context to understand the Old Architecture limitations and how it has been possible to overcome them with the New Architecture.
It points to the Architecture tab for further information.
> [Guide - The New Architecture] Why A New Architecture

- docs/native-components-android.md
> Fixing issue #3082 for missing import in native-components-android

- docs/introduction.md
- website/versioned_docs/version-0.60/introduction.md
- website/versioned_docs/version-0.61/introduction.md
- website/versioned_docs/version-0.62/introduction.md
- website/versioned_docs/version-0.63/introduction.md
- website/versioned_docs/version-0.64/introduction.md
- website/versioned_docs/version-0.65/introduction.md
- website/versioned_docs/version-0.66/introduction.md
- website/versioned_docs/version-0.67/introduction.md
The whitespace for the style attribute seems to have been formatted incorrectly. 
Fix it so that it is more easier to understand at first glance
The introduction.md files in docs, versiond_docs are updated.
> Fix imporperly formatted code in introduction

- docs/publishing-to-app-store.md
Added all the necessary steps needed to publish the iOS app to App store.
Resolve issue #3075
> docs: add to Build app for Release.

- docs/_getting-started-macos-ios.md
> Clarify usage of Ruby version managers

- website/blog/2022-05-19-GAAD-2022-update.md
Publishing this blogpost on behalf of @alextait1
As always, feedbacks are more than welcome 👍
> Blogpost: React Native Accessibility - GAAD 2022 Update

- docs/_getting-started-macos-android.md
Fixes https://github.com/facebook/react-native-website/pull/3128#discussion_r878680520
Apply one of the suggested corrections. 🙂
> Getting Started: fix typo

- docs/scrollview.md
- website/versioned_docs/version-0.68/scrollview.md
New props landed [here](https://github.com/facebook/react-native/commit/49a1460a379e3a71358fb38888477ce6ea17e81a)
---
Sync with others repo
- https://github.com/facebook/react-native/pull/33948
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60618
> docs: add automaticallyAdjustKeyboardInsets to scrollview props

- website/contributing/release-candidate-minor.md
- website/contributing/release-candidate-patch.md
- website/contributing/release-stable-minor.md
- website/contributing/release-stable-patch.md
As we have discussed internally, we want to add a step for going through the testing steps to increase our confidence when doing a release.
> Add steps for release testing

- docs/hermes.md
- website/architecture/bundled-hermes.md
This is a follow-up to [this](https://github.com/facebook/react-native-website/pull/3159) PR adding docs explaining the bundled hermes. There were a couple of small typos, mistakes I have noticed when reading through it.
> Fix typos for the bundled hermes docs

- docs/_integration-with-existing-apps-kotlin.md
- docs/integration-with-existing-apps.md
Add Kotlin example to integration with existing apps. Created in docs/_integration-with-exisiting-apps-kotli
> Add Kotlin to docs/_integration-with-exisiting-apps-java

- website/blog/2022-06-21-version-069.md
- website/blog/authors.yml
This PR adds a blogpost to be posted once 0.69 is released. It currently depends on [this](https://github.com/facebook/react-native-website/pull/3163) PR as we link to it from this blogpost.
> Blog post for 0.69 RN release

- docs/layoutanimation.md
In the given example, an error is thrown as spring damping
> fix: spring damping error in example

- website/blog/2022-06-21-version-069.md
Fixes #3179 
This PR fixes the broken internal link in latest blogpost reported by @DemonDaddy22.
> correct link in 0.69 blogpost

- website/contributing/release-candidate-minor.md
- website/contributing/release-stable-minor.md
- website/contributing/release-stable-patch.md
When doing the release of `0.69.0`, we have noticed the guide for releasing a stable minor had a few inconsistencies.
> Update release steps

- docs/intro-react-native-components.md
- website/versioned_docs/version-0.69/intro-react-native-components.md
> Just removed a typing mistake.

- website/sidebars.json
- website/versioned_sidebars/version-0.65-sidebars.json
- website/versioned_sidebars/version-0.66-sidebars.json
- website/versioned_sidebars/version-0.67-sidebars.json
- website/versioned_sidebars/version-0.68-sidebars.json
- website/versioned_sidebars/version-0.69-sidebars.json
> add communication-android link to Android Guides

- website/architecture/architecture-overview.md
> docs: add build tools to Table of Contents

- docs/new-architecture-library-ios.md
> docs: fix package location

- website/versioned_docs/version-0.70/the-new-architecture/pillars-codegen.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
Small follow up to https://github.com/facebook/react-native-website/pull/3304
I forgot to update a couple of files for 0.70. I'm doing it here.
> Follow-up on CMake clarification for 0.70

- docs/_getting-started-macos-ios.md
- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
This PR applies the comments left by @thymikee in #3323.
It also adds a couple of fixes in some other pages that were broken.
> [Fix]Improve wording for iOS getting started

- docs/layout-props.md
> clean warning

- website/showcase.json
> Update showcase link for Artsy

- CODE_OF_CONDUCT.md
Updates the `CODE_OF_CONDUCT.md` to reflect the recommendation for Meta Open Source projects, which is the [Contributor Covenant](https://www.contributor-covenant.org).
> Update to Contributor Covenant

- website/community/communities.md
> fix: duplicate header

- website/src/theme/BlogSidebar/Desktop/index.d.ts
- website/src/theme/BlogSidebar/Mobile/index.d.ts
> Fix headers on *.ts files

- docs/new-architecture-app-intro.md
Corresponding doc update given this change:
https://github.com/facebook/react-native/pull/34843/files
> New Architecture - Remove the extra steps required to copy .so files

- docs/new-architecture-app-intro.md
> Fix typo in New Architecture Intro

- website/versioned_docs/version-0.70/hermes.md
Followup to https://github.com/facebook/react-native-website/pull/3376
The Hermes docs added in PR #3376 apply to Version 0.70, so with this we make sure that version of the docs also includes these instructions.
The changes in this PR should be identical to those from #3376, with the exception that they are being made on the 0.70 version of hermes.md.
> Upstream hermes.md to version 0.70 of the docs

- docs/view-style-props.md
Relates to this PR: https://github.com/facebook/react-native/pull/33783
> Added borderCurve prop to view-style-props.md

- docs/state.md
- website/versioned_docs/version-0.60/state.md
- website/versioned_docs/version-0.61/state.md
- website/versioned_docs/version-0.62/state.md
- website/versioned_docs/version-0.63/state.md
- website/versioned_docs/version-0.64/state.md
- website/versioned_docs/version-0.65/state.md
- website/versioned_docs/version-0.66/state.md
- website/versioned_docs/version-0.67/state.md
- website/versioned_docs/version-0.68/state.md
- website/versioned_docs/version-0.69/state.md
- website/versioned_docs/version-0.70/state.md
Superseeds #3112
Reformat and update the example on the latest State page and versioned ones.
> State: reformat example

- docs/debugging.md
Fix bug "no matches found: *:S"
> Fix adb logcat command

- docs/new-architecture-app-intro.md
> chore: fix typo

- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
> Fix documentation for Turbo Native Modules on 0.70

- docs/button.md
Fix this sentence with more up to date guidance.
> Recommend Pressable over Touchable for alternative to Button

- docs/typescript.md
Fix link in TypeScript docs. 
Verified fix running locally
> Fix React Native CLI link

- website/contributing/release-troubleshooting.md
This PR adds some instruction to handle a failed release.
> feat: add instructions in case the release fails

- website/contributing/changelogs-in-pull-requests.md
See here for how it is used in code https://github.com/microsoft/rnx-kit/blob/a9fd54dedc8fb84898778bca8256b43fea670942/incubator/rn-changelog-generator/src/utils/getChangeDimensions.ts#L4
> Add [Breaking] to commit changelog documentation

- website/contributing/changelogs-in-pull-requests.md
PR companion of https://github.com/facebook/react-native/pull/35541 about valid changelog entries. This aligns with the source of truth, which is the changelog generator, in particular here: https://github.com/microsoft/rnx-kit/blob/main/incubator/rn-changelog-generator/src/utils/getChangeDimensions.ts
> fix changelog entries

- docs/more-resources.md
> Update ignite blurb on more resources

- docs/hermes.md
Another update for .71 on how Hermes is enabled/disabled on Android
> [0.71] Update page on Enabling Hermes for 71

- website/blog/authors.yml
This adds myself as a blog post author in preparation of a blog post coming next week.
> Add Vincent Riemer as a blog post author

- website/blog/2022-12-13-pointer-events-in-react-native.md
This is a small tweak to our post's intro to make it a bit clearer as to the rest of the content of the post.
> Refine the "Pointer Events in React Native" blog post's intro

- docs/the-new-architecture/cxx-custom-types.md
- docs/the-new-architecture/cxx-cxxturbomodules.md
- website/sidebars.json
A comprehensive guide to C++ Turbo Native Modules
> Add Cxx TurboModule Guide

- website/community/staying-updated.md
The link to the blog in line 10 redirects incorrectly as it redirects into the /community path when it is outside the /community path.
https://user-images.githubusercontent.com/4989177/207844009-de49be2b-3775-4763-84cd-fa33a4520a78.mp4
> Update community staying-updated.md

- docs/accessibilityinfo.md
This slipped by. Updating the examples here for TS.
> Update AccessibilityInfo Inline JSX to TSX

- docs/permissionsandroid.md
https://github.com/facebook/react-native/pull/35533
> Rename `POST_NOTIFICATION` to `POST_NOTIFICATIONS`

- docs/handling-touches.md
> Fixed typo.

- docs/animated.md
> Fix typo in animated.md

- website/contributing/release-stable-minor.md
Update the guide to release a stable minor with the recent changes.
> Feat: Update releasing a minor

- docs/platform-specific-code.md
> Grammar/typo fix: Add hyphen to title

- website/versioned_docs/version-0.71/signed-apk-android.md
Based on
- https://github.com/facebook/react-native-website/pull/3522
0.71 update
> Replace deprecated --variant with --mode in 0.71 docs version

- docs/integration-with-android-fragment.md
- website/versioned_docs/version-0.71/integration-with-android-fragment.md
> Clarify docs around DefaultReactNativeHost

- website/blog/2023-01-03-typescript-first.md
Remove notes about 0.71 being in pre-release now that 0.71 has been released
> Remove references to pre-release of 71

- docs/text.md
- website/versioned_docs/version-0.71/text.md
Documentation for this PR: https://github.com/facebook/react-native/pull/35017
> Add `dynamicTypeRamp` documentation

- docs/native-modules-android.md
- website/versioned_docs/version-0.68/native-modules-android.md
- website/versioned_docs/version-0.69/native-modules-android.md
- website/versioned_docs/version-0.70/native-modules-android.md
- website/versioned_docs/version-0.71/native-modules-android.md
> change the use of incorrect word

- docs/new-architecture-app-intro.md
- website/versioned_docs/version-0.71/new-architecture-app-intro.md
> typo in new arch intro docs

- docs/the-new-architecture/pillars.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars.md
> Fix Info block

- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
8ce663968d9.png">
After TM:After TM:Before:Before:
> Add language alternatives to TM&Fabric guides

- website/react-native-dict.json
- website/versioned_docs/version-0.60/navigation.md
- website/versioned_docs/version-0.61/navigation.md
- website/versioned_docs/version-0.62/navigation.md
- website/versioned_docs/version-0.63/navigation.md
- website/versioned_docs/version-0.64/navigation.md
- website/versioned_docs/version-0.65/navigation.md
- website/versioned_docs/version-0.66/navigation.md
- website/versioned_docs/version-0.67/navigation.md
- website/versioned_docs/version-0.68/_markdown-m1-cocoapods.mdx
- website/versioned_docs/version-0.68/navigation.md
- website/versioned_docs/version-0.69/_markdown-m1-cocoapods.mdx
- website/versioned_docs/version-0.69/navigation.md
- website/versioned_docs/version-0.70/_getting-started-macos-ios.md
- website/versioned_docs/version-0.70/_markdown-m1-cocoapods.mdx
- website/versioned_docs/version-0.70/navigation.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/navigation.md
- website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Also added it to antfu/case-police#148 so our tooling will fix this in the future.
> fix: Cocoapods -> CocoaPods

- docs/button.md
> Fix: Broken Link

- docs/flatlist.md
A small change to update the ViewabilityHelper's link to its current location.
> fix: update ViewabilityHelper.js link

- docs/imagebackground.md
> fix: imageUrl in imageBackGround page

- docs/interactionmanager.md
> Wrap scheduling alternatives in `code`

- docs/improvingux.md
The current url https://developer.apple.com/design/human-interface-guidelines/ios/overview/design-principles/ is outdated
> Updated apple's human-interface-guidelines

- docs/testing-overview.md
Including [Maestro](https://maestro.mobile.dev/) at the docs...
> Adding Maestro as a suggestion of E2E test section

- docs/_getting-started-macos-android.md
- website/versioned_docs/version-0.68/_getting-started-macos-android.md
- website/versioned_docs/version-0.69/_getting-started-macos-android.md
- website/versioned_docs/version-0.70/_getting-started-macos-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-android.md
Add more detail to macOS steps for installing JDK.
> Add more detail on how to set up jdk

- docs/sourcemaps.md
The language was a little ungrammatical/unclear, so I updated a few words
> Update sourcemaps.md with minor grammar and wording changes

- docs/hermes.md
- website/versioned_docs/version-0.71/hermes.md
fix wrong folder to gradle.properties
> docs: Update hermes.md gradle.properties folder

- docs/react-native-gradle-plugin.md
> Update react-native-gradle-plugin.md docs

- docs/new-architecture-app-intro.md
- docs/new-architecture-appendix.md
- docs/new-architecture-library-intro.md
- docs/new-architecture-troubleshooting.md
This PR updates the New Architecture playbook with the changes discussed in 0.72
> [RN][New Architecture] Update Playbook with 0.72 changes

- docs/_getting-started-macos-ios.md
- plugins/remark-lint-no-dead-urls/package.json
- website/package.json
- yarn.lock
Resolves [Dependabot alerts / #26](facebook/react-native-website/security/dependabot/26).
> Upgrade got dependency

- docs/text.md
- docs/view.md
- website/versioned_docs/version-0.65/text.md
- website/versioned_docs/version-0.65/view.md
- website/versioned_docs/version-0.66/text.md
- website/versioned_docs/version-0.66/view.md
- website/versioned_docs/version-0.67/text.md
- website/versioned_docs/version-0.67/view.md
- website/versioned_docs/version-0.68/text.md
- website/versioned_docs/version-0.68/view.md
- website/versioned_docs/version-0.69/text.md
- website/versioned_docs/version-0.69/view.md
- website/versioned_docs/version-0.70/text.md
- website/versioned_docs/version-0.70/view.md
- website/versioned_docs/version-0.71/text.md
- website/versioned_docs/version-0.71/view.md
- website/versioned_docs/version-0.72/text.md
- website/versioned_docs/version-0.72/view.md
Update the docs to reflect the documentation changes in https://github.com/facebook/react-native/pull/38195
> Fix docs for onResponderGrant

- docs/_integration-with-existing-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.72/_integration-with-existing-apps-java.md
- website/versioned_docs/version-0.72/_integration-with-existing-apps-kotlin.md
https://github.com/facebook/react-native/commit/6f11b10a88235ad7de1a5777e5cdf7a582a231b7
> react-native-gradle-plugin renamed to @react-native/gradle-plugin

- website/architecture/architecture-glossary.md
> Fix typo in architecture-glossary.md

- docs/native-components-ios.md
> docs: change js to tsx

- docs/handling-text-input.md
> update: use new react.dev docs link

- docs/upgrading.md
Added second package manager to make docs better :D
Before: 
After:
https://github.com/facebook/react-native-website/assets/63900941/2208c4cb-e340-41c9-a0c6-22274ebf660e
> Add second package manager in "Upgrade dependencies" section.

- website/architecture/bundled-hermes.md
> [bundled-hermes.md] Fix broken link

- website/contributing/release-testing.md
- Fix pre-release test cases table formatting (code block cell widths).
- Group deprecated features at end of table.
> Fix formatting (followup to #3858)

- plugins/remark-snackplayer/package.json
- plugins/remark-snackplayer/src/index.js
- plugins/remark-snackplayer/tests/index.js
- plugins/remark-snackplayer/tests/output/output1.html
- plugins/remark-snackplayer/tests/output/output2.html
- website/modules/snackPlayerInitializer.js
- website/src/css/customTheme.scss
- yarn.lock
Fixes #3751
Refs #3753
This is the continuation of work started in the mentioned PR. Besides the height change, I have also disabled the device frames to spare some vertical space. 
The preview presentation in that mode is a bit off (device is not centered in the preview pane), but I will address that on the Snack side soon.
> adjust SnackPlayer height and presentation

- package.json
- yarn.lock
Add a resolution to address GitHub Security Alert until updating Docusaurus to get a fix.
> Add resolution for axios

- docs/more-resources.md
> Fixed grammatical error in More Resources documentatioj

- docs/pressable.md
- website/versioned_docs/version-0.70/pressable.md
- website/versioned_docs/version-0.71/pressable.md
- website/versioned_docs/version-0.72/pressable.md
> add correct type of Pressable style prop

- docs/publishing-to-app-store.md
Need this as well when publishing to App Store.
> Add App Store screenshot requirements

- docs/images.md
> Fix some typos in the docs

- website/react-native-dict.json
- website/versioned_docs/version-0.70/images.md
- website/versioned_docs/version-0.71/images.md
- website/versioned_docs/version-0.72/accessibility.md
- website/versioned_docs/version-0.72/images.md
- website/versioned_docs/version-0.72/view-style-props.md
- website/versioned_docs/version-0.73/accessibility.md
- website/versioned_docs/version-0.73/images.md
- website/versioned_docs/version-0.73/statusbar.md
- website/versioned_docs/version-0.73/view-style-props.md
Backport few of the latest landed OSS PRs, which were blocked on/missing the versioned changes.
Update the versioned files, in case of API/Components changes, verify the correct version.
> backport few of latest landed OSS PRs to versioned docs

- docs/_getting-started-macos-ios.md
https://github.com/facebook/react-native/issues/42260#issuecomment-1890043712
> Update required Xcode version to 14.1

- website/blog/2022-07-08-hermes-as-the-default.md
> Fix bad link in 2022-07-08-hermes-as-the-default.md

- website/contributing/how-to-run-and-write-tests.md
Updating some of the instructions for Android testing as they were stale
> Update testing instructions for Android

- docs/the-new-architecture/why.md
Adds missing word in the new architecture docs
> Add missing "object"

- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-stable-patch.md
- Small tweaks to commands.
- Add guidance on using a GitHub access token.
> Update release instructions for changelog generator

- docs/_integration-with-existing-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
- docs/_integration-with-existing-apps-objc.md
- docs/_integration-with-existing-apps-swift.md
- website/versioned_docs/version-0.73/_integration-with-existing-apps-java.md
- website/versioned_docs/version-0.73/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.73/_integration-with-existing-apps-objc.md
- website/versioned_docs/version-0.73/_integration-with-existing-apps-swift.md
Fixes: https://github.com/facebook/react-native-website/issues/4006
> update integration with existing apps docs

- docs/react-18-and-react-native.md
> Clarify React18 concurrent root and remove opt-out for 0.74

- docs/native-components-android.md
- website/versioned_docs/version-0.70/native-components-android.md
- website/versioned_docs/version-0.71/native-components-android.md
- website/versioned_docs/version-0.72/native-components-android.md
- website/versioned_docs/version-0.73/native-components-android.md
Hi
Added missing import to https://reactnative.dev/docs/native-components-android?android-language=java#3-create-the-viewmanager-subclass
> [android][native-components-android.md] fix missing import

- docs/pushnotificationios.md
Accounting for deprecations and API changes in PushNotificationIOS for 0.74
https://deploy-preview-4012--react-native.netlify.app/docs/next/pushnotificationios
> Update PushNotificationIOS docs for 0.74

- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.70/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.72/_getting-started-macos-ios.md
- website/versioned_docs/version-0.73/_getting-started-macos-ios.md
We want to recommend using latest Xcode whenever possible
> Update Xcode recommendation to use latest

- website/blog/authors.yml
Adding folks from release crew in prep for 0.74
> Add alan, alfonso for authors for 0.74 post

- docs/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.71/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.72/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.73/the-new-architecture/landing-page.md
> Add info block about moved docs for New Architecture

- docs/intro-react.md
> Cats should not drink dairy milk

- website/community/overview.md
RN has had over 2mm weekly downloads for the past month: https://npmtrends.com/react-native
> Bump weekly downloads to 2 million

- docs/optimizing-javascript-loading.md
- website/versioned_docs/version-0.70/ram-bundles-inline-requires.md
- website/versioned_docs/version-0.71/ram-bundles-inline-requires.md
- website/versioned_docs/version-0.72/ram-bundles-inline-requires.md
- website/versioned_docs/version-0.73/ram-bundles-inline-requires.md
Remove this.state which seems to be left over from a class component code snippet, in favour of functional component
> Update optimizing-javascript-loading.md to remove class syntax

- docs/state.md
- website/versioned_docs/version-0.72/state.md
- website/versioned_docs/version-0.73/state.md
Changed old react.org website link to new react.dev website
> Update state.md to new react website

- website/versioned_docs/version-0.74/profile-hermes.md
This is a broken link preventing the website from building
> Fix broken link on website

- website/blog/2024-04-22-release-0.74.md
Follow-ups to the 0.74 announcement blog post.
> [blog] Update 0.74 post with info on Flipper removal, extended attribution

- website/blog/2024-04-22-release-0.74.md
- website/versioned_docs/version-0.74/_getting-started-linux-android.md
- website/versioned_docs/version-0.74/_getting-started-macos-android.md
- website/versioned_docs/version-0.74/_getting-started-macos-ios.md
- website/versioned_docs/version-0.74/_getting-started-windows-android.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-objc.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-swift.md
- website/versioned_docs/version-0.74/flexbox.md
- website/versioned_docs/version-0.74/interactionmanager.md
- website/versioned_docs/version-0.74/intro-react.md
- website/versioned_docs/version-0.74/javascript-environment.md
- website/versioned_docs/version-0.74/layout-props.md
- website/versioned_docs/version-0.74/native-components-android.md
- website/versioned_docs/version-0.74/native-modules-android.md
- website/versioned_docs/version-0.74/native-modules-ios.md
- website/versioned_docs/version-0.74/optimizing-javascript-loading.md
- website/versioned_docs/version-0.74/platform-specific-code.md
- website/versioned_docs/version-0.74/platform.md
- website/versioned_docs/version-0.74/pushnotificationios.md
- website/versioned_docs/version-0.74/security.md
- website/versioned_docs/version-0.74/shadow-props.md
- website/versioned_docs/version-0.74/state.md
- website/versioned_docs/version-0.74/text-style-props.md
- website/versioned_docs/version-0.74/text.md
- website/versioned_docs/version-0.74/view-style-props.md
- website/versioned_docs/version-0.74/virtualizedlist.md
Resolves #4094.
Steps ran:
- Reverted #4087 locally.
- `yarn version:cut 0.74`
> [docs] Update 0.74 versioned docs

- docs/platform-specific-code.md
- website/versioned_docs/version-0.74/platform-specific-code.md
This PR enhances the platform specific page with tags and hover tooltips on the tags.
This PR is partial completion of #3047
> feat: add iOS, Android tags into platform-specific

- docs/upgrading.md
- website/versioned_docs/version-0.74/upgrading.md
> Remove mention of deprecated Expo upgrade command

- website/docusaurus.config.js
This brings reactnative.dev aligned to react.dev
> Update ReactConf Banner

- docs/headless-js-android.md
- website/versioned_docs/version-0.74/headless-js-android.md
> Use startForegroundService instead startService

- website/versioned_docs/version-0.74/_getting-started-linux-android.md
- website/versioned_docs/version-0.74/_getting-started-macos-android.md
- website/versioned_docs/version-0.74/_getting-started-macos-ios.md
- website/versioned_docs/version-0.74/_getting-started-windows-android.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-java.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-objc.md
- website/versioned_docs/version-0.74/_integration-with-existing-apps-swift.md
- website/versioned_docs/version-0.74/get-started-without-a-framework.md
- website/versioned_docs/version-0.74/getting-started.md
- website/versioned_docs/version-0.74/introduction.md
- website/versioned_docs/version-0.74/set-up-your-environment.md
- website/versioned_docs/version-0.74/typescript.md
- website/versioned_sidebars/version-0.74-sidebars.json
> Backport "Adds getting started docs with React Native Frameworks" to 0.74

- website/src/css/index.scss
- website/src/pages/Home/Hero/FloorBackground.js
- website/src/pages/Home/components/SectionTitle/styles.module.css
Address small issues with new Home page:
* invalid props used in `FloorBackground` component
* set minimal height to the social links container to avoid layout shift on load
* extend the SectionTile max width slightly to better align the sentences
CC @jonsamp  
https://github.com/facebook/react-native-website/assets/719641/a27fba96-e931-446c-8fc4-9a443e90d0ab
> address small issues with new Home page

- website/community/staying-updated.md
> react conference 2024 is added

- website/src/pages/Home/Hero/styles.module.css
I spotted a horizontal scrollbar on the homepage. Took care of it with a quick CSS fix (100vw to 100%)! Homepage should fit your screen perfectly now for a smoother browsing experience.
> Remove Horizontal Scroll

- website/docusaurus.config.js
React Conf has sadly ended. Time to revert #4066
> Revert React Conf 2024 banner

- docs/_getting-started-macos-android.md
- website/versioned_docs/version-0.74/_getting-started-macos-android.md
> Add java_home env var for macos

- website/blog/2024-06-25-use-a-framework-to-build-react-native-apps.md
Drafting a new blogpost. I'd like a pass before we can merge this
> [Blogpost] Use a framework to build React Native apps

- docs/_integration-with-existing-apps-swift.md
Fixes https://github.com/facebook/react-native-website/issues/4170
> Fix 404 on _integration-with-existing-apps-swift.md

- website/blog/authors.yml
@blakef @gabrieldonadel @siddharthkul
Please verify that your details are correct 👍
> Adding more authors to the website

- website/blog/2024-08-12-release-0.75.md
cc @gabrieldonadel @brentvatne
> Add reference on how to use Expo SDK 51 w/ 0.75

- website/docusaurus.config.js
> Add re-watch banner for React Conf Keynote 2024

- website/blog/authors.yml
> Add several Github social links to authors

- yarn.lock
Bump some lockfile transitive deps to mitigate two CVEs
- https://github.com/facebook/react-native-website/security/dependabot/75
- https://github.com/facebook/react-native-website/security/dependabot/76
> Bump transitive deps: express, serve-static, send

- website/.prettierignore
- website/package.json
- website/src/css/customTheme.scss
Prettier wasn't being run in CI
> Add GitHub prettier check

- website/blog/authors.yml
I'm an IC again :) 
Also, I updated my username 😱
> Update Eli White's role from EM to SWE

- docs/handling-touches.md
> refactor: move examples to functional components

- docs/native-modules-ios.md
I was reading though the docs and noticed an example had an unused import. I removed it :)
> docs: Removes unused import in Native Modules example in native-modules-ios.md

- docs/the-new-architecture/pure-cxx-modules.md
- Fixed found wrong platform context in Android section
> docs: Fixed wrong platform reference

- website/package.json
- yarn.lock
> Remove react-tweet

- website/blog/2024-10-23-the-new-architecture-is-here.md
- website/package.json
- yarn.lock
- **Remove react-tweet**
- **fix: reword avoiding left and right for mobile**
> reword batch transition updates

- docs/the-new-architecture/pure-cxx-modules.md
> Fix typos/grammar in pure-cxx-modules.md

- docs/the-new-architecture/using-codegen.md
Fix WebViewNativeComponent typo
> fix: WebViewNativeComponent typo extension to ts

- website/docusaurus.config.js
Fixes https://github.com/facebook/react-native-website/issues/4318
> Fix broken banner in home page

- docs/the-new-architecture/using-codegen.md
- docs/the-new-architecture/what-is-codegen.md
- website/versioned_docs/version-0.76/the-new-architecture/using-codegen.md
- website/versioned_docs/version-0.76/the-new-architecture/what-is-codegen.md
Corrects a handful of spelling, formatting, and grammatical issues
> Update spelling and formatting for codegen docs

- docs/turbo-native-modules.md
- website/versioned_docs/version-0.76/turbo-native-modules.md
> docs: remove type assertion

- docs/react-native-devtools.md
- website/versioned_docs/version-0.76/debugging.md
- website/versioned_docs/version-0.76/react-native-devtools.md
> docs: change the localhost by the react native hostname.

- website/versioned_docs/version-0.71/accessibility.md
I erroneously added an extra bullet point in the 0.71 docs in front of the listitem entry in PR #4352. This fixes it.
> Remove extra bullet introduced in #4352

- docs/image.md
- website/versioned_docs/version-0.75/image.md
- website/versioned_docs/version-0.76/image.md
modified on RN 0.76.0 version, fresco version is not compatible.
https://github.com/facebook/react-native/issues/47408
https://github.com/facebook/react-native/issues/46095
> doc(image): fix fresco version.

- website/versioned_docs/version-0.76/fabric-native-components-android.md
Hey, 
This PR fixes small typo in the docs
> fix: typo in fabric docs

- docs/the-new-architecture/codegen-cli.md
- website/versioned_docs/version-0.76/the-new-architecture/codegen-cli.md
fixes #4337
preview link - https://deploy-preview-4348--react-native.netlify.app/docs/the-new-architecture/codegen-cli
> fix codegen CLI example commands

- docs/the-new-architecture/codegen-cli.md
- website/versioned_docs/version-0.76/the-new-architecture/codegen-cli.md
New NPM package is https://www.npmjs.com/package/@react-native/codegen
> Fix codegen URL

- docs/fabric-native-components.md
- website/versioned_docs/version-0.76/fabric-native-components.md
Found a few grammar issues to fix
> docs: fix minor grammar

- website/contributing/how-to-open-a-pull-request.md
A small note/addition on how to now easily run react-native (from source) and test changes. With a link to the RNTester readme.
> docs: add how you can run / test changes on a forked react-native through RNTester

- website/blog/authors.yml
> Update X handle for huntie

- docs/fabric-native-components-android.md
- docs/fabric-native-components-ios.md
- website/versioned_docs/version-0.76/fabric-native-components-android.md
- website/versioned_docs/version-0.76/fabric-native-components-ios.md
As the title says, this PR fixes typos in Fabric Native Components Introduction.
> Fix typos in Fabric Native Components Introduction

- docs/fabric-native-components.md
This PR fixes indentation of the Codegen specification in Fabric Native Components Introduction.
> Fix Codegen specification in Fabric Native Components Introduction

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- STYLEGUIDE.md
- plugins/remark-lint-no-dead-urls/README.md
- plugins/remark-snackplayer/README.md
- scripts/lint-examples/README.md
Improved the formatting of the documentation to enhance consistency and clarity throughout the text. Changes include adjustments to headings, link formatting, and list styles.
> Fix some markdown files

- website/docusaurus.config.ts
Refactor the Docusaurus configuration to utilize type assertions for plugin options, enhancing type safety and clarity.
> Update Docusaurus config with type assertions for plugins

- website/src/css/customTheme.scss
Enhance the theme styles to be more consistent with the rest of the website.
before
after
before
after
before
after
> Update border radius styles for consistency improvements

- docs/_integration-with-existing-apps-ios.md
- website/versioned_docs/version-0.76/_integration-with-existing-apps-ios.md
> Fix duplicate imports in Integration with Existing Apps

- docs/_integration-with-existing-apps-ios.md
- docs/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.76/_integration-with-existing-apps-ios.md
- website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
> Add missing syntax highlighting in Integration with Existing Apps

- docs/textinput.md
Related to https://github.com/facebook/react-native/pull/47671.
> Add documentation for disableKeyboardShortcuts prop in TextInput

- docs/linking.md
Fixes typo: period in the middle of a sentence. Further clarifies the paragraph's meaning.
> Fixes typo: period in the middle of a sentence. Further clarifies the paragraph's meaning.

- website/versioned_docs/version-0.76/modal.md
see facebook/react-native#48954
> fix(Modal): remove non-existent prop

- docs/the-new-architecture/create-module-library.md
- website/versioned_docs/version-0.76/the-new-architecture/create-module-library.md
- website/versioned_docs/version-0.77/the-new-architecture/create-module-library.md
florid in English has a different meaning than what we meant to express here.
> [RN] Replace 'florid' with 'rich'

- website/static/.well-known/atproto-did
For atproto verification (e.g. bsky)
> add atproto did

- docs/view-style-props.md
- website/versioned_docs/version-0.77/view-style-props.md
Added documentation for outline props which were released on 0.77
> Add documentation for outline on View Style Props page

- docs/the-new-architecture/codegen-cli.md
- website/versioned_docs/version-0.76/the-new-architecture/codegen-cli.md
- website/versioned_docs/version-0.77/the-new-architecture/codegen-cli.md
Fixes https://github.com/facebook/react-native-website/issues/4460
> Clarify implications of using includesGeneratedCode = true with codegen

- website/blog/authors.yml
Fix inconsistent formatting of authors.
> Fix authors formatting

- docs/react-native-gradle-plugin.md
Add documentation for https://github.com/facebook/react-native/pull/49449/files
> Document `enableBundleCompression`

- .github/workflows/pre-merge.yml
this was disabled when we migrated to yarn berry
> Enable yarn cache in GitHub Actions workflow

- website/community/staying-updated.md
Adds a simple link on Staying up to date community page
> add youtube playlist for Chain React 2024

- website/versioned_docs/version-0.78/_integration-with-existing-apps-kotlin.md
Wrong url was used linking to MainApplication.kt file instead. 
0.76-0.78 versions affected
> Update link to MainActivity.kt file

- website/docusaurus.config.ts
[Preview](https://deploy-preview-4560--react-native.netlify.app/)
> Add React Conf announcement bar

- docs/_integration-with-existing-apps-ios.md
- website/versioned_docs/version-0.78/_integration-with-existing-apps-ios.md
The podfile is changed in version 0.78, so we need to update a couple of lines in the brownfield integration.
> [RN][Doc] Update brownfield to match the new Podfile

- docs/the-new-architecture/advanced-topics-modules.md
- website/sidebars.ts
We want ot add more guides on how to implement advanced functionalities with Native Modules.
This PR is an initial refactor of the entry page for the new guides we want to write
> [RN][NativeModules] Refactor the advanced topic section

- docs/the-new-architecture/advanced-topics-components.md
- docs/the-new-architecture/advanced-topics-modules.md
- website/sidebars.ts
This PR refactors the Advanced Topic section for components to start writing some other guides for components
> [RN][Docs] Refactor the Advanced Topics of the Component

- website/docusaurus.config.ts
Add bluesky link in `FIND US`.
> chore: add bluesky link

- docs/linking.md
The example doesn't works correctly without overriding the application function.
> override in the swift code

- website/sidebars.ts
- website/versioned_docs/version-0.79/targetevent.md
Duplicate of #4619 but I merged that PR into the wrong base branch
> Add targetevent to sidebar

- docs/turbo-native-modules-ios.md
> misc(docs): add missing curly bracket

- docs/scrollview.md
- website/versioned_docs/version-0.77/scrollview.md
- website/versioned_docs/version-0.78/scrollview.md
- website/versioned_docs/version-0.79/scrollview.md
- website/versioned_docs/version-0.80/scrollview.md
- website/versioned_docs/version-0.81/scrollview.md
Supersedes:
* #4134
Correct ScrollView `alwaysBounceVertical` prop default value description. I have also re-checked the code to confirm the result of discussion in this PR.
> ScrollView: update `alwaysBounceVertical` prop description

- website/src/pages/showcase.tsx
• Simplified Shopify's showcase description to reflect current state
• Removed reference to "actively migrating" since all mobile apps now use React Native
> update Shopify showcase description
