docs/geolocation.md, docs/scrollview.md
This fixes #15 
Added Link for the _PermissionAndroid API_
=> Fixes Geolocation View Link Issue

docs/scrollview.md
This one fixes #10
Added proper link o the Flatlist link
=> Fixing the Flatlist link Issue

docs/scrollview.md, docs/sectionlist.md
This fixes #14.
Added Link to the Flatlist
=> Fixes the link on Sectionlist

website/versioned_docs/version-0.5/more-resources.md
Adding a link to Native Directory - a curated list of React Native libraries
=> Added a link

website/versioned_docs/version-0.5/flexbox.md
It should say "width" instead of "height" :)
=> Corrected typo

website/versioned_docs/version-0.50/virtualizedlist.md
=> Fixed FlatList and SectionList links

.circleci/config.yml, website/.prettierrc, website/core/Footer.js, website/core/RemarkablePlugins.js, website/package.json, website/pages/en/versions.js, website/siteConfig.js, website/static/js/codeblocks.js
Format with Prettier and nag on Circle if needed
=> Use Prettier

docs/contributing.md
Fixed link for [this #comment](https://github.com/facebook/react-native-website/pull/26#issuecomment-349417170)
=> Fixed link in Contributing.md for docs folder

docs/native-components-android.md, website/versioned_docs/version-0.5/native-components-android.md
Nit-picking with spacing.
Also applied to versioned docs.
=> Fix spacing in Android Native UI Components

website/versioned_docs/version-0.5/running-on-device.md
Fixes small typo within "Running On Device" page.
=> Fix small typo: rooter -> router

docs/improvingux.md, docs/integration-with-existing-apps.md, docs/running-on-device.md
Went through some old PRs in `facebook/react-native` and applied the changes here:
- https://github.com/facebook/react-native/pull/16551
- https://github.com/facebook/react-native/pull/16580
- https://github.com/facebook/react-native/pull/16667
- https://github.com/facebook/react-native/pull/16757
=> Copy over proposed changes from the old repo

docs/modal.md
Added example to Modal documentation
=> Add example to Modal documentation

docs/webview.md
Related facebook/react-native#17190
=> Document WebView initialScale property

.prettierrc, docs/stylesheet.md, website/package.json
This should help editors pick up the config when formatting files on save.
=> Move Prettier config to the project root

docs/using-a-scrollview.md
=> Fixed a typo on "that" to "than"

website/pages/en/versions.js
=> Fix link to RC release notes

docs/image.md
=> Update broken links.

website/showcase.json
=> fixed f8 showcase link

docs/improvingux.md
=> Fixed typo: challange → challenge

docs/images.md
Use proper location for link, as of latest.
=> Referenced code moved

docs/flatlist.md
=> Correct capitalisation

docs/contributing.md
=> Fix link to beginner friendly issues

docs/network.md
Since ListView is DEPRECATED, source: http://facebook.github.io/react-native/docs/listview.html
#<Issue>
=> Updated the FetchExample component with FlatList

docs/appstate.md, docs/toastandroid.md, website/versioned_docs/version-0.19/appstate.md, website/versioned_docs/version-0.28/appstate.md, website/versioned_docs/version-0.31/toastandroid.md, website/versioned_docs/version-0.42/appstate.md, website/versioned_docs/version-0.46/appstate.md, website/versioned_docs/version-0.49/toastandroid.md, website/versioned_docs/version-0.5/appstate.md, website/versioned_docs/version-0.5/toastandroid.md, website/versioned_docs/version-0.50/toastandroid.md, website/versioned_docs/version-0.53-RC/appstate.md
- AppState for #78
- ToastAndroid for missing properties
=> Update AppState and ToastAndroid docs

docs/cameraroll.md, docs/geolocation.md, docs/image.md, docs/linking.md, docs/modal.md, docs/netinfo.md, docs/permissionsandroid.md, docs/pushnotificationios.md, docs/vibration.md
Goes along with https://github.com/facebook/react-native/pull/17776
=> Cleanup: Update docs

docs/linking.md
Add documentation about the return value of the `canOpenURL` method.
=> Update Linking doc

docs/sectionlist.md
=> Fix typo in sectionlist.md

docs/textinput.md
Improved the docs for clearButtonMode.
https://github.com/facebook/react-native/commit/ebc98840e93c336e8c9e4a93c78e6ca03591f0ec
=> Improved documentation for clearButtonMode.

docs/navigation.md
=> Update broken links

docs/textinput.md
Remove from doc according to commit 
https://github.com/facebook/react-native/commit/dabb78b1278d922e18b2a84059460689da12578b
EDITED: Wrong commit id.
=> Remove autoGrow from TextInput

docs/direct-manipulation.md
Simple URL update to the REACT website
=> intelligently applying `shouldComponentUpdate` link updated

docs/running-on-device.md
=> Updated text to what is actually shown on the device

docs/flexbox.md
Related https://github.com/facebook/react-native-website/pull/120
=> Added `spaceEvenly` value to `Layout with Flexbox`

docs/maintainers.md, website/versioned_docs/version-0.5/maintainers.md
If you need issue management access, please reach out to me! I'll add more details on how to get this access later.
=> Deprecate Facebook-GitHub-Bot

docs/state.md
=> Fix broken link.

website/pages/en/help.js
=> fix components-and-apis link

docs/image.md
=> Add fadeDuration prop

docs/animated.md
Making it a little clearer that you can use vector config options with vector values.
#<Issue>
=> Adding vector config clarification

docs/webview.md
Include @Benmidi's very useful information from this issue: https://github.com/facebook/react-native/issues/915
#915
=> Update renderLoading Prop

docs/integration-with-existing-apps.md
Make the same update as pull https://github.com/facebook/react-native-website/pull/219 but for the swift section.
=> Glog lower case matters (for swift)

docs/contributing.md
=> Fix typo in contributing.md

docs/easing.md
=> Remove broken link from easing.md

docs/native-modules-android.md
I'm not familiar with Android development, but since I've got a client that needs a native Android module I looked at the docs to create one.
Because I don't know much about Android development, I lost a lot of time figuring out where & how I needed to add the files needed to create the Toast example.
Maybe being more specific regardless what you need to create & how it would help others like me to save time :)
hopefully this little contribution helps!
=> add filenames to example (Toast Example)

docs/direct-manipulation.md
Fixes the broken ref callback link in Direct Manipulation section
Closes #143
=> direct-manipulation.md: Fix ref callback link

docs/layout-props.md
The only change is to the order of the text in this document file.
=> Fix Alphabetization of Layout Props

docs/webview.md
Add the missed property in WebView documentation. 
https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.android.js#L175
=> Add allowUniversalAccessFromFileURLs property in WevView

docs/state.md
Hi,
I've fixed a minor typo while going through the documentation.
Thanks!
=> Fixed a minor typo.

docs/more-resources.md, website/versioned_docs/version-0.5/more-resources.md
fix the broken links of "Extending React Native" paragraph.
=> Update more-resources.md to fix broken links

docs/scrollview.md
Added nestedScrollEnabled prop to scrollview documentation to accompany PR https://github.com/facebook/react-native/pull/18299
=> Added nestedScrollEnabled prop to scrollview docs

docs/systrace.md
=> Minor cleanup on systrace.md to improve clarity

website/versioned_docs/version-0.5/integration-with-existing-apps.md, website/versioned_docs/version-0.52/integration-with-existing-apps.md
=> Add missing CxxBridge pod

docs/sectionlist.md, website/versioned_docs/version-0.55/sectionlist.md
SectionList Example 1 is displayed incorrectly.
=> Fix SectionList example

docs/more-resources.md
Tested the change
I have Tested visual changes in all latest versions of common browsers, on both desktop and mobile.
I have run yarn prettier to ensure my changes are consistent with other files in the repo.
Issue Fixed - #230 
Screenshot of visual change
=> Updated Layout doc with link to the new Yoga website

docs/geolocation.md
Include note about needing the RCTGeolocation pod for geolocation features for iOS
=> Update geolocation.md to include note about required pod on iOS

docs/geolocation.md, website/versioned_docs/version-0.15/geolocation.md, website/versioned_docs/version-0.16/geolocation.md, website/versioned_docs/version-0.18/geolocation.md, website/versioned_docs/version-0.21/geolocation.md, website/versioned_docs/version-0.25/geolocation.md, website/versioned_docs/version-0.34/geolocation.md, website/versioned_docs/version-0.35/geolocation.md, website/versioned_docs/version-0.39/geolocation.md, website/versioned_docs/version-0.42/geolocation.md, website/versioned_docs/version-0.45/geolocation.md, website/versioned_docs/version-0.46/geolocation.md, website/versioned_docs/version-0.48/geolocation.md, website/versioned_docs/version-0.49/geolocation.md, website/versioned_docs/version-0.5/geolocation.md, website/versioned_docs/version-0.50/geolocation.md, website/versioned_docs/version-0.53/geolocation.md, website/versioned_docs/version-0.54/geolocation.md
See --> #287
Hope that helps!
Thanks :bowtie:
=> Document extended geolocation.stopObserving() method #287

docs/keyboardavoidingview.md, website/versioned_docs/version-0.54/keyboardavoidingview.md, website/versioned_docs/version-0.55/keyboardavoidingview.md
KeyboardAvoidingView have prop enabled and mark as required.
=> Add prop enabled for KeyboardAvoidView document follow RN 0.54.

docs/getting-started.md
This step got a bit confusing for me as a non windows developer and thought others not familiar with this environment may have the same issue.
#<Issue>
=> Added Windows to Control Panel step for Android Studio setup

docs/layout-props.md
See https://stackoverflow.com/a/39316901/82609
=> Document flexWrap not working with alignItems: 'stretch'

docs/text-style-props.md, docs/text.md
#2088
This work is documentation for a corresponding enhancement PR to be made against react-native.   It addresses functionality discussed in issue [#2088](https://github.com/facebook/react-native/issues/2088) 
The related PR is https://github.com/facebook/react-native/pull/18387
Screenshots of doc changes:
=> docs for textTransform style

docs/webview.md
This PR adds the documentation for the new property "geolocationEnabled" for WebView component.
=> Doc for Android WebView "geolocationEnabled" prop

docs/troubleshooting.md
Added Ubuntu instruction to find the process PID
=> Documentation update PID lookup for ubuntu

docs/webview.md
This PR updates the documentation for WebView component to include the new prop originWhitelist
=> Update WebView documentation for originWhitelist

docs/image.md
=> [DOC] fixed errata in image doc

docs/viewpagerandroid.md
add "setPage" and "setPageWithoutAnimation" methods docs.
#<Issue>
=> add "setPage" methods docs

website/static/css/react-native.css
In Docusaurus 1.0.15 we changed how the navbar looks, which doesn't play well with RN website's custom CSS. I tweaked them to make them fit and removed some unused CSS. 
Check out the Netlify preview to see how it looks.
=> Fix sidebar CSS for Docusaurus update

docs/contributing.md, docs/image.md, docs/keyboardavoidingview.md, docs/performance.md, docs/running-on-device.md, docs/sectionlist.md, docs/signed-apk-android.md, docs/textinput.md, docs/tutorial.md, docs/using-a-scrollview.md, docs/viewpagerandroid.md, docs/webview.md, website/blog/2018-05-07-using-typescript-with-react-native.md, website/versioned_docs/version-0.54/keyboardavoidingview.md, website/versioned_docs/version-0.55/keyboardavoidingview.md, website/versioned_docs/version-0.55/sectionlist.md
Some of the existing code is not prettified. This PR prettifies them so that future PRs will not contain formatting fixes made by Prettier. No code was written manual in this PR.
=> Prettify code

docs/backhandler.md
..and replace androidBackHandler with backHandler.
=> Add an example which use removeEventListener

docs/vibration.md
Changed the first clause to agree with the second, @ line 12
=> Small sentence correction in vibration.md

docs/webview.md
These methods can be seen in the source files for both Android and iOS
- https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js
- https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.android.js
and in the example
https://github.com/facebook/react-native/blob/master/RNTester/js/WebViewExample.js#L114
=> Adds missing documentation for WebView methods

docs/contributing.md
#362 
Made changes to try and contain all the required guidance for testing at the top of the document within the Get Involved section
=> Added further guidance for testing within contributing.md

website/pages/en/versions.js
Originally issue facebook/react-native#19735 and PR facebook/react-native#19738
=> Fix github issues hyperlink

docs/removing-default-permissions.md, website/sidebars.json
Adds Android article on how to remove default/unnecessary permissions
Closes #387
=> Adds Android article on how to remove default/unnecessary permissions

docs/building-for-apple-tv.md
=> Remove random characters from Apple TV example

docs/tutorial.md, website/versioned_docs/version-0.5/tutorial.md
`View` was not imported so the Hello World sample would not compile.
=> Fixes Hello World sample code

docs/modal.md
=> alert is in the Alert module

docs/state.md
Since Mobx is also very Popular and gaining popularity. It's Reactive way is something which is nice to have, Requesting Mobx also needed to be added to the React native docs.
=> Added Mobx to the documentation

docs/running-on-device.md
reference https://stackoverflow.com/questions/21631313/xcode-project-vs-xcode-workspace-differences
=> CocoaPods requires opening .xcworkspace in Xcode

docs/performance.md
=> install transform-remove-console as dev dependency

docs/native-modules-android.md
File path was changed and specified from https://github.com/facebook/react-native-website/pull/231  but package name was not changed.
Thanks.
=> Update package on native-modules-android.md (Toast Example)

docs/webview.md, website/versioned_docs/version-0.52/webview.md, website/versioned_docs/version-0.53/webview.md, website/versioned_docs/version-0.55/webview.md, website/versioned_docs/version-0.56/webview.md
This reverts commit 13dc824cdd3110ce4fa1e3580a903ee43ee1f2d5.
Resolves #455
=> Revert "Document initialScale property (#64)"

docs/safeareaview.md
Added a note on minimum version of iOS for `SafeAreaView`.
#17638
=> Specify usage limitations of SafeAreaView

docs/getting-started.md
=> Note that you need to open a project first.

docs/accessibility.md
=> Update accessibility.md with accessibilityIgnoresInvertColors

docs/view.md
=> Add accessibilityIgnoresInvertColors to view properties in view.md

docs/native-modules-android.md
See https://github.com/facebook/react-native-website/issues/470
=> Added import statements

docs/native-components-android.md
Reverts facebook/react-native-website#474
=> Revert "Added missing code"

docs/more-resources.md, website/pages/en/help.js
This PR aims to expand the community section to cover better the React Native community at large.
I attempted to list all the places [some time ago](https://twitter.com/Kelset/status/1019963807546867712) but now PR #459 remembered me about it so I think it's time I work it out.
I think that now is ready for review.
=> Update the Community section

website/pages/en/help.js
Hi,
Just a small PR to add our Discord server link to the listed communities on the help page. We have around  ~2000 members - mainly in relation [Firebase](https://firebase.google.com/) services in React Native, more specifically the [React Native Firebase](https://github.com/invertase/react-native-firebase) module. 🔥
=> Add react-native-firebase discord server link to help page communities

docs/webview.md, website/blog/2018-08-27-wkwebview.md
New blog post and accompanying documentation.
=> [Blog] Introducing WKWebView-backed WebView

docs/animated.md
=> Add missing properties doc to Animated

docs/navigation.md
It is no longer actively being worked on.... 
https://github.com/airbnb/native-navigation/issues/114
https://github.com/airbnb/native-navigation/issues/145
=> Remove AirBnB Native Navigation

docs/geolocation.md
=> Fix typo Geolocation -> geolocation

docs/inputaccessoryview.md
This PR adds a "known issues" section to `InputAccessoryView`.
=> Add "known issues" section to InputAccessoryView

docs/maintainers.md
"Issues that *have have had* no activity..." -> "Issues that *have had* no activity..."
=> Fix typo in maintainers.md

docs/toastandroid.md
Updated the readme file to reflect the import statement in the basic usage section and also added an advanced usage section that seemed to work for me.
=> Updated the ToastAndroid.md

docs/scrollview.md
Based on these changes:
https://github.com/facebook/react-native/commit/fd744dd56ca183933a67e8398e1d20da14a31aab
https://github.com/facebook/react-native/commit/5f48d281190db9b71dbad5ca9209fd4ae4e1b124
=> Update scrollview.md to include snapToOffsets/snapToStart/snapToEnd

docs/pixelratio.md
=> updated to include new iphone models

website/versioned_docs/version-0.57/textinput.md
=> fix contextMenuHidden link

docs/images.md
Some files moved around in metro
=> Minor docs URL fix

docs/text.md
=> Added Space

website/versioned_docs/version-0.57/getting-started.md
Add changes from #582 to the latest (v0.57) docs.
=> Update Getting Started in v0.57 (latest) docs

docs/animations.md, website/versioned_docs/version-0.5/animations.md
=> typo in 'specially'

docs/permissionsandroid.md
=> Add possible Buttons to rationale

docs/webview.md
As per https://github.com/facebook/react-native/blob/c70abb393fb1d7410d5a092a331de4919a5ad0ea/Libraries/Components/WebView/WebView.android.js#L157
=> Added allowFileAccess Android WebView property

docs/text.md
=> Text component behaviour inside another Text component

docs/permissionsandroid.md
Previously these attributes were not fully documented, only mentioned in an example.
=> Document buttonPositive, buttonNegative, buttonNeutral

website/static/css/react-native.css
I added a slight transform on the .big-button hover effect that does:
```
transform: scale(1.05)
```
and I added a transition to the .big-button class that transitions this change as well.
=> .big-button nicer hover effect

website/static/css/react-native.css
Up to preference, but this may look a bit nicer compared to the old hover effect for the big buttons in the hero section.
=> Lighter big button color change on hover

docs/asyncstorage.md
=> Correct whitespace in AsyncStorage "Fetching data"

docs/layoutanimation.md
Add LayoutAnimation Properties on doc based on [the source code](https://github.com/facebook/react-native/blob/master/Libraries/LayoutAnimation/LayoutAnimation.js).
=> Add missing properties doc to LayoutAnimation

docs/debugging.md
Adds information on how to debug iOS apps using Safari Dev tools.
=> Added info on how to debug using Safari

docs/stylesheet.md
=> Clarifying exactly what properties absoluteFill includes

docs/building-from-source.md
also made Ndk version consistent with links
=> Update to new way of referencing dependencies

docs/touchablehighlight.md
=> Clarifying opacity is between 0 and 1, adding default

README.md
The documentation had a small bug with `'<version>'`, which was being ignored in the markdown.
> Run `yarn version <version>` where '<version>' is the new version being released.
+ also added periods to the list items just to keep consistency in the doc.
=> Fix small bug in ReadMe doc and add consistent periods.

docs/more-resources.md
adding the crash/error monitoring services that support react native
=> add crash reporting services for react native

docs/image-style-props.md
I just add the enum for `resizeMode`.
=> Fix resize mode for image style props

docs/stylesheet.md
=> Fix minor typo for stylesheet docs.

docs/textinput.md
I keep having to look these up and keep not finding them in the docs.
=> [TextInput] add more details on callback arguments

docs/communication-ios.md
=> Added note about appProperties changes being lost.

docs/upgrading.md, website/versioned_docs/version-0.5/upgrading.md
=> Fix typo in docs upgrading

docs/refreshcontrol.md
add RefreshControl import, beacuse its confusing, i think what it was custom component, not described in example
=> Update refreshcontrol.md, missing import confusing

docs/getting-started.md
Added  expo start command along with npm start
=> Added alternate command to start the server

docs/image.md
Add missing Image's `progressiveRenderingEnabled` prop documentation.
https://github.com/facebook/react-native/commit/f450e849427c877fa75986ccd6b2008a63a6c58d
=> add "progressiveRenderingEnabled" documentation

docs/permissionsandroid.md
Update the requestMultiple 'permissions' parameter description:
'Array of permission' -> 'Array of permissions'.
=> Fix typo in permissionsandroid.md

docs/sectionlist.md
Related with https://github.com/facebook/react-native-website/issues/510
=> moved renderItem from optional to required props - sectionlist

docs/communication-ios.md, docs/improvingux.md, docs/more-resources.md
#660 
Hey @hramos ,
**Google just changed their policy for autoplay videos, it has to be muted**
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
`<video height="256" loop autoplay muted>`
**Working change:**
=> Improving UX video auto-play fix

docs/textinput.md
=> fixed typo

docs/layout-props.md
=> url updated

docs/building-from-source.md
Hi, 
This PR is fixing minor things in building form sources instruction in order to follow up RN's template made with `react-native init`.
It's not crucial but might be valuable for not very experienced developer and my puritanical soul didn't allow me to leave it 🤷‍♂️
=> Follow up changes in template RN project for building from sources

docs/textinput.md
This PR adds a "known issues" section to TextInput.
Related to #564
=>  Add "known issues" section to TextInput

docs/sectionlist.md
had to dig through the source code for a while to find it 🙃
=> Document the `progressViewOffset` property

docs/asyncstorage.md
=> fix typo in asyncstorage.md

docs/pushnotificationios.md
Needs to be lowercase to work correctly
=> Fixing presentLocalNotificationLink

docs/dimensions.md
Explains the difference between screen and window for Android
=> Android: difference between screen and window

docs/integration-with-existing-apps.md
This PR adds documentation to pair with https://github.com/facebook/react-native/pull/23135 - specifically for integrating React Native into existing apps that are not covered by the `template` project.
=> [android] document required Network Security Config for React Native packager

docs/running-on-device.md
Project was not building in XCode, until I assigned the correct development certificates to the Tests branch as well
=> Update correct signing information for iOS

docs/textinput.md
=> add onSubmitEditing callback argument documentation

docs/tutorial.md
According to the ancient traditions of our people, "Hello, world!" shall be written with a comma after the "Hello".
=> Properly honor our ancestors

docs/scrollview.md
https://github.com/facebook/react-native/pull/19110
=> Update scrollview.md with disableScrollViewPanResponder prop

docs/view.md
https://github.com/facebook/react-native/pull/19052
=> iOS supports needsOffscreenAlphaCompositing

website/blog/2019-03-01-react-native-open-source-update.md
To be published in a couple of hours.
=> Blog Post: Open Source Update

docs/javascript-environment.md, website/versioned_docs/version-0.5/javascript-environment.md
=> Fix babel transforms link

website/blog/2019-03-12-releasing-react-native-059.md
Related to https://github.com/facebook/react-native/issues/23866, add clarifying instructions.
=> [0.59] [Blog] Add upgrade instructions

docs/getting-started.md, website/versioned_docs/version-0.5/getting-started.md, website/yarn.lock
As discussed in Discord, this is a WIP pull request to improve the wording in "Getting Started" to help people understand the differences between using Expo CLI and React Native CLI to get a "Hello World" app running.
=> Explain options in "Getting Started"

docs/image.md
=> Add Image.getSizeWithHeaders documentation

docs/pushnotificationios.md
I think it should be mentioned because many believe that this is already works out of the box. And if searching for a solution there are only few links to solve this issue.
=> Add details about foreground iOS notifications

docs/text.md
Related to https://github.com/facebook/react-native/commit/d2153fc58d825006076a3fce12e0f7eb84479132
Do not merge until 0.60 or cherry pick to 0.59
=> Update textAlign: justify for android O+

docs/getting-started.md
This may increase the number of people experimenting with release candidates.
=> Add instructions about the --version argument

docs/imagepickerios.md
=> add details about parameters for openCameraDialog and openSelectDialog

docs/native-modules-android.md
1. Change "create" to big caption
2. Provide more instruction to create ToastExample.js. Before it is confusing where should I include those content.
=> Update Android Native Modules tutorial in native-modules-android.md

docs/linking.md
Add documentation for `Linking.openSettings()`
https://github.com/facebook/react-native/pull/23965
=> Update Linking adding the brand new openSettings method

docs/integration-with-existing-apps.md
The changes here are based on updates from https://github.com/facebook/react-native/pull/24066
cc @dulmandakh
=> Update Android cleartext traffic configuration docs

docs/backhandler.md
I failed to remove `BackHandler` with using document style.
I succeeded in removing with keeping `BackHandler` as a value of `NativeEventSubscription`.
Thank you.
Reference: https://stackoverflow.com/a/52797669/3774895
=> Remove BackHandler with using NativeEventSubscription

docs/direct-manipulation.md
=> Fixed Broken link to NativeMethodsMixin.js

docs/using-a-scrollview.md
See facebook/react-native#20154
=> ScrollView zoom is not supported on Android

docs/sectionlist.md
=> Fix case typos

docs/view-style-props.md
=> Suggest adding overflow: 'hidden' if borderRadius fails

docs/animated.md
=> typo lineal -> linear

docs/text.md
Documentation change in parallel with https://github.com/facebook/react-native/pull/19216
=> Add dataDetectorType prop to Text for Android

README.md, website/package.json, website/yarn.lock
=> Upgrade to docusaurus@1.8.0

docs/signed-apk-android.md
=> docs: Fix JDK and Gradle capitalization

docs/navigation.md
docs for linking react-native-gesture-handler to react-native 
because of which i have wasted 1/2 an hour it would be good if its mentioned there
=> docs:Link react-native-gesture-handler to react-native

docs/pushnotificationios.md
See  https://stackoverflow.com/questions/45440627/do-remote-push-notifications-require-to-add-uibackgroundmodes-in-info-plist
=> Add Background Modes/Remote notifications to docs.

docs/view.md
https://github.com/facebook/react-native-website/pull/873 got merged with conflicts. Fixing it now. My bad.
cc @charpeni @cpojer
=> fix accessibility docs with conflicts

docs/direct-manipulation.md
=> Clarifying a sentence

website/blog/2019-03-01-react-native-open-source-update.md
=> Fix typo in March blog post

docs/native-modules-android.md
=> Typo / grammar

docs/native-modules-android.md
=> Clarification

docs/accessibilityinfo.md
see related  facebook/react-native#24746
TLDR:
AccessibilityInfo.announceForAccessibility support for Android
=> [Android][A11y] AccessibilityInfo.announceForAccessibility

docs/accessibility.md
This PR adds the additional accessibility roles and states added in https://github.com/facebook/react-native/pull/24095
=> Add additional accessibility roles and states to the documentation.

docs/scrollview.md
Added *** *** around important deprecated warnings of features.
=> Markdown - emphasized deprecation

website/core/Footer.js
...plus some slight tweaks to other items in the footer.
=> Add link to Contributor Guide in website footer

docs/timers.md
=> Remove TimerMixin

docs/alert.md
#929<Issue>
- Update type property
- Update Android documentation
=> Update alert.md with new APIs #929

docs/flatlist.md
#929
-alphabetized api list
(incomplete)
=> Update flatlist apis for #929

website/i18n/en.json
This file is autogenerated when running `yarn start` locally, and was missed in https://github.com/facebook/react-native-website/pull/941
=> [Infra] Add 0.59/Linking to en.json

website/pages/en/help.js
Adds the React Native Show under "Staying up to date"
=> [Help] Add React Native Show

docs/accessibility.md, docs/view.md
Made slight improvements to the accessibilityRole and accessibilityStates documentation. Added documentation for accessibility actions support.
=> Accessibility Documentation Improvements

docs/textinput.md
This PR adds documentation for the feature added in https://github.com/facebook/react-native/pull/25028
=> Document showSoftInputOnFocus

docs/button.md
☂️☂️☂️☂️☂️☂️☂️☂️ #929  ☂️☂️☂️☂️☂️☂️☂️☂️
Rearranged things to be in alphabetical 
new APIs added:
-nextFocusDown
-nextFocusRight
-nextFocusLeft
-nextFocusUp
-nextFocusForward
-touchSoundDisabled
=> ☂️  update button.md APIs #929

docs/scrollview.md
**Original issue:** #929
**Props added:**
`disableIntervalMomentum`, `invertStickyHeaders`, `maintainVisibleContentPosition`, `persistentScrollbar`, `scrollToOverflowEnabled`, `onScrollToTop`,  `scrollBarThumbImage`
**This commit need to be improved:**
1 - Add link to `Touchable` props
2 - Fix the type of `scrollBarThumbImage`
=> Update ScrollView APIs

docs/native-components-ios.md
Add section Handling multiple native views in native-components-ios
=> Add section Handling multiple native views

docs/state.md
This is a minor code indentation fix. Please review and merge it.
=> code indentation fix

docs/toolbarandroid.md
Part of [#929](https://github.com/facebook/react-native-website/issues/929)
=> Sorted in alphabetical order

docs/app-extensions.md
[Fixes #999](https://github.com/facebook/react-native-website/issues/999)
=> Fixes broken url

docs/settings.md
=> Sorted in alphabetical order settings.md

docs/animations.md
=> Fix broken animations example links

docs/image.md
=> Document RAW image formats supported by iOS

website/sidebars.json
These components are listed in `components-and-apis`.
=> Add `tabbarios` & `tabbarios-item` to sidebars

docs/getting-started.md, docs/more-resources.md, docs/performance.md, docs/scrollview.md, docs/sectionlist.md, docs/signed-apk-android.md, docs/statusbar.md, docs/view.md, website/versioned_docs/version-0.60-RC/getting-started.md, website/versioned_docs/version-0.60-RC/more-resources.md, website/versioned_docs/version-0.60-RC/performance.md, website/versioned_docs/version-0.60-RC/scrollview.md, website/versioned_docs/version-0.60-RC/sectionlist.md, website/versioned_docs/version-0.60-RC/signed-apk-android.md, website/versioned_docs/version-0.60-RC/statusbar.md, website/versioned_docs/version-0.60-RC/view.md
Fixed a few typos in the documentation 😄
=> Fix a few typos within docs/

website/blog/2019-06-12-react-native-open-source-update.md
Celebrating all the awesome work people did.
=> June Open Source Update Blog Post

docs/flexbox.md
=> add definition and example of how flexbox works

website/blog/2019-06-12-react-native-open-source-update.md
=> Fix a typo

docs/touchableopacity.md, docs/touchablewithoutfeedback.md
This is part of #929 
-  The [`accessibilityIgnoresInvertColors`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L107) prop
-  The [`accessibilityState`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L110) prop
-  The [`nativeID`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L154) prop
-  The [`touchSoundDisabled`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L150) prop
-  The [`accessibilitytraits`](https://github.com/facebook/react-native-website/blob/master/docs/touchablewithoutfeedback.md#accessibilitytraits) prop
-  The …
=> Update touchablewithoutfeedback.md && touchableopacity.md 

docs/optimizing-flatlist-configuration.md
There were some incorrect statements and some language that could use clarification.
=> Fix up new optimizing flatlist doc

docs/dimensions.md
=> Sorted in alphabetical order dimensions.md

docs/native-modules-android.md
Added missing `DeviceEventManagerModule` import to example.
=> Add missing import to example

docs/animated.md, docs/animations.md
=> Mention Animated's FlatList and SectionList

docs/javascript-environment.md
=> Update Optional Chaining stage

website/blog/2019-07-03-version-60.md
=> Fix uri typo in 0.60 blog post

docs/flatlist.md
Correct `viewAreaCoveragePercentThreshold` instead of `viewAreaPercentThreshold`
=> Correct `viewAreaCoveragePercentThreshold`

docs/hermes.md
Update domain name in `hermes.md` from https://hermesvm.io to https://hermesengine.dev
Reference: https://github.com/facebook/hermes/pull/14
=> Fix: Update Hermes engine url

website/blog/2019-07-17-hermes.md
=> It's also an engine.

docs/virtualizedlist.md
Wrong links:
* https://facebook.github.io/react-native/docs/virtualizedlist#ListItemComponent
* https://facebook.github.io/react-native/docs/virtualizedlist#ListFooterComponentStyle
* https://facebook.github.io/react-native/docs/virtualizedlist#ListHeaderComponentStyle
* https://facebook.github.io/react-native/docs/virtualizedlist#persistentScrollbar
=> Fix several links

website/pages/en/index.js
Small PR based on conversations on Discord - this rewords partner text to include other contributors.
=> [homepage] reword partners to include other contributors

website/pages/en/index.js
1. Remove unused `Component` export.
2. `export default () => ...` is not recommended because it doesn't get a name. Changing this to an explicit assignment. Happy to change to `App` or whatever but this seemed clear enough.
=> Tweak home page example

website/static/js/headerAnimation.js
=> fix header animation when loaded in background tab

docs/keyboardavoidingview.md
Since it is possible to use "height" as the behavior prop, the documentation should indicate so in the overview.
=> Clarify documentation on KeyboardAvoidingView

docs/flexbox.md
=> Add, Flex wrap playground url add

docs/props.md
Helps with understanding that 'props' is short for 'properties' (in my opinion)
=> Update props.md - what is props?

docs/upgrading.md
=> Fixed numbering issue in 'Upgrading' page

docs/pickerios.md
=> Link to onChange section

docs/touchableopacity.md
=> activeOpacity description block repeat correction

docs/javascript-environment.md
Think I got most of the new additions from the [metro defaults](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/package.json)
=> Updates the JS environment

website/versioned_docs/version-0.59/linking.md
See https://github.com/facebook/react-native-website/pull/1117#issuecomment-518923100
=> Remove `openSettings` entry from TOC

docs/getting-started.md
yarn must be installed otherwise you will get a lot of errors
=> brew install yarn

docs/stylesheet.md
I was going over the documentation for absoluteFill and absoluteFillObject and realized it could use some improvement.
Thanks!
=> docs: Fixed code example & cleared up difference between absoluteFill vs. absoluteFillObject

docs/integration-with-existing-apps.md
Given Podfile doesn't work with react-native 0.60
=> update podfile content as per react-native 0.60

.github/CODEOWNERS, docs/typescript.md, website/sidebars.json
And here's the PR all the others have been working up to, this adds a quick overview on how to:
- start with TypeScript
- add TypeScript to an existing project
- talks about how it works via babel
- gives an example to look at
- gives some extra context on where to look at next
Open to feedback on what else could be in here?
I also added myself as an auto-reviewer to this file which should make it easy for me to validate changes if it's complex 👍
=> Added a first pass at TS docs for React Native

docs/more-resources.md
I get a 404 on the current link.
=> Update Link For Native Directory

website/pages/en/index.js
`allowFullScreen` has to be in camelCase to be taken into consideration.
=> Set allowFullScreen to Eli's talk

docs/components-and-apis.md, website/static/css/react-native.css
Component cards were not clickable, except on the title.
From now, the whole card will be clickable and it will scale a bit on hover.
=> Improve design of Components and APIs page

website/pages/en/help.js
=> Update links related to React Conf

docs/flatlist.md, website/versioned_docs/version-0.60/flatlist.md
More snack examples. This time for FlatList component.
=> imp: Add snack examples to FlatList

docs/inputaccessoryview.md
=> Update inputaccessoryview.md - fix link

website/siteConfig.js, website/static/css/header.css, website/static/js/2019_docs-survey.js
=> Adding banner for docs survey, please remove in 2 weeks

docs/refreshcontrol.md, docs/safeareaview.md, docs/scrollview.md
Snack examples for `ReafreshControl`, `SafeAreaView` and `ScrollView`.
=> imp: snack example for RefreshControl, SafeAreaView and ScrollView

docs/sectionlist.md
Snack example for SectionList component.
=> imp: Snack example for SectionList

docs/out-of-tree-platforms.md
=> Add react-native-community/react-native-tvos to out-of-tree-platforms.md

docs/optimizing-flatlist-configuration.md
=> Improve Optimizing FlatList page

docs/components-and-apis.md
=> Remove WebView from components-and-apis

website/sidebars.json, website/versioned_sidebars/version-0.60-sidebars.json
Optimizing FlatList shouldn't be the first guide for newcomers.
=> Change the order of Optimizing FlatList

docs/getting-started.md, website/versioned_docs/version-0.5/getting-started.md
=> Replace tag ending with </button>

docs/native-modules-android.md, docs/navigation.md, website/versionedDocsBlacklist.json, website/versioned_docs/version-0.5/components-and-apis.md, website/versioned_docs/version-0.5/height-and-width.md, website/versioned_docs/version-0.5/native-modules-android.md, website/versioned_docs/version-0.5/navigation.md, website/versioned_docs/version-0.5/optimizing-flatlist-configuration.md, website/versioned_docs/version-0.60/hermes.md, website/versioned_docs/version-0.60/inputaccessoryview.md, website/versioned_docs/version-0.60/out-of-tree-platforms.md, website/versioned_docs/version-0.60/refreshcontrol.md, website/versioned_docs/version-0.60/safeareaview.md, website/versioned_docs/version-0.60/scrollview.md, website/versioned_docs/version-0.60/sectionlist.md
=> Republish 0.60

website/blog/2019-09-18-version-0.61.md
=> Add 0.61 blog post

docs/debugging.md, docs/fast-refresh.md, website/i18n/en.json, website/sidebars.json
This PR adds a new guide for Fast Refresh starting in 0.62.
=> Add guide for Fast Refresh

docs/native-modules-android.md
this fix a Syntax-Error in Code-Example.
=> Add missing parenthesis

docs/typescript.md
https://github.com/react-native-community/cli/issues/764#issue-501488768
=> Updating the rn ts init command as per the issue mentioned.

docs/native-components-android.md
=> Use updated constructor for ReactImageView (#1291)

website/pages/en/help.js
=> Fix markup related to React Conf

docs/getting-started.md
=> Updated Live Reloading to Fast Refresh

docs/typescript.md
=> Fix babel.config.js example in typescript.md

docs/clipboard.md
Additional notice for specific data types
=> Added notice to Clipboard

docs/native-components-ios.md
=> Fix typo in docs/native-components-ios.md

website/pages/en/help.js
The current invite link goes to our React Native channel, but we need new users to see the welcome channel's information.
=> Use vanity URL for Reactiflux

.alexignore, website/versioned_docs/version-0.61/debugging.md, website/versioned_docs/version-0.61/fast-refresh.md
This PR fixes lint issues found in `versioned_docs` directory for version 0.61
#1338
=> Fix lint rules in version 0.61

docs/typescript.md
=> Update typescript.md with a md typo fix

.alexignore, website/versioned_docs/version-0.60/animated.md, website/versioned_docs/version-0.60/appstate.md, website/versioned_docs/version-0.60/asyncstorage.md, website/versioned_docs/version-0.60/communication-android.md, website/versioned_docs/version-0.60/datepickerios.md, website/versioned_docs/version-0.60/dimensions.md, website/versioned_docs/version-0.60/drawerlayoutandroid.md, website/versioned_docs/version-0.60/easing.md, website/versioned_docs/version-0.60/flatlist.md, website/versioned_docs/version-0.60/hermes.md, website/versioned_docs/version-0.60/imagebackground.md, website/versioned_docs/version-0.60/inputaccessoryview.md, website/versioned_docs/version-0.60/layout-props.md, website/versioned_docs/version-0.60/modal.md, website/versioned_docs/version-0.60/out-of-tree-platforms.md, website/versioned_docs/version-0.60/panresponder.md, website/versioned_docs/version-0.60/safeareaview.md, website/versioned_docs/version-0.60/scrollview.md, website/versioned_docs/version-0.60/sectionlist.md, website/versioned_docs/version-0.60/statusbar.md, website/versioned_docs/version-0.60/text.md, website/versioned_docs/version-0.60/textinput.md, website/versioned_docs/version-0.60/touchablewithoutfeedback.md, website/versioned_docs/version-0.60/vibration.md, website/versioned_docs/version-0.60/view.md
This PR fixes lint issues found in `versioned_docs` directory for version 0.60
#1338
=> Fix lint rules in version 0.60

.alexignore, website/versioned_docs/version-0.40/layout-props.md, website/versioned_docs/version-0.40/panresponder.md, website/versioned_docs/version-0.40/scrollview.md, website/versioned_docs/version-0.40/textinput.md
=> fixed insensitive and inconsiderate language version-0.40

.alexignore, website/versioned_docs/version-0.6/textinput.md, website/versioned_docs/version-0.6/touchableopacity.md
👋 This PR adds lint rules and fixes issues for `versioned_docs` directory for `version-0.6`
#1338
=> Docs: Lint versioned_docs/version-0.6

website/versioned_docs/version-0.13/scrollview.md, website/versioned_docs/version-0.13/textinput.md
This PR fixes lint issues found in versioned_docs directory for version 0.13
#1338
=> Fix lint rules v013

.alexignore, website/versioned_docs/version-0.54/appstate.md, website/versioned_docs/version-0.54/flatlist.md, website/versioned_docs/version-0.54/modal.md, website/versioned_docs/version-0.54/sectionlist.md, website/versioned_docs/version-0.54/textinput.md, website/versioned_docs/version-0.54/vibration.md
This PR fixes lint issues  for version 0.54
#1338
=> Fix lint rules in version 0.54

website/versioned_docs/version-0.53/appstate.md, website/versioned_docs/version-0.53/scrollview.md, website/versioned_docs/version-0.53/textinput.md
=> Fixed linting in version 0.53

README.md, STYLEGUIDE.md
Since I have been working on the docs with a number of community contributors, the same advice and guidance has recurred several times. All should adhere to these guidelines to maintain a unified voice and reliable quality for many readers to come
=> Adding styleguide for contributing writers

.alexignore, website/versioned_docs/version-0.45/flatlist.md, website/versioned_docs/version-0.45/layout-props.md, website/versioned_docs/version-0.45/navigatorios.md, website/versioned_docs/version-0.45/panresponder.md, website/versioned_docs/version-0.45/scrollview.md, website/versioned_docs/version-0.45/sectionlist.md, website/versioned_docs/version-0.45/textinput.md, website/versioned_docs/version-0.45/view.md
This PR adds lint rules and fixes issues for versioned_docs directory for version-0.45
https://github.com/facebook/react-native-website/issues/1338
=> Docs: Lint versioned_docs/version-0.45

.alexignore, website/versioned_docs/version-0.15/asyncstorage.md, website/versioned_docs/version-0.15/textinput.md
This PR fixes insensitive, inconsiderate writing issues found in versioned_docs directory for version 0.15.
The term "simple" was removed or replaced in the files: 
* version-0.15/textinput.md
* version-0.15/asyncstorage.md
#1338
=> Fix lint rules v015

.alexignore, website/versioned_docs/version-0.7/scrollview.md, website/versioned_docs/version-0.7/textinput.md
👋 This PR adds lint rules and fixes issues for `versioned_docs` directory for `version-0.7`
#1338
=> Docs: Lint versioned_docs/version-0.7

.alexignore, website/versioned_docs/version-0.48/animated.md, website/versioned_docs/version-0.48/flatlist.md, website/versioned_docs/version-0.48/layout-props.md, website/versioned_docs/version-0.48/listview.md, website/versioned_docs/version-0.48/listviewdatasource.md, website/versioned_docs/version-0.48/modal.md, website/versioned_docs/version-0.48/navigatorios.md, website/versioned_docs/version-0.48/scrollview.md, website/versioned_docs/version-0.48/sectionlist.md, website/versioned_docs/version-0.48/view.md
This PR is part of #1338 
Applied lint rules to documents for version 0.48
=> docs: fix lint rule in version 0.48

.alexignore, website/versioned_docs/version-0.49/animated.md, website/versioned_docs/version-0.49/flatlist.md, website/versioned_docs/version-0.49/modal.md, website/versioned_docs/version-0.49/navigatorios.md, website/versioned_docs/version-0.49/scrollview.md, website/versioned_docs/version-0.49/sectionlist.md, website/versioned_docs/version-0.49/tabbarios.md, website/versioned_docs/version-0.49/text.md, website/versioned_docs/version-0.49/textinput.md, website/versioned_docs/version-0.49/vibration.md, website/versioned_docs/version-0.49/view.md
This PR is part of #1338
Applied lint rules to documents for version 0.49
=> docs: fix lint rule in version 0.49

.alexignore, website/versioned_docs/version-0.52/animated.md, website/versioned_docs/version-0.52/flatlist.md, website/versioned_docs/version-0.52/layout-props.md, website/versioned_docs/version-0.52/sectionlist.md, website/versioned_docs/version-0.53/appstate.md, website/versioned_docs/version-0.53/scrollview.md, website/versioned_docs/version-0.53/textinput.md
=> Lint rules v 0.52

.alexignore, website/versioned_docs/version-0.10/textinput.md
👋 This PR adds lint rules and fixes issues for `versioned_docs` directory for `version-0.10`
#1338
=> Docs: Lint versioned_docs/version-0.10

.alexignore, website/versioned_docs/version-0.14/textinput.md
Lint for insensitive/inconsiderate language on `versioned_docs/version-0.14`
#1338
=> Versioned docs 0.14

.alexignore, website/versioned_docs/version-0.12/animated.md, website/versioned_docs/version-0.12/easing.md, website/versioned_docs/version-0.12/scrollview.md, website/versioned_docs/version-0.12/textinput.md, website/versioned_docs/version-0.12/touchableopacity.md
Lint for insensitive/inconsiderate language in `versioned_docs/version-0.12`
#1338
=> Versioned docs 0.12

.alexignore, website/versioned_docs/version-0.27/drawerlayoutandroid.md, website/versioned_docs/version-0.27/navigatorios.md, website/versioned_docs/version-0.27/scrollview.md, website/versioned_docs/version-0.27/textinput.md
=> Fix lint rules in v0.27

.alexignore, website/versioned_docs/version-0.9/scrollview.md, website/versioned_docs/version-0.9/textinput.md
=> Fix lint rules in v0.9

.alexignore, website/versioned_docs/version-0.51/animated.md, website/versioned_docs/version-0.51/easing.md, website/versioned_docs/version-0.51/flatlist.md, website/versioned_docs/version-0.51/layout-props.md, website/versioned_docs/version-0.51/scrollview.md, website/versioned_docs/version-0.51/sectionlist.md, website/versioned_docs/version-0.51/text.md, website/versioned_docs/version-0.51/textinput.md
=> Fix lint rules in v0.51

.alexignore, website/versioned_docs/version-0.47/flatlist.md, website/versioned_docs/version-0.47/layout-props.md, website/versioned_docs/version-0.47/modal.md, website/versioned_docs/version-0.47/scrollview.md, website/versioned_docs/version-0.47/sectionlist.md, website/versioned_docs/version-0.47/view.md
=> Fix lint rules in v0.47

.alexignore, website/versioned_docs/version-0.30/drawerlayoutandroid.md, website/versioned_docs/version-0.30/layout-props.md, website/versioned_docs/version-0.30/modal.md, website/versioned_docs/version-0.30/scrollview.md, website/versioned_docs/version-0.30/textinput.md
This PR fixes insensitive, inconsiderate writing issues found in versioned_docs directory for version 0.30.
#1338
=> Version 0.30

.alexignore, website/versioned_docs/version-0.41/modal.md, website/versioned_docs/version-0.41/scrollview.md, website/versioned_docs/version-0.41/textinput.md, website/versioned_docs/version-0.41/touchableopacity.md
This PR adds lint rules and fixes issues for versioned_docs directory for version-0.41!!
#1338
=> fixed insensitive and inconsiderate language v0.41

.alexignore, website/versioned_docs/version-0.42/animated.md, website/versioned_docs/version-0.42/appstate.md, website/versioned_docs/version-0.42/layout-props.md, website/versioned_docs/version-0.42/navigatorios.md, website/versioned_docs/version-0.42/scrollview.md, website/versioned_docs/version-0.42/textinput.md
=> Lint versioned_docs/version-0.42

.alexignore, website/versioned_docs/version-0.38/modal.md, website/versioned_docs/version-0.38/textinput.md
This PR fixes lint issues found in `versioned_docs` directory for version 0.38
#1338
=> Fix lint rules in version 038

.alexignore, website/versioned_docs/version-0.58/drawerlayoutandroid.md, website/versioned_docs/version-0.58/navigatorios.md, website/versioned_docs/version-0.58/scrollview.md
I merged the 0.58 fixes without it being removed from .alexignore (see: https://github.com/facebook/react-native-website/issues/1338)
=> Add 0.58 to .alexignore

.alexignore, website/versioned_docs/version-0.36/animated.md, website/versioned_docs/version-0.36/layout-props.md, website/versioned_docs/version-0.36/modal.md, website/versioned_docs/version-0.36/scrollview.md, website/versioned_docs/version-0.36/textinput.md
This PR fixes lint issues found in `versioned_docs` directory for version 0.36
#1338
=> fix lint rules in version 036

.alexignore, website/versioned_docs/version-0.19/animated.md, website/versioned_docs/version-0.19/scrollview.md, website/versioned_docs/version-0.19/textinput.md
There is possibly going to be a conflict with 0.18 `animated.md` with @mehtavishwa30
=> Fix linting in versioned_docs/version-0.19

.alexignore, website/versioned_docs/version-0.20/imagestore.md, website/versioned_docs/version-0.20/scrollview.md, website/versioned_docs/version-0.20/textinput.md
Mostly copied from previously fixed docs.
=> Fix linting for versioned_docs/version-0.20

.alexignore, website/versioned_docs/version-0.21/scrollview.md
=> Removed 'easy' from scrollview.md

.alexignore
No lint issues found in `versioned_docs` directory for version 0.35
#1338
=> Fix lint rules in version 035: No issues found

.alexignore, website/versioned_docs/version-0.34/animated.md, website/versioned_docs/version-0.34/layout-props.md, website/versioned_docs/version-0.34/modal.md, website/versioned_docs/version-0.34/navigatorios.md, website/versioned_docs/version-0.34/textinput.md
This PR fixes lint issues found in `versioned_docs` directory for version 0.34
#1338
=> Fix lint rules in version 0.34

.alexignore, website/versioned_docs/version-0.33/layout-props.md
This PR fixes lint issues found in versioned_docs directory for version 0.33
There were only 2 \o/
#1338
=> Fix lint rules in version 0.33

.alexignore, website/versioned_docs/version-0.31/asyncstorage.md, website/versioned_docs/version-0.31/panresponder.md, website/versioned_docs/version-0.31/textinput.md, website/versioned_docs/version-0.31/touchableopacity.md, website/versioned_docs/version-0.33/layout-props.md
This PR fixes lint issues found in versioned_docs directory for version 0.31
soz for the bad commit history, pls squash and merge?
#1338
=> Fix lint rules in version 0.31

.alexignore, website/versioned_docs/version-0.21/scrollview.md, website/versioned_docs/version-0.24/scrollview.md, website/versioned_docs/version-0.24/textinput.md
=> Lint 0.21 and 0.24  for insensitive and inconsiderate language 

.alexignore, website/versioned_docs/version-0.23/animated.md, website/versioned_docs/version-0.23/asyncstorage.md, website/versioned_docs/version-0.23/dimensions.md, website/versioned_docs/version-0.23/easing.md, website/versioned_docs/version-0.23/scrollview.md, website/versioned_docs/version-0.23/textinput.md
This PR fixes lint issues found in versioned_docs directory for version 0.23
#1338
=> Fix lint rules in version 0.23

.alexignore, website/versioned_docs/version-0.26/panresponder.md, website/versioned_docs/version-0.26/scrollview.md, website/versioned_docs/version-0.26/touchableopacity.md
Fixed alex linting errors for v0.26 docs.
=> Fix lint errors in v0.26

.alexignore, website/versioned_docs/version-0.25/asyncstorage.md, website/versioned_docs/version-0.25/drawerlayoutandroid.md, website/versioned_docs/version-0.25/scrollview.md, website/versioned_docs/version-0.25/textinput.md, website/versioned_docs/version-0.25/touchableopacity.md
Fixes lint issues found in versioned_docs directory for version 0.25
Also, looks like alex does not catch the word `simplest` for some reason but I've changed that too.
#1338
=> Fix lint issues in version 0.25

.alexignore, website/versioned_docs/version-0.43/animated.md, website/versioned_docs/version-0.43/dimensions.md, website/versioned_docs/version-0.43/easing.md, website/versioned_docs/version-0.43/layout-props.md, website/versioned_docs/version-0.43/scrollview.md, website/versioned_docs/version-0.43/textinput.md
- remove version-0.43 from .alexignore
- fix version-0.43/animated.md
- fix version-0.43/dimensions.md
- fix version-0.43/easing.md
- fix version-0.43/layout-props.md
- fix version-0.43/scrollview.md
- fix version-0.43/textinput.md
Fixes lint issues for version 0.43 #1338
=> #1338 Fix alex lint issues for version-0.43

.alexignore, website/versioned_docs/version-0.22/animated.md, website/versioned_docs/version-0.22/textinput.md
Fixed lint errors for version 0.22 (#1338)
=> Fix lint errors for version 0.22

.alexignore, website/versioned_docs/version-0.18/animated.md, website/versioned_docs/version-0.18/dimensions.md, website/versioned_docs/version-0.18/imagestore.md, website/versioned_docs/version-0.18/scrollview.md
fixed lint errors for version - 0.18  
🎊 This is the last PR for (#1338)
=> fixed lint errors for v0.18

.alexignore
=> Remove the now irrelevant comment from .alexignore

docs/more-resources.md, website/versioned_docs/version-0.5/more-resources.md
=> Updating links to App Center

website/package.json, website/yarn.lock
Upgrading to the latest version which allows us to customize the meta descriptions on individual pages, which we need as not all pages have taglines to generate descriptions from. My thanks to the Docusaurus team for adding this feature!
=> upgrading docusaurus to latest version

docs/linking.md
=> Remove additional commas

docs/typescript.md
=> Add missing typescript package to npm install

website/versioned_docs/version-0.43/touchablenativefeedback.md, website/versioned_docs/version-0.5/navigator.md, website/versioned_docs/version-0.60/touchablenativefeedback.md, website/versioned_docs/version-0.61/debugging.md
- Fix misnamed method headers / index entries (fixes #1428)
=> Fix misnamed method headers / index entries (fixes #1428)

docs/removing-default-permissions.md
=> Add a hint for free (license-less) apps

README.md
=> Fix broken link on STYLEGUIDE

docs/transforms.md
Update Transforms.md change props to Methods,it is api not a react component ,
it must be Methods more than Props.
=> Update Transforms.md change props to Methods

docs/text-style-props.md
fontVariant support for Android was added with https://github.com/facebook/react-native/pull/27006
=> Update docs to reflect fontVariant Android support

docs/typescript.md
This PR has only documentation formatting adjustments.
I have added some new indentation where needed in the code example and add a missing space in style declaration.
=> Adjust few TypeScript's documentation formatting

docs/getting-started.md
Fix error when init a new react native project using typescript template:
=> Fix typescript template

website/blog/2019-11-18-react-native-doctor.md
Add back some numbers on the contributions
=> Update intro sentence

docs/native-modules-android.md
This should be mentioned in doc itself: https://stackoverflow.com/a/36901160/4452048
=> Add information about removing listener

docs/share.md
=> fix grammar

docs/dimensions.md
=> Fix parameter formatting in dimensions doc

docs/clipboard.md
=> Fix parameter formatting in Clipboard docs

docs/panresponder.md
=> Fix parameter formatting in panresponder doc

docs/keyboard.md
=> Fix parameter formatting

docs/switch.md
This PR is in reference to Issue #929 and is for updating the doc for modal.
It contains:
Adding snack player example to switch.md
=> Add snack player example to switch.md

docs/dimensions.md
=> Dimensions with examples

docs/easing.md
=> [docs] fix typo in easing page

docs/pushnotificationios.md
=> :pencil: fix the PushNotificationIOS Podfile example

docs/activityindicator.md
Following changes has been made:
* use functional component
* simplify styles
* remove duplicated example
* remove unused imports
Refs #1272
=> simplify ActivityIndicator snack example

docs/modal.md
Based on https://github.com/facebook/react-native/pull/26706 this PR adds information about the new prop introduced for android.
=> modal.md - add translucent statusbar option

docs/getting-started.md
=> Update text to Node 12 LTS

docs/linking.md
Updating the docs after this PR:
https://github.com/facebook/react-native/pull/26607
=> Updated docs to reflect exceptions when using the Linking API in Simulator

docs/textinput.md
Added missing prop for textAlign.
=> docs: Update textinput.md

website/versioned_docs/version-0.61/getting-started.md
Applied change from #1536 to version 0.61 document.
=> docs: Remove advice to enable Fast Refresh for new apps

docs/scrollview.md
Improve formatting of nativeEvent shape for easier readability. Since this was a fairly small change I considered directly opening a PR.
=> Docs: improve ScrollView nativeEvent formatting

website/versioned_docs/version-0.58/geolocation.md
Fix links for http://facebook.github.io/react-native/docs/geolocation.html page
=> Fix links for website

docs/intro-react.md
=> Small fixes to React guide

docs/introduction.md
The description is a bit incorrect. It's not commented out: `//` comments don't work inside JSX text content. So they actually do appear in the text. This is text, not a comment.
=> Tweak the first example

docs/intro-react.md
Not insisting on this wording in particular, but I think we need to make this a bit more precise.
In particular, you probably meant `useState` rather than `setState`.
=> Tweak state explanation

docs/handling-text-input.md
Convert class to function and use `useState` hook
=> Update TextInput example with hooks

website/versioned_docs/version-0.60/typescript.md
=> Fix typo in typescript.md

docs/navigation.md, website/versioned_docs/version-0.5/navigation.md
The current documentation refers to React Navigation 4. We're about to publish new major version of React Navigation, so I have updated the documentation.
=> Update docs for React Navigation 5

docs/keyboardavoidingview.md
Added example using functional Component to KeyboardAvoidingView component. #1579
=> Added Snack example for KeyboardAvoidingView #1579

docs/touchableopacity.md
Issue: #1579
- Updated snack and example.
=> TouchableOpacity: update Snack example

docs/pushnotificationios.md
Changed description of PushNotificationIOS Methods to have consistent format for optional properties.
=> docs: consistency for optional properties

docs/button.md
Issue: #1579 
Seems like example is already using function component :)
=> Button: Update code snippet and example

docs/touchablehighlight.md
Issue: #1579
- Updated snack and example.
I've also removed prop which I didn't find in [TouchableHighlight](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableHighlight.js) 
[TouchableWithoutFeedback](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js) and [TVTouchable](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TVTouchable.js) but I might missing something.
=> TouchableHighlight: Update API and Snack to functional component.

docs/view-style-props.md
In Reference to #1579 
This PR adds a Snack Example for `View Style Props`.
=> View Style Props: Added Snack Example 🍿

docs/statusbar.md
Added Status Bar examples with hooks related to #1579
=> Docs: StatusBar example updated using Expo and Hooks

docs/using-a-scrollview.md
Refs #1579.
This is not a part of API documentation but I think that current example on the "Using a ScrollView" page could be improved as well.
=> simplify "Using a ScrollView" docs example

docs/debugging.md
=> Add details about SourceMaps when debugging using Safari

docs/network.md
Refs #1579, #1272.
Same as with earlier PR, this page is not a part of "Component Docs Drive" but I think it will be a good supplementary improvement to those changes. 
@rachelnabors Question is if class component example should be rewritten and retained (using tabs)  or is it okay to just replace it?
=> rewrite fetch example using hooks

docs/native-modules-android.md
467081 for startActivityForResult request code is upper 16bit. so Error will be invoked.
=> ImagePicker RequestCode update

docs/running-on-device.md
=> Updated running-on-device.md making signing for Test more noticeable 

docs/state.md
i updated only the example state to hooks!!
=> Update Example state.md with Hooks

docs/virtualizedlist.md
Added example using functional Component to Virtualized List component. #1579
=> Added snack example for virtualized list #1579

docs/running-on-device.md
Developer options are under Settings -> System
=> Updated location of Developer Options in ReadMe

docs/modal.md
https://github.com/facebook/react-native-website/issues/1579
- Adding new code blocks as shown by @rachelnabors
- Adding better styling for example
- Both function and class example added
=> docs: Modal updated API and examples

docs/network.md, website/blog/2018-03-22-building-input-accessory-view-for-react-native.md
Replacing the occurrence of `facebook.github.io/react-native` with `reactnative.dev` to match the new domain.
=> chore: renew url

docs/appstate.md
Hi, I've added functional component examples with hooks for AppState API. #1579
=> updated example to use functional components and hooks

docs/view.md
Seemed like the right thing to do
=> Add class component example to View

website/static/img/homepage/cross-platform.svg
Replace .jsx with .js as RN doesn't support .jsx out of the box:
See https://github.com/facebook/react-native/pull/5296
=> React native doesn't support .jsx extension

docs/share.md
Here is an update for the #1579 regarding the Share component doc.
The class component already exists. I am adding a functional component example too as well as add the support for Snack player.
=> update Share doc with functional component example

docs/transforms.md
Contains the Snack Examples and some details for using Transform style properties. 
However, the skew property on Android isn't working, so I'll mark it as a pending item.
Pending items in this PR:
=> 🔷🔹 Transforms 🔸🔶 - Added Snack Examples ▫️◻️⬜️

docs/navigation.md
=> Fix typo in navigation doc

docs/props.md
i update examples props.md to functional component !!
=> Update examples props.md to functional components.

docs/actionsheetios.md
Refs #1579.
This PR adds simple Snack example to the ActionSheetIOS API page.
=> add Snack example for ActionSheetIOS

docs/height-and-width.md
@rachelnabors  i change this little example with functional component
=> Change width and height.md  example with functional component

docs/drawerlayoutandroid.md
Related to #1579 
Added Snack example with Hooks.
Updated API:
- drawerPosition has changed from taking Int32 to take 'left' or 'right'
- No other changes have been spotted on the API
=> Docs: DrawerLayoutAndroid

docs/animated.md, docs/animations.md, docs/panresponder.md
Contains New Function + Class Component examples for the
- Animated API
- PanResponder API
- Animations Guide
Willing to create more examples ﹣ if cool ideas are suggested 😎 💡 🤝
=> 💃🏽 Animated & PanResponder 👨🏽‍🎤 Snack Examples 👯‍♀️

docs/touchablewithoutfeedback.md
#1579
TouchableWithoutFeedback：
I changed  example code to use a Snack player.
=> TouchableWithoutFeedback: example code in a Snack player

.alexrc.js, docs/testing.md, website/i18n/en.json, website/sidebars.json
I'm putting up first version of testing guide for RN apps. Since it was written by just me (and @rachelnabors provided review and did some improvements and corrections) we'll need more people looking at this and providing feedback before it can be published.
This part of the testing doc is an introduction, more theoretical than practical and can be thought of as the RN counterpart of [react testing overview](https://reactjs.org/docs/testing.html). The plan is to add a more example-driven doc later, kinda like [react testing recipes](https://reactjs.org/docs/testing-recipes.html).
[preview here](https://deploy-preview-1469--react-native.netlify.com/docs/next/testing)
Thanks for your comments!
=> Add testing guide - introduction / overview

docs/profiling.md
This small PR fixes issue #1655 in the `next` docs.
=> fix link on the Profiling page

docs/typescript.md
=> Update Typescript init template name

docs/text-style-props.md
Issue: #1579
- Added Snack example
I tried to explore the most of properties possible =)
=> Text Style Props: add Snack Example

docs/usewindowdimensions.md
=> Fix typo in useWindowDimensions doc

docs/interactionmanager.md
In Reference to #1579
This PR adds Snack examples, function components and hooks for the InteractionManger API.
=> InteractionManager: Add Snack examples, function components and hooks

docs/clipboard.md
Updated url for the `clipboard` repo as it got renamed recently
=> docs: update url for clipboard repo

docs/style.md
this PR update example style.md @rachelnabors !
=> update example style.md with functional component

website/versioned_docs/version-0.5/more-resources.md
Updated the link **showcase** in **More Resource** section. 
fix for #1724
=> Update showcase link of More Resource

docs/permissionsandroid.md
#1579
Adding PermissionAndroid Snack Example.
=> Adding PermissionAndroid Snack Example.

docs/layoutanimation.md
Contains the snack with both functional & class component example for LayoutAnimations. Since LayoutAnimations have both inbuilt and custom config, this documentation requires two examples. One for inbuilt presets and another one for creating our own animation config. 
The following checklist tracks the completion of both examples
Previously - https://github.com/facebook/react-native-website/pull/1609
=> 🎶 LayoutAnimation 🕺🏽 - Added Snack Examples

docs/using-a-listview.md
@rachelnabors  i update this examples with functional components :)!!
=> update 2 examples usinglistview with functional components

docs/direct-manipulation.md
@rachelnabors  this PR changes 3 examples direct manipulation with functional components !!
=> change examples direct manipulation functional components

docs/virtualizedlist.md
=> VirtualizedList Props and Methods Update #1579
