facebook/react-native-website

- .circleci/config.yml
This PR adds increased `no_output_timeout` value to the CI `test` pipeline to prevent lately appearing timeouts:
> Too long with no output (exceeded 10m0s): context deadline exceeded
* https://app.circleci.com/pipelines/github/facebook/react-native-website/3540/workflows/a569353a-f917-4cdd-bb55-0466e5644bd7/jobs/16802
---
Refs: 
* https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-
> attempt to fix CI test pipeline job timeout

- .circleci/config.yml
Refs: #2483
This PR adds extended timeout also to the website deploy pipeline due to:
* https://app.circleci.com/pipelines/github/facebook/react-native-website/3548/workflows/a6678a87-4be6-4193-9915-106172f5e4c0/jobs/16834
> CI: add extended timeout to the website deploy

- docs/modal.md
- website/versioned_docs/version-0.63/modal.md
This PR updates the Modal component page to latest pattern, adds missing platform labels and missing defaults. 
Also both syntaxes examples, in base and latest versioned docs, have been simplified a bit.
> update modal page, add missing defaults, simplify examples

- docs/native-modules-intro.md
- website/versioned_docs/version-0.63/native-modules-intro.md
Since [Android Pay was rebranded into Google Pay since Jan, 2018](https://blog.google/products/google-pay/announcing-google-pay/), this doc also follow.
> Android Pay is now Google Pay

- website/src/css/customTheme.scss
- website/src/theme/BlogSidebar/index.js
- website/src/theme/BlogSidebar/styles.module.css
TL:DR - This PR adds the year headers/dividers to the Blog Sidebar, with aim to improve UX and break up the long list a bit (so it's not that "visual heavy").
Currently within Docusaurus V2, when using `"all"` as a blog post count setting value, there is not possible to define any kind of grouping using the build in options. Fortunately I was able to leverage the swizzle, which provides ability to customize component and hook up into additional blog sidebar items data. 
The implementation is very simple and it's based on the year extraction from permalink (because currently blog sidebar items do not include the post creation date), but since permalinks are generated by Docusaurus in specific pattern, this solution should be solid enough. (I'm not that happy with that, but it's the only …
> add year dividers to the blog posts sidebar

- docs/upgrading.md
- website/versioned_docs/version-0.63/upgrading.md
Looks like the "sluggification" of link anchors changed sometimes ago, so there might be other link anchor issues.
> docs: fix typo in link anchor

- docs/profiling.md
- website/versioned_docs/version-0.63/profiling.md
When clicking on systrace, it should internally route to `.../profiling#profiling-android-ui-performance-with-systrace` and not on `.../performance#profiling-android-ui-performance-with-systrace` which doesn't even exists.
> update link to profiling with systrace

- docs/text.md
This update in the documentation fixes a react-native issue, fixes https://github.com/facebook/react-native/issues/30326 
`ellipsizeMode="middle"` does not work when using `numberOfLines` higher then 1.
```javascript
<Text numberOfLines={2} ellipsizeMode="middle" >Some long text</Text>
```
It is a limitation from the Android Open Source Project `TextView` class
https://github.com/aosp-mirror/platform_frameworks_base/blob/523e3b9b7922685cff53d046884e0037004dcea7/core/java/android/widget/TextView.java#L10372-L10375
https://developer.android.com/reference/android/widget/TextView#setEllipsize(android.text.TextUtils.TruncateAt)
```java
* If {@link #setMaxLines} has been used to set two or more lines,
* only {@link android.text.TextUtils.TruncateAt#END} and
* {@link …
```
> fix react-native issue #30326 - Text numberOfLines={2} and other than ellipsizeMode="tail" breaks on Android

- docs/alert.md
- sync-api-docs/package.json
- website/docusaurus.config.js
- website/package.json
- website/src/css/customTheme.scss
- website/src/theme/DocItem/index.js
- website/versioned_docs/version-0.63/intro-react-native-components.md
- yarn.lock
Refs: #2523 
This PR updates the Docusaurus related packages to the latest version. It includes fixes and tweaks for the swizzled components, fix for a missing config filed warning and bump of few other dependencies like `alex` and `fs-extra`.
Invalidates: #2522 
As mentioned in the referenced PR, Docusaurus bump includes the `prismjs` update, so the Dependabot PR is no longer required:
* https://github.com/facebook/react-native-website/pull/2525/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR9184
> update Docusaurus to latest version

- README.md
- netlify.toml
- package.json
- website/core/PrismTheme.js
- website/package.json
- yarn.lock
This PR bumps the `glob-promise` package (also update the version of already bumped in the lock packages) and fixes few warning reported by `@manypkg/cli` check.
Additionally I have also cleaned up the `PrismTheme` comments, they were a legacy of the migration, most of them were outdated or incorrect anyway.
> small deps bumps, fix mankypkg CLI check warnings

- website/showcase.json
Add link to NerdWallet blog link: https://www.nerdwallet.com/blog/engineering/beyond-the-browser-how-nerdwallet-went-native/
> Add NerdWallet blog link

- docs/_getting-started-macos-android.md
- website/versioned_docs/version-0.63/_getting-started-macos-android.md
While trying to run Android on my mac, `react-native doctor` kept reporting it couldn't find the Android SDK. After a bit of Googling and cursing, I discovered installing the `Android SDK Command-line Tools` resolved this problem. I didn't see any mention in the documentation so figured I'd propose it to be added. Happy to put this in the troubleshooting section if that would be more appropriate.
> Include Android SDK Command-line Tools

- website/versioned_docs/version-0.63/linking.md
The note telling people to "link RCTLinking to your project" is out of date due to the introduction of [auto-linking](https://reactnative.dev/blog/2019/07/03/version-60#native-modules-are-now-autolinked) in React Native 0.60.
The note is quite confusing for users who are simply directed to [this](https://reactnative.dev/docs/linking-libraries-ios#manual-linking) article explaining how to link a now nonexistent `.xcodeproj` file to their main Xcode project.
[Step 3](https://reactnative.dev/docs/linking-libraries-ios#step-3) from the referenced article is still required as auto-linking will not add the header files for RCTLinkingManager (located in the LinkingIOS folder) into the header search paths. As such I have tweaked the wording of the note and updated the link to point to step 3.
> Update note about RCTLinking to account for the addition of auto-linking in 0.60

- docs/handling-text-input.md
- docs/handling-touches.md
- docs/style.md
fixes https://github.com/facebook/react-native/issues/29308 fixes https://github.com/facebook/react-native/issues/25441 fixes https://github.com/facebook/react-native/issues/28694 fixes https://github.com/facebook/react-native/issues/27333
Adding further notice in the docs to help developers troubleshoot the following issues:
- The touch area never extends past the parent view bounds 
Explanation https://github.com/facebook/react-native/issues/29308#issuecomment-792864162 
Related issues https://github.com/facebook/react-native/issues/29308 https://github.com/facebook/react-native/issues/27333
- Negative margin is not supported on Android
Explanation https://stackoverflow.com/a/10673572
Related issues https://github.com/facebook/react-native/issues/25441 …
> Add Clarification to Docs - Views are not clickable if parent has height of 0

- docs/height-and-width.md
- website/versioned_docs/version-0.63/height-and-width.md
As I learned here:
https://github.com/facebook/react-native/issues/30716
height and width render significantly differently on different screens, and that's to be expected.
> height and width are not the same on different screens

- website/docusaurus.config.js
It looks like shared blog post have the same metadata set as the home page:
The `metadatas` field has been moved from V1 and it might be possible that those entries are messing with Docusaurus logic. Official Docusaurus opted-out those tags, and their shared blog post are looking correct, let's try that.
> attempt to fix share metadata

- website/blog/2021-03-11-version-0.64.md
A couple of typos: Devtools -> DevTools, plus a case mismatch in the Inline Requires snippet.
> Fix typos in 0.64 blog post

- docs/introduction.md
- website/versioned_docs/version-0.64/introduction.md
In the getting-started page (introduction.md) the Tabs bar is not working properly -
when I click on web it opens ios, 
when I click on ios  it opens android
and when I click on android it opens web.
The problem seemed to be that the tabs weren't organized in the same order as the getDevNotesTabs array (which was the values for the Tabs element).
> fixed introduction md Tabs functionality

- docs/ram-bundles-inline-requires.md
- website/versioned_docs/version-0.64/ram-bundles-inline-requires.md
Devs in the community including myself are getting tripped up because it seems `export BUNDLE_COMMAND=ram-bundle` is merely *redundant* with Hermes enabled -- when in fact, it is incompatible.  To successfully build with Hermes, `ram-bundle` must NOT be specified as the bundle command.
e.g.: https://github.com/fastlane/fastlane/issues/17657#issuecomment-732764675
> Clarify note about Hermes + RAM Bundles

- docs/scrollview.md
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.60/scrollview.md
- website/versioned_docs/version-0.61/scrollview.md
- website/versioned_docs/version-0.62/scrollview.md
- website/versioned_docs/version-0.63/scrollview.md
- website/versioned_docs/version-0.64/scrollview.md
This PR removes props available only for VR platform, to avoid documentation users confusion. VR platform is not open source and it's used mainly by FB and other partners internally.
The changes are applied to `next` and all versioned docs. Additionally the styles for VR platform tag has been removed from SCSS.
> remove VR platform props from docs

- netlify.toml
- website/docusaurus.config.js
In this PR I'm attempting to speed up the Netlify preview deploys, but reducing the number of version which Docusaurus had to process during the build. Most of the PRs are targeted for the latest version docs or `next` ones, so publishing only `next` and two latest versions should speed up the preview deployment a bit (which currently is the longest running check from PR workflow).
The changes also includes the cleanup of `netlify.toml` file, so far the build command was copied 1:1 from the old Circle CI file and it looks like Netlify allow the configuration to be a bit more readable, so why not leverage that.
> attempt to speed up Netlify preview deploys

- website/docusaurus.config.js
Refs #2557
This PR include small tweak for Netlify preview deploys - now available versions are extracted programmatically from `versions.json`, so after new version cut the values will be updated.
> extract versions for deploy preview programmatically

- website/src/pages/index.js
- website/src/pages/showcase.js
- website/src/pages/versions.js
It looks like there were still few minor problems with share data of custom pages after update to the latest Docusaurus version.
This PR aim to solve all of them and to improve the included meta data for custom pages.
> improve share metadata after latest update

- docs/scrollview.md
The `ScrollView.scrollWithoutAnimationTo()` method was removed from the codebase a while ago in https://github.com/facebook/react-native/commit/c7e89909da70ac5290f9971080eb897567db3e43. This removes it from the documentation, too.
**Test Plan:**
Locally verified that the method is no longer documented by going to: http://localhost:3000/docs/next/scrollview#scrolltoend
> Remove ScrollView.scrollWithoutAnimationTo() documentation

- docs/accessibilityinfo.md
- docs/appearance.md
- docs/appstate.md
- docs/dimensions.md
- docs/keyboard.md
- docs/linking.md
The following listener removal methods are deprecated. This update the documentation to reflect this, and it update the example code to use the recommended event subscription `remove()` methods.
- `Appearance.removeChangeListener`
- `AccessibilityInfo.removeEventListener`
- `Appearance.removeChangeListener`
- `AppState.removeEventListener`
- `Dimensions.removeEventListener`
- `Keyboard.removeListener`
- `Linking.removeEventListener`
**Test Plan:**
Locally verified that the method is no longer documented by going to: http://localhost:3000/docs/next/scrollview#scrolltoend
> Deprecate `removeListener` APIs

- docs/ram-bundles-inline-requires.md
- website/versioned_docs/version-0.64/ram-bundles-inline-requires.md
> docs: fix minor typo

- docs/flatlist.md
- docs/refreshcontrol.md
- docs/virtualizedlist.md
React Native PR [30737](https://github.com/facebook/react-native/pull/30737) introduces iOS support for the `progressViewOffset` prop in `RefreshControl`, `FlatList`, and `VirtualizedList`.
This PR updates the documentation for those components to remove the `Android` specifier.
> Documentation Update for RN PR #30737 - Remove Android specifier for progressViewOffset prop.

- docs/accessibilityinfo.md
This PR adds documentation for the features implemented in https://github.com/facebook/react-native/pull/31063.
> feat: add `getRecommendedTimeoutMillis` section on accessibilityInfo

- docs/accessibility.md
Downloading from the Google Play Store is the best way to get access to TalkBack on emulators.
> Update TalkBack download info in accessibility.md

- docs/actionsheetios.md
- website/versioned_docs/version-0.64/actionsheetios.md
Mention that the `destructiveButtonIndex` option takes either a number or an array of numbers.
> Update the documentation of ActionSheetIOS

- docs/timers.md
- website/versioned_docs/version-0.64/timers.md
The link would lead to a "Page not found" as the content have been archived
Updated the link to point to the archive
Maybe this should be redacted or point to a more up to date example
As a momentary fix it would at least show the original content behind this link
> Fix broken mozilla.org link in timers.md

- docs/typescript.md
- website/versioned_docs/version-0.64/typescript.md
Refs #2593
The current example in TypeScript guide looks a bit outdated and will produce runtime error due to attempt of creation a negative length `Array`. The styling have some issues (overlapping `StatusBar` on iOS) and it was cramped a bit. Also the TS Playground URL was missing the `export`.
This PR refactors and updates the example in `next` and latest versioned docs (`0.64`) to fix all the issues mentioned above.
> update TypeScript guide example and TS Playground link

- docs/native-components-ios.md
`requireNativeComponent` has not accepted 3 arguments since React Native 0.56. The Android documentation was updated when that changed (https://github.com/facebook/react-native-website/pull/464), but iOS was missed.
Partially addresses #2588... the versioned docs should also be updated, but since the change would be identical I thought I'd just put up the one file for review first.
The use of comments to describe properties was based on https://reactnative.dev/docs/native-components-android... personally I use Typescript so I'm not sure if there's a standard pattern for that in pure JS.
> Update references to requireNativeComponent in iOS Native Components doc

- website/versioned_docs/version-0.60/native-components-ios.md
- website/versioned_docs/version-0.61/native-components-ios.md
- website/versioned_docs/version-0.62/native-components-ios.md
- website/versioned_docs/version-0.63/native-components-ios.md
- website/versioned_docs/version-0.64/native-components-ios.md
This is identical to #2589, but now applying the change to the versioned docs (because the corresponding code change was made prior to RN 0.60)
@Simek (since you reviewed the previous PR)
> Update references to requireNativeComponent in the versioned iOS Native Components docs

- docs/out-of-tree-platforms.md
The [Proton native](https://github.com/kusti8/proton-native) project was not actively maintained but had a reference, which is now pointing to a maintained fork of the project!
> Updating proton native project not maintained!

- website/blog/2021-05-20-GAAD-One-Year-Later.md
**To be released on May 20th**
This Pull request is for the one year anniversary of React Native taking the GAAD pledge to reflect on the progress made towards a more accessible React Native. 
All feedback is welcome!
> GAAD 1 year later blog post 5/20

- docs/direct-manipulation.md
I noticed that the docs suggest using `setNativeProps` when it's probably simpler to just call `.clear` on a `TextInput` ref.
> Update Direct Manipulation docs to mention TextInput's .clear()

- docs/usecolorscheme.md
- website/versioned_docs/version-0.64/usecolorscheme.md
I discovered this via [this Stack Overflow answer](https://stackoverflow.com/a/61124384/3098651) which points to [this `react-native` PR](https://github.com/facebook/react-native/commit/f7b90336be25b78935549aa140131d4d6d133f7b).
> Add a note about the chrome debugger causing useColorScheme to always return "light"

- website/package.json
- website/src/css/customTheme.scss
- website/src/css/index.scss
- yarn.lock
This PR updates the Docusuaurus to the latest release (`beta.0`), updates the SASS support and fixes the Algolia UI overwrites and other minor custom styles after the update.
> update Docusaurus to latest beta, fix SCSS, fix Algolia styles

- docs/text.md
> Fixed some minor typos

- docs/flexbox.md
It works on the sandbox but if you copy the code and run it you get an error.
'no-wrap'. Removed hyphen to be 'nowrap'.
> Fix/Value for flexWrap

- docs/dynamiccolorios.md
Update docs to support High Contrast colors, outlined in this PR: https://github.com/facebook/react-native/pull/31651
> support high contrast colors

- docs/images.md
This functionality was removed in https://github.com/facebook/metro/commit/7674ca076e03483a17a37c31481807e2b67dea29, released in [Metro 0.59.0](https://github.com/facebook/metro/releases/tag/v0.59.0) and eventually in RN 0.64. This was a poorly-communicated breaking change at the time and we might want to undo it, but for now the website should reflect what actually works.
Related:
https://github.com/facebook/react-native/issues/31099
https://github.com/facebook/react-native/issues/31348
https://github.com/facebook/metro/issues/676
> Images: Remove mention of platform-specific extensions

- docs/native-modules-android.md
- website/versioned_docs/version-0.64/native-modules-android.md
This is removing the unused and confusing failure callback in the example code. The text above the example is talking about the node callback convention with a single callback for success and error.
> Remove unused failureCallback in example

- docs/debugging.md
- website/versioned_docs/version-0.64/debugging.md
Updates the file referenced for enabling iOS remote debugging.
* `RCTWebSocketExecutor.m` has been changed from Objective-C to Objective-C++, thus renamed to `RCTWebSocketExecutor.mm`
* `RCTWebSocketExecutor.mm` has been moved from `Libraries/WebSocket/` to `React/CoreModules/`
> Update reference to file for iOS remote debugging

- docs/text-style-props.md
- website/versioned_docs/version-0.64/text-style-props.md
`react-native-web` does not support the deprecated `Slider` component causing the `TextStyleProps` example to fail with a React minified error upon loading the page.
As discussed here:
https://github.com/facebook/react-native-website/pull/2476#issuecomment-864892954
@Simek 
**before**
**after**
- Make example only available on `ios` and `android`
- See screenshot
- Ran `yarn prettier` to verify the file doesn't contain any styling issues
> Disable web-preview for TextStyleProps example

- website/src/theme/DocVersionSuggestions/index.js
Fixes #2665
This PR includes the fix for the versions banner issue introduced after upgrading Docusaurus to the latest version.
I had to swizzle the `DocVersionSuggestions` component and expand the initial bail check by adding `activeVersion.isLast`:
```ts
if (!latestVersionSuggestion || activeVersion.isLast) {
return <></>;
}
```
CC: @slorber
> fix for version banner in the latest docs

- docs/hermes.md
Notable changes (out of the three): 
- make the intro section slightly less platform-specific
- provide an example of creating a Release build for iOS using the `react-native` CLI
> Clarify some things in the Hermes section

- docs/imagebackground.md
- website/versioned_docs/version-0.64/imagebackground.md
Fixes #2664
Expo and RNW supports `resizeMode` in styles out-of-box and both approaches are fine, however on core platforms the only correct way to set resize mode currently is to use `resizeMode` prop instead of style.
The changset also includes few tweaks, like missing separators, or adjusted example UI. I have also backported all the changes to the latest versioned docs (for `0.64` release).
> update ImageBackground example

- website/src/pages/index.js
Simple update removing the undefined className in ScreenRect function.
> Removed undefined className

- docs/layout-props.md
`aspect-ratio` is now a CSS property with decent [support](https://caniuse.com/mdn-css_properties_aspect-ratio) and an [MDN link](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio). I haven't compared the implementation of `aspectRatio` in RN vs. `aspect-ratio` in the CSS spec in detail, so if they diverge we may want to just remove the comment about `aspect-ratio` being non-standard. Let me know and I can update my PR.
> Add MDN link for aspectRatio

- docs/out-of-tree-platforms.md
- website/versioned_docs/version-0.64/out-of-tree-platforms.md
I haven't worked/maintained react-native-dom for a year or two now and don't think it makes sense to direct people over to the project anymore. This commit removes it from the list.
> Remove react-native-dom from list of out-of-tree platforms

- netlify.toml
Refs #2686
This PR is an attempt to resolve the CORS error, while fetching the `movies.json` for the `Network` examples at:
* https://reactnative.dev/docs/network
> attempt to fix CORS issue with `movies.json` file

- docs/javascript-environment.md
- website/core/TableRowWithCodeBlock.js
- website/src/css/customTheme.scss
In light of https://github.com/facebook/metro/pull/681, I thought it fitting to update the list of syntax transforms so users know exactly what will work and what won't. Feel free to make any chages as you see fit, I wasn't sure where to put some things.
> Update Syntax Transforms list

- website/src/css/customTheme.scss
Refs #2676
This small PR adds `white-space: break-spaces;` property to the `code` block in `table`s, which allow the code block content wrapping, if there is not enough space in the page container to fit the line. This mostly applies for the mobile devices and in most cases should prevent the horizontal page overflow and horizontal scrollbars.
> allow wrapping code blocks content in tables

- docs/getting-started.md
- plugins/remark-snackplayer/README.md
- website/docusaurus.config.js
- website/snackPlayerInitializer.js
- website/versioned_docs/version-0.64/getting-started.md
Updates the Snack player and other Snack URLs to use the new `.dev` domain. *The old `.io` domain still works, but requires an additional redirect on the server.
- Update Snack url in docusaurus.config
- Update Snack urls
- `cd website && yarn start`
- Verified that the Snack player loads as expected
> Update Snack to .dev domain

- docs/network.md
This fixes a typo in [networking](https://reactnative.dev/docs/network) documentation.
> docs: typo correction

- docs/textinput.md
- website/versioned_docs/version-0.64/textinput.md
this PR add required labels for specific platform, little changes in style examples, and fix broken link.  additional useEffect  `autoFocus` property.
cc: @Simek
> website: add required labels TextInput 

- docs/navigation.md
As of React Navigation 6, we recommend using native-stack by default which will have better performance.
> Use native-stack for getting started with navigation

- website/src/pages/showcase.js
this PR fix link in showcase for React Native open source apps, something weird happen in dev works but in production still infinite red link home page!.
cc: @Simek
> chore: fix link in showcase

- docs/touchablehighlight.md
Unnecessary use of conditional expression for default assignment.
source: https://eslint.org/docs/rules/no-unneeded-ternary
> docs: removed unnecessary use of ternary

- docs/network.md
- website/versioned_docs/version-0.64/network.md
This PR contains documentation for the proposed changes in this PR https://github.com/facebook/react-native/pull/27701.
> Documentation about proposed RCTSetCustomNSURLSessionConfigurationProvider

- docs/button.md
- docs/text.md
Update Accessibility Documentation (#2679) 
Added _AccessibilityActions_ and _onAccessibilityAction_  props for [Button](https://reactnative.dev/docs/next/button) and [Text](https://reactnative.dev/docs/next/text) component.
> Added accessiblity documentation for Button and Text component

- docs/statusbarios.md
`StatusBarIOS` has been removed from core in  facebook/react-native#31466
> docs: update `StatusBarIOS` deprecation message

- website/docusaurus.config.js
- website/src/css/customTheme.scss
Refs #2727 
This PR fixes the announcement banner border issue, mostly visible in light theme. 
The changeset also includes tweaks the link hover effect and removes the example comments from the config file.
> fix survey banner border and link hover color

- docs/text.md
const bodyText = useState("This is not really a bird nest.");
This code for example throughs a warning "Functions are not valid as a React child..."
> fix warning: functions are not valid as ReactChild

- README.md
This PR aims to clarify how to run and lint the website locally. 
It looks like some of the part of Readme were not fully updated when repository was transformed to use Yarn workspaces. 🙂
> update Readme to clarify local running and linting

- website/blog/2021-08-30-react-native-is-hiring-managers.md
Adds a new blog post to the React Native website titled, "React Native Is Hiring Managers, To Expand Beyond Mobile".
**Test Plan:**
Verify formatting and lint cleanliness:
```
cd react-native-website/website
../node_modules/.bin/prettier -w blog/2021-08-26-many-platform-vision.md
node_modules/.bin/alex blog/2021-08-26-many-platform-vision.md
```
Follow [the Contributing instructions in README.md](https://github.com/facebook/react-native-website#-contributing) to test visually inspect the blog post locally.
> Add "React Native Is Hiring Managers" blog post

- CONTRIBUTING.md
- STYLEGUIDE.md
- website/src/pages/versions.js
- website/static/_redirects
This small PR fixes the external links and references using the old main branches name of React and React Native repositories.
> fix external links to React and React Native repositories

- docs/_integration-with-exisiting-apps-objc.md
- docs/_integration-with-exisiting-apps-swift.md
- website/versioned_docs/version-0.65/_integration-with-exisiting-apps-objc.md
- website/versioned_docs/version-0.65/_integration-with-exisiting-apps-swift.md
this PR remove section `See the Code` in ` _integration-with-exisiting-apps-objc.md`  this link repo has removed!.
reference #2746
> docs: remove "see the code" section in swift an objc examples

- website/blog/2021-08-26-many-platform-vision/index.md
- website/blog/2021-08-30-react-native-is-hiring-managers.md
- website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
- website/blog/authors.yml
Migrates recent blog posts to use `authors.yml` and update **React Native's Many Platform Vision** to include all of the originally intended authors. (The post was created before multiple authors were supported by Docusaurus.)
> Migrate recent blog posts to `authors.yml`

- docs/troubleshooting.md
- Changed the path to use latest file and folder structure as per react-native@0.65.1
> Update iOS path to use a different port

- docs/linking.md
The type definition of sendIntent is quite confusing on first glance. Properties as well as possible types of value are separated by comma. Using this notation should be clearer!
> Clearify type definition of sendIntent parameter

- docs/out-of-tree-platforms.md
- website/versioned_docs/version-0.64/out-of-tree-platforms.md
- website/versioned_docs/version-0.65/out-of-tree-platforms.md
Refs https://github.com/facebook/react-native-website/pull/2684#issuecomment-900275456
This PR updates the current Out-of-tree platforms list and includes the following changes:
* `react-native-web` added to the list
* `react-native-tvos` description updated to signify Android TV support
* remove `react-native-desktop` hence it's no longer maintained
* `react-native-turbolinks` is more similar to library than separate platform, so I have removed it from the list, ~~I will add it to the RN Directory later~~ **(EDIT: it has been added already)**
I'm not sure if the list division to Partners and Community is a good idea, can revert this part back, if requested.
CC @douglowder @necolas For the check on the entries description 🙂
> update out-of-tree platforms list

- docs/button.md
- docs/image.md
- docs/linking.md
- docs/pressable.md
- docs/text.md
- docs/textinput.md
- docs/touchablewithoutfeedback.md
- docs/view.md
- website/versioned_docs/version-0.65/button.md
- website/versioned_docs/version-0.65/image.md
- website/versioned_docs/version-0.65/pressable.md
- website/versioned_docs/version-0.65/text.md
- website/versioned_docs/version-0.65/textinput.md
- website/versioned_docs/version-0.65/touchablewithoutfeedback.md
- website/versioned_docs/version-0.65/view.md
Fixes #2769
This PR is mostly inspired by the issue report, besides fixing the regression introduced by extracting shared types to the separate pages it also clean up those types on other pages and ensures that type definitions using shared types are formatted in the same way everywhere.
I have also made a small tweaks to the few other event types and removed the redundant with new design "Required" column form the `Pressable` page.
The changes also have been backported to the `0.65` docs.
The changes has been tested by running website on `localhost`. 
Also `yarn lint` and `yarn lint:versioned` checks did not output any warnings or errors.
> fix and generalize shared event types definitions

- website/blog/2021-08-17-version-065.md
- website/blog/2021-08-19-h2-2021.md
- website/blog/2021-08-26-many-platform-vision/index.md
- website/blog/2021-08-30-react-native-is-hiring-managers.md
- website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
Docusaurus parses the date of a blog post from the filename and not the `date` field. This removes the `date` fields from existing blog posts that have it, and it fixes the filename of the "Announcing React Native 0.65" blog post.
The last point will fix the bug report tweeted here: https://twitter.com/madebyjonny/status/1435605294164414477
> Remove blog date fields and fix filename discrepancy

- package.json
- yarn.lock
Addresses this vulnerability:
- https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
The `trim` breaking change at 1.0.0 was a license change:
- https://github.com/Trott/trim/blob/main/CHANGELOG.md
> Force `trim@^1.0.1` resolution

- docs/linking.md
On Android 11 in order for `Linking.canOpenUrl` to return `true` the scheme/intent must be specified in AndroidManifest.xml and queryable. This is not currently clear in the documentation even though specific instructions are given for iOS.
> Add help relating to Android intent queries

- docs/native-components-android.md
As a Javascript / React-Native developer I had a hard time figuring out how to integrate a custom native SDK with React Native using Android Fragments. Please correct anything that you wish. This information took me 3 days to figure out, especially the part with `setupLayout` and `manuallyLayoutChildren` so I wish an example like this was available in the official documentation. And I think I am not alone. I was expecting the code without `setupLayout` and `manuallyLayoutChildren` to work but i had no luck. If somebody has any better solution in your team, or any explanation, it would also be really nice to state in the documentation. Thank you for React Native, I love it.
> docs: add fragment to native-components-android.md

- website/docusaurus.config.js
When you click on it, it says the survey is already closed.
> Remove the link to 2021 React Community Survey

- package.json
- website/package.json
- yarn.lock
As the title says, I'm adding an explicit dependency on `ansi-regex@^5.0.1`
> Bump ansi-regex to ^5.0.1 to fix CVE-2021-3807

- website/blog/2018-01-18-implementing-twitters-app-loading-animation-in-react-native.md
- website/blog/2018-08-27-wkwebview.md
- website/docusaurus.config.js
This PR fixes the errors at end of deploy preview build, which were related to couple of links in the older blog posts.
For now it should be fine to just replace the links with absolute URLs, but in a long term, it would be nice to have the option for the blogpost (similar to docs `onlyIncludeVersions` field), which should not include older posts than decaled date or time span, which should fix the issue in a long term. CC @slorber
> fix preview deploy failure due to links in older blog posts

- docs/scrollview.md
- website/versioned_docs/version-0.65/scrollview.md
- website/versioned_docs/version-0.66/scrollview.md
Added an entry for the `ScrollView` option` stickyHeaderHiddenOnScroll `to the documentation.
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#added-1
> add section of `stickyHeaderHiddenOnScroll` option

- website/blog/2018-05-07-using-typescript-with-react-native.md
Hello 👋 Since I wrote this blog post, the init command to start a new React Native project with TypeScript was updated. I updated the command already in #690, but it's been changed again. This blog post is the number two Google result for "create react native app typescript" so I think it's worth keeping the command up-to-date. Thanks!
> Updates RN TypeScript project init command on blog post

- docs/permissionsandroid.md
I did end up auditing the codebase and finding a few missing permissions. So I opened up a PR upstream in RN - https://github.com/facebook/react-native/commit/4b25a0aaa077caf9c437bcfeef8a226eda5a102e and it was merged today.
So this is pointed to the next documentation release. This adds:
https://developer.android.com/reference/android/Manifest.permission.html#ACCEPT_HANDOVER - 28
https://developer.android.com/reference/android/Manifest.permission.html#ACTIVITY_RECOGNITION - 29
https://developer.android.com/reference/android/Manifest.permission.html#ANSWER_PHONE_CALLS - 26
https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_NUMBERS - 26
https://developer.android.com/reference/android/Manifest.permission.html#UWB_RANGING - 31
---
Would you accept a PR to …
> feat: add next RN permissions (android)

- docs/native-components-android.md
This commit updates the documentation of Android native components with Fragments as it was incomplete as pointed out in #2838.
- adds an example for CustomView to make it more understandable
- remove `.getParent()` because it was incorrectly left in by me last time
- add an example of how to make width/height come from props, as I think people will use it like this most of the time
- add an example with PixelRatio.getPixelSizeForLayoutSize(200) as I think people will use it like this most of the time
> docs: update native components android fragments

- website/blog/2019-09-18-version-0.61.md
- website/blog/2020-03-26-version-0.62.md
- website/blog/2020-07-06-version-0.63.md
- website/blog/2021-03-12-version-0.64.md
- website/blog/2021-08-17-version-065.md
- website/blog/2021-10-01-version-066.md
- website/versioned_docs/version-0.65/roottag.md
- website/versioned_docs/version-0.66/roottag.md
This PR updates all the remaining Changelog file links on the website (mostly in blog posts), so now they leads to the core repository instead of deprecated/archived RNC repository.
> update changelog links after RNC deprecation

- docs/scrollview.md
Looks like duration prop isn't available anymore for ScrollView.scrollToEnd.
https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/Libraries/Components/ScrollView/ScrollViewCommands.js#L28-L31
According to this comment it was deleted at some point.
https://github.com/facebook/react-native/issues/25589#issuecomment-510488031
> Remove doc reference to duration in scrollToEnd

- docs/sectionlist.md
Update props inheritance
Props of SectionList are inherits from VirtualizedSectionList -> VirtualizedList -> ScrollView.
Since VirtualizedSectionList isn't documented on website, IMO, SectionList should declare its props is inherited from VirtualizedList at least.
> Update props of SectionList to declare inheritance from VirtualizedList explicitly

- docs/virtualizedlist.md
- website/versioned_docs/version-0.60/flatlist.md
- website/versioned_docs/version-0.60/listview.md
- website/versioned_docs/version-0.60/scrollview.md
- website/versioned_docs/version-0.60/virtualizedlist.md
- website/versioned_docs/version-0.61/flatlist.md
- website/versioned_docs/version-0.61/listview.md
- website/versioned_docs/version-0.61/scrollview.md
- website/versioned_docs/version-0.61/virtualizedlist.md
- website/versioned_docs/version-0.62/flatlist.md
- website/versioned_docs/version-0.62/listview.md
- website/versioned_docs/version-0.62/scrollview.md
- website/versioned_docs/version-0.62/virtualizedlist.md
- website/versioned_docs/version-0.63/flatlist.md
- website/versioned_docs/version-0.63/listview.md
- website/versioned_docs/version-0.63/scrollview.md
- website/versioned_docs/version-0.63/virtualizedlist.md
- website/versioned_docs/version-0.64/flatlist.md
- website/versioned_docs/version-0.64/scrollview.md
- website/versioned_docs/version-0.64/virtualizedlist.md
- website/versioned_docs/version-0.65/scrollview.md
- website/versioned_docs/version-0.65/virtualizedlist.md
- website/versioned_docs/version-0.66/flatlist.md
- website/versioned_docs/version-0.66/scrollview.md
- website/versioned_docs/version-0.66/virtualizedlist.md
Follow up to #2857 
This PR fixes the invalid `duration` key description for the `ScrollList` and attempts to generalize the description and documentation of all `scrollToEnd` props available in the `*List` components.
In the future, we should also take a deeper look into the the exact exported types per component/list, since usually we do not duplicate the props description if that prop comes from parent/extended component. In case of `scrollToEnd`, it might be only a `VitualizedList` prop, but for now it was more important to remove invalid information to avoid users confusion. 🙂 
I have also removed few in-content ToC's on the deperecated `ListView` pages, since they are the relict of the past, when website do not use the build-in ToC (right sidebar). Somehow this list survived the …
> update and generalize all of the `scrollToEnd` prop descriptions

- docs/_getting-started-windows-android.md
What:
Updated React Native CLI Quickstart/Windows-Android docs to use the LTS version of node during choco install, and recommended use of LTS in general, similarly to how React docs do the same.
Why:
_getting-started-windows-android.md currently lists the choco install command as:
```choco install -y nodejs.install openjdk8```
...which will install node.js version 17 (current)
While you will still be able to init an app with the react-native CLI and node.js 17, the command ```npx react-native run-android``` **_will fail_** due to the same bug affecting [facebook/create-react-app#11562](https://github.com/facebook/create-react-app/issues/11562)
> win/android docs: update node install to use nodejs-lts

- docs/native-components-android.md
- website/versioned_docs/version-0.66/native-components-android.md
This PR aims to improve a bit the readability of [Android Native Components](https://reactnative.dev/docs/next/native-components-android) page.
There are basically two changes, the first improves the Table of Content by adjusting the used header sizes. 
The second one refactors comments with file names to the `title` parameter for the Docusaurus code block, which will appear above the code. It was used on the website in the past but very sparsely.
I have also reformatted example codes in few places, so they better fit the website default content width.
The changes have also been backported to the `0.66` docs, which was the only version (besides `next` where Fragments example was present).
> improve ToC and readability of Android Native Components

- docs/animations.md
- website/versioned_docs/version-0.66/animations.md
There's an incorrect link in animations.md for `AnimatedGratuitousApp` example. I'm opening this proposal to bring this to your attention. I can't find the example file in the Animated folder anymore, therefore I don't know what should I replace this link with.
> Updated missing link in animations.md

- docs/appstate.md
There was no description of the return value from `addEventListener()`.
There currently does not seem to be documentation for [EventSubscription](https://github.com/facebook/react-native/blob/00bb2ba62d86477884484aad0cd72d3627d5f221/Libraries/vendor/emitter/EventSubscription.js#L17), which I would link to from this page if such a doc page existed.
> Add "return" details for addEventListener()

- docs/view-flattening.md
Formatting for view-flattening
> Formatting for view-flattening

- docs/render-pipeline.md
Formatting and re-structuring for render-pipeline.md
I also removed the bottom most paragraph in Fabric State Update section. I thought it was redundant and uninformative.
> Format render-pipeline.md

- docs/fabric-renderer.md
> Format fabric-renderer.md

- website/src/css/customTheme.scss
Refs: #2882
So far we were not using non-linkable grouping in the sidebar (`collapsible: false`), but this feature could be leverage for the The New Architecture guide and future website content. This also enables us to rethink the current sidebar organization, which also can benefit for those non-linkable sections.
At this moment titles of the groups looks like the regular entry, which might confuse the users, This PR adds the proper styling for those sidebar headers and also fixes the missing indentation and unintended font size overwrite at the sidebar top-level after one of the latest Docusaurs updates.
> You can only see the indent and font size changes in here. If you want to see the non-linkable check out the preview in #2882.
> add styles for non-linkable sidebar entries

- docs/animations.md
useEffect is already imported as itself.
> Remove unnecessary keyword

- docs/architecture-glossary.md
- docs/fabric-renderer.md
- docs/render-pipeline.md
- docs/view-flattening.md
- docs/xplat-implementation.md
- website/sidebars.json
- website/versioned_docs/version-0.66/architecture-glossary.md
- website/versioned_docs/version-0.66/fabric-renderer.md
- website/versioned_docs/version-0.66/render-pipeline.md
- website/versioned_docs/version-0.66/view-flattening.md
- website/versioned_docs/version-0.66/xplat-implementation.md
- website/versioned_sidebars/version-0.66-sidebars.json
The following PR introduces the following changes to the Architecture:
* rename of Architecture Glossary page to `architecture-glossary` instead of just `glossary` (this matches the convection introduced by `architecutre-overview` and there might be a second "glossary"/"appendix" when the new architecture Playbook will land). Ideally we should start to group the docs files into subfolders (v1 doesn't support this afaik, but it should not be a problem in v2.
* update the Architecture sidebar, so it structure matches the other top-level pages on the website (flipped `collapsible`)
* reorder platforms in one of the sentence to alphabetical order.
> architecture section small tweaks

- docs/actionsheetios.md
Reference https://github.com/facebook/react-native/pull/31972
This prop was missing in docs
> feat: add cancelButtonTintColor props in ActionSheetIOS for change cancel tint color

- website/docusaurus.config.js
- website/package.json
- website/src/css/customTheme.scss
- website/src/theme/BlogSidebar/index.js
- yarn.lock
This PR updates the Docusaurus to the latest available beta. 
The changeset also include the following fixes:
* fix layout overflow and misplaced ToC on certain viewport widths (however table overflow is still an issue, but it doesn't break page layout anymore)
* fix mobile sidebar menu styling (font colors and sizing, element background colors etc.)
* fix blog sidebar padding on certain viewports
* fix the styling of blog tags and "Read More" buttons after update
* fix for the duplicate chevrons in the next/prev buttons in blog
* fix link style overwrite in new annotation blocks
* fix missing `key` warning in the swizzled BlogSidebar
* slightly improve the main Navbar overflow issues on certain viewport sizes (collapse quicker search bar, tweak the element padding and size)
The changes …
> update Docusaurus, fix layout issues, fix warnings

- README.md
While starting the server , I found 'docusaurus' is not recognized as an internal or external command, operable program or batch file .  It took me some time to find the solution and found this command on stackoverflow. If included here, the command might help the user in dealing with such problems and it will save the user's time.
> Adding a command

- docs/modal.md
[here](https://github.com/facebook/react-native/blob/main/Libraries/Modal/Modal.js#L61) we can see that Modal inherits view props, so I'm adding this information to docs
> docs: adds `View props` to props section of Modal

- docs/new-architecture-app-intro.md
- docs/new-architecture-app-modules-android.md
- docs/new-architecture-app-modules-ios.md
- docs/new-architecture-app-renderer-android.md
- docs/new-architecture-app-renderer-ios.md
- docs/new-architecture-appendix.md
- docs/new-architecture-library-android.md
- docs/new-architecture-library-intro.md
- docs/new-architecture-library-ios.md
- website/src/css/customTheme.scss
This PR aims to improve the code block readability (code block on the website are quite narrow, so it bets to wrap the code around ~65-70 chars per line to avoid horizontal scrolling if possible) and correctness in the new Architecture playbook pages. 
Mainly whitespace and formatting has been changed, however there are few other changes, like sections rework in libraries intro.
I have also tried to add support for the Flow syntax highlight, but it might require some changes or update of Prism library in the Docusaurus to work as intended. Currently the Flow code is unhighlighted, and when flow is listed in additional supported languages in config the website fail to start (due to missing file for Flow highlight definition). 
It also looks like the TypeScript highlight works a bit better …
> new-arch code formatting and small tweaks

- website/docusaurus.config.js
- website/package.json
- yarn.lock
This PR aims to improve the build and deploy speed by switching the Webpack loader to the `esbuild-loader`.
This do not yield same effects as fully switching to full ESBuild pipeline, but should shorten the build times a bit.
I have also added Flow to the additional supported languages by Prism, since the new architecture playbook included few  examples written in Flow and we were using TS rules so far to highlight those code blocks.
> switch to esbuild-loader, add Flow highlight support

- docs/new-architecture-library-intro.md
Small changes to the playbooks to make JS examples clearer.
> Use descriptive component names and fix use of ref

- website/blog/2022-01-19-version-067.md
- website/blog/authors.yml
This PR does add the 0.67 blogpost along with a couple things in the author.yml file :)
(as a temporary potential date I've put this Wednesday, we can tweak accordingly to when it will actually happen)
It will have to be merged along with: https://github.com/facebook/react-native-website/pull/2926
> blogpost for 0.67

- website/blog/2022-01-21-react-native-h2-2021-recap.md
- website/blog/authors.yml
> blogpost: React Native - H2 2021 Recap

- website/blog/2022-01-21-react-native-h2-2021-recap.md
The post was written in Dec and posted in Jan, so this wording needs to be updated.
> Fix typo in H2 blog post: next year -> this year

- website/versioned_docs/version-0.67/running-on-device.md
this PR remove text, fix this issue #2941
> docs: remove text running-on-device

- docs/using-a-scrollview.md
> Fix small grammatical error

- docs/_getting-started-macos-android.md
[The previous Brew installation command for adoptOpenJDK is now deprecated.](https://github.com/AdoptOpenJDK/homebrew-openjdk/tree/f6e8c971c98f5ba48aedf2a5d218ebc914ee2304)
Followed the documentation and change the method to install Temurin.
> Fix the guide to the deprecated OpenJDK installation command.

- docs/optimizing-flatlist-configuration.md
A minor update to the docs addressing the issue : https://github.com/facebook/react-native-website/issues/2880
> Add function based components example for Flat list optimisation

- docs/render-pipeline.md
Change to singular, _a React Element **Tree**_ (without "s").
> Update typo in render-pipeline.md

- docs/tutorial.md
I'm not sure we 'find' a function! 'Define' sounds more like what we're aiming for!
> Update typo in tutorial.md

- docs/typescript.md
Add troubleshooting guide for react native typescript
> Add an extra command to the troubleshooting guide for react-native-typescript

- docs/image.md
The [onLoad](https://reactnative.dev/docs/next/image#onload) event documentation is not correct, here is the sample:
```js
const onLoad = ({width, height, uri}) = {}
```
```js
const onLoad = ({nativeEvent: {source: {width, height, uri}}}) = {}
```
It was missing `nativeEvent` and `source` property. If you look at [onLayout](https://reactnative.dev/docs/next/image#onlayout) it has the `nativeEvent` property as well.
> (Image) Fix documentation for onLoad event.

- docs/linking.md
AndroidManifext.xml should be AndroidManifest.xml
> Fixed a typo in Linking page.

- docs/new-architecture-app-renderer-ios.md
Following the current instructions verbatim, I'm getting the following errors:
```
[!] [Codegen] Error: app_path is required for use_react_native_codegen_discovery.
[!] [Codegen] If you are calling use_react_native_codegen_discovery! in your Podfile, please remove the call and pass `app_path` and/or `config_file_dir` to `use_react_native!`.
```
Reading through `react_native_pods.rb`, I think it should be enough to set `RCT_NEW_ARCH_ENABLED=1`, and pass `app_path` to `use_react_native`. The entire `if use_codegen_discovery` block is unnecessary. `use_react_native_codegen_discovery` gets called by `use_react_native!`.
Further, it would be great if we can drop `RCT_NEW_ARCH_ENABLED` and instead use the value of `fabric_enabled` to determine whether to enable codegen etc. But I suppose that's …
> fix(ios): update Fabric in Podfile instructions

- docs/_getting-started-macos-ios.md
- docs/_integration-with-exisiting-apps-objc.md
- docs/_integration-with-exisiting-apps-swift.md
- docs/_markdown-m1-cocoapods.mdx
- docs/hermes.md
- docs/libraries.md
- docs/navigation.md
- docs/new-architecture-app-renderer-ios.md
- docs/new-architecture-library-intro.md
- docs/new-architecture-library-ios.md
- docs/new-architecture-troubleshooting.md
- docs/troubleshooting.md
Add notes to help Mac M1 users troubleshoot common problems with Cocoapods.
> 📚 Add instruction for M1 users to work with Cocoapods

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.65/_getting-started-linux-android.md
- website/versioned_docs/version-0.65/_getting-started-macos-android.md
- website/versioned_docs/version-0.65/_getting-started-windows-android.md
- website/versioned_docs/version-0.66/_getting-started-linux-android.md
- website/versioned_docs/version-0.66/_getting-started-macos-android.md
- website/versioned_docs/version-0.66/_getting-started-windows-android.md
- website/versioned_docs/version-0.67/_getting-started-linux-android.md
- website/versioned_docs/version-0.67/_getting-started-macos-android.md
- website/versioned_docs/version-0.67/_getting-started-windows-android.md
Resolve #2738
As of React Native [v0.65.0](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0650), the [default Android SDK version has been upgraded to 30](https://github.com/facebook/react-native/commit/c7efd5b369aa7605a1017791440735ab72bc9fa8). I think it's necessary to update the documentation to reflect the changes.
The changes have been backported to all applicable versions (0.65, 0.66, 0.67 and current).
> Update Android SDK version to 30

- website/src/css/_shared.scss
- website/src/css/customTheme.scss
This fixes a color contrast issue with a handful of links throughout the React Native website. These links were previously rendering as `--ifm-color-primary` (#06bcee) on white, which is a contrast ratio of only 2.22:1, failing all WCAG criteria. 
https://webaim.org/resources/contrastchecker/?fcolor=06BCEE&bcolor=FFFFFF
This PR changes the link color to be #357da1, which changes the color contrast to 4.56: 1, passing WCAG AA criteria.
https://webaim.org/resources/contrastchecker/?fcolor=357DA1&bcolor=FFFFFF
This change is only made when in light mode, since in dark mode, the original color against black has good contrast (9.43:1), and the new one is lower contrast (4.59:1).
Screenshots of all the affected UI in light mode, dark mode, and when hovered are below.
Dark Mode version menu …
> Updated link colors to meet WCAG color contrast guidelines.

- docs/new-architecture-app-modules-android.md
- This PR fixes the spelling of TurboMudule to TurboModule.
> fix: spelling error mudule -> module

- docs/_markdown-new-architecture-warning.mdx
- docs/new-architecture-app-intro.md
- docs/new-architecture-app-modules-android.md
- docs/new-architecture-app-modules-ios.md
- docs/new-architecture-app-renderer-android.md
- docs/new-architecture-app-renderer-ios.md
- docs/new-architecture-appendix.md
- docs/new-architecture-intro.md
- docs/new-architecture-library-android.md
- docs/new-architecture-library-intro.md
- docs/new-architecture-library-ios.md
- docs/new-architecture-troubleshooting.md
I've update all the warning banners to point to this discussion in the working group:
- https://github.com/reactwg/react-native-new-architecture/discussions/8
> Update migration guide feedback link to the working group

- docs/render-pipeline.md
- website/versioned_docs/version-0.66/render-pipeline.md
- website/versioned_docs/version-0.67/render-pipeline.md
Adding some sections to the 'Render, Commit, and Mount' page as it makes clearer to follow.
> Add TOC sections for the 'Render, Commit, and Mount' page

- website/src/css/customTheme.scss
Currently, when viewing some of the pages, the website main container is resized a bit, which result in unnecessary layout shift when changing pages.
After the investigation it looks like the wide code blocks (with horizontal scrollbar) are the culprit in there. Unfortunately I was not able to fix an easy solution, padding and width seems to be set to the correct values, so I had to change the code block content display property, which do not affect to actual display of code blocks, but prevent the block from resizing the container. :man_shrugging:
> fix layout resizing when page includes wide code block

- docs/render-pipeline.md
- website/versioned_docs/version-0.66/render-pipeline.md
- website/versioned_docs/version-0.67/render-pipeline.md
From https://github.com/reactwg/react-native-new-architecture/discussions/1#discussioncomment-2276764
> Fix deeplink to react-host-components-or-host-components in Glossary

- website/siteConfig.js
Migrate Algolia account on archived Docusaurus v1 site: https://archive.reactnative.dev
See also https://v1.docusaurus.io/blog/2021/11/05/algolia-migration
---
@Simek I invited you to a react-native-archive project on the DocSearch dashboard. Let me know if I should invite anyone else at Meta.
v1 site search is still working (readonly), but @shortcuts still recommend to migrate because some day that readonly index might be deleted
---
Preview: https://deploy-preview-2990--react-native-archive.netlify.app/
> Migrate Algolia DocSearch account

- docs/text.md
- website/versioned_docs/version-0.67/text.md
This PR changes the documentation of the android_hyphenation property to the new changes of version 0.67.3 as stated in this changelog: 
https://github.com/facebook/react-native/blob/main/CHANGELOG.md#android-specific-3
This PR corresponds to the following issue:
https://github.com/facebook/react-native/issues/33104
> changed android_hyphenation to version 0.67.3

- docs/text.md
- website/versioned_docs/version-0.64/text.md
- website/versioned_docs/version-0.65/text.md
- website/versioned_docs/version-0.66/text.md
- website/versioned_docs/version-0.67/text.md
Added the normal enum to all docs where android_hyphenationFrequency was used. 
As asked in [2982](../2982)
> Hyphenation normal enum

- docs/render-pipeline.md
- website/versioned_docs/version-0.67/render-pipeline.md
This PR adds the phases headers to the New Architecture Render Pipeline page. This change has been suggested in the work group discussion thread.
The changes have also been backported to the `0.67` docs. Additionally I have removed the in-content ToC from the page, since we have the automatic ToC on the right we tend to remove the ToCs from the content, because it's a bit time consuming to keep the links up to date in a long term.
> add ToC headers for phases on Render Pipeline page

- docs/new-architecture-library-android.md
I've updated the docs as they were a bit out of date for the codegen.
Reference of the various keys is also here:
https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt
> Clarify the Configure Codegen in your Gradle File section

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
Changes in two parts. For both Linux and MacOS getting started guides:
* From version 4 of command line tools the path to binaries was updated to `/cmdline-tools/latest/bin` with the previous being deprecated. 
* The name of the path environment variable has been updated to `ANDROID_SDK_ROOT` (https://developer.android.com/studio/command-line/variables#:~:text=ANDROID_HOME%2C%20which%20also%20points%20to%20the%20SDK%20installation%20directory%2C%20is%20deprecated.)
This PR updates the paths for both docs and replaces instances `ANDROID_HOME` with the updated `ANDROID_SDK_ROOT`.
NOTE: there are instances of ANDROID_HOME within the windows getting started guide but as they are backed up with images also utilising this name that I am unable to replace then have opted to leave that guide as …
> refactor(getting-started): path to sdk binaries

- docs/new-architecture-app-renderer-ios.md
This pr replaces a couple of hardcoded strings with a placeholder that the user must fill in Xcode.
Before that, the user must remember to update those strings manually. By using Xcode placeholders, the compiler will ask the user to change them.
> 📚Use placeholders instead of hardcoded strings

- docs/new-architecture-library-intro.md
This PR fixes a code snippet adding the right annotation for [`Flow`](https://flow.org/) and fixing a definition of a method.
> 📚Use @flow annotation and fix syntax

- docs/new-architecture-library-intro.md
This PR improve the documentation about creating specs in JS for the new architecture.
* It specifies that the Turbomodules spec file must be named `Native<MODULE NAME>.js`
* It adds a paragraph on how to write a Spec for a fabric component
* It specifies that a Fabric Component spec file must be named `<MODULE NAME>NativeComponent.js`
* It adds an example for a Fabric Component spec.
> 📚Improve documentation about JS Specs

- docs/new-architecture-library-ios.md
This PR replaces the dependency from `React` with the one from `React-Core` in a code snippet.
> 📚 Use more specific dependency React-Core

- docs/new-architecture-app-renderer-ios.md
This PR fixes a typo in a code snippet.
The react-native template generates an AppDelegate which declares a variable named `bridge` but the snippet uses the name `_bridge` to refer to the same variable.
> 📚Rename _bridge into bridge

- docs/new-architecture-app-renderer-ios.md
This PR updates a code snippet to use empty dictionaries instead of `nil` values.  Despite the code work in both ways, an empty dictionary is a safer and more future-proof approach.
> 📚 Use empty dicts instead of nil

- docs/new-architecture-app-modules-ios.md
This PR fixes a concrete type in a code snippet.
The snippet as it was written does not compile because, in order to use the  `JSCExecutorFactory`, we need to also import the related header. We added this detail in a comment in the code.
The snippet has been updated with the `HermesExecutorFactory`: the related header is already imported in the guide and this makes Hermes the default executor.
> 📚 Rename JSCExecutorFactory into HermesExecutorFactory

- docs/new-architecture-library-intro.md
The codegenNativeCommands section has incorrect example
Here you can find a working example:
https://github.com/callstack/react-native-pager-view/pull/534/commits/9f46b8fddb300a28e73e2a5eee6dbb6ef946bab0
> fix codegenNativeCommands section example

- sync-api-docs/generateMarkdown.js
- sync-api-docs/propFormatter.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- docs/integration-with-android-fragment.md
- website/core/TabsConstants.js
- website/versioned_docs/version-0.67/integration-with-android-fragment.md
This PR updates the "[https://reactnative.dev/docs/integration-with-android-fragment](Integration with an Android Fragment)" documentation to display Kotlin and java code samples
This is the first step on the effort to display Kotlin code in RN OSS documentation
> Add kotlin sample code in "Integration with an Android Fragment" documentation

- website/src/css/customTheme.scss
This PR fixes small display issues which emerges after latest Docusaurus upgrades. The list includes:
* removed broken and unnecessary shadow for the code block container (mostly visible in light theme)
* fixed uneven padding for the blog container on mobile
* reduced the spacing between blog post on the posts list (it was set to `5rem`, which is a bit too much, especially on mobile devices)
> small custom CSS fixes and tweaks

- docs/integration-with-android-fragment.md
- website/versioned_docs/version-0.67/integration-with-android-fragment.md
Just noticed that we had references to Java and `.java` files in the body of the text. I'm updating them.
> Update references from Java to Java/Kotlin in the body of the article

- README.md
The update of the project structure in the Readme file has been request by @kelset here:
* https://github.com/facebook/react-native-website/pull/3000#issuecomment-1064201720
I have updated the project structure to match latest changes and I have switched a bit the way in witch the structure is displayed, removing the example files and replacing them with more generic descriptions which I hope clarify the placement of files a bit more.
I have also updated the paragraphs around the graph so they refer to the updated structure, however I feel like those parts can be phrased a bit more clearly, but I have tried my best as a non-native speaker. 😉
> update project structure in Readme file

- website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Since latest changes to the docs structure and introducing multiple docs instances part of the website is versioned, and part of the website is static.
Due to those changes I feel like the `VersionDropdown` adds a bit of unnecessary confusion, so I have decided to swizzle it and propose a change that hides the version selector from all of the non-versioned pages. The selector is only visible when viewing the pages from `Guides`, `APIs` and `Components`. This might not be in line with other Docususaurus sites, but I feel like it's a better UX in our case.
I have decided to swizzle because AFAIK Docusuaurs do not offer a configs for the changes I would like to achieve. 
The code I have added has been annotated with comment starting with `(CUSTOM)`, so we can identify the part we edited …
> hide VersionDropdown on non-versioned pages, reduce the visible versions list

- docs/build-speed-android.md
- docs/build-speed.md
- docs/new-architecture-app-modules-android.md
- website/sidebars.json
I'm adding a short guide on how to use single arch ABI and ccache to speedup android builds.
Feedbacks are more than welcome 🙏
> [Guide] Speeding up your Android/iOS Build

- docs/new-architecture-appendix.md
Displaying data in the table is quite compact, but in case of Types section in Appendix it's a bit too much condensed, which leads to layout overflow and poor mobile experience.
This PR refactors the New Arch Appendix types section extracting each type to its own small section. This change increases the overall readability on mobile and fixes the page overflow on desktop.
⚠️ On thing which I'm not sure what to do is "Type aliases of the above" entry. It is removed in this version, because it was a bit hard to fit this in nicely after refactor. Maybe we can add this as a more general sentence which just list the supported types in type aliases? If anyone got an idea please suggest the change or directly contribute to the PR branch.
> New Arch Appendix types section refactor

- website/blog/2022-03-30-version-068.md
- website/blog/authors.yml
This PR does add the 0.68 blogpost along with adding Andrei in the author.yml file :)
(as a temporary potential date I've put today, we can tweak accordingly to when it will actually happen)
It will have to be merged along with: https://github.com/facebook/react-native-website/pull/3033
> blogpost for 0.68

- docs/accessibility.md
- docs/button.md
- docs/text.md
- docs/touchablewithoutfeedback.md
- docs/view.md
This PR is going to add the `accessibilityLanguage` prop documentation to all the components targeted by the changes of https://github.com/facebook/react-native/pull/33090.
I'm not a native english speaker so I'm open to improvements / changes 🙂
> Added the `accessibilityLanguage` prop documentation

- docs/native-modules-android.md
- docs/native-modules-ios.md
- website/versioned_docs/version-0.63/native-modules-android.md
- website/versioned_docs/version-0.63/native-modules-ios.md
- website/versioned_docs/version-0.64/native-modules-android.md
- website/versioned_docs/version-0.64/native-modules-ios.md
- website/versioned_docs/version-0.65/native-modules-android.md
- website/versioned_docs/version-0.65/native-modules-ios.md
- website/versioned_docs/version-0.66/native-modules-android.md
- website/versioned_docs/version-0.66/native-modules-ios.md
- website/versioned_docs/version-0.67/native-modules-android.md
- website/versioned_docs/version-0.67/native-modules-ios.md
- website/versioned_docs/version-0.68/native-modules-android.md
- website/versioned_docs/version-0.68/native-modules-ios.md
TypeScript example in native modules guide was missing trailing semicolon. 
To see the change locally, go to: http://localhost:3000/docs/0.67/native-modules-ios
Before:
After:
> Add missing semicolon in native modules guide

- website/blog/2022-03-30-version-068.md
* Added hint for m1 jdk
* fallbackResource can just be safely removed without replacement
> Clarified 0.68 breaking changes

- docs/debugging.md
- docs/getting-started.md
- docs/libraries.md
- docs/more-resources.md
- docs/permissionsandroid.md
- docs/publishing-to-app-store.md
- docs/pushnotificationios.md
- docs/security.md
- docs/upgrading.md
- website/blog/2017-03-13-introducing-create-react-native-app.md
- website/versioned_docs/version-0.68/debugging.md
- website/versioned_docs/version-0.68/getting-started.md
- website/versioned_docs/version-0.68/libraries.md
- website/versioned_docs/version-0.68/more-resources.md
- website/versioned_docs/version-0.68/permissionsandroid.md
- website/versioned_docs/version-0.68/publishing-to-app-store.md
- website/versioned_docs/version-0.68/pushnotificationios.md
- website/versioned_docs/version-0.68/security.md
- website/versioned_docs/version-0.68/upgrading.md
Expo has change the domain a while ago and additionally some of the pages have been moved out of versioned docs portion.
This PR updates the Expo links used in `next` and `0.68` docs. Additionally I have fixed few links in an old blogpost, and I have corrected few sentences related to Expo around links.
> update Expo links in `next` and `0.68` docs

- docs/build-speed.md
- website/versioned_docs/version-0.68/build-speed.md
Added a small section that the first build with `--active-arch-only` on a clean environment might break (it does on 0.68). The issue is fixed on `main` and will land on 0.69: https://github.com/facebook/react-native/commit/5dff920177220ae5f4e37c662c63c27ebf696c83
(maybe we want to backport it to 0.68.1 @kelset ?)
Aside from that, better to have it on paper somewhere.
> Add a Troubleshooting section to the Build Speed guide

- .circleci/config.yml
Ref: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
this PR changes the CircleCI Docker image name according to the docs:
* https://circleci.com/developer/images/image/cimg/node
Run the CI! 😉
> [ci] switch to next-gen CircleCI img

- docs/_getting-started-macos-android.md
- website/blog/2022-03-30-version-068.md
- website/versioned_docs/version-0.68/_getting-started-macos-android.md
I've been evaluating some OpenJDK distributions recently and I tested Zulu11 on a clean M1 Mac. I believe we should be good moving from temurin11 to zulu11.
If we believe this is creating to much confusion for users as we recently moved from adoptopenjdk to temurin, I can update the doc to mention zulu11 only for M1 users.
As a rule of thumb, I'd be happy to offer a command that works for users on both archs.
cc @danilobuerger
> Suggest Zulu11 for all the users (regardless of M1 or not)

- docs/accessibility.md
These labels were starting the sentence and made it look off.
Before: 
https://reactnative.dev/docs/accessibility#accessibilityhint
After: 
- Pull down this branch
- Run `yarn start`
- Go to [http://localhost:3000/docs/next/accessibility](http://localhost:3000/docs/next/accessibility)
- Verify that the iOS and Android labels look correct
> Fix iOS and Android labels under accessibilityHint

- website/docusaurus.config.js
- website/package.json
- website/src/css/customTheme.scss
- website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
- website/versioned_docs/version-0.60/geolocation.md
- website/versioned_docs/version-0.61/geolocation.md
- website/versioned_docs/version-0.62/geolocation.md
- website/versioned_docs/version-0.63/geolocation.md
- yarn.lock
Superseeds:
* #3022
This PR updates Docusaurus to latest beta (`beta.18`) and most of the other dependencies.
Due to changes in Docusaurus code, I had to adjust the config and add a bunch of fixes to our custom styles, which become broken after the update. I also had to duplicate the GA move in the config, otherwise the website won't start.
I have run the updated version of the website on `localhost` and I used the currently shipped website as a 1:1 comparison, so the style issues was easier to spot, however, there still might be small display problems which I was not able to catch. If you see any regression in preview deploy, please let me know!
> update Docusaurus and other deps, fix broken styles

- docs/communication-android.md
This PR includes:
Sample code of Kotlin for `docs/communication-android` doc.
> Add Kotlin code for "Communication Android" documentation 

- docs/optimizing-flatlist-configuration.md
there was a mistake which was accidentally introduced while calling the function. The function invocation missed the `this` keyword.
> fix: mistake is function call.

- docs/the-new-architecture/landing-page.md
Adds content to the New Architecture landing page, which should introduce the New Architecture and direct the reader to the relevant content for them.
> New Architecture landing page

- docs/_getting-started-macos-ios.md
This PR adds a small paragraph about the `.xcode.env` file in the Getting Started guide.
> [Doc] add paragraph on .xcode.env

- docs/the-new-architecture/pillars.md
This PR adds the introductory section to the New Architecture Pillars.
> [Guide - The New Architecture] Pillars

- docs/performance.md
- website/versioned_docs/version-0.60/performance.md
- website/versioned_docs/version-0.61/performance.md
- website/versioned_docs/version-0.62/performance.md
- website/versioned_docs/version-0.63/performance.md
- website/versioned_docs/version-0.64/performance.md
- website/versioned_docs/version-0.65/performance.md
- website/versioned_docs/version-0.66/performance.md
- website/versioned_docs/version-0.67/performance.md
- website/versioned_docs/version-0.68/performance.md
When I read the documentation, it did not think to install the plugin because we deactivate our logger in production.
When I debugged a production build last week, I noticed several `console.*` calls. These all came from third party libraries.
In order to make more aware of this problem, I have adapted the documentation.
> Note for the plugin `transform-remove-console`

- website/architecture/threading-model.md
Superseds stale #3001
This PR fixes typo in threading-model doc.
> fix typo in threading-model doc

- docs/_getting-started-macos-android.md
Apple M1 chip has a 64 bit ARM architecture also known as AArch64, so it requires the emulator setup with above image. You can find this problem all over stack overflow, i.e https://stackoverflow.com/questions/68312799/android-studio-the-emulator-process-for-avd-pixel-2-api-30-has-terminated-on
> Macos/Android Getting Started: M1 mac new system image

- docs/textinput.md
- website/versioned_docs/version-0.66/textinput.md
- website/versioned_docs/version-0.67/textinput.md
- website/versioned_docs/version-0.68/textinput.md
This reflects the changes introduced by #31781 which added support for the `url` type on Android
> Update valid values for keyboardType

- website/src/css/customTheme.scss
The class for the font size in media seems to be incorrect. It does not make the font size of the banner smaller.
> customTheme.css (Make Font size smaller in banner)

- website/src/css/customTheme.scss
As seen on the picture above, the 'new' badge is right next to 'pressable' text.
In current React Native website, the 'new' badge (on computers) floats right.
However, switching the screen to mobile/ipad, the badge appears next to the text instead of floating right.
Using `margin-left: auto;` will make the button flat right inside the div in mobile screens.
> Make the 'new' badge float right in mobile

- website/src/pages/versions.js
GitHub main branch has been renamed from master to main.
Though some links had 'master' in them, it still worked as GitHub alerted the users it was renamed.
However, comparing does not work here as there is no branch by the name of master.
Changed master to main to properly check out the latest commits.
> Update version compare from latest to right now

- website/contributing/release-candidate-minor.md
Adding the step to tag/bump the Hermes version during the RN release process.
(cc @hramos @neildhar)
> Updating release instructions with Hermes bump steps

- docs/custom-webview-android.md
This PR adds kotlin code examples in custom webview documentation.
Related to #3018
> Update custom webview documentation with kotlin code examples

- docs/hermes.md
- website/versioned_docs/version-0.68/hermes.md
Fixes #3105
The way how you can enable/disable Hermes since RN 0.68 has changed, but the website hasn't been updated. Here I'm fixing it.
> Clarify how to enable hermes since RN 0.68

- docs/new-architecture-app-intro.md
TurboModules requires Folly and Folly requires some specific flag to be set in the app to work properly.
The required flags and how to set where missing in the documentation. I choose to put them in that specific point because they appear after we make the `AppDelegate` conform to the `RCTCxxBridgeDelegate` protocol.
> [fix] add documentation about how to configure Folly properly

- docs/_getting-started-windows-android.md
Fix the wrong android version name from "Q" to "R", to match the API level of 30.
> docs: fix the mismatch between android version name and its API level

- docs/communication-ios.md
The repository has been moved from `react-native-community`.
> Update RN Geolocation library URL.

- docs/troubleshooting.md
This commit updates the troubleshoot.md file by writting the solution to the ./gradlew EACCES error for mac users.
> solution for Error: spawnSync ./gradlew EACCES

- docs/new-architecture-app-intro.md
This PR fixes the title and anchoring for the `iOS: Setup Folly` section of the playbook.
| --- | --- |
| <img width="1138" alt="Screenshot 2022-05-18 at 21 22 51" src="https://user-images.githubusercontent.com/11162307/169149178-19257391-f86e-405d-b1bc-4116ad5ad9bc.png"> | <img width="1090" alt="Screenshot 2022-05-18 at 21 22 06" src="https://user-images.githubusercontent.com/11162307/169149062-a39ba1db-19d7-407c-90cc-304973e73dec.png">|
> [FIX] iOS: Setup Folly Title

- docs/new-architecture-app-renderer-ios.md
This PR removes The New Architecture/Enabling Fabric on iOS/[Add Babel Plugins](https://reactnative.dev/docs/next/new-architecture-app-renderer-ios#3-add-babel-plugins) section.
`babel-plugin-codegen` is not stabilized yet, and is not beneficial for Fabric as of now.
The plugin will become a part of the Metro preset in the future, so this section is effectively redundant.
> Remove "Add Babel Plugins" Section

- docs/signed-apk-android.md
Run command prompt as administrator to generate RSA key pair from windows, otherwise error occurred `keytool error java.io.filenotfoundexception my-upload-key.keystore (access is denied)`
> For Windows Run command prompt as administrator

- docs/touchableopacity.md
The method was labelled as an Android one but it says "Apple TV only".
> correction on tvParallaxProperties

- website/core/PrismTheme.js
- website/src/css/customTheme.scss
As mentioned in https://github.com/facebook/react-native-website/pull/3143#issuecomment-1144607744, there is an alternative way to fix the Prism code block background issues.
It looks like the custom theme was using legacy field, IIRC this came from the days when VSCode themes could be used as Prism themes.
Let's fix the field name and remove the CSS overwrite.
> alternative fix for the CodeBlocks background

- docs/textinput.md
Updated the TextInput multiline property's docs. Part of the text needs to be styled as a note.
> Updated TextInput multiline property

- docs/react-18-and-react-native.md
- website/sidebars.json
I'm adding a page about React 18 and Concurrent React to the New Architecture section.
Feedbacks are welcome as always 👍
Fixes #787
> Add a page about React 18 & Concurrent React

- README.md
'open http://localhost:3000' was surrounded with backtick which presented itself as a code and not a link.
`open http://localhost:3000`
open http://localhost:3000
> Remove backtick from readme

- docs/hermes.md
- website/architecture/bundled-hermes.md
- website/sidebarsArchitecture.json
This PR adds:
- A small paragraph in the Hermes page about Bundled Hermes.
- A new page in the Architecture section with a deep-dive on Bundled Hermes.
For the latter, I've create a new section called _Build Tools_. I'm open for suggestions for improvements on this 👍 
cc @fortmarek @hramos @neildhar as we want this on the website before we materialize the documentation for 0.69
> Add a page explaining Bundled Hermes

- website/architecture/bundled-hermes.md
Just a small nit proposed in https://github.com/reactwg/react-native-releases/discussions/21
> Add Build Tools for Visual Studio 2022 to Bundled Hermes

- docs/headless-js-android.md
- website/versioned_docs/version-0.68/headless-js-android.md
> Add Kotlin code for "headless-js-android" documentation

- website/static/_redirects
React Native core repository Readme file contains old, general link to the Contributing section of the website and after latest changes it leads to 404 page.
Apply the correct redirect for the old Contributing section link.
> correct redirect for Contributing section landing page

- website/src/css/customTheme.scss
After latest upgrades and changes I have spotted that CodeBlocks do not display correctly. The problems were:
* additional spacing at the bottom of code block
* inconstant styling of inner buttons
* missing title background color in dark mode
This PR applies the needed SCSS tweaks and fixes. 
Changes have been tested by running the website locally.
https://user-images.githubusercontent.com/719641/174797652-ca0f964f-7091-4f01-837f-a78e1ab0cf1c.mp4
> small tweaks for the CodeBlocks appearance

- docs/accessibility.md
- docs/colors.md
- docs/communication-ios.md
- docs/direct-manipulation.md
- docs/flexbox.md
- docs/height-and-width.md
- docs/hermes.md
- docs/images.md
- docs/linking-libraries-ios.md
- docs/native-components-ios.md
- docs/navigation.md
- docs/profile-hermes.md
- docs/profiling.md
- docs/publishing-to-app-store.md
- docs/ram-bundles-inline-requires.md
- docs/signed-apk-android.md
- docs/timers.md
This PR is the first in series, in which I going to replace legacy styling and workarounds with new Docusuaurs features (I have decided to split the changes into few PR so the amount of changes won't be overwhelming for the reviewers).
The first change is to replace the the old `blockquote` blocks which were used for emphasising the content before the [Admonitions](https://docusaurus.io/docs/markdown-features/admonitions) was a thing. I have chosen the styling and added a custom tile (if needed) based on the current "notes" content.
Ideally, we want to get rid of all `blockquote` like that, to be able to use the component for the regular quotes, but this might take a longer while, so ATM I have put my focus on the unversioned docs.
The second change is that CodeBlock now supports `title` …
> replace old blockquotes with admonitions, add codeblocks titles (part 1)

- website/contributing/updating-upgrade-helper.md
The link is now broken, I'm updating it with a Github Permalinkg
> Update diff-purge docs link with permalinks

- docs/running-on-device.md
While I was trying to run an app on my tablet I faced an issue that the device was listed as unauthorized, and while it was the only device listed on the list when I run `npm run android` the emulator was opened
I did a google search and end up with this fix
> added a note in running your app on real device section

- docs/alert.md
Support to override Alert interface style to match your app. For example, You want to change the style of the alert.
react-native PR:  https://github.com/facebook/react-native/pull/33553
> Add userInterfaceStyle option to Alert

- docs/accessibility.md
The description for Accessibility property "accessibilityIgnoresInvertColors" incorrectly states that the value should be set to "false" to prevent color inversion. Correct value is "true" per the Apple documentation (https://developer.apple.com/documentation/uikit/uiview/2865843-accessibilityignoresinvertcolors) and my personal testing.
> Update accessibilityIgnoresInvertColors property

- docs/typescript.md
- TS Config: `compilerOptions.types`: https://www.typescriptlang.org/tsconfig#types
- Preview: https://deploy-preview-3166--react-native.netlify.app/docs/next/typescript
---
The issue:
---
After fix:
---
<details>
<summary>`yarn why @types/node`</summary>
```java
yarn why v1.22.17
[1/4] Why do we have the module "@types/node"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@types/node@18.0.0"
info Reasons this module exists
- "@jest#types" depends on it
- Hoisted from "@jest#types#@types#node"
- Hoisted from "jest-haste-map#@types#node"
- Hoisted from "jest-util#@types#node"
- Hoisted from "jest-worker#@types#node"
- Hoisted from "jest#@jest#core#@types#node"
- Hoisted from "jest-haste-map#@types#graceful-fs#@types#node"
- …
```
> Fix for "Type 'Timeout' is not assignable to type 'number'"

- docs/javascript-environment.md
- website/versioned_docs/version-0.65/javascript-environment.md
- website/versioned_docs/version-0.66/javascript-environment.md
- website/versioned_docs/version-0.67/javascript-environment.md
- website/versioned_docs/version-0.68/javascript-environment.md
- website/versioned_docs/version-0.69/javascript-environment.md
Most of proposals already in spec
- Finished TC39 Proposals: https://github.com/tc39/proposals/blob/main/finished-proposals.md
- Preview: https://deploy-preview-3184--react-native.netlify.app/docs/javascript-environment#javascript-syntax-transformers
> Fix outdated "JavaScript Syntax Transformers"

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
I get reports of build errors from users that have chosen JDK18, that JDK does not work yet and should not be included either explicitly or even as part of an acceptable range ("...or newer")
See https://github.com/react-native-device-info/react-native-device-info/issues/1431#issuecomment-1165443830
I will add a second commit here in a moment for linux setup
> docs(jdk): recommend JDK 11. JDK18 will not work. JDK17 may not work < 0.68

- website/contributing/release-candidate-minor.md
- website/contributing/release-candidate-patch.md
- website/contributing/release-stable-minor.md
- website/contributing/release-stable-patch.md
When doing the latest release, we have noticed the `--version` flag in the patch releases guide is incorrect and it should be `-v` instead.
> Fix invocation of bump script command

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.68/_getting-started-linux-android.md
- website/versioned_docs/version-0.68/_getting-started-macos-android.md
- website/versioned_docs/version-0.68/_getting-started-windows-android.md
- website/versioned_docs/version-0.69/_getting-started-linux-android.md
- website/versioned_docs/version-0.69/_getting-started-macos-android.md
- website/versioned_docs/version-0.69/_getting-started-windows-android.md
As of React Native [v0.68.0](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0680), the [default Android SDK version has been upgraded to 31](https://github.com/facebook/react-native/commit/00ac034353cbc867991bf79cb1dd103353f47126).
The changes have been backported to all applicable versions (0.68, 0.69, and current).
> Update Android SDK version to 31

- docs/easing.md
Style fix. Consistent with other references to parameters or method names.
> Use monospace for method name on docs/easing

- docs/profile-hermes.md
This is a nit, but I've realized that this snippet inside `profile-hermes` was originally marked as Java code while in reality is Groovy code (as it's from a .gradle file).
> Update snippet in profile-hermes to be Groovy rather than Java

- docs/the-new-architecture/_markdown_beta_ts_support.mdx
- docs/the-new-architecture/backward-compatibility-turbomodules.md
This PR adds the guide to create a backward compatible TurboModule. 
Draft while we wait for Android.
> [Guide - The New Architecture] TurboModules as Native Modules

- docs/the-new-architecture/backward-compatibility-fabric-components.md
This PR adds the guide to create a backward compatible Fabric Component.
Draft while we wait for Android.
> [Guide - The New Architecture] Fabric Components as Native Components

- docs/new-architecture-library-android.md
This PR adds kotlin code sample to the file "new-architecture-library-android.md"
Looks like so on my local website
references #3018
> Add kotlin code sample to new-architecture-library-android.md

- docs/_getting-started-windows-android.md
Like "Android 12 (S)" is wrapped with backticks, "Android SDK Build-Tools" should also be wrapped with backticks for consistency.
> Wrap "Android SDK Build-Tools" with backticks

- docs/build-speed.md
Removed duplicated sentence from docs
> Update build-speed.md page in docs

- docs/new-architecture-intro.md
> docs: add two sections to the New Architecture

- docs/debugging.md
Standalone react-devtools frequently has trouble connecting to a running simulator instance, as noted in the docs, on the GH repo, and on [SO](https://stackoverflow.com/questions/50867874/react-native-cannot-connect-to-react-devtools-using-android-simulator). 
Often, it is necessary to run `adb reverse tcp:8097 tcp:8097` to get standalone react-devtools to connect to a running simulator instance. It would be helpful to note this in the docs here, rather than forcing users to search the GH docs, and SO. (Also, a note - the GH docs state that this is only necessary when not using a local emulator, but this is not the case, as evidenced by the aforementioned [SO question](https://stackoverflow.com/questions/50867874/react-native-cannot-connect-to-react-devtools-using-android-simulator), …
> Note on connecting to React Native simulator.

- website/contributing/release-branch-cut-and-rc0.md
During the release of 0.70.0-rc0 we noticed a couple of missing points in the release runbook. I'm fixing them. @kelset they should maybe be picked up inside https://github.com/facebook/react-native-website/pull/3221 as well.
> Fix a couple of problems on the release runbook

- docs/improvingux.md
- website/versioned_docs/version-0.69/improvingux.md
Fixes #3084
This PR replaces the existing videos and Snack links on the Improving UX page with the `SnackPlayer` components.
During this process I have also refactored and updated the examples, and the changes have been backported to `0.69`.
Unfortunately we cannot remove `mp4` files since those videos are used in the older version of docs.
> Improving UX: replace videos and links with SnackPlayers, update examples

- docs/debugging.md
I accidentally broke the CI, my bad. I rebase and merged https://github.com/facebook/react-native-website/pull/3222 without waiting for CI results.
Here is the fix.
As a side note, should we enable automerge?
> Fix extra whitespace on debugging.md

- docs/new-architecture-library-intro.md
- website/versioned_docs/version-0.68/new-architecture-library-intro.md
- website/versioned_docs/version-0.69/new-architecture-library-intro.md
Hey! 
This PR adds few missing informations in the **Prerequisites for Libraries** guide.
- Add section about Codegen helper types
- Add info about replacing`requireNativeComponent` with `codegenNativeComponent`
- Fix section title
- Fix spaces in code examples
> Add more info to Prerequisites for Libraries guide

- docs/running-on-simulator-ios.md
Changes:
1. Change double quote to single quote in order to escape paranthesis
2. Add iOS version command
3. Add udid command
> [Documentation] iOS Simulator version&udid

- website/contributing/release-roles-responsibilites.md
Copilot should run a retrospective after a new minor is released (at least in cases when there's enough to talk about) cc @kelset
> Add retrospective as a copilot responsibility

- website/contributing/_markdown-async-testing-note.mdx
- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-candidate-patch.md
- website/contributing/release-roles-responsibilites.md
- website/contributing/release-stable-patch.md
- yarn.lock
This PR wants to update the docs as a follow up items from the RN69 retro we did last week.
3 main changes:
* add a note about doing testing async since it takes time
* reword the roles page to default to a 2+2 composition of the crew at all times
* remove testers & supporters since we have decided to not have those roles anymore
Also, for some reason there's yarn.lock change that keeps popping up so I just integrated it
> update release related docs page

- docs/image.md
**Proposed documentation update**
This is missing, but this is an important information. Imagine a view sized 100x150 and an image sized 200x300. The old description could be interpreted in a way, that the image doesn't scale at all!
I agree, once you know it, this might be obvious, but I still feel like it's needed piece of info
> Update docs for image.md

- docs/linking.md
When dealing with functions which return Promises, it's helpful to be
clear about whether something _returns_ a value, or whether the
returned Promise will _resolve to_ a value.
> chore: Specify return vs resolve

- docs/new-architecture-app-modules-android.md
> Add kotlin examples in new-architecture-app-modules-android.md

- website/src/pages/index.js
This is a follow up to a conversation in the RN Discord; this changes the links that the call to actions sends you to - these two seemed more appropriate than what was there before.
I didn't fully remove the tutorial page because with a quick check it seems like that it's cross-referenced in other places, and I wanted to keep this PR minimal. If we agree to merging this we can revisit what to do with that tutorial page.
> Change links in main home page

- website/sidebars.json
This PR fixes a typo in the sidebar (from `Migrati` to `Migration`)
> Fix typo in the sidebar

- docs/permissionsandroid.md
Android 13 introduces multiple new permission. 
This PR aims to updates the documentation for multiple new permission that android 13 introduce that have been merged to master in the core repo. 
```
- `BODY_SENSORS_BACKGROUND`: 'android.permission.BODY_SENSORS_BACKGROUND'
- `READ_MEDIA_IMAGES`: 'android.permission.READ_MEDIA_IMAGES'
- `READ_MEDIA_VIDEO`: 'android.permission.READ_MEDIA_VIDEO'
- `READ_MEDIA_AUDIO`: 'android.permission.READ_MEDIA_AUDIO'
- `POST_NOTIFICATION`: 'android.permission.POST_NOTIFICATIONS'
- `NEARBY_WIFI_DEVICES`: 'android.permission.NEARBY_WIFI_DEVICES'
```
Related PR
https://github.com/facebook/react-native/pull/33471
Based on the commit, this should be available in React Native starting from [v0.70.0-rc.0](https://github.com/facebook/react-native/releases/tag/v0.7 …
> Adding Android 13 Permissions into PermissionsAndroid

- docs/textinput.md
While working on `D36140890` There is already behavior implemented to set the TextInput caret/cursor color independently from the selection box color in Android. However this handy prop, was not documented.
The behavior can be found here:
[https://www.internalfb.com/code/fbsource/[f116d651b2e8]/xplat/js/react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java?lines=512](https://www.internalfb.com/code/fbsource/[f116d651b2e8]/xplat/js/react-native-github/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java?lines=512)
If you are a Meta employee, you can view the diff that implemented the cursorColor [on Phabricator](https://www.internalfb.com/diff/D36208656).
This diff is already synced into OSS and …
> Adding cursorColor Props On TextInput Android

- website/contributing/_markdown-GH-release-notes-prerelease.mdx
- website/contributing/_markdown-road-to-release-template.mdx
- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-candidate-patch.md
A small PR to do a bit of refactoring and update a couple of templates around releases and release notes.
> docs (releases): small refactoring and updating templates

- docs/keyboard.md
https://github.com/facebook/react-native/commit/1e48274223ee647ac4fc2c21822b5240f3c47e4c fixed keyboard events on Android 11+ when an activity has set `android:windowSoftInputMode` to `adjustNothing`. Update the documentation to reflect the change.
> Update documentation for keyboard events on Android

- website/package.json
- website/src/css/customTheme.scss
- yarn.lock
This PR updates the Docusuaurs to the latest and stable release! 🎉
There is no changelog published yet from latest RC, but there were almost no changes between those versions.
Testing the bump locally I was not bale to spot any visual regressions.
I have also utilize this bump to address the warning admonitions style, which since bump to RC started to match again against one of our legacy CSS selectors, which lead to unexpected effect (text centered, small font), those issue have been fixes as well as double underline for links in admonitions.
> Update to Docusaurus stable release, fix alert admonition styling

- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-candidate-patch.md
Since the testers group doesn't exist anymore, removing a couple of leftover references.
> chore(releases): remove old references to testers

- docs/appregistry.md
- docs/debugging.md
- docs/getting-started.md
- docs/linking.md
- docs/permissionsandroid.md
- docs/publishing-to-app-store.md
- docs/pushnotificationios.md
- docs/running-on-device.md
- docs/signed-apk-android.md
- docs/typescript.md
- docs/upgrading.md
- website/core/TabsConstants.js
- website/versioned_docs/version-0.69/appregistry.md
- website/versioned_docs/version-0.69/debugging.md
- website/versioned_docs/version-0.69/getting-started.md
- website/versioned_docs/version-0.69/linking.md
- website/versioned_docs/version-0.69/more-resources.md
- website/versioned_docs/version-0.69/permissionsandroid.md
- website/versioned_docs/version-0.69/publishing-to-app-store.md
- website/versioned_docs/version-0.69/pushnotificationios.md
- website/versioned_docs/version-0.69/running-on-device.md
- website/versioned_docs/version-0.69/signed-apk-android.md
- website/versioned_docs/version-0.69/typescript.md
- website/versioned_docs/version-0.69/upgrading.md
We recently made some changes, [such as moving away from the global Expo CLI package to a local CLI and `create-expo-app`](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) and [moving away from `expo build`](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). 
This pull requests accounts for these changes and backports them to the 0.69 docs, because Expo SDK 46 currently uses React Native 0.69.
> Update references to Expo / Expo CLI

- docs/images.md
- website/versioned_docs/version-0.69/images.md
By default React Native would set `NSCache.totalCostLimit` to 20MB and the single image size limit to 2MB (bitmap size). The default cache size may not be enough for applications that make heavy use of images. 
But thanks to this [commit](https://github.com/facebook/react-native/commit/61b013e7ad8a1cc28ee39434d2fd96b74b96cf5f) now you can configure the image cache size on iOS by adding `RCTSetImageCacheLimits` in your app App Delegate.
This feature should be available from [v0.69.0-rc.0](https://github.com/facebook/react-native/releases/tag/v0.69.0-rc.0)
> feat(images): Adding iOS Image Cache Limits

- docs/the-new-architecture/pillars-codegen.md
- docs/the-new-architecture/pillars-fabric-components.md
Fixes tiny typos in the new architecture docs
> nit: fix typo in new architecture docs

- docs/new-architecture-library-intro.md
The two section [Using `forwardRef`](https://reactnative.dev/docs/next/new-architecture-library-intro#using-forwardref) and [Using a `getter`](https://reactnative.dev/docs/next/new-architecture-library-intro#using-a-getter-note-the-addition-of-getviewref) are alternative solutions to get rid of `findNodeHandle`, based on the type of component (function or class). 
However, the current structure of the doc leads the reader to think that these are two other API that needs to be migrated: they are at the same level of the `findNodeHandle` one and they also appear in the ToC of the page, on the right.
This PR moves them down one level, reducing the importance of their title and it should make them disappear from the ToC on the right.
> Move the "Using `forwardRef`" and "Using a `getter`" sections to a lower hierarchy level

- docs/toastandroid.md
- website/versioned_docs/version-0.62/toastandroid.md
- website/versioned_docs/version-0.63/toastandroid.md
- website/versioned_docs/version-0.64/toastandroid.md
- website/versioned_docs/version-0.65/toastandroid.md
- website/versioned_docs/version-0.66/toastandroid.md
- website/versioned_docs/version-0.67/toastandroid.md
- website/versioned_docs/version-0.68/toastandroid.md
- website/versioned_docs/version-0.69/toastandroid.md
Hello everybody!
The example of the file that talks about Toasts on Android, is without camelCase in `useState`.
This PR includes the camelCase pattern in referenced articles.
😉
> Upgrade toast Android example to camelCase

- docs/new-architecture-library-intro.md
In the Migration to the New Architecture, there are some sections that are suggested steps to migrate away from an API that appear at the same level as the other APIs. 
This can create confusion and can make the migration look bigger than what it actually is.
This PR moves these step at the proper hierarchy layer.
> [Fix] JS migration api

- website/blog/2022-09-05-version-070.md
- website/blog/authors.yml
Here the blogpost for the next stable 🎉
> Blog post for 0.70 RN release

- docs/textinput.md
This PR adds the `readOnly` prop to the TextInput documentation  
Follow-up of https://github.com/facebook/react-native/pull/34444
> feat: Add readOnly prop to TextInput docs 

- docs/accessibilityinfo.md
Add documentation regarding the new `prefersCrossFadeTransitions` method from to `AccessibilityInfo` 
Related to https://github.com/facebook/react-native/pull/34406
> feat: Add prefersCrossFadeTransitions to AccessibilityInfo docs

- docs/textinput.md
This PR adds the `rows` Android only prop to the TextInput documentation
Related to https://github.com/facebook/react-native/pull/34488
> feat: Add rows prop to TextInput docs

- docs/textinput.md
This PR adds the `inputMode` prop to the TextInput documentation
Related to https://github.com/facebook/react-native/commit/9fac88574e2f8c2f46b7f081273845f833fe1b75
> feat: Add inputMode prop to TextInput docs

- docs/flexbox.md
> Fix color reference in flexbox.md

- docs/accessibility.md
- docs/view.md
adds the accessibilityRole grid to a FlatList, VirtualizedList, ScrollView or SectionList.  Adds the in/out of grid announcements.
PR https://github.com/facebook/react-native/pull/34267
fixes https://github.com/facebook/react-native/issues/30861 fixes https://github.com/facebook/react-native/issues/30972
> [Documentation] adding accessibilityRole grid to documentation

- docs/view.md
This PR adds the `tabIndex` Android-only prop to the View documentation
Related to  https://github.com/facebook/react-native/commit/621f4cf3b12979b62d2e1d49d63eaf85e0707026
> feat: Add tabIndex prop to View docs

- docs/image.md
This PR adds the `tintColor` prop to the Image documentation
Related to https://github.com/facebook/react-native/commit/7a6f0e44b26b7a6eddb25d5e05948a1992a1629e
> feat: Add tintColor prop to Image docs

- docs/textinput.md
This PR adds the `enterKeyHint` prop to the `TextInput` documentation
Related to https://github.com/facebook/react-native/commit/8c882b4f3d361be715c8ec2793c545c687711b5e
> Added enterKeyHint prop to textInput docs

- docs/new-architecture-intro.md
- docs/react-18-and-react-native.md
- website/versioned_docs/version-0.70/new-architecture-app-intro.md
This PR addresses the missing feedback from #3268
> [Fix]Address feedback from #3268

- docs/native-modules-android.md
- docs/native-modules-ios.md
- website/versioned_docs/version-0.70/native-modules-android.md
- website/versioned_docs/version-0.70/native-modules-ios.md
This box is unnecessary (and old). We already have a deprecation notice on top that is more up to date and linking to the correct docs.
> Remove unnecessary box from Legacy Native Modules/Components

- docs/testing-overview.md
In `testing-overview.md`, the section headings have the first letter capitalized, like "Integration Tests" and "Component Tests". It's inconsistent to have "Unit tests".
> Fix title case in testing-overview.md

- docs/new-architecture-library-ios.md
- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
This PR describes the changes introduced by this [PR](https://github.com/facebook/react-native/commit/82e9c6ad611f1fb816de056ff031716f8cb24b4e) in the React Native repo. 
Currently, React Native is exposing a function that, given a Cocoapod spec, is able to install the dependencies required by the New Architecture, reducing the amount of code 
the library maintainers have to write.
> [FEAT] Add doc to simplify podspecs for Native Modules and Native Components

- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.70/_getting-started-macos-ios.md
THis PR adds some extra setup requirements for iOS so that people do not incur in issues like [this](https://github.com/facebook/react-native/issues/34608) or 
[this](https://github.com/facebook/react-native/issues/34601). It assumes that we have also fixed the CLI already, but it contains some extra instruction to cover the time 
we need to update it.
Once the PR is accepted, I'll backport these changes to 0.70.
> [Fix] Improve Getting started with iOS

- docs/new-architecture-library-intro.md
Just realized that two links were broken to the appendix. I'm fixing them
> Fix broken links to Appendix

- website/src/pages/versions.js
The "all versions" page had some outdated wording, with incorrect timings.
> minor tweaks to the wording for the versions page

- website/versioned_docs/version-0.68/build-speed.md
Unfortunately, we currently have the broken link in the code on `main` which prevents PROD deployment from ending successfully.
This is also a reason why the new Showcase entries are not visible on the website.
Fix incorrect link listed by Docusaurus check.
> fix incorrect link to re-enable prod deploy

- website/docusaurus.config.js
- website/src/css/customTheme.scss
This is a follow-up to a conversation that happened in the RN Discord; I saw the [Flutter website](https://flutter.dev/) having a clean and organised navbar and I wondered if that could have been replicated for the RN website.
Luckily, as pointed out by @slorber, Docusaurus supports this dropdown behaviour directly: https://docusaurus.io/docs/next/api/themes/configuration#navbar-dropdown
so the changes are fairly minimal, from a code perspective.
What I ended up doing for this first iteration is to group under "development" the 4 elements (in alphabetical order) "Architecture", "API", "Components", "Guides" and then re-add to the navbar the "Showcase" element.
Here are a few screenshots to show the result:
(but also ofc verify via the deployed preview)
---
A potential "second iteration" …
> Modify the top navbar to be less full

- docs/new-architecture-app-intro.md
The AGP 7.3 bump allows us to cleanup a bit of the configuration code we have for Gradle in the New Architecture migration guide.
> Update docs with AGP 7.3.x setup

- docs/colors.md
This updates the Colors documentation with examples of the new format supported by `rgb`, `rgba`, `hsl` and `hsla`. It also adds a new section about the support for `hwb`.
Related to https://github.com/facebook/react-native/commit/ac1fe3b7eb8e16f5feddeeac846ff70080dc119e
> feat: Update colors docs regarding expanded support for CSS Colors

- docs/text.md
- docs/touchablewithoutfeedback.md
- docs/view.md
This PR updates `Text`, `TouchableWithoutFeedback`, and `View` documentations adding information about the new `id` prop.
Related to https://github.com/facebook/react-native/pull/34522
> feat: Add id prop to Text, TouchableWithoutFeedback and View docs

- docs/new-architecture-library-intro.md
- docs/the-new-architecture/pillars.md
- docs/the-new-architecture/use-app-template.md
I was re-reading the whole set of new arch docs and I noticed a few things that needed to be fixed, so here's the PR :)
It's all fairly minor stuff, typos and things like those.
> chore: clean up new arch docs

- docs/image.md
This PR adds documentation for crossOrigin, referrerPolicy, width, height, src and srcSet props to the Image doc
Related to commit https://github.com/facebook/react-native/commit/47a05bc26ab76add640183c1d9d8cbba39d7d0d2
and issue https://github.com/facebook/react-native/issues/34424
> Added Documentation for crossOrigin, referrerPolicy, width, height, src and srcSet props to Image

- docs/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
Hello,
This PR removes misleading `isFabricEnabled` check from the docs. This is no longer needed since `codegenNativeComponent` is calling `requireNativeComponent` internally. This check was also removed from [RNNewArchitectureLibraries example](https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-fabric-component-070/colored-view/src/index.js)
> fix: remove isFabricEnabled check from docs

- docs/accessibility.md
- docs/view.md
This PR adds documentation for the `aria-modal` prop.
Related to commit https://github.com/facebook/react-native/commit/095f19a681e22bd5f9438758112cc9628499b631
and issue https://github.com/facebook/react-native/issues/34424
> added documnetatuin for `aria-modal` prop

- docs/profile-hermes.md
- docs/sourcemaps.md
- website/sidebars.json
I am continuing to struggle for an official source for enabling/using sourcemaps. I figured I would scan code/bugs/issues of the upcoming 0.70.x version and learn everything to start a document.
Nothing easier in the world then to put something wrong on the Internet and folks will correct you. I tested these and they are valid sourcemap generation process that works for a manual symbolication as well as Sentry.
I do wish to get some folks that work/build on the systems to verify my claims in here, but I would love a sourcemap doc that shows both iOS and Android to start. 
Demo: https://deploy-preview-3293--react-native.netlify.app/docs/next/sourcemaps
> New: Sourcemap Page

- docs/flatlist.md
- docs/sectionlist.md
- docs/virtualizedlist.md
- website/versioned_docs/version-0.70/flatlist.md
- website/versioned_docs/version-0.70/sectionlist.md
- website/versioned_docs/version-0.70/virtualizedlist.md
Commit: https://github.com/facebook/react-native/commit/5854b11bf9d42bab9dbe62b9152a3d3a94e42c13
RN: 0.70.x +
> Add ability to pass ItemSeparatorComponent as React Element

- docs/native-modules-android.md
CalendarModule.createCalendarEvent is referenced as CalendarModule.createCalendarEventCallback a few times in the jsx code snippets, which is incorrect
> fix(native-modules-android.md): rename createCalendarEventCallback

- .alexrc.js
- LICENSE
- plugins/remark-snackplayer/src/index.js
- plugins/remark-snackplayer/tests/index.js
- sync-api-docs/extractDocsFromRN.js
- sync-api-docs/generateMarkdown.js
- sync-api-docs/magic.js
- sync-api-docs/methodFormatter.js
- sync-api-docs/preprocessGeneratedApiDocs.js
- sync-api-docs/propFormatter.js
- sync-api-docs/sync-api-docs.js
- sync-api-docs/utils.js
- website/core/DocsRating.js
- website/core/PrismTheme.js
- website/core/TableRowWithCodeBlock.js
- website/core/TabsConstants.js
- website/image-check.js
- website/snackPlayerInitializer.js
- website/src/pages/animations/_dissectionAnimation.js
- website/src/pages/animations/_headerAnimation.js
- website/src/pages/index.js
- website/src/pages/showcase.js
- website/src/pages/versions.js
- website/src/theme/BlogSidebar/Desktop/index.js
- website/src/theme/BlogSidebar/Mobile/index.js
- website/src/theme/DocItemFooter/index.js
- website/src/theme/Icon/ExternalLink/index.js
- website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Applies the updated copyright header (with Meta Platforms, Inc. instead of Facebook, Inc.) to all `*.js` files.
> Apply updated copyright to `*.js` files

- docs/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
Hello,
This PR removes `isTurboModuleEnabled` check from the docs, since it's no longer needed.
> fix: remove isTurboModuleEnabled check from docs

- docs/the-new-architecture/pillars-codegen.md
I've noticed a typo in the iOS codegen script paths.
> Fix codegen iOS scripts paths

- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
Closes #3018
This PR adds all the missing Kotlin snippets as we're close to 100% 🎉 
I've also updated multiple bugs in the corresponding Java snippets.
Moreover I've:
- Updated all the packages to be lowercase `com.MyPackage` -> `com.mypackage`
- Updated all the classes to don't use the iOS prefixes `RNTMyComponent` -> `MyComponent`
Specifically on the latter we had a mixture of the two. I'm leaning towards using the platform specific nomenclature but we can discuss on this if we wish.
> Finalize the Kotlinization

- website/docusaurus.config.js
Adds a missing header to `docusaurus.config.js`.
> Missing header in `docusaurus.config.js`

- website/versioned_docs/version-0.65/_getting-started-linux-android.md
- website/versioned_docs/version-0.65/_getting-started-macos-android.md
- website/versioned_docs/version-0.65/_getting-started-windows-android.md
- website/versioned_docs/version-0.66/_getting-started-linux-android.md
- website/versioned_docs/version-0.66/_getting-started-macos-android.md
- website/versioned_docs/version-0.66/_getting-started-windows-android.md
- website/versioned_docs/version-0.67/_getting-started-windows-android.md
This PR resolves #3088 
This fix only affects document for older versions of react-native
Fixed mismatches for Android API level and version label
> Fix Android version label for older version documents

- docs/layout-props.md
This PR updates the `aspectRatio` style prop documentation to also support strings.
Related to https://github.com/facebook/react-native/commit/14c91cdf59949959dd2e39af4fed5bee01c3cba1
> feat: Update aspectRatio supported types docs

- docs/_getting-started-macos-android.md
- website/versioned_docs/version-0.70/_getting-started-macos-android.md
First of all, thanks for React Native! 🙌 Such amazing software and great DX
Just a quick PR to reorder the zsh and bash files, since the newer versions of macOS have switched from bash to zsh (so this will become increasingly common that people will need to use the zsh files)
> Reorder zsh because newer macOS uses zsh

- docs/running-on-simulator-ios.md
- website/versioned_docs/version-0.70/running-on-simulator-ios.md
this PR update iOS simulators according this PR https://github.com/react-native-community/cli/pull/1701
> docs: update running on simulator iOS

- docs/the-new-architecture/backward-compatibility-turbomodules.md
- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
The previous descriptions of how to create a TurboModule and to create a backward-compatible TurboModule contained incorrect and partial information for what concern iOS. This 
PR improve the description, including how to properly import the Spec file and with the required changes.
> [Fix] Improve TM explanation

- website/contributing/how-to-contribute-code.md
- website/contributing/how-to-run-and-write-tests.md
- website/contributing/release-testing.md
This PR updates the docs to account for the new RN>=71 local script for E2E testing (this https://github.com/facebook/react-native/pull/34513)
While working on it, I've also cleaned up a few references here and there to things that don't exist anymore (RIP release testers) and overall wordiness :)
> chore(release): Update release testing section for new E2E testing script

- docs/headless-js-android.md
- website/versioned_docs/version-0.70/headless-js-android.md
Fixed typo to make the Kotlin and Java examples the same.
> Fixed typo in headless-js-android.md

- docs/hermes.md
Hermes is now the default JS engine. Instead of explaining how to enable Hermes on the current version, we now explain how to opt-in in older versions and how to opt-out in versions where Hermes is the default.
> Add updated instructions on using Hermes

- website/contributing/how-to-build-from-source.md
Adding a missing paren in the sentence under **Publish your own version of React Native**.
> fix: missing paren in publishing

- docs/typescript.md
- website/versioned_docs/version-0.69/typescript.md
- website/versioned_docs/version-0.70/typescript.md
Issue: #3167
- Preview: https://deploy-preview-3342--react-native.netlify.app/docs/next/typescript
- `@tsconfig/react-native` already recommend `es2019` (see: [`bases/react-native.json#L10`](https://github.com/tsconfig/bases/blob/96274973952a623d9f2e310987ceb4a19dcc362c/bases/react-native.json#L10))
- Commit: https://github.com/tsconfig/bases/commit/ff86e2c43c883837a5e07800697be435641a3b1d
- `react-native-template-typescript` use by default `@tsconfig/react-native` (see : [`template/tsconfig.json#L3`](https://github.com/react-native-community/react-native-template-typescript/blob/5b22365750a285feddf7a3db26450cda4fe4cd1d/template/tsconfig.json#L3)
- PR: https://github.com/react-native-community/react-native-template-typescript/pull/281
> Recommend to use `es2019` and use community driven TS config `@tsconfig/react-native`

- website/src/pages/index.js
Following internal discussion, this opens up wording on our homepage (significantly, the secondary tagline) to align with our [Many Platform Vision](https://reactnative.dev/blog/2021/08/26/many-platform-vision).
Text wrapping is not negatively affected across desktop and mobile breakpoints.
**Desktop**
**Mobile**
> Tweak homepage text to more broadly refer to platforms

- docs/_getting-started-windows-android.md
- docs/accessibility.md
- docs/image.md
- docs/react-18-and-react-native.md
- docs/the-new-architecture/backward-compatibility.md
- docs/touchablewithoutfeedback.md
- website/versioned_docs/version-0.60/_getting-started-windows-android.md
- website/versioned_docs/version-0.61/_getting-started-windows-android.md
- website/versioned_docs/version-0.62/_getting-started-windows-android.md
- website/versioned_docs/version-0.63/_getting-started-windows-android.md
- website/versioned_docs/version-0.64/_getting-started-windows-android.md
- website/versioned_docs/version-0.64/image.md
- website/versioned_docs/version-0.65/_getting-started-windows-android.md
- website/versioned_docs/version-0.65/image.md
- website/versioned_docs/version-0.66/_getting-started-windows-android.md
- website/versioned_docs/version-0.66/image.md
- website/versioned_docs/version-0.67/_getting-started-windows-android.md
- website/versioned_docs/version-0.67/image.md
- website/versioned_docs/version-0.68/_getting-started-windows-android.md
- website/versioned_docs/version-0.68/image.md
- website/versioned_docs/version-0.69/_getting-started-windows-android.md
- website/versioned_docs/version-0.69/image.md
- website/versioned_docs/version-0.69/react-18-and-react-native.md
- website/versioned_docs/version-0.70/_getting-started-windows-android.md
- website/versioned_docs/version-0.70/image.md
- website/versioned_docs/version-0.70/react-18-and-react-native.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility.md
While working on some updates for docs/accessibility.md I noticed that a couple of words inside the docs were misspelled, this gave me the idea to test other files as well using the VS Code extension [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) which unveiled a few other typos.
> chore: Fix documentation typos

- docs/_getting-started-windows-android.md
as `openjdk11` is [Deprecated](https://community.chocolatey.org/packages/openjdk11) 
update `openjdk11` to [`microsoft-openjdk11`](https://community.chocolatey.org/packages/microsoft-openjdk11)
```diff
- choco install -y nodejs-lts openjdk11
+ choco install -y nodejs-lts microsoft-openjdk11
```
#3379
> update to microsoft-openjdk11

- docs/text-style-props.md
This PR updates the `fontVariant` style prop documentation to also support space-separated strings.
Related to https://github.com/facebook/react-native/commit/09d420707f586710bb0f00981aca989b00f8761a
> feat: Update fontVariant supported types docs

- docs/accessibility.md
This adds documentation regarding all aria Web props recently added to react-native due to  https://github.com/facebook/react-native/issues/34424. The description of most of these items was based on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes.
Related to https://github.com/facebook/react-native/commit/98d84e571df64b00e1ed3484923a1d8169dcfda1, https://github.com/facebook/react-native/commit/ebdb23c6e060897112b060c25172135d50c78cd3, https://github.com/facebook/react-native/commit/720cdbc658aa0b513d106526eb81d749fa957c99, https://github.com/facebook/react-native/commit/f353119113d6fc85491765ba1e90ac83cb00fd61 and https://github.com/facebook/react-native/commit/7ea54a408734ccde9ee01a12942bf5722e9cf7c1
> feat: Add aria Web props to Accessibility docs

- docs/alert.md
Docs for https://github.com/facebook/react-native/pull/32538
> Add the "preferred" AlertButtonStyle

- docs/build-speed.md
Soft links require an absolute path to work properly.  Before this change, `which /usr/local/bin/gcc` still resolves to `/usr/bin/gcc` even with `/usr/local/bin` being earlier in the `$PATH` variable.
> Fixing symbolic links

- docs/text.md
- docs/textinput.md
Update Text docs according to the change from https://github.com/facebook/react-native/pull/31272
Thanks!
> docs: added lineBreakStrategyIOS to text and text-input

- docs/platform-specific-code.md
- website/versioned_docs/version-0.60/platform-specific-code.md
- website/versioned_docs/version-0.61/platform-specific-code.md
- website/versioned_docs/version-0.62/platform-specific-code.md
- website/versioned_docs/version-0.63/platform-specific-code.md
- website/versioned_docs/version-0.64/platform-specific-code.md
- website/versioned_docs/version-0.65/platform-specific-code.md
- website/versioned_docs/version-0.66/platform-specific-code.md
- website/versioned_docs/version-0.67/platform-specific-code.md
- website/versioned_docs/version-0.68/platform-specific-code.md
- website/versioned_docs/version-0.69/platform-specific-code.md
- website/versioned_docs/version-0.70/platform-specific-code.md
Superseeds #3127
Update the "require" word used in two places on the page, backport the correction to versioned docs.
> Platform Specific Code: tweak wording

- docs/build-speed.md
- website/versioned_docs/version-0.68/build-speed.md
- website/versioned_docs/version-0.69/build-speed.md
- website/versioned_docs/version-0.70/build-speed.md
Follow up for #3329
Backport the change performed on the latest doc to the versioned files + macOS name correction.
> Speeding up Build: backport ccache command change to versioned docs

- docs/hermes.md
- docs/javascript-environment.md
- website/architecture/bundled-hermes.md
- website/versioned_docs/version-0.60/hermes.md
- website/versioned_docs/version-0.61/hermes.md
- website/versioned_docs/version-0.61/javascript-environment.md
- website/versioned_docs/version-0.62/hermes.md
- website/versioned_docs/version-0.62/javascript-environment.md
- website/versioned_docs/version-0.63/hermes.md
- website/versioned_docs/version-0.63/javascript-environment.md
- website/versioned_docs/version-0.64/hermes.md
- website/versioned_docs/version-0.64/javascript-environment.md
- website/versioned_docs/version-0.65/hermes.md
- website/versioned_docs/version-0.65/javascript-environment.md
- website/versioned_docs/version-0.66/hermes.md
- website/versioned_docs/version-0.66/javascript-environment.md
- website/versioned_docs/version-0.67/hermes.md
- website/versioned_docs/version-0.67/javascript-environment.md
- website/versioned_docs/version-0.68/hermes.md
- website/versioned_docs/version-0.68/javascript-environment.md
- website/versioned_docs/version-0.69/hermes.md
- website/versioned_docs/version-0.69/javascript-environment.md
- website/versioned_docs/version-0.70/hermes.md
- website/versioned_docs/version-0.70/javascript-environment.md
Hermes is the default as of React Native 0.70, and bundled Hermes was introduced in 0.69.
The versioned docs for 0.69 and 0.70 have been updated to remove the explicit mention of their own version numbers:
- When looking at versions of the docs for 0.69 and later, we just mention that Hermes is now bundled into RN.
- When looking at versions of the docs for 0.70 and later, we just mention that Hermes is now the default.
And for the versioned docs for 0.61 - 0.69:
- When enabling Hermes, no need to specify 0.60.4 as the minimum, as the docs are for version 0.61 and up.
Since the docs are versioned, we do not need to call out when something was introduced unless it is directly relevant, e.g. we still make the caveat that Hermes by default is a 0.70+ feature under "Enabling Hermes on Older …
> Update Hermes docs with recent changes

- docs/image.md
- docs/text-style-props.md
- docs/transforms.md
- docs/view-style-props.md
- docs/view.md
This PR updates documentation to include all the missing props related to https://github.com/facebook/react-native/issues/34425.
- Updates Image docs to include `objectFit` (https://github.com/facebook/react-native/commit/b2452ab216e28e004dc625dd8e1ad32351a79be9)
- Updates TextStyle `fontWeight` to accept number (https://github.com/facebook/react-native/commit/f1c1f8116ba1cfa9d10c5b8c30b98b796047b9c2)
- Updates `transforms` docs to include space-separated string examples (https://github.com/facebook/react-native/commit/34db2d4e939cab4c37e5a8e6ec95800cce227c98)
- Add `pointerEvents` to View Style Props docs (https://github.com/facebook/react-native/commit/5c109b37a42d16b35d8ddf2371d42d47f4d49fb2)
> feat: Update documentation regarding W3C Web Styles 

- docs/accessibility.md
- docs/text.md
- docs/touchablewithoutfeedback.md
- docs/view.md
Follow up PR of https://github.com/facebook/react-native-website/pull/3396. 
This adds documentation to `View`, `Text` and `TouchableWithoutFeedback` regarding all aria Web props recently added to react-native due to  https://github.com/facebook/react-native/issues/34424. The description of most of these items was based on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes.
Related to https://github.com/facebook/react-native/commit/98d84e571df64b00e1ed3484923a1d8169dcfda1, https://github.com/facebook/react-native/commit/ebdb23c6e060897112b060c25172135d50c78cd3, https://github.com/facebook/react-native/commit/720cdbc658aa0b513d106526eb81d749fa957c99, https://github.com/facebook/react-native/commit/f353119113d6fc85491765ba1e90ac83cb00fd61 and …
> feat: Add aria Web props to component docs

- docs/image.md
This PR adds the `alt` prop to the Image documentation
Related to https://github.com/facebook/react-native/commit/71fda5e0c2093380d08761c945f1e3029af6697f
> feat: Add alt prop to Image docs

- docs/textinput.md
This PR updates the `autoComplete` prop documentation from `TextInput` to unify values for Android (autoComplete) and iOS (textContentType) with Web (autoComplete).
Related to https://github.com/facebook/react-native/commit/73abcba40f305634efaafea8969cdfeb4982df0e
> feat: Update TextInput autoComplete docs [w3c]

- website/src/css/customTheme.scss
Docusaurus have a feature for autogenerated category pages, this seems to work well in our case, but since we customize website appearance some style tweaks and correction have to be made to allow usage of this feature.
This PR adds the required styles changes for the autogenerated category pages, so those page no longer overflow the layout and shrinks the content.
Additionally, I had to correct the sidebar entry styles, since for the clickable categories the structure of element is a bit different.
The changes have been tested by running docs website locally.
> global style tweaks for the category pages feature

- docs/virtualizedlist.md
VirtualizeList internally uses contexts to allow buidling tree of nested VirtualizedList refs. This is an API really meant to only be called by VirtualizedList, but is public so other VirtualizedList instances can call it. The object shape, parameters, etc can change (and did change a bit in 0.71). Remove it from documentation, since folks should not rely on it.
> Don't document VirtualizedList context

- website/showcase.json
Super small PR to add to the MSFT apps a link to our new official blogpost https://devblogs.microsoft.com/react-native/. We are still in the process of finalising the look and content and I hope that overtime we'll be able to point the different apps to different blogposts, but for now this should be enough :)
> chore(showcase): add links to MSFT devblog

- plugins/remark-snackplayer/src/index.js
This makes a couple changes in preparation for TypeScript examples. Going through 20 pages for core components, most examples can be shifted to be both JavaScript and strict TypeScript. Some are not compatible as both, and need to be separated as JS examples vs TS examples.
**Add parameter to SnackPlayer blocks**
Snack defaults a code block to represent a file named [`App.js`](https://github.com/expo/snack/blob/main/docs/url-query-parameters.md#parameters). This extension effects how the file is parsed during bundling, and the syntax highlighting it is given in the editor. We allow passing the extension, so that specific examples can specifically target JS vs TS. This directive will later be used to determine how the file is used during linting.
**Change default example extension to …
> Allow TypeScript in Snacks (and optional "ext" parameter)

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/native-components-android.md
- docs/testing-overview.md
- docs/typescript.md
- website/core/TabsConstants.js
This change updates the main TypeScript page with new instructions for 0.71, where TypeScript is the default language, and RN types are included by default.
This does not yet update samples for TS, which is still a work in progress. I also chose to omit information about the 0.70 to 0.71 migration, since it seems like it might make more sense in either the release announcement or a separate blog post instead of long-term in the documentation, but I would be open to feedback on that.
> Update TypeScript Page and References to TypeScript

- docs/the-new-architecture/pillars-fabric-components.md
There was a typo in `CenteredTextPackage.java` it should be `CenteredTextPackage` and not `RTNCenteredTextPackage`.
> Fabric component example java classname typo fixed

- docs/typescript.md
https://github.com/facebook/react-native/pull/35529 simplifies the ESLint config of the template a bit more compared to the previous version, more directly derived from the community template. I expect it will be cherry-picked into 0.71, so this updates the corresponding TS documentation on adding TS to a non-TS project to remove the extra differences.
> Update TS Instructions for Simplified Template

- docs/_integration-with-exisiting-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
Before .71 we need to update a couple of pages on the website. This is one of the first one: "Integration with Existing Apps" and it handles the changes implemented as part of:
- https://github.com/react-native-community/discussions-and-proposals/pull/508
> [0.71] Update page on Integration with Existing Apps for 71

- docs/getting-started.md
The guide needs to mention how to install the expo cli else the `expo start` command won't run, i have added it.
> Updated the installation instructions

- docs/direct-manipulation.md
- docs/drawerlayoutandroid.md
- docs/easing.md
- docs/flatlist.md
- docs/flexbox.md
- package.json
- scripts/lint-examples/patches/react-native+0.71.0-rc.0.patch
- yarn.lock
This updates examples so that all documents starting with A-F pass typechecking.
This needed to add a patch-package for incorrect types that should be temporary (will see if we can cherry-pick into 0.71).
Tested by `yarn tsc-examples` and visiting the pages edited.
> Typescriptify Examples A-F

- docs/handling-touches.md
- docs/image-style-props.md
- docs/improvingux.md
- docs/interactionmanager.md
- docs/intro-react.md
This makes examples in documents starting from H-J valid for TypeScript. This leaves 36 examples left. Verified these pages locally after the change.
> Typescriptify Examples H-J

- docs/keyboard.md
- docs/layout-props.md
- docs/linking.md
- docs/modal.md
- docs/network.md
- docs/panresponder.md
- docs/props.md
This makes examples in documents starting from K-P valid for TypeScript. This leaves 23 examples left. Verified these pages locally after the change.
> Typescriptify Examples K-P

- website/snackPlayerInitializer.js
Switching pages on mobile currently causes a blank snack example to show.
This is root caused to a workaround on the `onRouteUpdate` callback to read the DOM after mutation, which seems to work on desktop, but not on the mobile version of the site. This change moves to a newer lifecycle method called after the document is rendered to the DOM, which fixes the issue.
> Fix rendering of snacks on route update on mobile

- docs/refreshcontrol.md
- docs/sectionlist.md
- docs/segmentedcontrolios.md
- docs/settings.md
- docs/shadow-props.md
- docs/share.md
- docs/state.md
- docs/statusbar.md
- docs/stylesheet.md
- package.json
- scripts/lint-examples/patches/react-native+0.71.0-rc.0.patch
This makes examples in documents starting from Q-S valid for TypeScript. This leaves 9 examples left. Verified these pages locally after the change.
> Typescriptify Examples Q-S

- docs/react-native-gradle-plugin.md
- website/sidebars.json
I'm adding a page on the Gradle Plugin so we can use it as reference for documentation and to help user with configuration as we can deeplink to each config key now.
I've also added a section on how to use flavors/variants and short list of technical details of what RNGP is doing (this could be useful for brownfield users).
> [0.71] Add page on React Native Gradle Plugin for 71

- docs/build-speed.md
- docs/new-architecture-app-intro.md
- docs/new-architecture-library-intro.md
- docs/new-architecture-troubleshooting.md
- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
This PR contains all the updates for the New Architecture docs shipping with 0.71:
- I've removed all the App setup section as now is encapsulated inside RNGP
- I've clarified a bit the build-speed page as with .71 will be less relevant
- Libraries don't need to specify a `AndroidManifest.xml` with AGP 7.x anymore and can use `namespace` instead. One file less to create.
> [0.71][Android] Update pages on New Architecture for 71

- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.68/new-architecture-library-ios.md
- website/versioned_docs/version-0.69/new-architecture-library-ios.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
Hey, 
This PR removes explicit folly versions as specifying them is not needed anymore.
> fix: remove explicit folly version as it's not needed anymore

- docs/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
Hey, 
This PR fixes the syntax highlighting of objective-c files for fabric guide.
> chore: fix objective-c syntax highlighting on fabric guide

- docs/the-new-architecture/cxx-custom-types.md
The example given uses C++20 syntax which MSVC does not support yet.
It works in clang with some special compiler flags. 
Updated sample also works in C++17 with MSVC.
Verified that example compiles in Xcode
> Make C++ TM example work with C++17

- docs/direct-manipulation.md
This removes the deprecation notice at the top of "Direct Manipulation".
For the foreseeable future, `setNativeProps` will continue providing value in high frequency, performance-sensitive scenarios such as animations. Until we have a reasonable alternative, there is no reason for the deprecation notice to be displayed on this page.
This is additionally influenced by our ongoing work to implement `setNativeProps` in the New Architecture.
> Remove `NativeDeprecated` from "Direct Manipulation" page

- docs/native-modules-android.md
- website/versioned_docs/version-0.65/native-modules-android.md
- website/versioned_docs/version-0.66/native-modules-android.md
- website/versioned_docs/version-0.67/native-modules-android.md
- website/versioned_docs/version-0.68/native-modules-android.md
- website/versioned_docs/version-0.69/native-modules-android.md
- website/versioned_docs/version-0.70/native-modules-android.md
Improve Android Native Module examples for using `addListener`  and `removeListeners` with pattern that mimics the one in RCTEventEmitter on iOS. The current examples are not self explanatory, as `removeListeners` is called with not-obvious `count` parameter. I've sent 1 hr figuring out how all of these should work and want to save other readers from having to do the same research.
> fix: improve examples for Android Native Modules addListener/removeListeners

- docs/native-modules-setup.md
- website/versioned_docs/version-0.64/native-modules-setup.md
- website/versioned_docs/version-0.65/native-modules-setup.md
- website/versioned_docs/version-0.66/native-modules-setup.md
- website/versioned_docs/version-0.67/native-modules-setup.md
- website/versioned_docs/version-0.68/native-modules-setup.md
- website/versioned_docs/version-0.69/native-modules-setup.md
- website/versioned_docs/version-0.70/native-modules-setup.md
When running a command with `npx`, there's no guarantee that it'll use the latest version of the package. If the package is already cached, it will use the cached version instead (see https://github.com/npm/cli/issues/4108). This can result in users getting a project based on an outdated template which might be missing any fixes.
This change adds `@latest` to the command to ensure that the latest version is always used. We already do this in Bob's documentation: https://github.com/callstack/react-native-builder-bob
> Add @latest when creating library to ensure up-to-date template

- docs/_integration-with-exisiting-apps-swift.md
Updated instructions to add React Native to existing iOS app using swift
- Added window reference which is to be included in the AppDelegate
- Updated Podfile instructions 
Correct documentation to include window reference when integrating into existing iOS swift project. If a window reference is not included in iOS swift project the app will crash with error Thread 1: "-[ProjectName.AppDelegate window]: unrecognized selector sent to instance 0x600001f9dd60"
> Include window reference for iOS swift projects

- docs/new-architecture-library-intro.md
Updates the New Architecture migration guide in the following ways:
- Removed the `findNodeHandle` and `measure*()` migration steps.
- Backward compatibility landed in https://github.com/facebook/react-native/commit/455ca8cfaf8060def528425e2a58b19930009fdd.
- Rewrote the introduction for this section of the migration steps.
- Added more details on our plans to eventually deprecate `UIManager`, but to continue supporting it (and the development is actively ongoing).
- Omit references to the deprecation of `findNodeHandle`.
- In lieu of removing the code snippets from the obsolete `measure*()` section, I've included a code snippet demonstrating usage of the native component instance methods.
> Remove `findNodeHandle` and `measure*()` New Architecture Migration Steps

- docs/typescript.md
Noticed the diffs used here are out of date compared to the RN template (even the previous TS one). Update based on the current out-of-the-box files.
> Update diffs in TypeScript path alias instructions

- website/contributing/release-branch-cut-and-rc0.md
This PR improves the contributing section, listing a set of heuristic we follow to adjust the changelog when we are preparing a new release of React Native.
> [Release] Add heuristic on how to manually handle the changelog

- docs/keyboard.md
- website/versioned_docs/version-0.71/keyboard.md
Fixes issues in docs/keyboard.md where methods have an incorrect heading (and hence sidebar title).
This is my first contribution. If I made a mistake, please do let me know and I will resolve it ASAP.
> fix errors in keyboard.md

- docs/signed-apk-android.md
CLI v10 compatible with v0.71 deprecated `--variant`
> Replace deprecated `--variant` with `--mode`

- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
See https://github.com/facebook/react-native/issues/35832#issuecomment-1397125019.
This also aligns with existing code examples which use extensionless imports (more portable).
> Fix import in Turbo Native Modules sample code

- docs/new-architecture-library-ios.md
- docs/the-new-architecture/pillars-codegen.md
- docs/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/new-architecture-library-ios.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Follow up to #3526 & #3525.
It looks like we are mentioning the artifact codegen script file in few docs, so I have updated all of the occurrences in unversioned and 0.71 docs.
> correct artifact codegen script name

- docs/_getting-started-macos-ios.md
For users of NVM ([a very popular Node.js version manager](https://2022.stateofjs.com/en-US/other-tools/#utilities)) and zsh (which is now the default shell on macOS), I want to add an info box to help workaround a common issue of the current React Native template, to help Xcode resolve the correct path for Node.js when invoking shell scripts.
On a related note, I've commented on an issue in the NVM repository to update the install.sh script to have this happen automatically for new users: https://github.com/nvm-sh/nvm/issues/338#issuecomment-1403559575
> Adding an info box on NVM and zsh to MacOS + iOS

- docs/headless-js-android.md
Mention that the timeout is in milliseconds.
Time units are important and may cause confusion!
Source: https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/jstasks/HeadlessJsTaskConfig.java#L43
> Update headless-js documentation

- website/blog/2023-01-27-71rc1-android-outage-postmortem.md
Sharing the outcome of the outage we had for Android builds in November 2022
> [Blogpost] React Native 0.71-RC0 Android outage postmortem

- docs/speeding-ci-builds.md
- website/sidebars.json
Adding a page to describe how to speed up CI builds excluding Flipper and how to handle transitive dependencies. This complete the work started in this 
[PR](https://github.com/facebook/react-native/pull/35686) by @retyui.
> Add page to speed up CI builds

- docs/typescript.md
I noticed that `compilerOptions` is not used in the `tsconfig.json` sample code.
It should be like here; https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping
I also made a minor appearance fix for the `babel.config.js` file.
> Fix "tsconfig.json" and "babel.config.js" example code

- docs/props.md
- website/versioned_docs/version-0.71/props.md
> rename type and method from GreetingsProps to GreetingProps

- docs/native-modules-android.md
the problem was to write and use  NativeEventEmitter in the new syntax (for new developpers) with useEffect
I solved and publish that code version tested
> new syntax in native modules android

- docs/pressable.md
- website/versioned_docs/version-0.68/pressable.md
- website/versioned_docs/version-0.69/pressable.md
- website/versioned_docs/version-0.70/pressable.md
- website/versioned_docs/version-0.71/pressable.md
I found `onHoverIn` and `onHoverOut ` is implemented  in [Presssable component](https://github.com/facebook/react-native/blob/d5e6d9cecd1a8b02d47c4dfaffc550167b093b32/Libraries/Components/Pressable/Pressable.js#L130-L138),
so I added description about those props to docs.
Diff's screenshot:
> Add description about onHoverIn/onHoverOut on Pressable

- package.json
- yarn.lock
As the title says:
https://github.com/hapijs/formula/security/advisories/GHSA-c2jc-4fpr-4vhg
> Bump @sideway/formula to address CVE-2023-25166

- docs/new-architecture-app-intro.md
- website/versioned_docs/version-0.71/new-architecture-app-intro.md
This PR fix some unprecise information present in the current documentation.
> Update Migration to the New Architecture section

- website/contributing/how-to-contribute-code.md
Fixes the redirection to the "/contributing/how-to-open-a-pull-request" page from the "contributing/how-to-contribute-code" page.
> fix the redirection to open pull request page

- docs/text.md
- website/versioned_docs/version-0.66/text.md
- website/versioned_docs/version-0.67/text.md
- website/versioned_docs/version-0.68/text.md
- website/versioned_docs/version-0.69/text.md
- website/versioned_docs/version-0.70/text.md
- website/versioned_docs/version-0.71/text.md
The [`Text`](https://reactnative.dev/docs/text) page of the documentation doesn't explain that the components embarks also the `onPressIn` and `onPressOut` props. 
Related to the issue [`#3563`](https://github.com/facebook/react-native-website/issues/3563)
> add onPressIn and onPressOut props on text page

- docs/new-architecture-library-intro.md
- website/versioned_docs/version-0.68/new-architecture-library-intro.md
- website/versioned_docs/version-0.69/new-architecture-library-intro.md
- website/versioned_docs/version-0.70/new-architecture-library-intro.md
- website/versioned_docs/version-0.71/new-architecture-library-intro.md
Hey, 
This PR updates misleading codegen types event description and also adds `UnsafeObject` helper type to the list.
> docs: update Codegen types description

- website/contributing/how-to-build-from-source.md
This greatly simplifies the build from source page and brings it up to standard to 0.71+
> Update the "Build from source" page

- docs/the-new-architecture/cxx-cxxturbomodules.md
- website/versioned_docs/version-0.71/the-new-architecture/cxx-cxxturbomodules.md
Hey! 
This PR updates links and init command for turbo modules docs.
> docs: update links and init command to 0.71

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
Documents the minimum Node version increasing from 14 to 16 from the next release, as per https://github.com/facebook/react-native/pull/36217
> Docs: RN's minimum Node version 14->16

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/the-new-architecture/use-app-template.md
- website/versioned_docs/version-0.71/_getting-started-linux-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-windows-android.md
- website/versioned_docs/version-0.71/the-new-architecture/use-app-template.md
`npx react-native init` [is not guaranteed](https://github.com/npm/cli/issues/4108) to pull in `react-native@latest`. When the bootstrapping CLI is mismatched from the react-native version it tries to install, it may not work correctly.
Currently, this means if you previously installed RN 0.70, you may end up using `react-native init` from RN 0.70, using CLI `9.2.1`, to bootstrap your React Native 0.71 app. This seems to lead to the CLI not correctly generating the template app. Most visibly, files like `_rbenv` are not converted to `.rbenv`.
This seems like a CLI bug. `--version` exists to allow CLI to bootstrap different RN version, so it should support this scenario. But we can change the example to one that prevents users from hitting it.
> Specify Explicit React Native Version For Init

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/getting-started.md
- website/versioned_docs/version-0.71/_getting-started-linux-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-windows-android.md
- website/versioned_docs/version-0.71/getting-started.md
For RN 0.71, similar to previous versions, when creating a new project using `npx create-expo-app` a JavaScript project template is used by default. This includes an **App.js**, not an **App.tsx**.
RN CLI projects though will include an **App.tsx**, so this PR updates those quickstarts to point to the right file as well.
This PR makes sure users are pointed to the correct file.
> docs: fix app.js/app.tsx references in quickstart

- docs/new-architecture-library-intro.md
- website/versioned_docs/version-0.71/new-architecture-library-intro.md
Fixes #3515
This fixes a few cases where Flow-specific examples are represented as TypeScript. Some of these were present in the original guide, and others I made worse during my mass conversion of inline code examples to TypeScript.
I think some of these were made to be `.ts` to appease syntax highlighting/formatting, but it looks like adding `@flow` is enough to inform both prettier over markdown, and prism syntax highlighting to render correctly. We also change some `.ts` to `.tsx` when components are used.
> Fix Flow/TypeScript Mismatches in New Architecture Library Intro

- website/contributing/bots-reference.md
This fixes a dead link on `/contributing/bots-reference` in the `label-actions` section.
> Updating dead link for label-action workflow

- docs/the-new-architecture/cxx-cxxturbomodules.md
For me, there is no clear reason to not keep the same style for the complete example project structure
Therefore, I added the missing vertical line
> fix: add vertical line in project structure

- docs/_getting-started-macos-android.md
version 0.71.3 uses Android SDK version 33. this updates the documentation to reflect this change
> fix: update android sdk version

- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.70/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- Updated docs to reflect the change to using a `Gemfile` instead of `.ruby-version`.
- Updated the links for 0.70 and 0.71 to the correct tagged file.
Closes #3592
> fix: ruby version link (#3592)

- docs/_getting-started-macos-ios.md
We now support Ruby versions >= 6.8.10, <= 3.2.0 (facebook/react-native#36281). This reduces some of the noise in our docs by removing error prone steps on setting up a Ruby Version Manager.
> docs: remove references to Ruby Version Management

- website/package.json
react-native-dict.json was not called in #3595.
> fix: case-police use local dictionary

- docs/appearance.md
This change is to support a new feature in Appearance called `setColorScheme`.
https://github.com/facebook/react-native/pull/36122
> Add docs for `setColorScheme`

- docs/image-style-props.md
- docs/image.md
- website/versioned_docs/version-0.71/image-style-props.md
- website/versioned_docs/version-0.71/image.md
PR related to the Issue [`#3579`](https://github.com/facebook/react-native-website/issues/3579).
As the commit has been released on the 0.71 version, so I did the changes on the _next_ and _0.71_ versions
> Move objectFit property explanation from Image page to Image Style Props one

- docs/_getting-started-windows-android.md
React Native is increasing the minimum Node JS requirement from 14 to 16 in facebook/react-native#36217, facebook/react-native-website#3580 for 0.72 onwards. Updating our Windows documentation to reflect the same as macOS.
> Update getting started Windows documentation to reflect min Node version

- docs/_getting-started-windows-android.md
Updating Setting up the development environment in Windows documentation to reflect ANDROID_SDK version bump.
React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Updating our Windows documentation to reflect the same as macOS.
> Update getting started in Windows

- docs/_getting-started-windows-android.md
Updating Setting up the development environment in Windows documentation to reflect Android version bump.
React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Updating our Windows documentation to reflect the same for corresponding Android version
https://github.com/facebook/react-native-website/pull/3605
> Update getting started in Windows to reflect Android version

- docs/_getting-started-macos-ios.md
We don't have a Ruby section anymore.
> fix: cocoapods mentioned old ruby section

- docs/_getting-started-linux-android.md
Updating Setting up the development environment in Linux documentation to reflect ANDROID_SDK version bump.
React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Correspondingly changing the Android version. Updating our documentation to reflect the same as macOS & Windows
Found in https://github.com/facebook/react-native-website/pull/3605
> Update Getting Started in Linux to reflect ANDROID_SDK bump

- docs/_getting-started-macos-android.md
Updating Setting up the development environment in MacOS documentation to reflect Android version bump.
React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Updating our MacOS documentation to reflect the same for corresponding Android version.
#3605
> fix : Getting started in Mac to reflect Android version

- website/versioned_docs/version-0.71/_getting-started-windows-android.md
Updating Setting up the development environment in Windows documentation to reflect ANDROID_SDK version bump for 0.71
React Native is increasing the minimum ANDROID_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.71 onwards. Correspondingly changing the Android version.
Follow-up to https://github.com/facebook/react-native-website/pull/3605
> Update getting started in Windows to reflect ANDROID_SDK bump for 0.71

- website/versioned_docs/version-0.71/_getting-started-macos-android.md
Updating Setting up the development environment in MacOS documentation to reflect ANDROID_SDK version bump for 0.71
React Native is increasing the minimum ANDROID_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.71 onwards. Correspondingly changing the Android version.
Follow-up to https://github.com/facebook/react-native-website/pull/3611
> Update getting started in MacOS to reflect ANDROID_SDK bump for 0.71

- website/versioned_docs/version-0.71/_getting-started-linux-android.md
Updating Setting up the development environment in Linux documentation to reflect ANDROID_SDK version bump for 0.71
React Native is increasing the minimum ANDROID_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.71 onwards. Correspondingly changing the Android version. 
Follow-up to https://github.com/facebook/react-native-website/pull/3612
> Update getting started in Linux to reflect ANDROID_SDK bump for 0.71

- website/package.json
- website/src/css/customTheme.scss
- website/src/pages/showcase.js
- website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
- yarn.lock
Upgrade these dependencies, so we can support deep-linking in [Tabs](https://deploy-preview-8225--docusaurus-2.netlify.app/docs/markdown-features/tabs/?current-os=ios#query-string).
> chore: upgrade docusaurus to 2.3.1 & react 18.2

- docs/virtualizedlist.md
Currently landing a change which adds `CellRendererProps` as a public type, and updates the description for `CellRendererComponent`. This updates the website in line.
> Update CellRendererComponent documentation

- docs/intro-react.md
React related links point to old site reactjs.org whereas new site is being used react.dev This PR introduces links to react.dev proper pages.
> Update React links to react.dev site

- docs/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
When following the guide to creating [Fabric Native Components](http://localhost:3000/docs/the-new-architecture/pillars-fabric-components) I ran into an issue where my newly crated native code wasn't synced over correctly.
In the docs,  I was told to `yarn add` in order to test the codegen.
https://github.com/facebook/react-native-website/blob/80ee7b3152a0bac14d13fc6a200c0a3ff9d2aa38/docs/the-new-architecture/pillars-fabric-components.md?plain=1#L359-L368
At the last step "5. Adding the Fabric Native Component To Your App", we tell users to `yarn add` again.
https://github.com/facebook/react-native-website/blob/80ee7b3152a0bac14d13fc6a200c0a3ff9d2aa38/docs/the-new-architecture/pillars-fabric-components.md?plain=1#L895-L902
If the local package is already there, the newly created native …
> Fix fabric native component example

- docs/textinput.md
- website/versioned_docs/version-0.71/textinput.md
This PR clarifies a breaking change with `textContentType` from changes in 0.71 as discussed here: https://github.com/facebook/react-native/issues/36229 and specifically acts on plan from this [comment](https://github.com/facebook/react-native/issues/36229#issuecomment-1470468374)
This can only be landed after we release 0.71.5
> `textContentType` breaking change clarification

- docs/_integration-with-existing-apps-objc.md
- docs/_integration-with-existing-apps-swift.md
- docs/animations.md
- docs/button.md
- docs/communication-ios.md
- docs/debugging.md
- docs/direct-manipulation.md
- docs/flatlist.md
- docs/image.md
- docs/imagebackground.md
- docs/inputaccessoryview.md
- docs/native-components-ios.md
- docs/native-modules-android.md
- docs/native-modules-ios.md
- docs/new-architecture-library-ios.md
- docs/panresponder.md
- docs/platformcolor.md
- docs/pressable.md
- docs/scrollview.md
- docs/speeding-ci-builds.md
- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
- docs/the-new-architecture/cxx-custom-types.md
- docs/the-new-architecture/cxx-cxxturbomodules.md
- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
- docs/troubleshooting.md
- docs/usecolorscheme.md
- docs/viewtoken.md
Refs #3634
This is a first PR in series, which aims to resolve the broken link issues after core repository restructurization.
It targets only unversioned docs links and updated them to point to the latest code (located at `main`).
> fix broken links in unversioned docs

- docs/more-resources.md
Just changed the link to point to the new React documentation at https://react.dev/learn
> Update More Resources React's Documentation link

- docs/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
file  CenteredText.java in class name is CenteredText. However, in the CenteredTextManager.java file, we used the name RTNCenteredText instead of CenteredText. This is causing issues when trying to create a fabric component, as the build fails when updating the class name to CenteredText. Everything works fine when using the correct class name.
> Naming inconsistency causing build failure in Android Java file.

- docs/scrollview.md
https://github.com/facebook/react-native/pull/35049 added support for this on Android
> Update platform label for `maintainVisibleContentPosition`

- scripts/update-redirect/index.js
- scripts/update-redirect/package.json
- website/package.json
- website/static/_redirects
Allows our CLI tool to user the latest version in the path, and gracefully handles this server side:
https://reactnative.dev/docs/0.71/X -> https://reactnative.dev/docs/X
Our CLI tooling will generate direct links based on OS, platform and version of React Native.  If you're running the latest version, our current docs don't support a version number infix.  For more details of why see [here](https://github.com/react-native-community/cli/pull/1902#issuecomment-1503094396) where the issue was originally raised.
Options that weren't better (IMHO):
- using the Docusaurus plugin-client-redirects → doesn't like non-existent paths (/0.71/) and would generate a bunch of placeholder html files with client side redirects.
- CLI checks the current version (failing which just default to top-level …
> feat: redirect current version urls

- docs/flexbox.md
For flexGrow functionality, it was written as `how any space within a container` and it should be `how much space within a container`
> Updated typo in flexGrow functionality

- docs/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-turbomodules.md
Between the Java and Kotlin code snippets for the Turbo Module example on this [page](https://reactnative.dev/docs/the-new-architecture/backward-compatibility-turbomodules?android-language=kotlin), the method names are different, which can cause some confusion to readers who are trying to compare it with the Native Module example.
Changes:
* Renamed the `add` method to `foo`
* Renamed the `CalculatorModule` class constructor to `MyModule` in the Java sample
> Update Kotlin code snippet for consistency with Java

- docs/hermes.md
- docs/publishing-to-app-store.md
- docs/running-on-device.md
- website/versioned_docs/version-0.71/hermes.md
- website/versioned_docs/version-0.71/publishing-to-app-store.md
- website/versioned_docs/version-0.71/running-on-device.md
i recently updated to react-native 0.71 and started receiving these console errors:
android:
`warn "variant" flag is deprecated and will be removed in future release. Please switch to "mode" flag.`
ios:
```
warn --configuration has been deprecated. Use --mode instead.
warn Parameters were automatically reassigned to --mode on this run.
```
i found this pr which updates the docs in a single file: https://github.com/facebook/react-native-website/pull/3522
i checked and there were a few more places using the `--variant` and `--configuration` flags, this pr changes those too. there are a few fixes for the versioned_docs/0.71, and also updates to the /docs folder so future versions are also correct.
> Replace deprecated `--variant` and `--configuration` with `--mode`

- sync-api-docs/magic.js
As asked to be done in this PR: https://github.com/facebook/react-native/pull/37053/
> Remove reference to `generatedComponentApiDocs.js`

- docs/signed-apk-android.md
Hey! 👋
In this PR I changed manual command with CLI command `build-android`, which was [introduced](https://github.com/react-native-community/cli/pull/1739) some time ago.
> chore: replace manual command with CLI command

- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Resolves: #3681 
The current docs for [Fabric Native Components](https://reactnative.dev/docs/next/the-new-architecture/pillars-fabric-components?android-language=kotlin#the-buildgradle-file) and [Turbo Native Modules](https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#the-buildgradle-file) are missing Kotlin Gradle Plugin in the build.gradle file. As a result, during the compilation process, any Kotlin files included in the project are ignored.
Test:
https://deploy-preview-3711--react-native.netlify.app/docs/next/the-new-architecture/pillars-fabric-components?android-language=kotlin#the-buildgradle-file
> docs: add Kotlin Gradle plugin in build.gradle

- docs/scrollview.md
Just correcting a minor error in the documentation for the `ScrollView` component.
> Update `ScrollView` documentation

- docs/shadow-props.md
- docs/text-style-props.md
- scripts/lint-examples/package.json
- website/versioned_docs/version-0.62/shadow-props.md
- website/versioned_docs/version-0.62/text-style-props.md
- website/versioned_docs/version-0.63/shadow-props.md
- website/versioned_docs/version-0.63/text-style-props.md
- website/versioned_docs/version-0.64/shadow-props.md
- website/versioned_docs/version-0.64/text-style-props.md
- website/versioned_docs/version-0.65/shadow-props.md
- website/versioned_docs/version-0.65/text-style-props.md
- website/versioned_docs/version-0.66/shadow-props.md
- website/versioned_docs/version-0.66/text-style-props.md
- website/versioned_docs/version-0.67/shadow-props.md
- website/versioned_docs/version-0.67/text-style-props.md
- website/versioned_docs/version-0.68/shadow-props.md
- website/versioned_docs/version-0.68/text-style-props.md
- website/versioned_docs/version-0.69/shadow-props.md
- website/versioned_docs/version-0.69/text-style-props.md
- website/versioned_docs/version-0.70/shadow-props.md
- website/versioned_docs/version-0.70/text-style-props.md
- website/versioned_docs/version-0.71/shadow-props.md
- website/versioned_docs/version-0.71/text-style-props.md
- yarn.lock
Resolves: #3715
React Native 0.72 removes the deprecated Slider component. Several of the Expo Snack based examples still use it, which we need to clean up to be able to upgrade the documents to 0.72.
This PR updates all the usages of Slider to use @react-native-community/slider community package
> docs: replace Slider usages to use @react-native-community/slider

- docs/datepickerios.md
- docs/flexbox.md
- docs/progressviewios.md
- scripts/lint-examples/.eslintrc.js
- scripts/lint-examples/package.json
- scripts/lint-examples/src/lintExamples.js
- yarn.lock
This bumps the types and other packages used during linting to match RN 0.72. This ensures the current `docs` are compatible with `0.72` before we cut a version.
> Bump Linting/Typechecking to RN 0.72

- docs/the-new-architecture/backward-compatibility-fabric-components.md
Updates a small grammar fix after reading through the documentation for `Fabric Components as Legacy Native Components`
> fix(backwards-compat-fabric): grammar typo

- plugins/remark-snackplayer/README.md
- plugins/remark-snackplayer/src/index.js
- website/docusaurus.config.js
This feature, added in https://github.com/expo/snack/pull/425 helps us avoid the issue reported by @NickGerleman in https://github.com/expo/snack/issues/422.
With this, we (Expo) can update the devices without affecting the React Native docs. We may do this due to outdated visual appearances or OS versions. Only when updated here, and validated that it doesn't cut anything off, the React Native docs can be updated too.
The cutoff is caused by the height changes in the device preview, and can be controlled here: https://github.com/facebook/react-native-website/blob/d67805884a7c0920dcefc1af5894580984918239/website/src/css/customTheme.scss#L1717
> feature: set fixed device types for Snack

- docs/react-native-gradle-plugin.md
codegenDir uses reactNativeDir in example.
p.s.: spotted it by reading source code of the gradle-plugin 😉.
> docs(gradle-plugin): fix typo for codegen example

- website/docusaurus.config.js
Google's Universal Analytics pipeline will [no longer process data from 1 July 2023](https://support.google.com/analytics/answer/11583528?sjid=12523431476709424134-EU). To continue gather web analytics we need to move over to Google Analytics 4 (GA4).
There are a couple of steps:
> feature: Move to GA4, UA stops working 1 July 2023

- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-updating-packages.md
- website/sidebarsContributing.json
- Updating the release docs after `0.72` branch cut off and RC0 release with the new steps to update and align packages on the new monorepo setup
- Moving the [wiki](https://github.com/facebook/react-native/wiki/Release-and-its-automated-processes) page that explains the new utility commands for updating packages to the website. The wiki page should link to the website documentation once this PR is merged.
> Branch cut updates

- docs/out-of-tree-platforms.md
according to the old discussion at https://github.com/react-native-community/discussions-and-proposals/discussions/487#discussioncomment-2987986 and after the app.js conf talk, it's a good time to add react-native-skia to the website.
> Add react-native-skia to out-of-tree platform list

- docs/scrollview.md
- website/versioned_docs/version-0.64/scrollview.md
- website/versioned_docs/version-0.65/scrollview.md
- website/versioned_docs/version-0.66/scrollview.md
- website/versioned_docs/version-0.67/scrollview.md
- website/versioned_docs/version-0.68/scrollview.md
- website/versioned_docs/version-0.69/scrollview.md
- website/versioned_docs/version-0.70/scrollview.md
- website/versioned_docs/version-0.71/scrollview.md
This defaults to `false`, see https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java#L188
> Correct default of nestedScrollEnabled

- website/contributing/release-candidate-patch.md
- website/contributing/release-stable-patch.md
When doing an RC patch, we should run `yarn bump-all-updated-packages` to ensure that we release the changed packages with the new RC.
> Add step for bumping packages when doing RC patch

- docs/_integration-with-existing-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
- docs/building-for-tv.md
- docs/clipboard.md
- docs/images.md
- docs/interactionmanager.md
- docs/native-components-ios.md
- docs/network.md
- website/blog/2016-03-24-introducing-hot-reloading.md
This is diff update the number of `JS`, `JSX`, `TS` & `TSX` code-blocks to switch to `let` & `const` from `var`.
And of course some markdown formatting touchups like code formatting.
P.S.: I came across these `var` references when working on #3732 😇
> Refactor: Switch to `let` & `const` from `var` in `JS`, `JSX`, `TS` & `TSX` code-blocks

- docs/_getting-started-macos-ios.md
- docs/_integration-with-existing-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
- docs/_integration-with-existing-apps-objc.md
- docs/_integration-with-existing-apps-swift.md
Fixes #3758
Wherever we've specified the package versions explicitly and haven't enclosed them in the inline-code-block (\`) or multiline-code-block (\```) they are resolved as an email protocol (address), which is _unintended_ and is a primary _security concern_.
This diff updates such occurrences to enclose them in inline code blocks and of course some code formatting touchups 😇
[SECURITY]: FIX unintended Email protocol resolution
|--------|--------|
| ![image](https://github.com/facebook/react-native-website/assets/55224033/17cbf5fb-1f5b-484c-90fc-86abffb695ce) | ![image](https://github.com/facebook/react-native-website/assets/55224033/974b5b07-6523-40b6-8716-85d20fc6ff09) | 
---
P.S.: Came across this when working on #3732
> SECURITY: FIX unintended Email protocol resolution

- website/contributing/release-roles-responsibilites.md
Clarifying that the Release Crew role is a multi month commitment that includes all supported React Native versions until the next minor work starts.
> Clarify Release Crew role timespan and responsibilities

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/_integration-with-existing-apps-java.md
- docs/_integration-with-existing-apps-kotlin.md
- docs/publishing-to-app-store.md
- docs/running-on-device.md
Currently, some docs are diverged from using `<kbd>` and rather use \` for formatting Keyboard Keys and Shortcuts. 
This diff updates docs to use the `<kbd>` HTML tag for formatting the same and of course, adds some formatting touchups.
[UI] Touchups: Use `<kbd>` for specifying Keyboard Keys and Shortcuts.
---
P.S.: I came across these occurrences when working on #3732 😇
> Touchups: Use `<kbd>` for specifying Keyboard Keys and Shortcuts

- docs/debugging.md
- docs/hermes.md
As a follow-up of https://github.com/facebook/react-native/pull/36754, which removes the remote debugging option from the dev menu, this PR updates the Debugging documentation, deprecating Remote debugging and recommending the usage of Direct debugging with Safari as an alternative. 
This also adds a quick section about Flipper as it currently is the hard-coded way of debugging when pressing `Open Debugger`
> Update Debugging docs to no longer recommend Remote debugging

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
Simplifies information on Metro in the Getting Started guide, to improve clarity and accuracy. Includes new one-liner for Metro as "the JavaScript build tool for React Native".
> [docs] Update/simplify info around Metro for env setup

- docs/metro.md
- docs/ram-bundles-inline-requires.md
- website/sidebars.json
- website/versioned_docs/version-0.72/metro.md
- website/versioned_docs/version-0.72/ram-bundles-inline-requires.md
- website/versioned_sidebars/version-0.72-sidebars.json
Adds first version of a **Metro** page to the docs, detailing configuration patterns available as of 0.72. A response to https://github.com/facebook/metro/issues/1010 (and https://github.com/kristerkari/react-native-svg-transformer/issues/276) — where there is some potential for user confusion under the 0.72 setup.
Backported to `website/versioned_docs/version-0.72`.
https://deploy-preview-3772--react-native.netlify.app/docs/metro
---
**Note**: We _may_ do a functional follow up to simplify `getDefaultConfig` in 0.72.x, and will more holistically Metro config loading in 0.73. However this PR is a first step to clearly document the current state of things.
> [docs] Add Metro configuration guide, update Metro config references

- docs/metro.md
- website/versioned_docs/version-0.72/metro.md
Small follow-up to #3772.
On **bold** vs `code` for package names:
- **pkg-name** (generally with a link) is used by npm, [Rollup](https://rollupjs.org/introduction/), [Vue](https://vuejs.org/guide/quick-start.html#using-vue-from-cdn), [Relay](https://relay.dev/docs/getting-started/prerequisites/) — I like this, but it's overwhelmed by the below 😅⬇️.
- `pkg-name` (generally with a link) is used by Expo, [react-native-windows](https://microsoft.github.io/react-native-windows/docs/getting-started), Node.js and [across this website](http://localhost:3000/docs/upgrading).
⬆️ cc @Simek Feels worth adding a brief style guide to this repo, I'd also like to align our use of keyboard shortcuts in a future PR (`<kbd>` and with key names, e.g.: <kbd>Cmd ⌘</kbd> + <kbd>K</kbd>).
> [docs] Remove static config note in Metro guide, adjust formatting

- docs/performance.md
Improving Grammar and Clarity in React Native's Performance Description
> Improving Grammar and Clarity.md

- website/contributing/how-to-build-from-source.md
With the monorepo changes, the way how we trigger a build from source had to be adapted.
This change is also pending a change on `react-native` before it can be merged:
- https://github.com/facebook/react-native/pull/36702
As this doc is not versioned, so I think we might want to hold on merging it till 0.72 lands?
On the other hand, the current setup is broken for nightlies and user should use the new instructions.
How do we feel about it?
> Update how-to-build-from-source for 0.72+

- docs/the-new-architecture/pillars-turbomodule.md
Documentation clarification for this page:
https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules#shared
`codegenConfig` is stated in text that it's an array, but in code example it's an object. See highlighted text-selection in the attached screenshot.
Either the text or the code example should change. **This PR changes the code example**, if this assumption is wrong I can open another PR changing the text.
---
---
> Clarify documentation for turbomodules

- docs/optimizing-flatlist-configuration.md
My fix solves the problem Update FlatList Optimization Guide for FCs #3677
> Update FlatList Optimization Guide for FCs

- website/contributing/how-to-contribute-code.md
- website/contributing/how-to-open-a-pull-request.md
Adds guidance to our Contributing docs around the introduction of a monorepo build setup.
- https://github.com/facebook/react-native/pull/38240
> [docs] Add guidance on repo build scripts

- docs/the-new-architecture/backward-compatibility-fabric-components.md
The [iOS section](https://reactnative.dev/docs/the-new-architecture/backward-compatibility-fabric-components#ios-1) of the Fabric Component Backwards Compatibility docs explicitly mentions the need to update two of the three documents created in the [Fabric Component iOS Native Code section](https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components#ios). 
As someone without experience writing native code, it was unclear that it is necessary to update all three documents. This PR updates the documentation to clarify that point and links back to the relevant section of the Legacy Native Component docs.
[Link to the discussion this PR stems from](https://github.com/reactwg/react-native-new-architecture/discussions/8#discussioncomment-6257033)
> docs: iOS backwards compatibility update

- website/src/theme/DocVersionBanner/index.js
Fixes #3797
[Swizzle](https://docusaurus.io/docs/swizzling) and eject the `DocVersionBanner`, tweak message wording for older versioned docs.
> [website] swizzle DocVersionBanner, tweak wording

- website/contributing/release-updating-packages.md
While doing [a fix in main](https://github.com/facebook/react-native/pull/38548#issuecomment-1645758671) we realised that the wording could be improved.
> tweak: improve wordiness on docs about bumping monorepo packages

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
Starting from React Native 0.73, users will need to use JDK 17. I'm updating the website so it's ready for the next version.
> Update website to use JDK 17

- website/contributing/how-to-contribute-code.md
- website/contributing/how-to-open-a-pull-request.md
Removes mandatory run of `yarn build/watch` when developing Node.js packages — matching the updated build setup in https://github.com/facebook/react-native/pull/38718 (these packages are now set up to run from source during development).
Partially reverts #3788 "[docs] Add guidance on repo build scripts"
> Update guidance on repo build scripts

- docs/running-on-device.md
- website/versioned_docs/version-0.69/running-on-device.md
- website/versioned_docs/version-0.70/running-on-device.md
- website/versioned_docs/version-0.71/running-on-device.md
- website/versioned_docs/version-0.72/running-on-device.md
The [Running On Device](https://reactnative.dev/docs/running-on-device) page has a broken link to https://docs.expo.dev/workflow/run-on-device/.
This updates it to https://docs.expo.dev/get-started/expo-go/.
> Update Expo Go guide link

- docs/new-architecture-appendix.md
- website/core/TableRowWithCodeBlock.js
- website/core/VerticalTable.js
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.71/new-architecture-appendix.md
- website/versioned_docs/version-0.72/new-architecture-appendix.md
Currently, on the New Architecture Appendix page the Typescript section table breaks the desktop and mobile display, also the Flow section readability is not that great.
This PR adds vary basic `VerticalTable` component, with data structure which allows us to avoid HTML entities (used due to MDX parse limitations/problems) and unifies the data structure and appearance between Flow and TypeScript sections.
The changes have also been backported to the two latest versioned docs.
~~One issue I can see is that relative component import would need to be updated manually after cutting new version. Would be nice to have a app root import alias, or something allowing to avoid relative import paths in docs (CC @slorber).~~
> This has been resolved by using [`@site` …
> [website] add VerticalTable, improve new arch appendix

- website/contributing/_markdown-older-bump-script.mdx
- website/contributing/release-branch-cut-and-rc0.md
- website/contributing/release-candidate-patch.md
- website/contributing/release-stable-minor.md
- website/contributing/release-stable-patch.md
This a follow up PR to update the docs to reflect a recent change in the release crew flow https://github.com/facebook/react-native/pull/38666
This is currently in the process of getting aligned & backported across the release support window:
* 72 https://github.com/facebook/react-native/pull/38888
* 71 https://github.com/facebook/react-native/pull/38890
* 70 https://github.com/facebook/react-native/pull/38892
This PR needs to be merged AFTER all those PRs are merged.
> chores(releases): rename script and add info note

- docs/native-modules-android.md
- docs/native-modules-ios.md
- website/versioned_docs/version-0.70/native-modules-android.md
- website/versioned_docs/version-0.70/native-modules-ios.md
- website/versioned_docs/version-0.71/native-modules-android.md
- website/versioned_docs/version-0.71/native-modules-ios.md
- website/versioned_docs/version-0.72/native-modules-android.md
- website/versioned_docs/version-0.72/native-modules-ios.md
Within the native module documentations there were two errors in the type conversion tables.
For Android the Promise type was missing from the conversion table.
For iOS two NSNumber conversions were present in the type conversion table. One of which stated NSNumber would be converted into a ?boolean. This table entry was removed as this seems to be not true. The other NSNumber entry which states NSNumber is converted to number? was left untouched.
> Fix native module type conversion tables for iOS and Android

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- docs/navigation.md
- docs/platform-specific-code.md
- docs/the-new-architecture/backward-compatibility-fabric-components.md
- docs/the-new-architecture/backward-compatibility-turbomodules.md
- docs/the-new-architecture/pillars-fabric-components.md
- docs/the-new-architecture/pillars-turbomodule.md
- package.json
- website/blog/2016-03-24-introducing-hot-reloading.md
- website/blog/2017-06-21-react-native-monthly-1.md
- website/blog/2017-11-06-react-native-monthly-5.md
- website/versioned_docs/version-0.70/platform-specific-code.md
- website/versioned_docs/version-0.71/platform-specific-code.md
- website/versioned_docs/version-0.72/navigation.md
- website/versioned_docs/version-0.72/platform-specific-code.md
- website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-fabric-components.md
- website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-turbomodules.md
- website/versioned_docs/version-0.72/the-new-architecture/pillars-fabric-components.md
- website/versioned_docs/version-0.72/the-new-architecture/pillars-turbomodule.md
- yarn.lock
As part of https://github.com/facebook/react-native-website/pull/3780 I'm regenerating the lockfile, which updates the `case-police` CI linter.
After the patch update, new issues are reported:
```
Webpack → webpack
Cocoapods → CocoaPods
```
cc @Simek 
---
Full log:
```
➜  react-native-website git:(slorber/update-case-police) yarn case-police '**/*.md' -p brands,general,products,softwares -d ./website/react-native-dict.json
yarn run v1.22.17
$ /Users/sebastienlorber/Desktop/projects/react-native-website/node_modules/.bin/case-police '**/*.md' -p brands,general,products,softwares -d ./website/react-native-dict.json
Case  Police  v0.5.14
835 files found for checking, 360 words loaded
Webpack → webpack 	 ./docs/_getting-started-linux-android.md:149:88
Webpack → webpack …
```
> Update case-police, fix case of webpack + CocoaPods

- website/community/communities.md
Since it's not either company-based nor explicitly for content sharing, I added a new "Independent communities" header as well. Reactiflux has had a React Native section since its inception! I didn't realize we hadn't requested to be listed before 😄
> Add Reactiflux to list of communities

- docs/native-components-ios.md
- docs/profile-hermes.md
- docs/pushnotificationios.md
- docs/scrollview.md
- docs/touchablenativefeedback.md
- website/architecture/render-pipeline.md
- website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
- website/blog/2016-12-05-easier-upgrades.md
- website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
- website/versioned_docs/version-0.70/native-components-ios.md
- website/versioned_docs/version-0.70/profile-hermes.md
- website/versioned_docs/version-0.70/pushnotificationios.md
- website/versioned_docs/version-0.70/scrollview.md
- website/versioned_docs/version-0.70/touchablenativefeedback.md
- website/versioned_docs/version-0.71/native-components-ios.md
- website/versioned_docs/version-0.71/profile-hermes.md
- website/versioned_docs/version-0.71/pushnotificationios.md
- website/versioned_docs/version-0.71/scrollview.md
- website/versioned_docs/version-0.71/touchablenativefeedback.md
- website/versioned_docs/version-0.72/native-components-ios.md
- website/versioned_docs/version-0.72/profile-hermes.md
- website/versioned_docs/version-0.72/pushnotificationios.md
- website/versioned_docs/version-0.72/scrollview.md
- website/versioned_docs/version-0.72/touchablenativefeedback.md
- yarn.lock
This is a follow-up of https://github.com/facebook/react-native-website/pull/3807
The goal is to adjust docs so that they render exactly the same on MDX v1 and MDX v2.
This permits my visual regression tests to avoid reporting false positives due to MDX behavior changes.
This also permitted to catch a few typos and inconsistencies.
Preview: https://deploy-preview-3830--react-native.netlify.app/
> chore: prepare docs for Docusaurus v3 upgrade - 2nd iteration

- docs/transforms.md
Adds documentation for [transformOrigin](https://github.com/facebook/react-native/pull/38559#issuecomment-1702758720) prop.
> docs: transform origin

- docs/headless-js-android.md
- website/versioned_docs/version-0.70/headless-js-android.md
- website/versioned_docs/version-0.71/headless-js-android.md
- website/versioned_docs/version-0.72/headless-js-android.md
Hey Team,
I think this caveat is outdated.
This was fixed in https://github.com/facebook/react-native/pull/33044 and it's now possible to use setTimeout from a HeadlessJsTask.
See:
https://github.com/facebook/react-native/pull/33043
https://github.com/facebook/react-native/pull/33044
> Remove out dated caveat about using setTimeout from a headless js task

- docs/transforms.md
- website/versioned_docs/version-0.70/transforms.md
- website/versioned_docs/version-0.71/transforms.md
- website/versioned_docs/version-0.72/transforms.md
Match the new page structure from https://github.com/facebook/react-native-website/commit/7025dea3b440a19cb5c2c31384c8043cb0dbe227 on versioned docs, and update the syntax to align more closely with how you'd use transform in a `style` prop.
> Fix syntax on transform examples

- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.72/the-new-architecture/pillars-turbomodule.md
Minor fix of file extension cause for someone it can be confusing to have .js file in final result when typescript code was used at the beginning
> change file extension to ts in turbo modules creation guide

- website/versioned_docs/version-0.72/debugging.md
> Fix link to redirect to standalone react-devtools

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.70/_getting-started-linux-android.md
- website/versioned_docs/version-0.70/_getting-started-macos-android.md
- website/versioned_docs/version-0.70/_getting-started-windows-android.md
- website/versioned_docs/version-0.71/_getting-started-linux-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-android.md
- website/versioned_docs/version-0.71/_getting-started-windows-android.md
- website/versioned_docs/version-0.72/_getting-started-linux-android.md
- website/versioned_docs/version-0.72/_getting-started-macos-android.md
- website/versioned_docs/version-0.72/_getting-started-windows-android.md
Tested on:
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS Ventura 13.5.2
Apple M2 chip
Screenshot:
> fix(getting started): update Android SDK path in Android Studio

- docs/out-of-tree-platforms.md
- website/versioned_docs/version-0.71/out-of-tree-platforms.md
- website/versioned_docs/version-0.72/out-of-tree-platforms.md
This PR updates the Out-of-Tree Platforms doc removing [Alita](https://github.com/areslabs/alita) and [Valence Native](https://github.com/valence-native/valence-native) from the list. These projects have remained dormant for the past few years and are no longer actively maintained.
> Delist unmaintained Out-of-Tree Platforms

- website/package.json
- website/src/css/versions.scss
- website/src/pages/versions.js
- yarn.lock
Update Docusaurus from nightly to the beta release and update related dependencies.
Additionally, I have fixed the content stretching issues on the Versions pages and added a paragraph explaing a bit more the archive snapshots we use to host older versions of docs.
> update Docusaurus to beta release, versions page tweaks

- website/sidebars.json
- website/versioned_sidebars/version-0.70-sidebars.json
- website/versioned_sidebars/version-0.71-sidebars.json
- website/versioned_sidebars/version-0.72-sidebars.json
This is an opinionated restructure of top level categories in the docs sidebar, with the aims of:
- Making items more navigable (ungrouping some of the concepts previously under "Workflow").
- Exposing "Debugging" as a top level item — ahead of incoming additions / a refresh to this section.
This affects the sidebar structure only — all page URLs are unchanged.
| - | - |
| <img width="150" alt="Screenshot 2023-10-10 at 15 15 30" src="https://github.com/facebook/react-native-website/assets/2547783/c4c408a8-372b-4c04-8377-6c992fb23c10"> | <img width="150" alt="Screenshot 2023-10-10 at 15 17 14" src="https://github.com/facebook/react-native-website/assets/2547783/e6af5268-0fee-4564-bd94-4e1db09ef5f7"> |
> [docs] Reorganise docs sidebar

- docs/textinput.md
- website/versioned_docs/version-0.70/textinput.md
- website/versioned_docs/version-0.71/textinput.md
- website/versioned_docs/version-0.72/textinput.md
This PR updates the default value of `textBreakStrategy` prop of `TextInput` component to 'highQuality' instead of 'simple'. This has been the default behaviour for quite some time now and it is tripping off developers. More details regarding this mismatch is available at https://github.com/facebook/react-native/issues/38244
> fix: default value of textBreakStrategy prop of TextInput component

- README.md
Adds high level instructions to update the versions/config files used by `@react-native-website/lint-examples` as part of the release process.
> Add section on updating linting tools

- website/blog/2022-07-08-hermes-as-the-default.md
Hi ;) 
Came across and figured by "last Oct" it was intended to link to my old blog post 😛
> Fix a backlink on hermes-as-the-default

- docs/native-debugging.md
- website/versioned_docs/version-0.72/native-debugging.md
Hi.
I checked the current [native debugging section in docs](https://reactnative.dev/docs/next/native-debugging) and realized that my previous [PR that adds more instructions](https://github.com/facebook/react-native-website/pull/3614) was deleted, I think this is because the file name was changed or something like that. 
[Current doc](https://reactnative.dev/docs/next/native-debugging):
[0.71 doc](https://reactnative.dev/docs/0.71/debugging#debugging-native-code):
> Recover debugging native code section

- docs/integration-with-android-fragment.md
- website/versioned_docs/version-0.70/integration-with-android-fragment.md
- website/versioned_docs/version-0.71/integration-with-android-fragment.md
- website/versioned_docs/version-0.72/integration-with-android-fragment.md
Added missing `xmlns:...` to `<FrameLayout ...` on the guide for adding RN to Fragments instead of activities.
Without specifying xmlns in newer versions:
> Added missing xmlns to FrameLayout

- docs/alert.md
- website/versioned_docs/version-0.71/alert.md
- website/versioned_docs/version-0.72/alert.md
The `options` parameter is currently not linkable because it should point to the #alertoptions fragment. This PR fixes that.
> docs: fix fragment for AlertOptions

- docs/speeding-ci-builds.md
Based on https://github.com/react-native-community/cli/blob/main/docs/dependencies.md#dependency, the field is `dependency` not `dependencies`.
> fix example code prop name

- docs/flatlist.md
- website/versioned_docs/version-0.70/flatlist.md
- website/versioned_docs/version-0.71/flatlist.md
- website/versioned_docs/version-0.72/flatlist.md
[FlatList extends its props from VirtualizedList](https://github.com/facebook/react-native/blob/97647d11841c9c97632617fe770439e3acb689ea/packages/react-native/Libraries/Lists/FlatList.d.ts#L22), so their docs should point to `VirtualizedList Props` instead of `ScrollView Props`.
> docs: changed FlatList props inheritance

- docs/new-architecture-library-intro.md
- docs/the-new-architecture/cxx-cxxturbomodules.md
- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.70/new-architecture-library-intro.md
- website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.71/the-new-architecture/cxx-cxxturbomodules.md
- website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.72/new-architecture-library-intro.md
- website/versioned_docs/version-0.72/the-new-architecture/cxx-cxxturbomodules.md
- website/versioned_docs/version-0.72/the-new-architecture/pillars-turbomodule.md
> docs: import TurboModule from react-native directly

- docs/native-components-android.md
> Correct `src` prop typing in native-components-android.md

- netlify.toml
- scripts/lint-examples/babel.config.js
- scripts/lint-examples/package.json
- scripts/lint-examples/tsconfig.json
- yarn.lock
Updates the harness for linting snack examples to the newest version of RN.
> Lint and typecheck examples against RN 0.73

- docs/new-architecture-library-android.md
- website/versioned_docs/version-0.70/new-architecture-library-android.md
- website/versioned_docs/version-0.71/new-architecture-library-android.md
- website/versioned_docs/version-0.72/new-architecture-library-android.md
- website/versioned_docs/version-0.73/new-architecture-library-android.md
The statement at the end says that since the generated abstract class extends ReactContextBaseJavaModule, all the functions are still accessible. But the sentence reads "should not use" which does not make sense, and "should not lose" should be used instead.
> Change 'use' to 'lose' to signify that functions are still accessible

- docs/hermes.md
- website/versioned_docs/version-0.73/hermes.md
The template has changed enough that the docs needed to be updated for the 0.73 release as well as next. This makes it clear how to disable Hermes.
Fixes #3950
> docs(hermes) disable Hermes matches template changes

- website/blog/2023-12-06-0.73-debugging-improvements-stable-symlinks.md
- yarn.lock
Add deprecation notice about types/react-native for 0.73
Note: We need this PR to land: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67459 but the deprecation notice still stands
> Add types/react-native deprecation notice to 73 blog post

- docs/publishing-to-app-store.md
- website/versioned_docs/version-0.73/publishing-to-app-store.md
Fixes #3951
This is no longer needed as the template sets those by default
> Do not suggest users to 'Enable App Transport Security'

- website/blog/2023-12-06-0.73-debugging-improvements-stable-symlinks.md
Want to call out that we will not be shipping patches on pre-existing versions due to DT deprecation process
> Clarify DT ts deprecation about patches

- website/src/css/customTheme.scss
Looks like we have introduce a small visual regression with one of the Docusaurus upgrade, so let's fix it!
Remove custom CSS overwrites, stick to the default values which seems to look fine now.
> fix table header appearance in dark mode

- docs/statusbar.md
The barStyle description with 'Light/Dark background' confuses, because the prop does not change the background color
> Update barStyle enum prop description on StatusBar component

- docs/view-style-props.md
Update View Style docs to include new logical border radius props
`borderEndEndRadius`
`borderEndStartRadius`
`borderStartEndRadius`
`borderStartStartRadius`
Related: https://github.com/facebook/react-native/pull/35572
> add logical border radius props

- docs/accessibility.md
Documentation clean up including more consistent grammar throughout, referring to screen readers versus VO or TB when referring to both platforms and some accessibility inaccuracies around actions.
> docs: update grammar and inaccuracies in accessiblity page

- .circleci/config.yml
Give it 8GB of memory since Docusaurus is liking to OOM during build, even when we restrict Node heap size.
> Give the CircleCI machines more memory

- docs/animations.md
- docs/scrollview.md
- website/versioned_docs/version-0.70/scrollview.md
- website/versioned_docs/version-0.71/scrollview.md
- website/versioned_docs/version-0.72/scrollview.md
- website/versioned_docs/version-0.73/scrollview.md
1. Recent releases support the prop on Android
2. As of 0.74, iOS does not throttle by default.
> Revise documentation for scrollEventThrottle

- docs/usewindowdimensions.md
- website/versioned_docs/version-0.70/usewindowdimensions.md
- website/versioned_docs/version-0.71/usewindowdimensions.md
- website/versioned_docs/version-0.72/usewindowdimensions.md
- website/versioned_docs/version-0.73/usewindowdimensions.md
Fixes: #3977
Removes community alternatives for the useWindowDimensions hook, as they have either been removed or are no longer maintained.
> remove community packages references from useWindowDimensions

- docs/appearance.md
- website/versioned_docs/version-0.70/appearance.md
- website/versioned_docs/version-0.71/appearance.md
- website/versioned_docs/version-0.72/appearance.md
- website/versioned_docs/version-0.73/appearance.md
This PR adds a note about color scheme flickering on iOS between light and dark modes when taking a screenshot when using Appearance API.
> Add a note about color scheme flickering on iOS between light and dark modes

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.70/_getting-started-linux-android.md
- website/versioned_docs/version-0.70/_getting-started-macos-android.md
- website/versioned_docs/version-0.70/_getting-started-macos-ios.md
- website/versioned_docs/version-0.70/_getting-started-windows-android.md
- website/versioned_docs/version-0.71/_getting-started-linux-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-android.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-windows-android.md
- website/versioned_docs/version-0.72/_getting-started-linux-android.md
- website/versioned_docs/version-0.72/_getting-started-macos-android.md
- website/versioned_docs/version-0.72/_getting-started-macos-ios.md
- website/versioned_docs/version-0.72/_getting-started-windows-android.md
- website/versioned_docs/version-0.73/_getting-started-linux-android.md
- website/versioned_docs/version-0.73/_getting-started-macos-android.md
- website/versioned_docs/version-0.73/_getting-started-macos-ios.md
- website/versioned_docs/version-0.73/_getting-started-windows-android.md
Currently, the [Setting up development environment guide](https://reactnative.dev/docs/environment-setup?guide=native&platform=ios#creating-a-new-application) for Android and iOS references outdated information about Expo [eject](https://docs.expo.dev/archive/glossary/#eject) which is a deprecated term and is used anymore.
This PR removes the eject reference and just referents to "adding Expo to a project" created using React Native CLI and links to Expo documentation for the steps required to follow.
> [docs] Update Setting up development environment guide

- docs/typescript.md
Command example was showing example for yarn only, i added a tab to show example for both (yarn + npx)
> Adapt tsc command for yarn and npm

- docs/native-modules-android.md
- website/versioned_docs/version-0.70/native-modules-android.md
- website/versioned_docs/version-0.71/native-modules-android.md
- website/versioned_docs/version-0.72/native-modules-android.md
- website/versioned_docs/version-0.73/native-modules-android.md
Description:
In Kotlin examples of Promises section in `native-modules-android.md`, import promise statement is missing, causing unresolve Promise reference.
This commit:
Include missing import promise statement in every `native-modules-android.md`.
> Include missing import promise statements

- website/contributing/release-testing.md
Adds brief notes on Debugging features for release testing, under a new "Test Notes" subheading. We will expand this over time.
> Add minimal Debugging expectations to release testing guide

- docs/the-new-architecture/pillars-turbomodule.md
- website/versioned_docs/version-0.73/the-new-architecture/pillars-turbomodule.md
Description: 
In the CalculatorPackage.kt file, there is a mistake in the code example. The getModule method of the CalculatorPackage class has an argument named "name" that is nullable. However, this argument in the extended class BaseReactPackage is non-null. This inconsistency causes an error in the Gradle build process.
extended class:
https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/BaseReactPackage.java
Fixes #3963
-
> Fixed a mistake in the code example in CalculatorPackage.kt in Turbo Native Modules guide.

- docs/text-style-props.md
- website/versioned_docs/version-0.70/text-style-props.md
- website/versioned_docs/version-0.71/text-style-props.md
- website/versioned_docs/version-0.72/text-style-props.md
- website/versioned_docs/version-0.73/text-style-props.md
Supersedes #3914
Fixes #3910
Add `lineHeight` prop description based on the origin PR, but a bit shorter + backport those changes to the versioned docs.
> TextStyleProps: add `lineHeight` prop description

- docs/javascript-environment.md
- website/versioned_docs/version-0.70/javascript-environment.md
- website/versioned_docs/version-0.71/javascript-environment.md
- website/versioned_docs/version-0.72/javascript-environment.md
- website/versioned_docs/version-0.73/javascript-environment.md
Update list of console APIs to also reflect `debug` and `groupCollapsed`
> doc: add console.debug, console.groupCollapsed to list of console APIs

- website/contributing/contributing-overview.md
add Twitter link to maintain consistency with other similar ReactNative references in the contribution guidelines
> add Twitter link to '@ReactNative' to maintain consistency with other '@ReactNative' references

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.73/_getting-started-linux-android.md
- website/versioned_docs/version-0.73/_getting-started-macos-android.md
- website/versioned_docs/version-0.73/_getting-started-windows-android.md
Modified documentation to add android sdk platform number and android version name for Android 14. This is the default android version that get added on initialising react native project with `npx react-native@latest init AwesomeProject`
Fix for #4036 
Documentation version affect: 0.73, next
> Fix for Issue 4036

- docs/virtualizedlist.md
- website/versioned_docs/version-0.71/virtualizedlist.md
- website/versioned_docs/version-0.72/virtualizedlist.md
- website/versioned_docs/version-0.73/virtualizedlist.md
`listKey` was removed, see: https://github.com/facebook/react-native/issues/37212#issuecomment-1539259551
> Remove `listKey` as it's no longer needed in RN 0.71+

- docs/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.71/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.72/the-new-architecture/landing-page.md
- website/versioned_docs/version-0.73/the-new-architecture/landing-page.md
As I was reading the new architecture landing page, I noticed what seemed like a missing word in this sentence, "Waiting for the official will...":
I added the word "release" after "official" -- assuming that was the intent of the sentence.
I ran the website locally to verify these changes:
> [docs] fix a missing word typo in the new architecture landing page

- docs/platform.md
My college @okwasniewski recently introduce a new Platform prop `isVision` https://github.com/facebook/react-native/commit/258d8e51b451b221e557dad4647cbd210fe37392
> Add a new `Platform.isVision` property (React Native 0.74.x)

- website/src/pages/index.js
The twitter url in hero section of home page is an external url, so clicking on it spoils the SPA router and opens the page in the same tab. This is going to give better user experience if this url opens in a new tab, and that's what I have done in this commit.
> Open twitter url in new tab

- docs/view-style-props.md
Related: https://github.com/facebook/react-native/pull/43078
Update the docs with the new cursor style prop, provided the above PR lands.
> Add cursor style prop

- website/docusaurus.config.js
I changed the href link to point to https://react.dev/ instead of https://reactjs.org/. I know reactjs.org redirects to react.dev, but I feel like it could be updated on the site as well
> chore: changed href to the new react.dev site

- website/docusaurus.config.js
This updates the banner to be a callout for ReactConf, similar to https://react.dev/
> Add ReactConf 2024 Banner

- docs/flexbox.md
- docs/layout-props.md
- website/architecture/architecture-glossary.md
- website/versioned_docs/version-0.70/flexbox.md
- website/versioned_docs/version-0.70/layout-props.md
- website/versioned_docs/version-0.71/flexbox.md
- website/versioned_docs/version-0.71/layout-props.md
- website/versioned_docs/version-0.72/flexbox.md
- website/versioned_docs/version-0.72/layout-props.md
- website/versioned_docs/version-0.73/flexbox.md
- website/versioned_docs/version-0.73/layout-props.md
While reading the docs I noticed these links are no longer working
> fix: broken yogalayout link references

- docs/profile-hermes.md
- docs/shadow-props.md
- website/blog/2023-01-27-71rc1-android-outage-postmortem.md
- website/contributing/how-to-contribute-code.md
- website/docusaurus.config.js
- website/package.json
- website/src/css/customTheme.scss
- website/versioned_docs/version-0.70/profile-hermes.md
- website/versioned_docs/version-0.70/shadow-props.md
- website/versioned_docs/version-0.71/profile-hermes.md
- website/versioned_docs/version-0.71/shadow-props.md
- website/versioned_docs/version-0.72/profile-hermes.md
- website/versioned_docs/version-0.72/shadow-props.md
- website/versioned_docs/version-0.73/profile-hermes.md
- website/versioned_docs/version-0.73/shadow-props.md
- yarn.lock
Upgrading to Docusaurus v3.2 gives the immediate following benefits:
- Faster cold/incremental build times
- Faster dev server hot reloads
- Reports broken anchor links (RN website has many of them to fix)
- Unlocks new Docusaurus features mentioned in release blog posts
- Other minor improvements
It should, it's a minor version that does not include any breaking changes.
And I ran visual regression tests comparing prod vs deploy preview to ensure nothing visual is impacted by the upgrade.
https://github.com/slorber/rnw-visual-tests/pull/2
The latest diff only contains 22 minor visual changes that are either expected, or improvements: https://app.argos-ci.com/slorber/rnw-visual-tests/builds/71/84659261
The React Native website builds significantly faster:
- 🔥 Cold builds: 95s ➡️ 66s (30% …
> Upgrade to Docusaurus v3.2

- docs/security.md
2 of the 4 Keystore libraries recommended in the docs are no longer maintained, and I think it is best to not list those as they might most likely not be compatible with the new arch, and have multiple bugs reported that will probably never get fixed:
- `react-native-encrypted-storage` has not been maintained for 2 years, and the repository has been archived in november 2023
- `react-native-sensitive-info` has not seen activity for 3 years
I have not found any new maintained libraries for this, which is a shame as `react-native-keychain` is not handling every use-case (it is opinionated about what your secrets are), and `expo-secure-store` requires to either use Expo or at least depend on the `expo` package, which has its drawbacks (version upgrades for example).
> Remove unmaintained Keystore libraries

- website/architecture/render-pipeline.md
Just a minor fix of punctuation for the sake of correctness and consistency.
> Fix punctuation in render pipeline: change `'“yellow“` to `'yellow'`

- docs/native-components-android.md
- docs/native-modules-android.md
- website/versioned_docs/version-0.73/native-components-android.md
- website/versioned_docs/version-0.73/native-modules-android.md
Hi, just a minor fix.
There is a Java comment example in the Kotlin section. Maybe a copy/paste errata?
> [android] 'native-modules-android' & 'native-components-android' docs consistency

- website/src/css/customTheme.scss
It has been pointed out that we still show "New" tag for page introduced few versions ago.
Remove "New" tag decoration from `Pressable`, `DynamicColorIOS` and `PlatformColor` reference pages.
Retained the code with a placeholder, since it might be useful in the future.
> remove "New" tag from pages existing for a while

- website/docusaurus.config.js
- website/src/css/index.scss
- website/src/pages/index.js
Update Twitter → X naming and branding on site homepage and in footer. Also switches (back) from custom follow button to official button widget from [publish.twitter.com](https://publish.twitter.com).
<details>
<summary><strong>Restores previous setup!</strong></summary>
This was motivated by seeing an updated follow button on the [archive.reactnative.dev](https://archive.reactnative.dev) site today! See 
https://github.com/facebook/react-native-website/commit/2161ea0297fdb72ff50bd9300056d4391ffa41ca for the historic source code.
</details>
**Header**
| Desktop | Mobile |
|--------|--------|
| <img width="1498" alt="image" src="https://github.com/facebook/react-native-website/assets/2547783/8a95f81a-1199-4ab1-988e-49709ee22314"> | <img width="495" alt="image" …
> Update X follow button and footer link

- docs/platform-specific-code.md
I made a minor correction to the `platform-specific-code.md` page regarding the placement of a comma in a sentence. The correction ensures that the parenthetical expression can be removed without changing the sentence's meaning. Specifically, I moved the comma after the word 'that' in the sentence starting with 'There is also a Platform.select method available...'.
> Fix grammatical error in platform-specific-code.md

- website/blog/2024-04-22-release-0.74.md
Minor changes:
- Fix Flipper docs link.
- Remove "(unsupported)" from details heading (soften language — could be misconstrued to Flipper as a whole).
- Un-bold JS debugging links.
> [blog] Adjust Flipper wording + links in 0.74 post

- docs/typescript.md
- website/versioned_docs/version-0.74/typescript.md
Use the new links [https://react.dev/learn/typescript](https://react.dev/learn/typescript) from [https://react.dev/](https://react.dev/) for version next and 0.74.
Older versions are skipped as they are not being maintained.
closes #4058
> fix: use new doc link from react.dev for ts

- docs/get-started-without-a-framework.md
- website/versioned_docs/version-0.74/get-started-without-a-framework.md
Fix RN CLI package name in "Getting started without a framework" docs.
> fix: RN CLI packaga name

- docs/debugging-native-code.md
- website/sidebars.json
As titled. We believe this heading is clearer than before. Affects `/docs/next`.
> [docs] Retitle native debugging guide

- docs/debugging-native-code.md
- docs/debugging.md
- website/sidebars.json
- website/versioned_docs/version-0.74/debugging.md
> [!Note]
> Stacked on https://github.com/facebook/react-native-website/pull/4139.
Adds a new admonition beneath the current guidance on Flipper. We want to gently nudge users to explore alternative tooling for inspecting their app's native logic. Linking to @jamonholmgren's [excellent post](https://shift.infinite.red/why-you-dont-need-flipper-in-your-react-native-app-and-how-to-get-by-without-it-3af461955109) is a good stand-in for a future detailed guide we want to include on this.
> [!Note]
> Nudging users towards first party native IDEs is a **long-term intent**. Even after we ship the new debugger, and build further capabilities into it which replace Flipper features, the upper bound for its functionality will be to model and inspect browser-like concepts. Phrased another way, native …
> [docs] Add tip fragment suggesting alternative tooling re: Flipper

- docs/out-of-tree-platforms.md
In this Pull Request I added React Native visionOS to `out-of-tree-platforms.md` page  that we created and maintain at @callstack.
> Mention React Native visionOS in OOT platforms page

- docs/upgrading.md
See: https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0759-react-native-frameworks.md#commands-to-be-removed
Related: https://github.com/react-native-community/cli/pull/2317
> Remove `upgrade` command references

- docs/stylesheet.md
Based on some digging, it seems as though `StyleSheet` no longer uses a registry of `ID`s: 
https://github.com/react-native-community/discussions-and-proposals/issues/400
https://github.com/facebook/react-native-website/pull/629#issuecomment-442501414
This PR updates the docs to reflect that change.
> chore: remove references to StyleSheetRegistry from StyleSheet docs

- docs/the-new-architecture/landing-page.md
- website/sidebars.json
- website/versioned_docs/version-0.74/the-new-architecture/landing-page.md
- website/versioned_sidebars/version-0.74-sidebars.json
After React Conf, we moved the New Arch to Beta but we forgot to update the website.
This PR fix our forgettance.
> [NewArch] Move the New Arch from Exp to Beta and reword a paragraph

- package.json
- yarn.lock
This is to resolve the issue of Axios security vulnerabilities https://github.com/advisories/GHSA-8hc4-vh64-cxmj
> Upgrade dependencies. Remove Axios as dependency

- docs/native-components-ios.md
- website/versioned_docs/version-0.75/native-components-ios.md
Updates `native-components-ios.md` to eliminate deprecated references to `prop-types` by suggesting TypeScript. This PR updates it for 0.75 (currently live) and Next.
While I was at it, I also updated the code snippets to functional components and to utilize line highlighting to make the code easier to comprehend.
| --- | --- |
| ![CleanShot 2024-08-19 at 10 49 03](https://github.com/user-attachments/assets/11f7accf-3e0e-4cbe-83d6-9b72692f6b3c) | ![CleanShot 2024-08-19 at 10 48 54](https://github.com/user-attachments/assets/22f806dd-e45c-4d75-b0b6-e0fa10665a70) |
> Remove PropTypes from `native-components-ios.md`

- docs/native-components-android.md
- website/versioned_docs/version-0.75/native-components-android.md
Updates `native-components-android.md` to eliminate deprecated references to `prop-types` by suggesting TypeScript. This PR updates it for 0.75 (currently live) and Next.
While I was at it, I also updated the code snippets to functional components and to utilize line highlighting to make the code easier to comprehend.
| --- | --- |
| ![CleanShot 2024-08-19 at 11 10 41](https://github.com/user-attachments/assets/52649873-7275-45cf-a0eb-0a7cb4dde134) | ![CleanShot 2024-08-19 at 11 11 02](https://github.com/user-attachments/assets/e056d0f3-303c-45a1-a6ed-120cc7abf988) |
> Remove PropTypes from `native-components-android.md`

- docs/performance.md
- website/versioned_docs/version-0.75/performance.md
Removes a minor reference to `propTypes` in `performance.md`. This PR updates it for 0.75 (currently live) and Next.
> Remove PropTypes from `performance.md`

- docs/running-on-device.md
Times change and Lightning cables are no longer needed for connecting your iOS device! This PR adds a mention about USB-C cables, hooray!
> docs: Update running-on-device.md for iOS to include mention about USB-C cables

- docs/image.md
This prop was [added in 0.75.0](https://github.com/facebook/react-native/commit/b6c343353765d8b13344841613250214fe8783db), but no documentation outside of JSDoc exists. This PR fixes that. It also organizes `referrerPolicy` alphabetically
> docs: add resizeMultiplier to Image props

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.75/_getting-started-linux-android.md
- website/versioned_docs/version-0.75/_getting-started-macos-android.md
- website/versioned_docs/version-0.75/_getting-started-macos-ios.md
- website/versioned_docs/version-0.75/_getting-started-windows-android.md
It's currently not possible to initialise a (community CLI) React Native >=0.75 project with Node 18.0, contrary to the docs, due to transitive dependency requirements. E.g:
Yarn 3.6.4 requires Node 18.12 and gives:
```
Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 18.0.0). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.
```
The transitive dep `@typescript-eslint/parser` requires `^18.18.0` and causes the installation to fail.
```
[3/5] 🚚  Fetching packages...
error @typescript-eslint/parser@7.18.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || >=20.0.0". Got "18.0.0"
error Found incompatible module.
```
Repro with:
```
nvm i 18.0
nvm use 18.0
npx @react-native-community/cli@latest init --version 0.75.2
``` …
> [0.75][main] Getting started: Bump documented Node.js minimum to 18.18

- website/architecture/render-pipeline.md
This pull request fixes a minor typo I encountered while reading the `rendering-pipeline` documentation:
> Similarly for iOS a `UIView` is created **~~with~~** and text is populated with a call to `NSLayoutManager`.
It also tweaks the formatting of one paragraph and the phrasing of a couple subsequent sentences to make them sound more natural, in English.
(Love the docs, by the way - feel free to edit this PR or close it, if it's not helpful 🫡)
> docs: fix render pipeline typo, tweak wording slightly

- website/contributing/contributing-overview.md
- website/contributing/how-to-open-a-pull-request.md
Supports https://github.com/facebook/react-native/pull/46420 (see [discussion](https://github.com/reactwg/react-native-releases/issues/476#issuecomment-2349048001)).
- Add Yarn install instructions.
- Add instructions for building `react-native-codegen`.
- Remove duplicated set of steps from `contributing-overview.md` — these are a subset of the step-by-step guide and were drifting out of sync.
> Add guidance on deps to the contributing guide

- docs/_getting-started-macos-android.md
This PR adds ELI5 style installation steps for installing the `Azul Zulu` JDK on MacOS, as glancing through it was not entirely obvious that you actually need to navigate to the folder and install the JDK manually, at least for me.
> docs: clarify the JDK update steps on MacOS

- docs/build-speed.md
- website/versioned_docs/version-0.74/build-speed.md
- website/versioned_docs/version-0.75/build-speed.md
In RN 0.74 support was added to natively support ccachng on ios by setting `enable_ccache` in the Podfile.
This change updates the relevant docs to use the much simpler instructions
> Improve ccache instructions Fixes #4215

- docs/animated.md
I noticed this link was broken, so I am fixing it.
> Fix `interpolate()` link on Animated docs

- website/src/css/customTheme.scss
Spotted recently that custom "Optimistic Display" font is not used for all text components after the latest Docusaurus update.
This PR reuses defined for IFM theme base font value, and applies it to the document body, which correctly propoaget the wanted font family down the DOM tree.
> fix incorrect font after the latest Docusaurus update

- README.md
- package.json
Remove "website:" prefixes from the root `start`, `build*`, `serve` npm scripts. This simplifies the steps needed to iterate in this project.
The `website/` dir is the only runnable target package in this monorepo — we can refactor later if this changes.
```sh
yarn start
```
> Simplify root npm scripts

- docs/text.md
- docs/view-style-props.md
- docs/viewtoken.md
While reading the `ViewStyle`, `ViewToken` and `Text` documentation, I noticed some small typos and formatting inconsistencies that I thought I would correct.
Please see explanations for any that aren't clear-cut below. Please feel free to correct these changes, if I've misread expectations.
> docs: fix small typos, in `ViewStyle`, `ViewToken`, `Text` docs

- docs/build-speed.md
- website/versioned_docs/version-0.71/build-speed.md
- website/versioned_docs/version-0.72/build-speed.md
- website/versioned_docs/version-0.73/build-speed.md
- website/versioned_docs/version-0.74/build-speed.md
- website/versioned_docs/version-0.75/build-speed.md
The banner suggest to update to 0.71, so I removed the banner from all the version >= 0.71 because there is no point in showing that information to users that are already on 0.71 or greater.
> Remove banner on build speed to update to 0.71

- docs/hermes.md
We're moving to the new debugger, so this legacy debugging just muddies
the water. I've also updated the config to remove flipper references.
> chore: hermes, remove legacy debugging + old config

- docs/image.md
**Summary:**
This PR corrects the misinformation regarding `webp` image format support in the `source` prop of React Native's `Image` component documentation. The current description incorrectly states that `webp` is only available when bundled with JavaScript on iOS, which is inaccurate. 
**Changes:**
- Updated the `Image` component's `source` prop description to accurately reflect the platform support for `webp` format.
- Clarified that `webp` is supported on Android by default and on iOS when using libraries like `react-native-webp` or `SDWebImage`.
**Impact:**
This correction ensures that developers are provided with accurate information regarding image format support across platforms, helping avoid confusion and potential implementation errors.
> docs: fix incorrect information about webp support in the source prop of React Native's Image component

- docs/image.md
Adds documentation for the new `resizeMethod` `none`. added in https://github.com/facebook/react-native/pull/46866
> Add documentation for `none` resizeMethod

- README.md
GitHub Action support was added in https://github.com/facebook/react-native-website/pull/4143, and we haven't used CircleCI since. Let's remove that from the README header
> Remove CircleCI status from README

- docs/the-new-architecture/codegen-cli.md
- docs/the-new-architecture/using-codegen.md
- docs/the-new-architecture/what-is-codegen.md
- website/sidebars.json
This PR moves the Codegen docs back into the website, in preparation of the New Architecture by default in 0.76.
> [NA] Move Codegen Docs back

- docs/profiling.md
No longer applies / connecting to JS DevTools isn't supported in a prod build. We also no longer recommend the in-app Perf Monitor.
Profiling features in React Native DevTools (at development time) will be separately documented. And in future, we'll likely review this entire guide when we productionise profiling builds with RNDT.
Resolves https://github.com/facebook/react-native-website/issues/4221.
> [docs] Remove references to Chrome profiler from Profiling guide

- website/architecture/landing-page.md
There was a typo in the manual on enabling the new architecture for Android.
> Android typo

- docs/the-new-architecture/direct-manipulation.md
- docs/the-new-architecture/layout-measurements.md
- website/sidebars.json
This change updates the documentation for measurements and direct manipulation in the New Arch.
It deletes parts that are not valid anymore or methods that are deprecated.
Do not consider the sidebar setup: we are going to review it once we have all the pieces of the New Architecture doc in place.
> [Docs][NA] Add measurements and Direct Manipulation

- website/contributing/how-to-open-a-pull-request.md
Just saw this while cloning the project fresh for another PR. When you clone the repo, you have to go into the directory before you add a new origin to it.
> fix: minor issue on how-to-open-a-pull-request.md

- docs/flexbox.md
- docs/image.md
- docs/stylesheet.md
- website/versioned_docs/version-0.70/image.md
- website/versioned_docs/version-0.71/image.md
- website/versioned_docs/version-0.72/image.md
- website/versioned_docs/version-0.73/image.md
- website/versioned_docs/version-0.74/image.md
- website/versioned_docs/version-0.75/image.md
- website/versioned_docs/version-0.75/stylesheet.md
Found some typos in multiple documents when going through them.
This PR fixes the typos in `/next` and versioned docs (where applicable).
> docs: Fix typos in multiple docs

- docs/statusbar.md
Add deprecation note as Android API backing Statusbar backgroundcolor prop is deprecated.
> Add deprecation note for Statusbar backgroundcolor prop

- website/blog/2024-10-23-release-0.76-new-architecture.md
Implements pending feedback I had on the 0.76 blog post: https://github.com/facebook/react-native-website/pull/4279#pullrequestreview-2390663521.
**Changes**
- Fix list formatting.
- I've added back some RNDT detail (this **_is_** shorter than the original v1!). Just don't want things to be cut quite as heavily, to preserve initial impressions and correctness — the AI shortening was too aggressive & don't quite have time to shorten further accurately.
> [blog] Fix bullets and re-expand RNDT section in 0.76 post

- website/static/_redirects
In the past months, we share a New Architecture link that was: https://reactnative.dev/docs/the-new-architecture/landing-page
This page now does not exists and it has to redirect to  https://reactnative.dev/architecture/landing-page
> Add redirect to landing page

- website/static/_redirects
Updates redirects following https://github.com/facebook/react-native-website/pull/4294. Removed routes under `/docs/next` have now shipped under `/docs`.
> [docs] Fix debugging /docs/next/ redirects following 0.76 cut

- website/blog/2024-10-23-release-0.76-new-architecture.md
Fixes small typo with a double colon next to boxShadow.
> fix: double colon in 2024-10-23-release-0.76-new-architecture.md

- docs/troubleshooting.md
The [Listen](https://github.com/guard/listen) gem's documentation moved from the [wiki](https://github.com/guard/listen/wiki) section to its [README](https://github.com/guard/listen/blob/master/README.md).
> [docs] Update troubleshooting.md to replace dead link

- website/architecture/landing-page.md
PR changing the suggested way of switching the new/old arch on `iOS` so it is similar to `Android`. Also, it seems more reasonable to have it in the `Podfile`, otherwise you (and your whole team) would have to remember about doing it every time.
> chore: suggest adding flag in Podfile instead of console

- docs/animations.md
- website/versioned_docs/version-0.71/animations.md
- website/versioned_docs/version-0.72/animations.md
- website/versioned_docs/version-0.73/animations.md
- website/versioned_docs/version-0.74/animations.md
- website/versioned_docs/version-0.75/animations.md
- website/versioned_docs/version-0.76/animations.md
I missed a few examples in #4200 where the example expo sandboxes were broken due to useAnimatedValue not being exported on web.
> Fix broken examples in Animated API docs

- docs/debugging.md
Remove localhost:3000 from the Debugging doc
> docs: Fix link for debugging native code

- website/architecture/landing-page.md
Update docs to fix a small typo in the architecture landing page.
> docs: fix typo in architecture landing page

- website/sidebars.json
- website/versioned_sidebars/version-0.76-sidebars.json
When reworking the website, there might be a wrongly resolved merge conflict that hid those two pages.
I'm bringing them back.
> [NA] Bring back layout measurement and direct manipulation

- docs/image.md
- docs/images.md
Cache control support was expanded to Android in https://github.com/facebook/react-native/pull/47182, namely the `reload` option. Let's update the docs to reflect that
> Update cache control to reflect Android support

- docs/fabric-native-components-android.md
- close #4327 
- Fix wrong syntax using enum class in Fabric Native Component
> Fix wrong syntax using Kotlin enum class

- website/showcase.json
- website/src/pages/showcase.js
The new Facebook and Instagram apps were written entirely in React Native. This change updates the showcase page to include links to each on the Meta Quest store, as well as an information link to one of Meta's recent blog posts on the topic
> Add Instagram and Facebook VR to showcase links

- website/src/pages/showcase.js
This minor change prevents word wrapping from splitting up "Meta" and "Quest" in the Showcase.
> Use `&nbsp;` in "Meta Quest"

- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.71/_getting-started-macos-ios.md
- website/versioned_docs/version-0.73/_getting-started-macos-ios.md
- website/versioned_docs/version-0.74/_getting-started-macos-ios.md
- website/versioned_docs/version-0.75/_getting-started-macos-ios.md
- website/versioned_docs/version-0.76/_getting-started-macos-ios.md
**Summary:** Fix the incorrect grammatical construction "If you are using version XX or greater than to install ...`
**Changelog:**
- [General] [Fixed] - Fix grammar mistake in docs about Getting started with macOS / iOS
> docs: fix grammar in Getting started with macOS / iOS

- docs/accessibility.md
- docs/view.md
- website/versioned_docs/version-0.70/accessibility.md
- website/versioned_docs/version-0.70/view.md
- website/versioned_docs/version-0.71/accessibility.md
- website/versioned_docs/version-0.71/view.md
- website/versioned_docs/version-0.72/accessibility.md
- website/versioned_docs/version-0.72/view.md
- website/versioned_docs/version-0.73/accessibility.md
- website/versioned_docs/version-0.73/view.md
- website/versioned_docs/version-0.74/accessibility.md
- website/versioned_docs/version-0.74/view.md
- website/versioned_docs/version-0.75/accessibility.md
- website/versioned_docs/version-0.75/view.md
- website/versioned_docs/version-0.76/accessibility.md
- website/versioned_docs/version-0.76/view.md
**What did I change?**
I added a platform label for the `onAccessibilityTap` prop on the [React Native documentation page](https://reactnative.dev/docs/accessibility#onaccessibilitytap).
**Why did I change it?**
An issue was reported regarding `onAccessibilityTap` not working on Android, but this prop is only intended for the iOS platform. This change will help clarify platform-specific behaviour and prevent future confusion among users.
**Reported issue** - https://github.com/facebook/react-native/issues/47149
**Action item** - https://github.com/facebook/react-native/issues/47149#issuecomment-2442379424
> fix: added platform label annotation of onAccessibilityTap prop

- docs/accessibility.md
- website/versioned_docs/version-0.71/accessibility.md
- website/versioned_docs/version-0.72/accessibility.md
- website/versioned_docs/version-0.73/accessibility.md
- website/versioned_docs/version-0.74/accessibility.md
- website/versioned_docs/version-0.75/accessibility.md
- website/versioned_docs/version-0.76/accessibility.md
The accessibility doc seemed to be missing info about the `listitem` role, which is an important complementary role to the `list` role.
I added an entry for it with a simple description of the purpose.
> Add missing listitem role do accessibiltiy doc

- docs/view.md
- website/versioned_docs/version-0.76/view.md
> collapsable is not Android only prop in new architecture

- docs/view.md
- website/versioned_docs/version-0.76/view.md
[collapsableChildren](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Components/View/ViewPropTypes.js#L582) is not documented on the website. Let's add it.
In this PR, I also add default value column to `collapsable`.
> add collapsableChildren to docs and add default value for collapsable

- docs/profiling.md
I couldn't get any of this to work last time I tried. I assumed the entire page is completely broken and outdated. Turns out, all of it is still relevant, it's just recommending tools that haven't worked for many years. This changes the recommendation to tools that actually work.
> Update Android profiling instructions

- docs/images.md
Cache control support for `force-cache` and `only-if-cached` on Android were added in https://github.com/facebook/react-native/pull/47426 and https://github.com/facebook/react-native/pull/47348 respectively
> Remove cache control platform hints

- docs/_getting-started-macos-android.md
If you simply follow the process in a MacOS + Android environment, this command seems correct to open the finder.
> docs: Updated _getting-started-macos-android.md for Finder commands in MacOS + android environment

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-windows-android.md
- website/versioned_docs/version-0.76/_getting-started-linux-android.md
- website/versioned_docs/version-0.76/_getting-started-macos-android.md
- website/versioned_docs/version-0.76/_getting-started-windows-android.md
In `0.76`, new projects are created using `Android SDK Build-Tools 35` and `Android SDK Platform 35`, but the documentation states to install `Android SDK Build-Tools 34` and `Android SDK Platform 34`
> fix: android versions in env setup guide

- docs/sectionlist.md
keyExtractor in sectionlist checks for item.key first. If it is not present it checks for item.id. If item.id is not present then it falls back to index.
> Update sectionlist.md for keyExtractor

- docs/textinput.md
A new prop `submitBehavior` is added to `TextInput` component and this deprecates `blurOnSubmit` prop.
This PR updates document to sync with the changes. Please refer to https://github.com/facebook/react-native/pull/45588 for more info.
> feat: add `submitBehavior` and deprecate `blurOnSubmit` of TextInput component

- docs/debugging.md
The debugging docs page had an outdated keyboard shortcut to open the dev menu for an iOS Simulator.
> Update iOS Simulator keyboard shortcut.

- docs/handling-text-input.md
This PR is a small change to the [Handling Text Input](https://reactnative.dev/docs/handling-text-input) code example.
As of now it looks like this, the text cursor collides with the box:
Adding a tiny bit of padding to the `TextInput` makes the cursor look better positioned:
Best regards and thank you for your awesome work!
> Add padding to TextInput in handling-text-input code example

- docs/image.md
`getSize` now can return promises
- ![image](https://github.com/facebook/react-native-website/assets/4661784/e53d738b-c806-4338-98bd-39c94490db6b)
- react-native PR: https://github.com/facebook/react-native/pull/42895
> Promote to use a Promise api instead of callbacks

- docs/textinput.md
- remove the mention of `useEffect` and `componentDidMount` from doc about `autoFocus`.
- the underlying Implementation was changed from JS to Native
-  [iOS PR](https://github.com/facebook/react-native/pull/27803), [Android PR](https://github.com/facebook/react-native/pull/27924),  [JS Removal PR](https://github.com/facebook/react-native/pull/27923)
> Update textinput.md - autoFocus

- docs/the-new-architecture/layout-measurements.md
The parameters of the `MeasureOnSuccessCallback` are spread out across `x`, `y`, `width`, `height`, etc, instead of being in a variable called `measurements`. I've updated to the code example to reflect that.
> Improved code example in layout-measurements.md

- docs/toastandroid.md
`showWithGravity` and `showWithGravityAndOffset` from ToastAndroid does not work for text toasts as of Android 11. [ToastModule](https://github.com/facebook/react-native/blob/8dabed60f456e76a9e53273b601446f34de41fb5/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/toast/ToastModule.kt#L48) uses `setGravity` which is no-op. More information can be found here:
- [setGravity docs](https://developer.android.com/reference/android/widget/Toast#setGravity(int,%20int,%20int))
- [Updates to toasts in Android 11 ](https://developer.android.com/about/versions/11/behavior-changes-11)
An alternative implementation could use `setView`, but:
1. It is [depracated](https://developer.android.com/reference/android/widget/Toast#setView(android.view.View))
2. [Custom toasts from the …
> Update ToastAndroid with changes in Android 11

- website/versioned_docs/version-0.76/accessibility.md
Port this change https://github.com/facebook/react-native-website/pull/4226 in the 0.76 versioned docs as the change was introduced in react-native 0.76.
---
This PR adds documentation for the newly added props in https://github.com/facebook/react-native/pull/45903:
accessibilityShowsLargeContentViewer: whether the large content viewer is shown
accessibilityLargeContentTitle: title of the large content viewer
> docs(accessibility): document large content viewer support on iOS

- docs/animations.md
This text appears to be referencing a class component that uses state to store the animated value. The example it is referencing is using function components, and the animated value is not state.
> Small update to Animations docs

- docs/touchablewithoutfeedback.md
Hey, I noticed that the `accessibilityIgnoresInvertColors` in `TouchableWithoutFeedback` documentation is missing information about iOS platform support. This could be confusing, since this property is only supported for iOS.
> Update accessibilityIgnoresInvertColors in TouchableWithoutFeedback

- website/src/css/customTheme.scss
- website/src/css/index.scss
Remove restrictions on CSS transitions to allow for native transitions in Docusaurus components.
this brings back things like: 
- sidebar menu transition in and out of view
- sidebar menu list expand and collapse animation
- link and button hover animation
- popover in and out animation
https://github.com/user-attachments/assets/ee3d5f03-37bc-4635-bd9b-9a17a2d97db6
closes #4379
> Enable Docusaurus native CSS transitions

- package.json
Include the packageManager field in package.json to specify the version of Yarn used for the project.
Corepack will use the specified version to ensure consistency across environments.
https://nodejs.org/api/corepack.html
closes #4378
> Add packageManager field to package.json for Yarn version specification

- .github/workflows/pre-merge.yml
Should save a decent amount of time (10-20s) on pre-merge jobs if we take advantage of setup-node's built-in caching. The yarn install step drops from ~45s to ~25s
> Enable caching on pre-merge jobs

- .github/workflows/pre-merge.yml
In recent PR CI we can see an unexpected build failure.
Bump used Node 18->20 and increase the amount of RAM which can be reserved by Node during the build process. Since public Ubuntu runners have 16GB of RAM this should be fine:
* https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Run the CI.
> [gha] tweaks for the pre-merge workflows

- package.json
- yarn.lock
Eliminate the deprecated babel-eslint dependency from the project to streamline the package.json and update yarn.lock accordingly.
> Remove deprecated babel-eslint dependency

- website/.remarkrc.mjs
- website/package.json
- yarn.lock
Disable the remark-lint plugin configuration to prevent it from being executed during linting due to long execution time.
this should reduce the ci time by 92% from 38mins to 3mins
> Disable 'no-broken-external-links' Remark Rule to Optimize CI Performance by 92%

- docs/the-new-architecture/using-codegen.md
- website/versioned_docs/version-0.76/the-new-architecture/using-codegen.md
Update docs for Codegen for 0.76 and 0.77
> [RN][Codegen] Add docs for advanced iOS usage

- docs/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.76/the-new-architecture/pure-cxx-modules.md
We discovered that in App pure Cxx Turbomodules stopped working from version 0.76 of React Native.
We have the [issue](https://github.com/facebook/react-native/issues/48298) tracking it and a [potential fix](https://github.com/facebook/react-native/pull/48340) for it. 
Given the Christmas break, we are not going to be able to ship a new release of React Native with the fix. Therefore we want to document this problem in the website.
> [RN][NewArch] Add danger block for C++ TurboModule

- website/src/css/customTheme.scss
Use the default width and eliminate the redundant table border width setting in the custom theme to streamline the styling.
before
after
before
after
> Make table border thicker and easier to see

- plugins/remark-codeblock-language-as-title/README.md
- plugins/remark-codeblock-language-as-title/package.json
- plugins/remark-codeblock-language-as-title/src/index.js
- plugins/remark-lint-no-dead-urls/package.json
- plugins/remark-snackplayer/package.json
- website/docusaurus.config.ts
- yarn.lock
Introduce a new remark plugin that sets the title metadata for code blocks based on their language, along with updates to dependencies and README documentation for clarity and consistency.
A custom [remark](https://github.com/remarkjs/remark) plugin that automatically sets the `title` metadata for code blocks in Markdown files based on the block's language.
- **Adds `title` Metadata**: For code blocks with a specified language (e.g., `js`, `python`), the plugin sets the `title` metadata to match the language.
- **Preserves Existing Metadata**: If the code block already contains metadata (`meta`) but lacks a `title`, the plugin appends the `title` without removing the existing metadata.
- **Ignores Code Blocks with Existing `title`**: If the `meta` field already includes a `title` …
> Add codeblock language as title remark plugin

- docs/headless-js-android.md
- website/versioned_docs/version-0.70/headless-js-android.md
- website/versioned_docs/version-0.71/headless-js-android.md
- website/versioned_docs/version-0.72/headless-js-android.md
- website/versioned_docs/version-0.73/headless-js-android.md
- website/versioned_docs/version-0.74/headless-js-android.md
- website/versioned_docs/version-0.75/headless-js-android.md
- website/versioned_docs/version-0.76/headless-js-android.md
Improve the clarity of the headless-js-android documentation by updating the code block syntax for XML.
> Update XML code block syntax in documentation

- website/docusaurus.config.ts
Update the default language setting in the Docusaurus configuration to take into account snippets with TypeScript.
> Change default language from 'jsx' to 'tsx' in Docusaurus config

- docs/_integration-with-existing-apps-ios.md
- docs/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
The urls should point to the right branch in the template repo,
otherwise users will download a wrong version of the files.
Fixes https://github.com/facebook/react-native-website/issues/4426
> Fix integration with existing apps URLs

- website/src/css/customTheme.scss
Revise the custom theme colors to enhance the appearance of the table of contents and code elements.
before
after
before
after
> Update colors for table of contents to be more in line with the theme

- website/src/css/customTheme.scss
Change the background color of the component grid to enhance the contrast.
before
after
> Better contrast for component grid component header

- docs/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
As per react native 0.76 release breaking changes documentation updated kotlin integration.
Kotlin integration code example missed the changes.
[0.76 breaking changes](https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#breaking-changes-1) 
**Issue**
#4430
>  fixed: kotlin SoLoader.init params to fix "library 'libhermes_executor.so' not found

- website/src/css/customTheme.scss
Improved link styling to take full height within the component grid to enhance usability and accessibility.
before
https://github.com/user-attachments/assets/a3c9d975-a1c6-4fc8-960b-a199375f4eb8
after
https://github.com/user-attachments/assets/cdb9c826-99d1-420b-a261-18c6dc4f7c73
the background color is apparently an existing style of the a tag that was auto enabled but it looks good actually
> Enhance component grid link clickability for better usability

- docs/hermes.md
Hi team,
I just found a small typo in the [hermes docs](https://reactnative.dev/docs/hermes). I tested it locally as well. If you require me to do anything further, just let me know.
> fix(docs): typo in hermes docs

- docs/layout-props.md
tsia, adding documentation for box sizing. I only added to Layout props. We could change some guides like https://reactnative.dev/docs/height-and-width but I do not think it's worth it/TMI. Lmk if you think otherwise!
> Box sizing documentation

- docs/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.76/the-new-architecture/pure-cxx-modules.md
Reverting https://github.com/facebook/react-native-website/pull/4402 - as of [RN0.76.6](https://github.com/facebook/react-native/releases/tag/v0.76.6) and [RN0.77.0-rc.6](https://github.com/facebook/react-native/releases/tag/v0.77.0-rc.6) the mentioned issue has been resolved
> [RN][NewArch] Remove danger block for Pure C++ TurboModule

- docs/modal.md
adding documentation on new `navigationBarTranslucent` prop for Modal that was added here: https://github.com/facebook/react-native/pull/47254/
> add prop Modal.navigationBarTranslucent 

- docs/view.md
- website/versioned_docs/version-0.70/view.md
- website/versioned_docs/version-0.71/view.md
- website/versioned_docs/version-0.72/view.md
- website/versioned_docs/version-0.73/view.md
- website/versioned_docs/version-0.74/view.md
- website/versioned_docs/version-0.75/view.md
- website/versioned_docs/version-0.76/view.md
This PR adds missing syntax highlighting and fixes indentation in the View's pointerEvents property.
> Add missing syntax highlighting in View

- website/blog/2025-01-21-version-0.77.md
I noticed that the work on the Swift template is credited to Riccardo only in 0.77 blog post. Since the bulk of work and prior art in React Native visionOS project was done by Oskar, I believe he deserves a little credit in that blog post :)
> fix: give credit to Oskar for Swift template

- docs/_integration-with-existing-apps-ios.md
- website/versioned_docs/version-0.77/_integration-with-existing-apps-ios.md
The Objective-C template files have been removed, so this PR changes the link targets to the previous ones.
> Fix invalid links in Integration with Existing Apps

- docs/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.77/the-new-architecture/pure-cxx-modules.md
In 0.77, we migrated the template from Objective-C to Swift.
However, swift and pure C++ modules do not work well together. In this PR, I'm adding a warning box with the same content of the [release blogpost](https://reactnative.dev/blog/2025/01/21/version-0.77#limitations).
This should addrss #4476
> [C++ TM] Add warning for iOS integration

- docs/fabric-native-components-ios.md
- website/versioned_docs/version-0.76/fabric-native-components-ios.md
- website/versioned_docs/version-0.77/fabric-native-components-ios.md
When releasing 0.76, we were aware of a couple of issues that were affecting the Native Components, and we added a warning box for the users. Now those issues are solved and we can remove the warning.
> [Native Components] Remove warning box as all the issues have been solved now.

- docs/handling-touches.md
- website/versioned_docs/version-0.70/handling-touches.md
- website/versioned_docs/version-0.71/handling-touches.md
- website/versioned_docs/version-0.72/handling-touches.md
- website/versioned_docs/version-0.73/handling-touches.md
- website/versioned_docs/version-0.74/handling-touches.md
- website/versioned_docs/version-0.75/handling-touches.md
- website/versioned_docs/version-0.76/handling-touches.md
- website/versioned_docs/version-0.77/handling-touches.md
Previously, the intro paragraph to Touchables read a bit weirdly. This PR improves the flow, word order and fixes incorrect use of a comma. This change has been applied to all versions of docs where Touchables were introduced. 
Doc page and section changed: https://deploy-preview-4500--react-native.netlify.app/docs/handling-touches#touchables
> Improve sentence structure for past and current docs on Touchables intro

- docs/_integration-with-existing-apps-ios.md
This change removes the warning box from the brownfield guide because we did an extra RC (RC.5) that includes the commit that lift the limitation expressed in the warning box.
> [RN][iOS][Brownfield] Remove warning as we already landed the commit in RC.5

- docs/backhandler.md
- website/versioned_docs/version-0.77/backhandler.md
`BackHandler.removeEventListener` was removed in 0.77.x 
RN PR: https://github.com/facebook/react-native/pull/45892
CHANGELOG: https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0770
> fix: Remove BackHandler.removeEventListener method for RN 0.77+

- docs/turbo-native-modules-android.md
- website/versioned_docs/version-0.78/turbo-native-modules-android.md
This PR fixes the parameter names in the `ReactModuleInfo` of `NativeLocalStoragePackage` constructor call in the example code provided in the [React Native documentation](https://reactnative.dev/docs/turbo-native-modules-introduction). Previously, the parameters were passed using incorrect names (`_name`, `_className`, `_canOverrideExistingModule`, and `_needsEagerInit`), which do not match the actual parameter names expected by the constructor.
This issue was reported in: https://github.com/facebook/react-native/issues/49573
> Fix: Use correct parameter names in ReactModuleInfo constructor

- docs/debugging.md
- docs/other-debugging-methods.md
Accompanies https://github.com/react-native-community/discussions-and-proposals/discussions/872, landing in React Native 0.79.
> [docs] Remove Remote JavaScript Debugging

- docs/the-new-architecture/pure-cxx-modules.md
- docs/the-new-architecture/using-codegen.md
- docs/turbo-native-modules-ios.md
With 0.79, we are updating how Native Modules are registered in React Native.
This PR updates the docs and the guides related to Native Modules and the related Codegen updates.
> [RN][iOS] Update Module Registration

- website/versioned_docs/version-0.78/optimizing-flatlist-configuration.md
The maintenance of `react-native-fast-image` is not in good condition, the last commit is 3 years old and the maintainer is not very active in the community currently. Now dream-lab-sports forked it and maintains this and added support for the new architecture, so I think it's good for everyone to update this
> docs: replace usage of react-native-fast-image

- docs/the-new-architecture/codegen-cli.md
Using an H1 here causes the TOC to entirely skip this section. See it here: https://reactnative.dev/docs/the-new-architecture/codegen-cli
> Fix heading in codegen-cli.md

- docs/flexbox.md
- website/versioned_docs/version-0.78/flexbox.md
Having `column-reverse` below `column` felt more natural to try it when compared to on the diagonal.
> Have column reverse below column instead of on the diagonal

- docs/textinput.md
https://github.com/facebook/react-native/pull/49549 Added support for the `numberOfLines` prop on iOS on the new architecture.
This PR also changes the description to say `maximum number of lines` to more accurately reflect that the behavior on the new architecture (TextInput expanding until it reaches the set limit) is the correct one.
> TextInput: update `numberOfLines` section

- website/src/css/customTheme.scss
Supersedes #4441
Approach the overflow problem differently, address most of the accessibility concerns from the origin PR.
https://github.com/user-attachments/assets/6fdd695c-44f2-42d3-a287-b35db514f2a7
> address table mobile overflow, tweak appearance

- website/src/css/customTheme.scss
Enhance the contrast of subtle color variables in the custom theme to improve visibility and accessibility.
continues #4541
before
after
> Update subtle color variables for improved contrast

- .alexrc.js
- docs/text.md
- package.json
- website/.remarkrc.mjs
- website/blog/2024-10-23-the-new-architecture-is-here.md
- website/package.json
- website/src/css/customTheme.scss
- website/src/pages/Home/Hero/styles.module.css
- website/src/pages/Home/Platforms/styles.module.css
- website/src/pages/Home/components/Section/styles.module.css
- website/versioned_docs/version-0.70/text.md
- website/versioned_docs/version-0.71/text.md
- website/versioned_docs/version-0.72/text.md
- website/versioned_docs/version-0.73/text.md
- website/versioned_docs/version-0.74/text.md
- website/versioned_docs/version-0.75/text.md
- website/versioned_docs/version-0.76/text.md
- website/versioned_docs/version-0.77/text.md
- website/versioned_docs/version-0.78/text.md
- yarn.lock
We did not touch the lint stack in a while. Let's update all of the related dependencies, address existing (unable to parse `.remarkrc.mjs`) and new issues, update configs.
Run the CI check, to make sure I did not miss anything
As a follow up, I want to look if all of ESLint plugins we use ready to migrate to ESLint 9 without using compat layer. If this is already possible, I will work on the migration.
> bump lint stack, update configs, fix new warnings

- docs/scrollview.md
- website/versioned_docs/version-0.70/scrollview.md
- website/versioned_docs/version-0.71/scrollview.md
- website/versioned_docs/version-0.72/scrollview.md
- website/versioned_docs/version-0.73/scrollview.md
- website/versioned_docs/version-0.74/scrollview.md
- website/versioned_docs/version-0.75/scrollview.md
- website/versioned_docs/version-0.76/scrollview.md
- website/versioned_docs/version-0.77/scrollview.md
- website/versioned_docs/version-0.78/scrollview.md
The `snapToAlignment` prop has been supported in Android since 0.67 (added https://github.com/facebook/react-native/commit/c6e5640e87e7cb5b514ded2c8d4cbb039bd02c5f for vertical, https://github.com/facebook/react-native/commit/deec1db9fdf2848941326ba5bebc11f3592a301e for horizontal) so this updates all of our active docs to remove the distinction that it's only on iOS
> Remove platform distinction on snapToAlignment

- website/contributing/contributing-overview.md
- website/contributing/versioning-policy.md
- website/sidebarsContributing.ts
This adds a versioning policy page for React Native that describes release cadence, nightlies, RCs, and defines what we consider a breaking change for React Native
> Add the Versioning Policy page for React Native

- docs/fabric-native-components.md
> [!WARNING]
Pull requests mentioned here will **not** be included in React Native 0.79
Following https://github.com/facebook/react-native/pull/49854 and https://github.com/facebook/react-native/pull/49950, it's no longer recommended to use deep imports when using codegen types and functions. Instead, they should be imported from the root `react-native` package.
> FabricNativeComponents: Update codegen imports

- docs/headless-js-android.md
- The original sample code signature doesn't match the HeadlessJsTaskService rewritten in Kotlin: https://github.com/facebook/react-native/blob/1156c08ac4d1fd9f782c87864d63c3f152f93734/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/HeadlessJsTaskService.kt#L56
> fix: override getTaskConfig method signature

- docs/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.79/the-new-architecture/pure-cxx-modules.md
In version 0.79.0 of [Cross-Platform Native Modules (C++)](https://reactnative.dev/docs/the-new-architecture/pure-cxx-modules#ios) the documentation for registering the module in the platform for iOS gives malformed JSON when explaining how to modify the `package.json` file.
https://github.com/facebook/react-native-website/issues/4579
> Update the JSON provided in the modification of the package.json file step

- .gitignore
- scripts/generate-llms-txt.js
- website/package.json
Adds a script that generates [`llms.txt`](https://llms.txt) - a single file containing all React Native documentation in a format optimized for LLMs. The file is generated during the website build process.
- Makes it easier for LLMs to understand and reference React Native documentation
- Provides a single, clean source of truth for documentation
- Helps LLMs give more accurate and up-to-date answers about React Native
- New script `scripts/generate-llms-txt.js` that:
- Parses sidebar config
- Validates all doc URLs
- Generates a clean markdown file
- Added to build process
- Added to `.gitignore`
- Verified all URLs are valid
- Checked generated markdown structure
- Tested build process
> Add script for generating `llms.txt`

- website/src/theme/Blog/Components/Author/styles.module.css
- website/src/theme/DocItem/Footer/styles.module.css
Our internal system noticed a couple of .css files that were missing the license.
This change adds the licenses to those files
> [RNW]Fix missing license in css files

- scripts/lint-examples/package.json
- yarn.lock
Our internal tools detected that versions <7.26.10 of @babel/runtime, @babel/runtime-core3j and @babel/helpers suffers from some vulnerability.
This change bumps those packages to ensure that the minimum version we are using is 7.26.10 that fixes those vulnerabilities.
[Security] - Bump @babel dependencies to fix vulnerabilities.
> [RNW][Deps] Bump babel dependencies to solve vulnerability issues

- website/showcase.json
Fixes https://github.com/facebook/react-native-website/issues/4588 
This PR removes several apps that no longer use React Native or are no longer available including:
- Skype ([Shutting Down May 2025](https://support.microsoft.com/en-us/skype/skype-is-retiring-in-may-2025-what-you-need-to-know-2a7d2501-427f-485e-8be0-2068a9f90472#:~:text=As%20of%20May%205th%2C%202025,same%20core%20features%20and%20more.))
- Amazon App Store ([deprecated](https://www.amazon.com/gp/mas/appstore/android/faq))
- Pinterest - No longer uses React Native
- Walmart Shopping & Grocery - Walmart uses React Native in other areas of the business, but not in the main grocery app. 
- Words with Friends 2 - uses Unity
- Call of Duty Companion App - No longer available
- Tencent QQ
- Gyroscope (Android)
Thank you to …
> Remove outdated entries in React Native showcase 

- docs/typescript.md
- website/versioned_docs/version-0.79/typescript.md
Small updates to the "Using TypeScript" guide. In particular, `@tsconfig/react-native` → `@react-native/typescript-config`.
> Tweak TypeScript guide

- website/blog/2025-04-08-react-native-0.79.md
See https://github.com/expo/expo/discussions/36551
> [blog] Add breaking change notice/info for 0.79 resolution changes

- docs/layout-props.md
- website/versioned_docs/version-0.77/layout-props.md
- website/versioned_docs/version-0.78/layout-props.md
- website/versioned_docs/version-0.79/layout-props.md
Adds the missing `contents` value to the `display` property.
https://reactnative.dev/blog/2025/01/21/version-0.77#simpler-layouts-with-display-contents
#4616
> Add display: 'contents'

- website/sidebars.ts
Without landing https://github.com/facebook/react-native-website/pull/4618, adding this sidebar link resolves to a 404 and the build fails
> Add targetevent to sidebar

- website/versioned_docs/version-0.79/targetevent.md
The URL checker that's failing in #4622 is for the current version of docs (0.79), not the *next* version of docs. This copies the `targetevent` file event though it's not being referenced in 0.79 to satisfy a build step
> Add targetevent to current versioned doc

- scripts/generate-llms-txt.js
- website/sidebarsArchitecture.ts
We spotted that LLMS generation script fails  in PR preview deployments when contributor adds a new page, which is not yet in the PROD.
Refs: 
* https://github.com/facebook/react-native-website/pull/4626#issuecomment-2918132359
Instead of failing whole build, skip non-existing URLs and warn about them in logs. All path defined in sidebar should exist, so if there is sth random added the build will still fail, but in the cases when the problem is just with fresh pages missing on PROD this should help, and unblock contributions.
1. Add random, non existing section, make sure that generation scripts works
2. Remove the bogus sidebar entry before merging.
> [scripts] LLMS: skip non-existing yet URLs instead of failing

- docs/i18nmanager.md
- website/sidebars.ts
Added to sidebar as well.
Related to https://github.com/facebook/react-native/pull/51661 and https://github.com/facebook/react-native/pull/51648
> Add I18nManager docs

- docs/the-new-architecture/create-module-library.md
Fixing a small typo in https://reactnative.dev/docs/the-new-architecture/create-module-library
> Fix small typo in the documentation

- docs/accessibility.md
- docs/view.md
- website/versioned_docs/version-0.78/accessibility.md
- website/versioned_docs/version-0.78/view.md
- website/versioned_docs/version-0.79/accessibility.md
- website/versioned_docs/version-0.79/view.md
- website/versioned_docs/version-0.80/accessibility.md
- website/versioned_docs/version-0.80/view.md
The current description of the accessible prop is misleading and confusing. The current wording implies that this prop mainly "groups its children into a single selectable component", which is a round-about way of saying it can receive focus, I think? I am not really sure what that means.
Regardless, the main point is not hammered home: This prop allows the View to be discoverable by screen readers (and other things).
The example is also a bit misleading, since Text is focusable by default on iOS. It is not wrong, but the example is better for a guide on label co-opting, not basic use of accessible.
Curious how, if at all, I should change this for previous versions.
NOTE: This is the same as https://github.com/facebook/react-native-website/pull/4653, with the requested changes. I had …
> Reword accessible prop in accessiblity guide

- docs/modal.md
This PR is a followup for https://github.com/facebook/react-native/pull/51483 to add documentation for this change.
> Add allowSwipeDismissal documentation

- website/versioned_docs/version-0.80/turbo-native-modules-android.md
The clear method was missing in the Java version and I added information to clean the build for possible errors.
> docs: update turbo-native-modules-android.md

- docs/build-speed.md
- website/versioned_docs/version-0.78/build-speed.md
- website/versioned_docs/version-0.79/build-speed.md
- website/versioned_docs/version-0.80/build-speed.md
Currently waiting for:
- https://github.com/facebook/react-native/pull/52378
to be merged to add this one.
> Add docs on how to configure a Maven Internal Mirror

- website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.77/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.78/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.79/_integration-with-existing-apps-kotlin.md
- website/versioned_docs/version-0.80/_integration-with-existing-apps-kotlin.md
Fix versioned docs links in _integration-with-existing-apps-kotlin
Related to #4669
> Fix versioned docs links in _integration-with-existing-apps-kotlin

- website/versioned_docs/version-0.76/fabric-native-components-android.md
- website/versioned_docs/version-0.77/fabric-native-components-android.md
- website/versioned_docs/version-0.78/fabric-native-components-android.md
- website/versioned_docs/version-0.79/fabric-native-components-android.md
- website/versioned_docs/version-0.80/fabric-native-components-android.md
Updated the versioned documentation to clarify the ReactModuleInfo setup for the Android Fabric WebView component.
Related to PR #4670
> Fix: update versioned docs for ReactModuleInfo Android Fabric WebView

- docs/_integration-with-existing-apps-kotlin.md
Fixed Markdown link syntax for Metro bundler URL
> Update _integration-with-existing-apps-kotlin Metro bundler URL

- docs/the-new-architecture/native-modules-custom-events.md
- website/versioned_docs/version-0.80/the-new-architecture/native-modules-custom-events.md
Fix the doc to use EventEmitter from CodegenTypes without deep import
> [DOC] Use CodegenTypes without deep import

- website/versioned_docs/version-0.79/textinput.md
- website/versioned_docs/version-0.80/textinput.md
Follow up to:
* #4553
Since we have released new versions since the PR has been created, we need to backport those changes to the newest, versioned docs.
> port `lineBreakModeIOS` addition to the versioned docs

- website/versioned_docs/version-0.80/pressable.md
Follow up to:
* #4543
Port `onPressMove` addition to the versioned doc for 0.80.
> port `onPressMove` addition to the versioned doc

- docs/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.77/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.78/the-new-architecture/pure-cxx-modules.md
- website/versioned_docs/version-0.80/the-new-architecture/pure-cxx-modules.md
Follow up to:
* #4578
Update template version in native modules guide in unversioned file and versioned docs to match correct version.
> update template version in native modules guide

- website/versioned_docs/version-0.74/textinput.md
- website/versioned_docs/version-0.75/textinput.md
- website/versioned_docs/version-0.76/textinput.md
- website/versioned_docs/version-0.77/textinput.md
- website/versioned_docs/version-0.78/textinput.md
- website/versioned_docs/version-0.79/textinput.md
- website/versioned_docs/version-0.80/textinput.md
Follow up to:
* #3739
Port recent `enterKeyHint` prop values update to the versioned docs.
> port `enterKeyHint` to versioned docs

- docs/animated.md
- docs/animations.md
- docs/easing.md
- docs/transforms.md
There are few PRs tackling issues with animation examples listed on the website. I was able to confirm the issues, and this take tried to handles most of them in unversioned docs.
Update animated examples to use the approach with ref, which also works on the web. Remove preview platforms limitations, refactor one of the examples to function component from class.
If this is the correct approach, I plan to backport the changes in the follow up PR.
> fix Animation examples, allow web preview

- website/blog/2025-06-12-react-native-0.80.md
This PR fixes the Podfile syntax to setting the `RCT_USE_RN_DEP` env variable in the 0.80 release blog post.
> Fix env variable configuration in 0.80 release blog post

- website/core/DocsRating.tsx
Spotted a warning about rules of hooks violation caused by `DocsRating` component. 
Move state variable declaration above first conditional rendering.
> fix `DocsRating` violating rules of hooks

- docs/textinput.md
- website/versioned_docs/version-0.73/textinput.md
- website/versioned_docs/version-0.74/textinput.md
- website/versioned_docs/version-0.75/textinput.md
- website/versioned_docs/version-0.76/textinput.md
- website/versioned_docs/version-0.77/textinput.md
- website/versioned_docs/version-0.78/textinput.md
- website/versioned_docs/version-0.79/textinput.md
- website/versioned_docs/version-0.80/textinput.md
Supersedes:
* #4009
Update link to the article visualizing available `keyboardType`s, apply change to unversioned and all versioned docs.
> TextInput: update link to article visualizing `keyboardType`s

- website/package.json
- yarn.lock
Supersedes:
* #4535 
Update `@babel/core` to the latest release from 7.26.x series, to address the mentioned above dependabot recommendation.
Additionally, I have added the explicit `@types/react` dev dependency to satisfy warning seen during the build.
> explicit React types, babel deps upate

- docs/building-for-tv.md
- docs/communication-android.md
- docs/integration-with-android-fragment.md
- docs/intro-react.md
- docs/introduction.md
- docs/libraries.md
- docs/network.md
- docs/optimizing-javascript-loading.md
- docs/running-on-device.md
- docs/security.md
- docs/testing-overview.md
- docs/typescript.md
- website/contributing/how-to-contribute-code.md
Since Docusaurs added admonitions we should use them, instead of stylized blockquote tags, which should be re-styled at the end of migration to represent actual quotes.
Migrate blockquote notes to admonitions for most pages in the Guides section.
> Guides: migrate blockquote notes to admonitions

- docs/the-new-architecture/what-is-codegen.md
- website/versioned_docs/version-0.81/the-new-architecture/what-is-codegen.md
- Fix grammar 
- Remove unnecessary emphasis
- Add URL to Turbo Native Modules
> Update what-is-codegen.md document to improve grammar and readability

- website/versioned_docs/version-0.77/text-style-props.md
- website/versioned_docs/version-0.78/text-style-props.md
- website/versioned_docs/version-0.79/text-style-props.md
- website/versioned_docs/version-0.80/text-style-props.md
- website/versioned_docs/version-0.81/text-style-props.md
Supersedes:
* #3272
Update the text `fontVariant` prop possible enum values. I have used HTML table instead to be able to leverage `colspan` attribute to reduce the amount of place the table takes vertically.
> update `fontVariant` possible enums list

- docs/textinput.md
- website/versioned_docs/version-0.77/textinput.md
- website/versioned_docs/version-0.78/textinput.md
- website/versioned_docs/version-0.79/textinput.md
- website/versioned_docs/version-0.80/textinput.md
- website/versioned_docs/version-0.81/textinput.md
Supersedes:
* #3560
Add `smartInsertDelete` prop to the TextInput documentation. List props in alphabetical order in unversioned and 0.80 doc.
> TextInput: add `smartInsertDelete` prop, reorder props

- docs/app-extensions.md
- website/versioned_docs/version-0.77/app-extensions.md
- website/versioned_docs/version-0.78/app-extensions.md
- website/versioned_docs/version-0.79/app-extensions.md
- website/versioned_docs/version-0.80/app-extensions.md
- website/versioned_docs/version-0.81/app-extensions.md
Removes recommendation to watch Conrad Kramer's talk on "Memory Use in Extensions" since it is unavailable on YouTube.
> Remove broken link to "Memory Use in Extensions" talk in `app-extentions.md`

- docs/textinput.md
- docs/view.md
- plugins/remark-snackplayer/README.md
- plugins/remark-snackplayer/src/index.js
- website/versioned_docs/version-0.77/textinput.md
- website/versioned_docs/version-0.77/view.md
- website/versioned_docs/version-0.78/textinput.md
- website/versioned_docs/version-0.78/view.md
- website/versioned_docs/version-0.79/textinput.md
- website/versioned_docs/version-0.79/view.md
- website/versioned_docs/version-0.80/textinput.md
- website/versioned_docs/version-0.80/view.md
- website/versioned_docs/version-0.81/textinput.md
- website/versioned_docs/version-0.81/view.md
So far, the Snack embedded element theme was coupled with preview device appearance which in some cases lead to readability problems in dark mode.
Refs:
* https://github.com/expo/snack/pull/643
Should address issues bring up in:
* https://github.com/facebook/react-native-website/pull/4639
* https://github.com/facebook/react-native-website/pull/4640
Add support for `deviceAppearance` query param, set it by default to `'light'`, but allow customization on case-by-case base.
In the process, I have also updated few examples, to make sure that they display and work correctly on mobile previews.
> fix Snacks preview appearance, allow customizing, tweak few examples

- website/src/css/customTheme.scss
An another small chunk of styling changes to align RN website appearance more with React.dev.
This one was suggested by @joevilches.
Alter the default Docusaurus admonitions styling to match a bit closer in-content notes on React website.
> align admonitions style with react.dev

- docs/image.md
- website/versioned_docs/version-0.77/image.md
- website/versioned_docs/version-0.78/image.md
- website/versioned_docs/version-0.79/image.md
- website/versioned_docs/version-0.80/image.md
- website/versioned_docs/version-0.81/image.md
Update the Fresco version used in the Image component to properly support 16KB pages on Android.
- Fresco added explicit support for 16KB page sizes starting from version 3.4.0 ([release notes](https://github.com/facebook/fresco/releases/tag/v3.4.0)).
- This PR updates Fresco to **3.6.0** for React Native 0.78 and above ([release notes](https://github.com/facebook/react-native/releases/tag/v0.78.0)).
- For versions prior to 0.78, Fresco remains at 3.4.0 to maintain stability.
- Android 16KB page issue in Image component
> Update Fresco to 3.6.0 to fix Android 16KB page issue

- docs/_getting-started-linux-android.md
- docs/_getting-started-macos-android.md
- docs/_getting-started-macos-ios.md
- website/versioned_docs/version-0.81/_getting-started-linux-android.md
- website/versioned_docs/version-0.81/_getting-started-macos-android.md
- website/versioned_docs/version-0.81/_getting-started-macos-ios.md
This PR updates the recommended Node.js version in the "Set Up Your Environment" documentation to align with the requirements of React Native 0.81.
The official blog post for the [React Native 0.81 release](https://reactnative.dev/blog/2025/08/12/react-native-0.81#minimum-nodejs-bumped-to-20) states that the minimum Node.js version has been bumped to **20.19.4** or higher.
However, the ["Set Up Your Environment" guide](https://reactnative.dev/docs/set-up-your-environment) currently still recommends **Node 18.18** or higher. This discrepancy can be confusing for developers.
This change updates the setup guide to reflect the new requirement, ensuring the documentation is consistent with the latest release.
> Update the required Node.js version to 20.19.4 for React Native v0.81 and later

- docs/_experimental-api-warning.mdx
- docs/accessibility.md
- docs/view.md
- docs/virtualview.md
We'll use this banner more often soon, so extracting prevents copy&pasting.
> Extract experimental API warning to a separate file

- scripts/generate-llms-txt.js
Currently, [the `llms.txt` file on PROD deployment](https://reactnative.dev/llms.txt) does not includes page links, only the section headers.
Fix logic responsible for handling unavailable pages, simplify code a bit.
Follow up idea: replace custom script with a Docusarus plugin, which would also generate `llms-full.txt`, see:
* https://github.com/rachfop/docusaurus-plugin-llms
Run `yarn generate-llms-txt` command locally, verify output.
> fix script generating llms.txt

- .github/workflows/pre-merge.yml
- netlify.toml
- package.json
- yarn.lock
Refs:
* https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
* https://answers.netlify.com/t/new-ubuntu-24-04-noble-numbat-build-image/130497#p-290898-what-about-ubuntu-2004-focal-fossa-4
Switch GitHub workflows and Netlify setup to use Node 22, bump yarn, align Netlify setup to what's used locally, remove cache plugin in favour of in-panel project config.
The Node upgrade and build image switch also speed up a build time quite noticeably:
> switch workflows and Netlify setup to use Node 22

- website/src/css/customTheme.scss
I have spotted that inline code blocks does not correctly line with the text in some cases, and `kbd` tags looks off when used inside annotations.
Update some top level styles and vars to avoid overwrites for inline code and code/pre blocks, fix pre background bleeding in light mode for block with a title (header), apply page background color to `kbd`s.
> visual tweaks for CodeBlock component, `code` and `kbd` elements

- docs/releases/release-levels.md
- docs/releases/releases.md
- docs/releases/versioning-policy.md
- website/sidebars.ts
- website/sidebarsContributing.ts
- website/static/_redirects
Add "Releases" section in the "Guides", add "Release Levels" doc explaining the approach and tips for using Canary and Experimental releases. 
Add and updated redirects for moved pages, correct links, formatting tweaks.
> add Releases section and Release Levels doc
